syntax = "proto2";

package gmm;

import "logs/proto/logs_annotations/logs_annotations.proto";

option objc_class_prefix = "GMM";
option java_multiple_files = true;
option java_outer_classname = "UserEvent3EnumsProto";
option java_package = "com.google.wireless.googlenav.proto";

enum Action {
    CLICK = 1;
    TURN_ON = 2;
    TURN_OFF = 3;
    SHAKE = 4;
    LONG_PRESS = 5;
    SWIPE = 6;
    TIMEOUT = 7;
    AUTOMATED = 8;
    INPUT_VOICE = 9;
    PINCH_OPEN = 10;
    PINCH_CLOSED = 11;
    DRAG = 12;
    TWO_FINGER_DRAG_UP = 13;
    TWO_FINGER_DRAG_DOWN = 14;
    DOUBLE_TAP = 15;
    TWO_FINGER_TAP = 16;
    TAP_THEN_DRAG_UP = 17;
    TAP_THEN_DRAG_DOWN = 18;
    ROLL = 19;
    FORCE_TOUCH = 20;
    HOVER = 21;
}

enum AppCheckpoint {
    APP_STARTED_COLD = 0;
    APP_STARTED_HOT = 1;
    RUNNING = 10;
    APP_BACKGROUNDED = 2;
    APP_STARTED_BACKGROUND_COLD = 23;
    APP_STARTED_BACKGROUND_HOT = 24;
    APP_ENDED_BACKGROUND_FETCH = 25;
    PROJECTED_APP_STARTED_COLD = 18;
    PROJECTED_APP_STARTED_HOT = 19;
    PROJECTED_APP_BACKGROUNDED = 20;
    VANAGON_MODE_STARTED = 28 [deprecated = true];
    VANAGON_MODE_ENDED = 29 [deprecated = true];
    APP_CLEARED_DATA = 9;
    USER_PREFERENCES_CHANGED = 21;
    APP_STARTUP_BROWSER_HANDSHAKE_STARTED = 11;
    APP_STARTUP_BROWSER_HANDSHAKE_ENDED = 12;
    APP_STARTUP_BROWSER_HANDSHAKE_TIMEOUT = 13;
    CHARGING_STATE_CHANGED = 3;
    NETWORK_TYPE_CHANGED = 4;
    NAVIGATION_STARTED = 5;
    NAVIGATION_ENDED = 6;
    MANUAL_CACHER_STARTED = 7;
    MANUAL_CACHER_COMPLETED = 8;
    POWER_SAVING_MODE_WILL_START = 14 [deprecated = true];
    POWER_SAVING_MODE_ENDED = 15 [deprecated = true];
    EXTERNAL_INVOCATION_STARTED = 16;
    EXTERNAL_INVOCATION_COMPLETED = 17;
    FIREBASE_SHORT_LINK_RESOLUTION_VIA_DLS_STARTED = 36;
    FIREBASE_SHORT_LINK_RESOLUTION_VIA_DLS_COMPLETED = 37;
    APP_CRASHED = 22;
    APP_REPORTED_MEMORY_PRESSURE = 26;
    WIDGET_STARTED = 27;
    TRANSIT_TRIP_TRACKING_STARTED = 30;
    TRANSIT_TRIP_TRACKING_ENDED = 31;
    APP_STALL_DETECTED = 32;
    MAP_STALL_DETECTED = 35;
    APP_UNCLEAN_EXIT_WITH_MEMORY_PRESSURE = 33;
    APP_LOADED_WITH_NO_LABELS_ON_MAP = 34;
    LOCATION_ACCURACY = 38;
    LOCATION_CURRENT_STATE = 39;
}

enum BatteryChargingState {
    UNKNOWN = 0;
    CHARGING = 1;
    NOT_CHARGING = 2;
    DISCHARGING = 3;
    FULL = 4;
}

enum ExternalPowerSource {
    NONE = 0;
    AC = 1;
    USB = 2;
    WIRELESS = 3;
    DOCK = 4;
}

enum LocationPowerSaveMode {
    LOCATION_MODE_UNKNOWN = 0;
    NO_CHANGE = 1;
    GPS_DISABLED_WHEN_SCREEN_OFF = 2;
    ALL_DISABLED_WHEN_SCREEN_OFF = 3;
    FOREGROUND_ONLY = 4;
    THROTTLE_REQUESTS_WHEN_SCREEN_OFF = 5;
}

enum LocationProviderState {
    LOCATION_PROVIDER_STATE_UNKNOWN = 0;
    HARDWARE_MISSING = 1;
    ENABLED = 2;
    DISABLED_BY_DEVICE_SETTING = 3;
    DISABLED_BY_PERMISSION_SETTING = 4;
}

enum ExternalInvocationType {
    EIT_UNKNOWN = 0;
    EIT_MAP_VIEW = 1;
    EIT_STREET_VIEW = 2;
    EIT_SEARCH = 3;
    EIT_CATEGORY_SEARCH = 140;
    EIT_DIRECTIONS = 4;
    EIT_NAVIGATION = 5;
    EIT_HANDLE_MFE_URL = 6;
    EIT_MAPS_ENGINE_MAP = 7;
    EIT_SEARCH_ALONG_ROUTE = 8;
    EIT_LOCATION_SHARING = 9;
    EIT_LOCATION_SHARING_REQUEST_LOCATION = 68;
    EIT_LOCATION_SHARING_IMESSAGE_NEW_SHARE = 111;
    EIT_LOCATION_SHARING_WIDGET = 139;
    EIT_LOCATION_SERVICES_SETTINGS = 151;
    EIT_PHOTO_SHARE = 10;
    EIT_MAPS_LOCAL_DISCOVERY = 11;
    EIT_MAPS_LOCAL_STREAM = 69;
    EIT_VOICE = 12;
    EIT_AUTH_SHGUN = 13;
    EIT_TIMELINE_NOTIFICATION = 14;
    EIT_CONTRIBUTION_PAGE = 15;
    EIT_EVENT_NOTIFICATION = 16;
    EIT_FEEDBACK = 17;
    EIT_GMM_SETTINGS = 18;
    EIT_INSTORE = 19;
    EIT_NOTIFICATION_SETTINGS = 20;
    EIT_OFFLINE = 21;
    EIT_PROFILE_PAGE = 22;
    EIT_RESET_ACTIVITY = 23;
    EIT_OOB_FLOW_ONLY = 24;
    EIT_EDIT_PUBLISHED = 25;
    EIT_RIDDLER = 26;
    EIT_TIMELINE_PUBLIC_URL = 27;
    EIT_TODO_PHOTO = 28;
    EIT_USER_PHOTOS = 29;
    DEPRECATED_EIT_LOCAL_GUIDE_SIGN_UP = 30 [deprecated = true];
    EIT_MAIN = 31;
    EIT_TRANSIT_NETWORK_STATUS = 32;
    EIT_TRAFFIC_HUB = 33;
    EIT_CONTRIBUTION_NOTIFICATION = 34;
    EIT_AUTH_TAXI = 35;
    EIT_TRANSIT_NEARBY = 36;
    EIT_REPORT_A_PROBLEM = 37;
    EIT_LAUNCHER_SHORTCUT = 38;
    EIT_PLACE_LIST_SHARED_URL = 39;
    EIT_MADDEN = 40;
    EIT_FACTUAL_MODERATION = 41;
    EIT_TAXI_RIDE_STATUS_UPDATE = 42;
    EIT_TRANSIT_STATION = 43;
    EIT_TAXI_ADD_PAYMENT = 44;
    EIT_GOOGLE_MY_BUSINESS_PLAYSTORE_NOTIFICATION = 45;
    EIT_ADD_A_PLACE = 46;
    EIT_WEBVIEW = 47;
    EIT_SAVED_PARKING = 48;
    EIT_YOUR_SAVED_PLACES = 49;
    EIT_LABELED_PLACES = 50;
    EIT_SAVED_PLACES_LIST_WITH_EMOJI_CAMPAIGN = 155;
    EIT_MISSIONS_NOTIFICATION = 51;
    EIT_PLUS_CODE_LOCATION = 52;
    EIT_REVIEWS_EDITOR = 53;
    EIT_SHOW_MAJOR_EVENT = 54;
    EIT_EDIT_ALIAS = 55;
    EIT_PLACE_QA = 56;
    EIT_TRANSIT_REROUTE = 57;
    EIT_UGC_TASKS = 58;
    EIT_UGC_POST_TRIP_QUESTIONS_NOTIFICATION = 59;
    EIT_UGC_VIEW_REVIEW = 137;
    EIT_UGC_VIEW_PHOTO_UPDATE = 138;
    EIT_TRANSIT_COMMUTE_BOARD = 60;
    EIT_DISPLAY_TIMELINE = 61;
    EIT_START_COMMUTE_SETUP = 62;
    EIT_COMMUTE_SETTINGS = 63;
    EIT_AT_A_PLACE_DEBUG = 64;
    EIT_SOCIAL_PLANNING = 65;
    EIT_TAXI_BOOK = 66;
    EIT_TRANSIT_SCHEMATIC_MAP = 67;
    EIT_CARETAKERS_PENDING_EDIT = 70;
    DEPRECATED_EIT_START_COMMUTE_SETUP_WITH_USER_CONSENT = 71 [deprecated = true];
    EIT_HOME_SCREEN = 72;
    EIT_BUSINESS_MESSAGING_NOTIFICATION = 73;
    EIT_PERSONAL_SCORE_MARKETING = 74;
    EIT_BUSINESS_MESSAGING_START_CONVERSATION = 75;
    EIT_TRANSIT_GUIDANCE_QUESTIONS = 76;
    EIT_CREATOR_ZONE = 77;
    EIT_BUSINESS_MESSAGING_MAPS_ONLY = 79;
    EIT_APRIL_FOOLS_2019 = 80;
    EIT_SERVICE_BUSINESS_POST_INTERACTION = 81;
    EIT_OFF_ROUTE_ALERTS = 82;
    EIT_REPLY_TO_REVIEWS_NOTIFICATION = 83;
    EIT_CREATOR_PROFILE = 84;
    EIT_RAP_MISSING_ROAD_DEBUG = 85;
    EIT_MEDIA_INTEGRATION_SETUP = 86;
    EIT_BUSINESS_INSIGHTS_NOTIFICATION = 87;
    EIT_WELCOME_TO_DESTINATION_NOTIFICATION = 88;
    DEPRECATED_EIT_IN_APP_SURVEY_NOTIFICATION = 89;
    EIT_GENERIC_WEBVIEW_NOTIFICATION = 90;
    EIT_INCOGNITO = 91;
    EIT_PARKING_PAYMENT = 92;
    EIT_SHOW_SEARCH_ALONG_ROUTE_PAGE = 93;
    EIT_BUSINESS_MESSAGING_MERCHANT = 94;
    EIT_DIDNT_GO_HERE = 95;
    EIT_PEOPLE_FOLLOW_LIST = 96;
    EIT_PLACESHEET = 97;
    EIT_ZERO_RATING_ACTIVATION = 98;
    EIT_MERCHANT_FRESHNESS_WIZARD = 99;
    EIT_BUSINESS_MESSAGING_OPT_OUT = 100;
    EIT_PHOTO_UPDATES_NOTIFICATION = 101;
    EIT_BUSINESS_MESSAGING_PROMO = 102;
    EIT_MERCHANT_CALL_TRACKING = 103;
    EIT_ORDER_PICKUP_OPT_IN = 104;
    EIT_MERCHANT_REVIEWS_LIST_NOTIFICATION = 105;
    EIT_LANGUAGE_PICKER_PROMO_NOTIFICATION = 106;
    EIT_ASSISTIVE_PICKUP_NOTIFICATION = 107;
    EIT_CLIENT_INVALID = 108;
    EIT_MERCHANT_BUSINESS_PROFILE_NOTIFICATION = 109;
    EIT_HOME_SCREEN_SHORTCUT = 110;
    EIT_SHORTCUT_EDITOR = 154;
    EIT_CRISIS_DETAILS = 112;
    EIT_MERCHANT_PERFORMANCE_NOTIFICATION = 113;
    EIT_MERCHANT_POSTS_NOTIFICATION = 114;
    EIT_MERCHANT_PHOTOS_OWNERS_COLLECTION_NOTIFICATION = 115;
    EIT_MERCHANT_PHOTOS_LATEST_COLLECTION_NOTIFICATION = 116;
    EIT_MERCHANT_BIZINFO_NOTIFICATION = 117;
    EIT_MERCHANT_SERVICE_LIST_NOTIFICATION = 118;
    EIT_DIRECTORY = 119;
    EIT_OMNI_MAPS_WILDFIRE = 120;
    EIT_ASSISTIVE_PICKUP_ETA_SHARING_DIALOG = 121;
    EIT_SET_PLUS_CODE_HOME_WORK_ADDRESS = 122;
    EIT_MERCHANT_TUTORIAL = 123;
    EIT_MERCHANT_VERIFY = 124;
    EIT_MERCHANT_QA = 125;
    EIT_MERCHANT_PROFILES = 126;
    EIT_OMNI_MAPS_AIR_QUALITY = 127;
    EIT_LIVE_TRIPS = 128;
    EIT_MERCHANT_VIEW_MESSAGES = 129;
    EIT_FOLLOW_STREAM = 130;
    EIT_TRAFFIC_WIDGET = 131;
    EIT_CHALLENGE_COMMUNITY_MILESTONE_NOTIFICATION = 132;
    EIT_HERE_AT_A_PLACE_MENU_NOTIFICATION = 133;
    EIT_IN_APP_UPDATE = 134;
    EIT_MERCHANT_MANAGE_MESSAGING_FAQS = 135;
    EIT_BUSINESS_MESSAGING_OPEN_INBOX = 141;
    EIT_PLACE_PHOTO_VIDEO = 142;
    EIT_MERCHANT_HUB = 143;
    EIT_TRANSIT_LINE_TRACKER = 144;
    EIT_MERCHANT_EDIT_FOOD_MENU = 145;
    EIT_MERCHANT_EDIT_FOOD_MENU_PHOTOS = 157;
    EIT_XR_EXTERNAL_CONTENT = 146;
    EIT_SET_HOME_ADDRESS = 147;
    EIT_MERCHANT_PROFILE_UPDATE = 148;
    EIT_MERCHANT_EDIT_SERVICES = 149;
    EIT_WEB_AND_APP_CONTROLS_WEBVIEW = 150;
    EIT_FITBIT_NAVIGATION_INFO_COORDINATOR = 152;
    EIT_GEOSPATIAL_LIVE_VIEW = 153;
    EIT_MAPS_GUIDE_LANDING_PAGE = 156;
    EIT_EDIT_SOCIAL_PROFILES = 158;
    EIT_ARRIVAL_ISSUE_NOTIFICATION = 159;
    EIT_WRITE_REVIEW_SEARCH = 160;
    EIT_SETTINGS = 161;
    EIT_MIRRORING_CONFIGURATION = 162;
    EIT_FIX_AN_ADDRESS = 163;
    EIT_WEARABLE_COMPASS_VIEW = 164;
    EIT_SEARCH_CATEGORY_OPTIONS = 165;
    EIT_RECENT_HISTORY = 166;
    EIT_PLACESHEET_HOME = 167;
    EIT_PLACESHEET_WORK = 168;
    EIT_EXTERNAL_TRIP_SHARING = 169;
    EIT_INFERRED_DIRECTIONS_DRIVING_CONGESTION_NOTIFICATION = 170;
    EIT_MERCHANT_ASSISTANT = 171;
    EIT_NAVATAR_SETTINGS = 172;
    EIT_TRANSIT_METRO_TICKET_BOOKING = 173;
    EIT_UGC_MOTIVATION = 174;
    EIT_CARPLAY_FULLSCREEN_APP = 175;
    EIT_CARPLAY_DASHBOARD = 176;
    EIT_CARPLAY_CLUSTER = 177;
    EIT_ENTERPRISE_ACTION_NAVIGATION_CONNECT = 178;
    EIT_MERCHANT_LOCAL_INSIGHTS = 179;
    EIT_OPT_IN_EXPERIENCE = 180;
    EIT_WRITE_REVIEW = 181;
    EIT_SHORTLIST = 182;
    EIT_ASK_MAPS = 183;
}

enum BadInvocationErrorDomain {
    UNKNOWN_BAD_INVOCATION_ERROR_DOMAIN = 0;
    BAD_INVOCATION_ERROR_NSURL = 1;
    BAD_INVOCATION_ERROR_GRPC = 2;
    BAD_INVOCATION_ERROR_CF_NETWORK = 3;
    BAD_INVOCATION_ERROR_FETCHER_STATUS = 4;
    BAD_INVOCATION_ERROR_FETCHER = 5;
    BAD_INVOCATION_ERROR_DIRECTION_SERVICE = 6;
    BAD_INVOCATION_ERROR_BACKEND = 7;
    BAD_INVOCATION_ERROR_FIREBASE_SHORT_LINK_RESOLUTION = 8;
}

enum PredictedNetworkQuality {
    PREDICTED_NETWORK_QUALITY_UNKNOWN = 0;
    UNINITIALIZED = 1;
    NOT_CATEGORIZED = 2;
    DOWN_THROUGHPUT_UNDER_100000_BPS = 3;
}
