syntax = "editions";

package geo_serving_proto.attribution;

import "java/com/google/apps/jspb/jspb.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option features = utf8_validation: NONE
;
option objc_class_prefix = "GSPATT";
option java_multiple_files = true;
option java_outer_classname = "TopicKeyProto";
option java_package = "com.google.geo.serving.proto.attribution";

message TopicKey {
    oneof key {
        string mid = 1;
        string gcid = 2;
        fixed64 city_fprint = 3 [jstype = JS_STRING];
    }
}
