syntax = "proto2";

package geo_serving_proto.attribution;

import "geo/serving/proto/attribution/user_caption.proto";
import "geo/serving/proto/link/link.proto";
import "java/com/google/apps/jspb/jspb.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option objc_class_prefix = "GSPATT";
option java_multiple_files = true;
option java_outer_classname = "UserAttributionProto";
option java_package = "com.google.geo.serving.proto.attribution";

message UserAttribution {
    optional string uploader_name = 1;
    optional string uploader_thumbnail_url = 2;
    optional geo_serving_proto.link.Link profile_link = 3;
    optional string obfuscated_gaia_id = 4;
    
    optional LocalGuideInfo local_guide_info = 9;
    message LocalGuideInfo {
        optional bool is_local_guide = 3;
        optional bool received_local_guide_badge = 1;
        optional int32 eligible_local_guide_level = 2;
    }
    
    optional int32 num_public_reviews = 6;
    optional int32 num_public_ratings = 10;
    optional int32 num_public_photos = 7;
    optional UserCaption caption = 11;
    
    reserved 5, 8, 12;
}
