syntax = "proto2";

package travel.frontend.common.proto.amenities;

import "logs/proto/feature/tree_ref.proto";
import "logs/proto/logs_annotations/logs_annotations.proto";
import "webutil/html/types/proto/html.proto";

option java_multiple_files = true;
option java_package = "com.google.travel.frontend.common.proto.amenities";

message HotelAmenities {
    repeated AttributeGroup attribute_groups = 1;
    repeated Attribute featured_attributes = 2;
    optional HealthAndSafetyInfo health_and_safety = 3;
    optional SustainabilityInfo sustainability = 4;
    optional AttributeGroup essential_info = 5;
}

message HealthAndSafetyInfo {
    repeated AttributeGroup health_and_safety_groups = 1;
    optional string health_and_safety_measures_uri = 2;
}

message SustainabilityInfo {
    repeated AttributeGroup sustainability_groups = 1;
    optional bool is_eco_certified = 2;
}

message AttributeGroup {
    optional AttributeGroupType type = 1;
    repeated Attribute attributes = 2;
    optional bool is_contextual = 3;
}

message Attribute {
    optional bool is_positive = 1;
    optional AttributeType attribute = 2;
    optional AttributeBadgeType badge = 3;
    optional bool is_applied = 4;
    optional SnippetInfo snippet = 5;
    optional logs.feature.TreeRef tree_ref = 6;
    optional string formatted_display_label = 7;
    
    extensions 470763916;
}

message SnippetInfo {
    optional string sentence = 1;
    optional webutil.html.types.SafeUrlProto source_link = 2;
    optional webutil.html.types.SafeUrlProto source_link_chrome = 78;
    optional webutil.html.types.SafeHtmlProto highlighted_text = 3;
    optional webutil.html.types.SafeHtmlProto source_domain_name = 4;
    optional webutil.html.types.SafeHtmlProto source_link_title = 5;
    optional webutil.html.types.SafeUrlProto favicon_url = 6;
    optional bool is_contextual = 7;
}

enum AttributeGroupType {
    UNKNOWN_ATTRIBUTE_GROUP_TYPE = 0;
    ACCESSIBILITY = 2;
    ACTIVITIES = 3;
    BATHROOMS = 20;
    BUSINESS_AND_EVENTS = 4;
    CHILDREN = 5;
    FOOD_AND_DRINK = 6;
    INTERNET = 7;
    LANGUAGES_SPOKEN = 21;
    PARKING_AND_TRANSPORTATION = 8;
    PETS = 9;
    POLICIES_AND_PAYMENTS = 10;
    POOLS = 11;
    PUBLIC_BATH = 27;
    ROOMS = 12;
    SERVICES = 13;
    WELLNESS = 14;
    ENHANCED_CLEANING = 15;
    MINIMIZED_CONTACT = 16;
    PHYSICAL_DISTANCING = 17;
    PERSONAL_PROTECTION = 18;
    INCREASED_FOOD_SAFETY = 19;
    ENERGY_EFFICIENCY = 22;
    WATER_CONSERVATION = 23;
    WASTE_REDUCTION = 24;
    SUSTAINABLE_SOURCING = 25;
    ECO_CERTIFICATIONS = 26;
}

enum AttributeType {
    UNKNOWN_ATTRIBUTE_TYPE = 0;
    ADULT_POOL = 86;
    AESTHETIC_SALON = 259;
    AIRPORT_SHUTTLE = 1;
    AIR_CONDITIONING = 2;
    AIR_CONDITIONING_ALL_ROOMS = 163;
    AIR_CONDITIONING_SOME_ROOMS = 164;
    ALL_INCLUSIVE_AVAILABLE = 3;
    ALL_INCLUSIVE_ONLY = 32;
    ARABIC_SPOKEN = 87;
    ARTIFICIAL_ONSEN = 265;
    BABYSITTING = 43;
    BAGGAGE_STORAGE = 51;
    BANQUET_HALL = 258;
    BAR = 4;
    BATHTUB_ALL_ROOMS = 88;
    BATHTUB_SOME_ROOMS = 89;
    BEACH_ACCESS = 5;
    BEACH_FRONT = 46;
    BEDROCK_BATH = 268;
    BICYCLES_RENTAL = 41;
    BOUTIQUE_STORES = 90;
    BREAKFAST_AVAILABLE = 54;
    BREAKFAST_BUFFET = 56;
    BREAKFAST_FOR_FREE = 6;
    BREAKFAST_PAID = 165;
    BUFFET_DINNER = 91;
    BUSINESS_CENTER = 7;
    CANTONESE_SPOKEN = 92;
    CAR_RENTAL_ON_PROPERTY = 39;
    CASH = 93;
    CASINO = 36;
    CATS_ALLOWED = 94;
    CHEQUE = 95;
    COFFEE_MAKER_ALL_ROOMS = 96;
    COFFEE_MAKER_SOME_ROOMS = 97;
    CONCIERGE = 38;
    CONVENIENCE_STORE = 40;
    CREDIT_CARD = 37;
    CURRENCY_EXCHANGE = 42;
    DEBIT_CARD = 98;
    DOCTOR_ON_CALL = 99;
    DOGS_ALLOWED = 100;
    DUTCH_SPOKEN = 101;
    ELEVATOR = 103;
    ELLIPTICAL_MACHINE = 104;
    ENGLISH_SPOKEN = 105;
    FAMILY_BATH = 263;
    FILIPINO_SPOKEN = 106;
    FITNESS_CENTER = 8;
    FREE_WEIGHTS = 107;
    FRENCH_SPOKEN = 108;
    FRONT_DESK = 33;
    GAME_ROOM = 55;
    GERMAN_SPOKEN = 109;
    GIFT_SHOP = 110;
    GOLF = 9;
    HAIR_SALON = 52;
    HINDI_SPOKEN = 111;
    HORSEBACK_RIDING = 47;
    HOT_TUB = 10;
    HOUSEKEEPING_AVAILABLE = 112;
    INDONESIAN_SPOKEN = 113;
    ITALIAN_SPOKEN = 114;
    JACUZZI = 266;
    JAPANESE_SPOKEN = 115;
    KARAOKE = 257;
    KIDS_ACTIVITIES = 116;
    KIDS_CLUB = 117;
    KID_FRIENDLY = 11;
    KITCHEN_IN_ROOMS_ALL = 12;
    KITCHEN_IN_ROOMS_SOME = 14;
    KOREAN_SPOKEN = 118;
    LAUNDRY_FULL_SERVICE = 31;
    LAUNDRY_SELF_SERVICE = 119;
    LAZY_RIVER = 120;
    LIFEGUARD = 121;
    LOCAL_SHUTTLE = 122;
    MANDARIN_SPOKEN = 123;
    MASSAGE = 35;
    MEETING_ROOMS = 124;
    MICROWAVE_ALL_ROOMS = 125;
    MICROWAVE_SOME_ROOMS = 126;
    MINIBAR_ALL_ROOMS = 127;
    MINIBAR_SOME_ROOMS = 128;
    MIXED_BATHING = 269;
    MOBILE_NFC = 129;
    MOBILITY_ACCESSIBLE_ELEVATOR = 130;
    MOBILITY_ACCESSIBLE_PARKING = 131;
    MOBILITY_ACCESSIBLE_POOL = 132;
    NATURAL_ONSEN = 264;
    NIGHTCLUB = 45;
    ONSEN = 166;
    OPEN_AIR_BATH = 262;
    PARKING_AVAILABLE = 15;
    PARKING_FOR_FREE = 16;
    PARKING_PAID = 17;
    PETS_ALLOWED = 18;
    POOL_AVAILABLE = 19;
    POOL_INDOORS = 20;
    POOL_INDOORS_AND_OUTDOORS = 21;
    POOL_OUTDOORS = 22;
    PORTUGUESE_SPOKEN = 133;
    PRIVATE_BATHROOM_ALL_ROOMS = 135;
    PRIVATE_BATHROOM_SOME_ROOMS = 136;
    PRIVATE_BEACH = 134;
    PRIVATE_CAR_SERVICE = 137;
    PUBLIC_BATH_ROOM = 261;
    PUBLIC_INTERNET_TERMINAL = 138;
    REFRIGERATOR_ALL_ROOMS = 139;
    REFRIGERATOR_SOME_ROOMS = 140;
    RESTAURANT = 23;
    ROOM_SERVICE = 24;
    RUSSIAN_SPOKEN = 141;
    SALON = 142;
    SAUNA = 34;
    SCUBA = 49;
    SELF_PARKING_AVAILABLE = 143;
    SHOWER_ALL_ROOMS = 144;
    SHOWER_SOME_ROOMS = 145;
    SMOKE_FREE_PROPERTY = 25;
    SNORKELING = 48;
    SOCIAL_HOUR = 146;
    SPA = 26;
    SPANISH_SPOKEN = 147;
    TABLE_SERVICE = 148;
    TABLE_TENNIS = 260;
    TENNIS = 44;
    THERMAL_POOL = 149;
    TRANSFER = 150;
    TREADMILL = 151;
    TURNDOWN_SERVICE = 152;
    VALET_PARKING_AVAILABLE = 153;
    VENDING_MACHINE = 154;
    VIETNAMESE_SPOKEN = 155;
    WADING_POOL = 156;
    WAKE_UP_CALLS = 157;
    WATERCRAFT_RENTAL = 50;
    WATERSLIDE = 159;
    WATER_BATH = 267;
    WATER_PARK = 158;
    WATER_SKIING = 53;
    WAVE_POOL = 160;
    WEIGHT_MACHINE = 161;
    WHEELCHAIR_ACCESSIBLE = 27;
    WHEELCHAIR_RENTAL = 270;
    WIFI_AVAILABLE = 28;
    WIFI_FOR_FREE = 29;
    WIFI_IN_PUBLIC_AREAS = 162;
    WIFI_PAID = 30;
    COMMON_AREAS_ENHANCED_CLEANING = 57;
    GUEST_ROOMS_ENHANCED_CLEANING = 58;
    PROPERTY_ENHANCED_CLEANING = 59;
    COMMERCIAL_GRADE_DISINFECTANT_CLEANING = 60;
    DISINFECTANT_CLEANING = 61;
    EMPLOYEES_TRAINED_CLEANING_PROCEDURES = 62;
    EMPLOYEES_TRAINED_HAND_WASHING_PROTOCOLS = 63;
    EMPLOYEES_WEAR_PROTECTIVE_EQUIPMENT = 64;
    FOOD_PREPARATION_AND_SERVING_SAFE_HANDLING = 65;
    FOOD_AREAS_ADDITIONAL_SANITATION = 66;
    INDIVIDUAL_PACKAGED_MEALS_AVAILABLE = 67;
    DISPOSABLE_FLATWARE = 68;
    SINGLE_USE_FOOD_MENUS = 69;
    NO_HIGH_TOUCH_ITEMS_COMMON_AREAS = 70;
    NO_HIGH_TOUCH_ITEMS_GUEST_ROOMS = 71;
    DIGITAL_GUEST_ROOM_KEYS = 72;
    PLASTIC_KEYCARDS_DISINFECTED = 73;
    ROOM_BOOKINGS_BUFFER = 74;
    HOUSEKEEPING_SCHEDULED_REQUEST_ONLY = 75;
    CONTACTLESS_CHECKIN_CHECKOUT = 76;
    COMMON_AREAS_OFFER_SANITIZING_ITEMS = 77;
    GUEST_ROOM_HYGIENE_KITS_AVAILABLE = 78;
    PROTECTIVE_EQUIPMENT_AVAILABLE = 79;
    FACE_MASK_REQUIRED = 80;
    PHYSICAL_DISTANCING_REQUIRED = 81;
    PLEXIGLASS_USED = 82;
    SHARED_AREAS_LIMITED_OCCUPANCY = 83;
    WELLNESS_AREAS_HAVE_PRIVATE_SPACES = 84;
    COMMON_AREAS_PHYSICAL_DISTANCING_ARRANGED = 85;
    CARBON_FREE_ENERGY = 167;
    EFFICIENT_HEATING_AND_COOLING = 168;
    EFFICIENT_LIGHTING = 169;
    ELECTRIC_CAR_CHARGING_STATIONS = 102;
    ENERGY_CONSERVATION_PROGRAM = 170;
    ENERGY_SAVING_THERMOSTATS = 171;
    ENERGY_USE_AUDITED = 172;
    GREEN_BUILDING_DESIGN = 173;
    REUSE_PROGRAM_LINENS = 174;
    REUSE_PROGRAM_LINENS_AND_TOWELS = 175;
    REUSE_PROGRAM_TOWELS = 176;
    WATER_EFFICIENT_FAUCETS = 177;
    WATER_EFFICIENT_SHOWERS = 178;
    WATER_EFFICIENT_TOILETS = 179;
    WATER_EFFICIENT_FAUCETS_AND_SHOWERS = 180;
    WATER_EFFICIENT_FAUCETS_AND_TOILETS = 181;
    WATER_EFFICIENT_FAUCETS_AND_SHOWERS_AND_TOILETS = 182;
    WATER_EFFICIENT_SHOWERS_AND_TOILETS = 183;
    WATER_USE_AUDITED = 184;
    COMPOSTABLE_FOOD_CONTAINERS_CUTLERY = 185;
    DONATION_PROGRAM_SOAP = 186;
    DONATION_PROGRAM_SOAP_AND_TOILETRIES = 187;
    DONATION_PROGRAM_TOILETRIES = 188;
    EXCESS_FOOD_COMPOSTED = 189;
    EXCESS_FOOD_DONATED = 190;
    EXCESS_FOOD_DONATED_AND_COMPOSTED = 191;
    FOOD_WASTE_REDUCTION_PROGRAM = 192;
    NO_SINGLE_USE_PLASTIC_STRAWS = 193;
    NO_SINGLE_USE_PLASTIC_WATER_BOTTLES = 194;
    NO_SINGLE_USE_PLASTIC_WATER_BOTTLES_OR_STRAWS = 195;
    NO_STYROFOAM_FOOD_CONTAINERS = 196;
    RECYCLING_PROGRAM = 197;
    REFILLABLE_TOILETRY_CONTAINERS = 198;
    SAFE_DISPOSAL_BATTERIES = 199;
    SAFE_DISPOSAL_ELECTRONICS = 200;
    SAFE_DISPOSAL_LIGHTBULBS = 201;
    SAFE_DISPOSAL_BATTERIES_AND_ELECTRONICS = 202;
    SAFE_DISPOSAL_BATTERIES_AND_ELECTRONICS_AND_LIGHTBULBS = 203;
    SAFE_DISPOSAL_BATTERIES_AND_LIGHTBULBS = 204;
    SAFE_DISPOSAL_ELECTRONICS_AND_LIGHTBULBS = 205;
    SAFELY_HANDLES_HAZARDOUS_SUBSTANCES = 207;
    WATER_BOTTLE_FILLING_STATION = 208;
    ECO_FRIENDLY_TOILETRIES = 209;
    LOCALLY_SOURCED_FOOD_AND_BEVERAGES = 210;
    MEALS_VEGAN = 211;
    MEALS_VEGAN_AND_VEGETARIAN = 212;
    MEALS_VEGETARIAN = 213;
    ORGANIC_CAGE_FREE_EGGS = 214;
    ORGANIC_FOOD_AND_BEVERAGES = 215;
    RESPONSIBLE_PURCHASING_POLICY = 216;
    RESPONSIBLY_SOURCED_SEAFOOD = 217;
    ABCD_TOURISM_LANOTETOURISTIQUE = 328;
    ACTIVELY_GREEN = 288;
    AESA = 218;
    ARC360 = 312;
    AUDUBON_INTERNATIONAL = 329;
    AUSTRIAN_ECOLABEL = 289;
    BETTERFLY = 351;
    BEYOND_GREEN = 313;
    BIOLIA = 331;
    BIOSCORE_SUSTAINABLE = 290;
    BIOSPHERE_RESPONSIBLE_TOURISM_STANDARD = 219;
    BIO_HOTELS = 314;
    BREEAM = 252;
    BREEAM_EXCELLENT = 223;
    BREEAM_GOOD = 221;
    BREEAM_OUTSTANDING = 224;
    BREEAM_PASS = 220;
    BREEAM_VERY_GOOD = 222;
    BUREAU_VERITAS = 225;
    B_LAB_GLOBAL = 330;
    CENIA_EFS = 291;
    CERTIFIED_GREEN_HOTEL = 292;
    CHINA_HOSPITALITY_ASSOCIATION = 332;
    CLIMATEPARTNER = 333;
    CONTROL_UNION = 226;
    COSTA_RICA_SUSTAINABLE_TOURISM = 293;
    DCA_ESG = 294;
    DEHOGA_UMWELTCHECK = 295;
    EARTHCHECK = 227;
    ECOSMART = 315;
    ECOSTARS = 296;
    ECOTOURISM_AUSTRALIA_ECO_CERITIFICATION_STANDARD = 229;
    ECOTOURISM_KENYA_ECO_RATING = 297;
    ECOWORLDHOTEL = 316;
    ECO_CERTIFICATION_MALTA_STANDARD = 228;
    ECO_CLIMATE_BADGE = 352;
    ECO_ROMANIA = 334;
    EDGE_GREEN_BUILDING = 317;
    EMAS = 318;
    ENVIRONMENTALLY_FRIENDLY_SERVICE = 319;
    EU_ECOLABEL = 298;
    FAIRMOOVE_ENVIRONMENTAL_FOOTPRINT = 355;
    FAIR_TRADE_TOURISM = 299;
    FIFTY_SHADES_GREENER = 335;
    FONDATION_LES_PAGES_VERTES = 336;
    FUTUREPLUS = 320;
    GLOBAL_ECOSPHERE_RETREATS_STANDARD = 300;
    GREAT_GREEN_DEAL = 230;
    GREEN_DESTINATIONS = 321;
    GREEN_GLOBE = 231;
    GREEN_GROWTH_2050_STANDARD = 232;
    GREEN_HOSPITALITY = 301;
    GREEN_KEY = 233;
    GREEN_KEY_ECO_RATING = 254;
    GREEN_LEAF_FOUNDATION = 337;
    GREEN_PEARLS_UNIQUE_PLACES = 302;
    GREEN_REAL_ESTATE_GREENRE = 338;
    GREEN_SEAL = 234;
    GREEN_SIGN = 303;
    GREEN_STAR_HOTEL_STANDARD = 235;
    GREEN_STEP_SUSTAINABLE_TOURISM = 304;
    GREEN_TOURISM = 305;
    GREEN_TOURISM_ACTIVE_STANDARD = 236;
    GSTC_CRITERIA = 322;
    HILTON_LIGHTSTAY = 237;
    HOSTELLING_INTERNATIONAL_QUALITY_AND_SUSTAINABILITY_STANDARD = 238;
    HOTELES_MAS_VERDES = 239;
    HOTEL_SUSTAINABILITY_BASICS = 339;
    IBEX_FAIRSTAY = 306;
    INTERTEK_ECOCHECK_STANDARD = 340;
    ISO_14001 = 241;
    ISO_50001 = 240;
    ISO_9001 = 307;
    JEA_ECO_MARK_PROGRAMME = 341;
    LEED = 253;
    LEED_CERTIFIED = 245;
    LEED_GOLD = 243;
    LEED_PLATINUM = 242;
    LEED_SILVER = 244;
    MIOSOTIS_AZORES_STANDARD = 350;
    MISSION_ZERO_ACADEMY_MIZA = 349;
    NABERS_ENERGY = 342;
    NABERS_WATER = 343;
    NORDIC_SWAN_ECOLABEL = 246;
    PREFERRED_BY_NATURE = 247;
    QIA_SERVICES = 344;
    QUALMARK = 345;
    QUEERVADIS = 353;
    SAKURA_QUALITY = 255;
    SERNATUR_SELLO = 308;
    SEYCHELLES_SUSTAINABLE_TOURISM_LABEL = 309;
    SMARTCERTIFICATIONIT = 346;
    SOCOTEC_SUMS = 310;
    SUSTAINABLE_MEETINGS_BERLIN = 323;
    SUSTAINABLE_TOURISM_NETWORK = 354;
    SUSTAINABLE_TRAVEL_IRELAND = 248;
    SUSTONICA_SUSTAINABLE_VACATION_RENTAL = 324;
    THE_LONG_RUN = 347;
    TOFTIGERS_FOOTPRINT = 311;
    TOFTIGERS_INITIATIVE_PUG = 249;
    TOURCERT_CERTIFICATION = 325;
    TRAVELIFE_STANDARD = 250;
    TUDESTINO_SOSTENIBLE = 348;
    TURKIYE_SUSTAINABLE_TOURISM_PROGRAM = 326;
    UNITED_CERTIFICATION_SYSTEMS_LIMITED = 251;
    VIABONO = 327;
    VIREO_SRL = 206;
    WYNDHAM_GREEN = 256;
    ENTIRE_HOUSE = 271;
    ENTIRE_APARTMENT = 272;
    NUM_SLEEPS = 273;
    NUM_BEDS = 274;
    NUM_BATHS = 275;
    NUM_BEDROOMS = 276;
    SQ_FEET_OR_METERS = 277;
    BALCONY = 278;
    CRIB = 279;
    FIRE_PLACE = 280;
    HEATING = 281;
    IRONING_BOARD = 282;
    MICROWAVE = 283;
    OUTDOOR_GRILL = 284;
    PATIO = 285;
    TV = 286;
    WASHER_DRYER = 287;
}

enum AttributeBadgeType {
    DEFAULT_NONE = 0;
    FREE = 1;
    EXTRA_CHARGE = 2;
    HOURS_24 = 3;
    DAILY = 4;
}
