syntax = "proto2";

package maps_paint_client;

option objc_class_prefix = "GMPC";
option java_multiple_files = true;
option java_package = "com.google.maps.paint.client";

enum VertexResolution {
    RESOLUTION_UNKNOWN = 0;
    RESOLUTION_4TH_PIXEL = 2;
    RESOLUTION_8TH_PIXEL = 3;
    RESOLUTION_16TH_PIXEL = 1;
    RESOLUTION_32ND_PIXEL = 4;
    RESOLUTION_64TH_PIXEL = 5;
    RESOLUTION_128TH_PIXEL = 6;
    RESOLUTION_256TH_PIXEL = 7;
    RESOLUTION_512TH_PIXEL = 8;
    RESOLUTION_1KTH_PIXEL = 9;
    RESOLUTION_2KTH_PIXEL = 10;
    RESOLUTION_4KTH_PIXEL = 11;
    RESOLUTION_8KTH_PIXEL = 12;
    RESOLUTION_16KTH_PIXEL = 13;
    RESOLUTION_32KTH_PIXEL = 14;
    RESOLUTION_64KTH_PIXEL = 15;
    RESOLUTION_128KTH_PIXEL = 16;
    RESOLUTION_256KTH_PIXEL = 17;
    RESOLUTION_512KTH_PIXEL = 18;
    RESOLUTION_1MTH_PIXEL = 19;
    RESOLUTION_2MTH_PIXEL = 20;
    RESOLUTION_4MTH_PIXEL = 21;
}

enum VertexEncoding {
    ENCODING_UNKNOWN = 0;
    ENCODING_SEQUENTIAL_VARINT = 1;
    ENCODING_SEQUENTIAL_FIXED16 = 2;
    ENCODING_DELTA_VARINT = 3;
}

enum Line3DEncoding {
    LINE_3D_ENCODING_UNKNOWN = 0;
    LINE_3D_ENCODING_DRACO = 1;
    LINE_3D_ENCODING_LAT_LNG_E7_ALT_FLOAT = 2;
}
