syntax = "proto2";

package maps_paint_client;

import "java/com/google/apps/jspb/jspb.proto";

option objc_class_prefix = "GMPC";
option java_multiple_files = true;
option java_package = "com.google.maps.paint.client";

message StyleTransforms {
    reserved 1;
    
    message Transform {
        optional int32 tag = 1;
        repeated int32 input_style_id = 2 [packed = true];
        repeated int32 output_style_id = 3 [packed = true];
    }
    
    enum Tag {
        TRANSFORM_UNKNOWN = 0;
        TRANSFORM_PINLET_TO_DOT = 1;
        TRANSFORM_FOR_TESTING = 2;
        TRANSFORM_BUSINESS_CLOSED = 3 [deprecated = true];
        TRANSFORM_EV_COMPATIBLE_STATION_14 = 4;
        TRANSFORM_EV_COMPATIBLE_STATION_15 = 5;
        TRANSFORM_EV_COMPATIBLE_STATION_16 = 6;
        TRANSFORM_EV_COMPATIBLE_STATION_17 = 7;
        TRANSFORM_RECENTLY_VIEWED_RESULT = 8;
        TRANSFORM_SELECTED = 10;
        TRANSFORM_TEMPORARILY_CLOSED = 11;
        TRANSFORM_RECOMMENDATION = 12 [deprecated = true];
        TRANSFORM_HIGHLIGHT = 15;
        TRANSFORM_MERCHANT_POSTS = 24 [deprecated = true];
        TRANSFORM_REGULATED_AREA = 14 [deprecated = true];
        TRANSFORM_MEDIUM_LIVE_BUSYNESS = 25;
        TRANSFORM_HIGH_LIVE_BUSYNESS = 26;
        TRANSFORM_CATEGORY_BOOST_RELATED_PLACES = 28 [deprecated = true];
        TRANSFORM_DISABLE_DURING_SEARCH = 29;
        TRANSFORM_SEARCH_NEARBY = 30;
        TRANSFORM_MUTE_NON_RESULT_POIS = 37;
        TRANSFORM_TOP_RATED_SEARCH_RESULT = 38 [deprecated = true];
        TRANSFORM_CHEAPEST_SEARCH_RESULT = 40 [deprecated = true];
        TRANSFORM_SECONDARY_POSITION = 39 [deprecated = true];
        TRANSFORM_NO_OP_NON_RESULTS = 41;
        TRANSFORM_AREA_BUSYNESS = 42;
        TRANSFORM_AREA_BUSYNESS_DARK_LAUNCH = 43 [deprecated = true];
        TRANSFORM_AREA_BUSYNESS_NO_STROKE_CHANGE = 70;
        TRANSFORM_PHOTO_PIN = 44;
        TRANSFORM_EMPHASIZED_POI = 45 [deprecated = true];
        TRANSFORM_EMPHASIZED_POI_BOLD = 46;
        TRANSFORM_HIDE_NON_RESULT_POIS = 47;
        TRANSFORM_DISABLE_TINY_REPRESENTATION_FOR_RASTER = 58;
        TRANSFORM_TRAVEL_MAP_HIDE_PRIMARY_LAYER = 48;
        TRANSFORM_PHOTO_PIN_WITH_PADDING = 49;
        TRANSFORM_SMALL_SEARCH_PHOTO_PIN_WITH_PADDING = 82;
        TRANSFORM_BROWSE_TO_DECIDE_HIDE_CITY_LABELS = 50;
        TRANSFORM_TRAVEL_AREA_OF_INTEREST = 51;
        TRANSFORM_TRAVEL_CORRIDOR_OF_INTEREST = 59;
        TRANSFORM_TRAVEL_MAP_LOST_CLUSTER = 64;
        TRANSFORM_TOURIST_CORRIDOR = 52;
        TRANSFORM_INDOOR_MAP_AVAILABLE = 53;
        TRANSFORM_EXPLORE_THIS_AREA_FOOD_AND_DRINK = 54;
        TRANSFORM_EXPLORE_THIS_AREA_SHOPPING = 55;
        TRANSFORM_EXPLORE_THIS_AREA_ATTRACTIONS = 56;
        TRANSFORM_25D_NAV_DESTINATION_HIGHLIGHT = 60;
        TRANSFORM_OCCLUDED_NAV_POLYLINE = 61;
        TRANSFORM_3D_BUILDING_HIGHLIGHT = 62;
        TRANSFORM_REMOVE_PISA_BUILDING_FOOTPRINT = 80;
        TRANSFORM_TRANSIT_ENTRANCE_SELECT = 63;
        TRANSFORM_ICONIC_TO_POI = 65;
        TRANSFORM_REMOVE_SUBTITLES = 66;
        TRANSFORM_TRANSIT_DIRECTIONS_HIDE_STATIONS_ON_ROUTE = 67;
        TRANSFORM_TRANSIT_DIRECTIONS_STATIONS_ON_ROUTE = 68;
        TRANSFORM_PERSONAL_EVENT_PIN = 69;
        TRANSFORM_ROUTE_RELEVANT_ROAD_LABELS = 71;
        TRANSFORM_NON_ROUTE_RELEVANT_ROAD_LABELS = 73;
        TRANSFORM_NON_ROUTE_RELEVANT_ROAD_TEXT_LABELS = 78;
        TRAVEL_MAP_TRANSFORM_PHOTO_PINS_TRANSPARENT = 72;
        TRANSFORM_TACTILE_MAP_HOVER = 74 [deprecated = true];
        TRANSFORM_TACTILE_HIDE = 75;
        TRANSFORM_TACTILE_TRANSITION_POI_ICON = 76;
        TRANSFORM_TACTILE_TRANSITION_SEARCH_NEARBY_ICON = 77;
        TRANSFORM_TACTILE_HOVER = 79;
        TRANSFORM_REMOVE_BACKGROUND_CONTENT = 81;
        TRANSFORM_MANEUVER_LANDMARK_HIGHLIGHT = 83;
    }
}
