syntax = "proto2";

package maps_paint_client;

import "java/com/google/apps/jspb/jspb.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option objc_class_prefix = "GMPC";
option java_multiple_files = true;
option java_package = "com.google.maps.paint.client";

message MapElementId {
    oneof id_type {
        fixed64 id = 1;
        bytes id_bytes = 2;
    }
    
    oneof id_namespace {
        int32 namespace_id = 3;
        bytes namespace_bytes = 4;
    }
}

message MapElementIdList {
    repeated IdGroup id_group = 1;
    message IdGroup {
        oneof id_list_type {
            Fixed64List fixed64_ids = 1;
            BytesList bytes_ids = 2;
        }
        
        oneof id_namespace {
            int32 namespace_id = 3;
            bytes namespace_bytes = 4;
        }
    }
    
    message Fixed64List {
        repeated fixed64 id = 1 [packed = true];
    }
    
    message BytesList {
        repeated bytes id = 1;
    }
}
