syntax = "proto2";

package maps_paint;

import "java/com/google/apps/jspb/jspb.proto";
import "maps/paint/proto/styler-description.proto";
import "net/proto2/contrib/js_proto/public/field_annotations.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option objc_class_prefix = "GMP";
option java_multiple_files = true;
option java_outer_classname = "PaintStyleOptionsProto";
option java_package = "com.google.maps.paint";

message PaintStyleOptions {
    optional string language_code = 2;
    optional string country_code = 3;
    optional bool has_debug_ip = 4;
    
    optional MapSource source = 5 [default = MAP_SOURCE_UNKNOWN];
    enum MapSource {
        MAP_SOURCE_UNKNOWN = 0;
        MAP_SOURCE_WEB = 4;
        MAP_SOURCE_APPLICATION = 65;
        MAP_SOURCE_STREETVIEW = 66;
        MAP_SOURCE_LOCAL_UNIVERSAL = 67;
        MAP_SOURCE_LOCAL_UNIVERSAL_TRANSIT_STATION = 1073;
        MAP_SOURCE_MOBILE_WEB_MAPS = 68;
        MAP_SOURCE_VECTOR = 69;
        MAP_SOURCE_TACTILE = 1105;
        MAP_SOURCE_TACTILE_GWS = 17681;
        MAP_SOURCE_TACTILE_SHARE = 17682;
        MAP_SOURCE_MOBILE_FE = 70;
        MAP_SOURCE_PRODUCT_SEARCH = 71;
        MAP_SOURCE_STATIC_MAP = 72;
        MAP_SOURCE_MYACCOUNT_HOME_WORK = 1153;
        MAP_SOURCE_MAPMAKER = 73 [deprecated = true];
        MAP_SOURCE_GT_ATLAS_DEPRECATED = 74;
        MAP_SOURCE_LOCATION_PLUS = 75;
        MAP_SOURCE_SMARTMAIL = 76;
        MAP_SOURCE_ELECTIONS = 77;
        MAP_SOURCE_MAPS_LITE = 78;
        MAP_SOURCE_MAPS_LITE_PWA = 1249;
        MAP_SOURCE_AWFE = 1265;
        MAP_SOURCE_PUBLICALERTS = 1266;
        MAP_SOURCE_IMAGE_SEARCH = 1267;
        MAP_SOURCE_KNOWLEDGE = 1268;
        MAP_SOURCE_KNOWLEDGE_CRISIS = 20289;
        MAP_SOURCE_HOTELS = 1269;
        MAP_SOURCE_TRAVEL_SEARCH_MAP = 1270;
        MAP_SOURCE_VISIT_GUIDE = 1271;
        MAP_SOURCE_AI_MODE = 1272;
        MAP_SOURCE_WEB_GEOXP_EMBED = 1273;
        MAP_SOURCE_API = 1;
        MAP_SOURCE_JS_V3_API = 18;
        MAP_SOURCE_JS_V3_API_EMBED = 289;
        MAP_SOURCE_JS_V3_API_EARTH_ENGINE = 290;
        MAP_SOURCE_ANDROID_API = 20;
        MAP_SOURCE_ANDROID_API_V1 = 321;
        MAP_SOURCE_ANDROID_API_V2 = 322;
        MAP_SOURCE_ANDROID_API_V2_GLASS = 5153;
        MAP_SOURCE_ANDROID_API_V3 = 323;
        MAP_SOURCE_ANDROID_API_V3_WITH_NAV = 5169;
        MAP_SOURCE_ANDROID_API_VB = 324;
        MAP_SOURCE_IPHONE_API = 21;
        MAP_SOURCE_IPHONE_API_V1 = 337;
        MAP_SOURCE_IPHONE_API_V2 = 338;
        MAP_SOURCE_IPHONE_API_V2_WITH_NAV = 5409;
        MAP_SOURCE_STREETVIEW_API = 22;
        MAP_SOURCE_STATIC_MAP_API = 23;
        MAP_SOURCE_EARTHBUILDER_API = 24;
        MAP_SOURCE_TILE_API = 25;
        MAP_SOURCE_VECTOR_TILE_API = 26;
        MAP_SOURCE_WEATHER_API = 27;
        MAP_SOURCE_MOBILE = 2;
        MAP_SOURCE_GMM = 33;
        MAP_SOURCE_GMM_OFFLINE = 529;
        MAP_SOURCE_GMM_OFFLINE_HI = 8465;
        MAP_SOURCE_GMM_OFFLINE_LO = 8466;
        MAP_SOURCE_GMM_INDOOR = 530;
        MAP_SOURCE_GMM_AGMM = 531;
        MAP_SOURCE_GMM_AGMM_NOTIFICATION = 8497;
        MAP_SOURCE_GMM_IGMM = 532;
        MAP_SOURCE_GMM_IGMM_NOTIFICATION = 8513;
        MAP_SOURCE_GMM_IGMM_WIDGET = 8514;
        MAP_SOURCE_GMM_EGMM = 533;
        MAP_SOURCE_GMM_COMMUTE_SERVER = 534;
        MAP_SOURCE_GMM_CREATOR_ZONE = 535;
        MAP_SOURCE_GMM_TIMELINE = 536;
        MAP_SOURCE_IPHONE = 34;
        MAP_SOURCE_NAVIGATION = 35;
        MAP_SOURCE_NAVIGATION_NIANTIC = 561;
        MAP_SOURCE_ANDROID = 36;
        MAP_SOURCE_ANDROID_SEARCH = 577;
        MAP_SOURCE_ANDROID_PERSONAL_RICH_EVENTS = 578;
        MAP_SOURCE_ANDROID_PIXEL_WEATHER = 579;
        MAP_SOURCE_GOGGLES = 37;
        MAP_SOURCE_GLASS = 38;
        MAP_SOURCE_IOS_GSA = 39;
        MAP_SOURCE_IOS_TRIPS = 40 [deprecated = true];
        MAP_SOURCE_ANDROID_TRIPS = 41 [deprecated = true];
        MAP_SOURCE_NAV_GO = 42;
        MAP_SOURCE_EARTH_XR = 44;
        MAP_SOURCE_EARTH = 3;
        MAP_SOURCE_EARTH_RENDER_SERVICE = 49;
        MAP_SOURCE_EARTH_PRO_VECTOR = 50;
        MAP_SOURCE_ADS = 5;
        MAP_SOURCE_CONTENTADS = 81;
        MAP_SOURCE_CONTENTADS_FORMATS = 1297;
        MAP_SOURCE_BOOKS = 6;
        MAP_SOURCE_INTERNAL_TOOL = 7;
        MAP_SOURCE_GO_TILES = 113;
        MAP_SOURCE_GT_ATLAS = 114;
        MAP_SOURCE_GT_ALF = 1825;
        MAP_SOURCE_CALYPSO = 1826;
        MAP_SOURCE_MY_MAPS_THUMBS = 115;
        MAP_SOURCE_ALLEYCAT_EXPLORE = 116;
        MAP_SOURCE_LAGMON = 117;
        MAP_SOURCE_SPECTRUM_TERRAFORM = 118;
        MAP_SOURCE_LOCAL_SERVICES_IMMERSIVE = 119;
        MAP_SOURCE_TRAVEL_ON_YOUTUBE = 120;
        MAP_SOURCE_AR_VIEWER = 121;
        MAP_SOURCE_CROUPIER_TASKABLE_AGENT = 122;
        MAP_SOURCE_MODERATION_AGENT = 123;
        MAP_SOURCE_KARTO = 128;
    }
    
    optional int32 style_zoom = 1000;
    repeated StylerDescription styler = 12;
    optional string quickstyle_dir = 15;
    optional bool inline_legend_styles_supported = 16 [deprecated = true];
    optional bool allow_text_scaling = 17;
    optional bool skip_intent_iconic_place = 19 [deprecated = true];
    optional bool disable_3d_buildings = 20;
    optional bool enable_iconic_icons = 21;
    
    reserved 1, 6, 7, 9, 10, 11, 13, 14, 18, 22, 23, 24, 25;
    
    reserved "experiment_id", "request_limit", "maps_api_version", "application_name", "os_version", "platform_id";
}
