syntax = "editions";

package maps_paint;

option features = utf8_validation: NONE
;
option objc_class_prefix = "GMP";
option java_multiple_files = true;
option java_outer_classname = "PromotedPlaceLoggingMetadataProto";
option java_package = "com.google.maps.paint.client";

message PromotedPlaceLoggingMetadata {
    optional string feature_id = 1;
    optional uint64 request_timestamp = 2;
    optional string ad_viewed_url = 3;
    optional bool is_counterfactual = 4;
    optional string ad_clicked_url = 5;
    optional string hotel_viewed_url = 6;
    optional int32 minimum_log_impression_duration_millis = 7;
    optional string business_name = 8;
}
