syntax = "editions";

package earth.state.derivedstate;

import "devtools/staticanalysis/pipeline/analyzers/proto_best_practices/proto/optouts.proto";
import "geo/earth/app/cpp/core/protos/view_group.proto";
import "geo/earth/app/cpp/core/state/state.proto";

option features = utf8_validation: NONE
;
option objc_class_prefix = "RTH";
option optimize_for = CODE_SIZE;
option java_outer_classname = "Searchderivedstate";
option java_package = "com.google.geo.earth.app.common.presenters.stateurl.derived";

message SearchDerivedState {
    optional bool search_panel_visible = 1;
    optional string place_mid_to_highlight_placemark_for = 3;
    optional string place_fid_to_highlight_placemark_for = 4;
    optional bool should_fly_to_next_search_results = 5;
    optional bool search_history_open = 6;
    optional bool search_suggestions_open = 7;
    optional string query = 8;
    optional int32 caret_position = 9;
    optional LatLonBox viewport = 10;
    optional bool search_results_available = 11;
    optional bool is_searching = 12;
    optional string group_id = 13;
    optional bool search_panel_suppressed_sui = 14;
    optional .earth.core.viewgroup.ViewGroup view_group = 15;
    optional bool is_homescreen_active = 16;
    
    reserved 2;
}
