syntax = "editions";

package logs_tactile;

import "logs/proto/maps/tactile/recommended-filtering-results.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option features = utf8_validation: NONE
;
option java_multiple_files = true;
option java_package = "com.google.common.logging.tactile";

message DirectionsCounterfactualRecommendedFilteringResults {
    optional string counterfactual_id = 1;
    optional LoggedRecommendedFilteringResults results = 3;
    
    reserved 2;
    
    reserved "recommended_filtering_results";
}
