syntax = "editions";

package maps_tactile.shared.placepreview;

import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "third_party/java/protobuf/java_features.proto";
import "third_party/protobuf/cpp_features.proto";

option features = field_presence: EXPLICIT
enum_type: CLOSED
;
option objc_class_prefix = "GMTTSHPP";
option java_multiple_files = true;
option java_outer_classname = "ScalableAttributeOptionsProto";
option java_package = "com.google.maps.tactile.shared.placepreview";

message ScalableAttributeOptions {
    optional bool include_wheelchair_accessible_entrance = 1;
    optional bool include_serves_vegetarian_only = 2;
}
