syntax = "editions";

package maps_tactile.shared.directions;

import "java/com/google/apps/jspb/jspb.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "third_party/java/protobuf/java_features.proto";
import "third_party/protobuf/cpp_features.proto";

option features = field_presence: EXPLICIT
enum_type: CLOSED
;
option objc_class_prefix = "GMTTSHD";
option java_multiple_files = true;
option java_outer_classname = "RoadStretchProto";
option java_package = "com.google.maps.tactile.shared.directions";

message RoadStretch {
    optional int32 start_offset_meters = 1;
    
    repeated FeatureId segment_id = 2;
    message FeatureId {
        optional fixed64 fprint = 2 [jstype = JS_STRING];
        
        reserved 1;
    }
    
    optional int32 end_offset_meters = 3;
}
