syntax = "editions";

package maps_spotlight;

import "net/proto2/bridge/proto/message_set.proto";

option features = utf8_validation: NONE
;
option objc_class_prefix = "GMSL";
option java_multiple_files = true;
option java_outer_classname = "DummyReportAProblemMetadata";
option java_package = "com.google.maps.spotlight";

message ReportAProblemMetadata {
    optional string feature_id = 1;
    
    extend .proto2.bridge.MessageSet {
        optional ReportAProblemMetadata message_set_extension = 131847358;
    }
}
