syntax = "proto2";

package geostore;

import "google/api/inclusion.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "geostore/base/proto/featureid.proto";
import "geostore/base/proto/openinghours.proto";
import "geostore/base/proto/options.proto";
import "geostore/base/proto/priceinfo.proto";
import "geostore/base/proto/service_area.proto";
import "geostore/base/proto/telephone.proto";
import "geostore/base/proto/timeschedule.proto";
import "knowledge/graph/protomesh/protomesh.proto";
import "java/com/google/apps/jspb/jspb.proto";

option objc_class_prefix = "GS";
option cc_enable_arenas = true;
option java_package = "com.google.geostore.base.proto";

message EstablishmentProto {
    optional TypeCategory type = 1 [default = TYPE_UNDEFINED, deprecated = true];
    enum TypeCategory {
        TYPE_ANY = 0;
        TYPE_UNDEFINED = 241;
        TYPE_DEPRECATED_AVIATION = 988002;
        TYPE_BUSINESS = 242;
        TYPE_TRAVEL_SERVICE = 61969;
        TYPE_LODGING = 991505;
        TYPE_HOTEL = 15864081;
        TYPE_RESORT = 15864082;
        TYPE_MOTEL = 15864083;
        TYPE_HOSTEL = 15864084;
        TYPE_GUESTHOUSE = 15864085;
        TYPE_VACATION_RENTAL = 15864086;
        TYPE_GAS_STATION = 991506;
        TYPE_REST_AREA = 991507;
        TYPE_CASH_MACHINE = 991508;
        TYPE_CAR_RENTAL = 991509;
        TYPE_CAR_REPAIR = 991510;
        TYPE_TAXI_STAND = 991511;
        TYPE_TRAVEL_AGENT = 991512;
        TYPE_BICYCLE_RENTAL_POINT = 991513;
        TYPE_ELECTRIC_VEHICLE_CHARGING_STATION = 991514;
        TYPE_SHOPPING = 61970;
        TYPE_GROCERY = 991521;
        TYPE_ANTIQUES = 991522;
        TYPE_APPAREL = 991523;
        TYPE_GIFTS = 991524;
        TYPE_JEWELRY = 991525;
        TYPE_SPORTING_GOODS = 991526;
        TYPE_VEHICLE = 991527;
        TYPE_SHOPPING_CENTER = 991528;
        TYPE_SUPERMARKET = 991529;
        TYPE_FAIRGROUNDS = 991530;
        TYPE_MARKET = 991531;
        TYPE_PRODUCE_MARKET = 15864497;
        TYPE_FARMERS_MARKET = 15864498;
        TYPE_LIQUOR_STORE = 991532;
        TYPE_SOUVENIR_SHOP = 991533;
        TYPE_INDUSTRIAL = 61971;
        TYPE_CONSTRUCTION = 991537;
        TYPE_BUILDING_MATERIAL = 15864593;
        TYPE_SECURITY_PRODUCTS = 15864594;
        TYPE_MECHANICAL = 991538;
        TYPE_TEXTILE = 991539;
        TYPE_CHEMICAL = 991540;
        TYPE_METAL = 991541;
        TYPE_TRANSPORTATION = 991542;
        TYPE_FREIGHT = 15864673;
        TYPE_AVIATION = 15864674;
        TYPE_COURIER = 15864675;
        TYPE_MOVING = 15864676;
        TYPE_PACKAGING = 15864677;
        TYPE_RAIL = 15864678;
        TYPE_PUBLIC_TRANSIT = 15864679;
        TYPE_WAREHOUSE = 15864680;
        TYPE_DEFENSE = 991543;
        TYPE_AGRICULTURE = 991544;
        TYPE_PLANTATION = 15864705;
        TYPE_PLANT_NURSERY = 15864706;
        TYPE_DESIGN = 991545;
        TYPE_UTILITIES = 991546;
        TYPE_POWER_PLANT = 15864737;
        TYPE_SEWAGE_TREATMENT_PLANT = 15864738;
        TYPE_WATER_TREATMENT_PLANT = 15864739;
        TYPE_SUBSTATION = 15864740;
        TYPE_MANUFACTURING = 991547;
        TYPE_BIOTECH = 991548;
        TYPE_MATERIALS = 991549;
        TYPE_MINING = 991550;
        TYPE_QUARRY = 15864817;
        TYPE_TANNERY = 15864818;
        TYPE_OIL_REFINERY = 15864819;
        TYPE_ADVERTISING_MARKETING = 61972;
        TYPE_LEGAL = 61973;
        TYPE_FAMILY_LAW = 991569;
        TYPE_IP_LAW = 991570;
        TYPE_LABOR_LAW = 991571;
        TYPE_PERSONAL_INJURY_LAW = 991572;
        TYPE_CRIMINAL_LAW = 991573;
        TYPE_PERSONAL_FINANCE = 61974;
        TYPE_LIFE_INSURANCE = 991585;
        TYPE_LENDING = 991586;
        TYPE_ACCOUNTING = 991587;
        TYPE_INVESTING = 991588;
        TYPE_BANKING = 991589;
        TYPE_HEALTH = 61975;
        TYPE_HEALTH_EQUIPMENT = 991601;
        TYPE_NURSING = 991602;
        TYPE_HEALTH_INSURANCE = 991603;
        TYPE_HEALTH_FACILITY = 991604;
        TYPE_DIAGNOSTIC_CENTER = 15865665;
        TYPE_HEALTH_RESOURCES = 991605;
        TYPE_NUTRITION = 991606;
        TYPE_VISION = 991607;
        TYPE_COUNSELING = 991608;
        TYPE_MASSAGE = 991609;
        TYPE_BLOOD_BANK = 991610;
        TYPE_HEARING = 991611;
        TYPE_HOME_GARDEN = 61976;
        TYPE_INTERIOR_DECOR = 991617;
        TYPE_DOMESTIC_SERVICES = 991618;
        TYPE_APPLIANCES = 991619;
        TYPE_PEST_CONTROL = 991620;
        TYPE_GARDENING = 991621;
        TYPE_ELECTRONICS = 61977;
        TYPE_COMPUTER = 991633;
        TYPE_COMPUTER_HARDWARE = 15866129;
        TYPE_COMPUTER_SECURITY = 15866130;
        TYPE_COMPUTER_SOFTWARE = 15866131;
        TYPE_COMPUTER_SUPPORT = 15866132;
        TYPE_AUDIO_DEVICES = 991634;
        TYPE_VIDEO_DEVICES = 991635;
        TYPE_REAL_ESTATE = 61978;
        TYPE_OFFICE_SERVICES = 61979;
        TYPE_ENTERTAINMENT = 61980;
        TYPE_GAMES = 991681;
        TYPE_CASINO = 15866897;
        TYPE_LOTTO = 15866898;
        TYPE_VIDEO = 15866899;
        TYPE_CLUBS = 991682;
        TYPE_DISCOTHEQUE = 15866913;
        TYPE_ANIMATION = 991683;
        TYPE_MODELING = 991684;
        TYPE_HUMOR = 991685;
        TYPE_MOVIES = 991686;
        TYPE_MOVIE_RENTAL = 15866977;
        TYPE_MOVIE_THEATER = 15866978;
        TYPE_MUSIC = 991687;
        TYPE_RADIO = 991688;
        TYPE_TV = 991689;
        TYPE_BAR = 991690;
        TYPE_PRINT_MEDIA = 991691;
        TYPE_ADULT = 61981;
        TYPE_SEXUAL_SERVICES = 991697;
        TYPE_ANIMALS = 61982;
        TYPE_PETS = 991713;
        TYPE_FISHERY = 991714;
        TYPE_ARTS = 61983;
        TYPE_BOOKS = 991729;
        TYPE_PERFORMING_ARTS = 991730;
        TYPE_GALLERY = 991731;
        TYPE_AUTOMOTIVE = 61985;
        TYPE_PARTS = 991761;
        TYPE_AUTO_FINANCE = 991762;
        TYPE_AUTO_INSURANCE = 991763;
        TYPE_RV = 991764;
        TYPE_MOTORCYCLES = 991765;
        TYPE_CARS = 991766;
        TYPE_TRUCKS_SUVS = 991767;
        TYPE_LICENSING = 991768;
        TYPE_MAINTENANCE = 991769;
        TYPE_PERSONAL_CARE = 61986;
        TYPE_BODY_ART = 991777;
        TYPE_COSMETICS = 991778;
        TYPE_FITNESS = 991779;
        TYPE_YOGA_CENTER = 15868465;
        TYPE_GYM = 15868466;
        TYPE_HAIR_CARE = 991780;
        TYPE_SPA = 991781;
        TYPE_BEAUTY_SALON = 991782;
        TYPE_CORPORATE_EVENTS = 61987;
        TYPE_HUMAN_RESOURCES = 61988;
        TYPE_FOOD_AND_DRINK = 61989;
        TYPE_BEVERAGE = 991825;
        TYPE_RECIPES = 991826;
        TYPE_COOKWARE = 991827;
        TYPE_CULINARY = 991828;
        TYPE_RETAIL = 991829;
        TYPE_RESTAURANT = 991830;
        TYPE_COFFEE = 991831;
        TYPE_BAKERY = 991832;
        TYPE_FOOD_CENTER = 991833;
        TYPE_TEA = 991834;
        TYPE_CAFE = 991835;
        TYPE_WINERY = 991836;
        TYPE_BREWERY = 991837;
        TYPE_FAST_FOOD = 991838;
        TYPE_FOOD_DELIVERY = 991839;
        TYPE_INTERNET = 61990;
        TYPE_WEB_DESIGN = 991841;
        TYPE_WEB_HOSTING = 991842;
        TYPE_WEB_SERVICES = 991843;
        TYPE_LIFESTYLE = 61991;
        TYPE_PHOTO_VIDEO = 61992;
        TYPE_ACTIVITIES = 61993;
        TYPE_BOATING = 991889;
        TYPE_CYCLING = 991890;
        TYPE_EQUESTRIAN = 991891;
        TYPE_FISHING = 991892;
        TYPE_HIKING = 991893;
        TYPE_HUNTING = 991894;
        TYPE_SWIMMING = 991895;
        TYPE_GOLF = 991896;
        TYPE_GOLF_COURSE = 15870337;
        TYPE_BASEBALL = 991897;
        TYPE_BASKETBALL = 991898;
        TYPE_HOCKEY = 991899;
        TYPE_MOTOR_SPORTS = 991900;
        TYPE_WINTER_SPORTS = 991901;
        TYPE_FOOTBALL = 991902;
        TYPE_SOCCER = 991903;
        TYPE_ICE_SKATING = 15870209;
        TYPE_BOXING = 15870210;
        TYPE_CRICKET = 15870211;
        TYPE_ROWING = 15870212;
        TYPE_RUGBY = 15870213;
        TYPE_RACQUET_SPORTS = 15870214;
        TYPE_ROCK_CLIMBING = 15870215;
        TYPE_REFERENCES = 61994;
        TYPE_MAPS = 991905;
        TYPE_TIME = 991906;
        TYPE_SCIENTIFIC_EQUIPMENT = 61995;
        TYPE_TELECOMMUNICATIONS = 61996;
        TYPE_EVENT_VENUE = 61997;
        TYPE_BANQUET_HALL = 991953;
        TYPE_CONFERENCE_HALL = 991954;
        TYPE_WEDDING_HALL = 991955;
        TYPE_EXHIBITION_HALL = 991956;
        TYPE_COMMUNITY_CENTER = 991957;
        TYPE_AUDITORIUM = 991958;
        TYPE_FUNCTION_HALL = 991959;
        TYPE_CONCERT_HALL = 991960;
        TYPE_AMPHITHEATER = 991961;
        TYPE_LAUNDRY = 61998;
        TYPE_LAUNDROMAT = 991969;
        TYPE_DRY_CLEANER = 991970;
        TYPE_MORTUARY = 61999;
        TYPE_REPAIR_AND_MAINTENANCE = 991745;
        TYPE_GOVERNMENT = 243;
        TYPE_BORDER_CROSSING = 3889;
        TYPE_CITY_HALL = 3890;
        TYPE_COURTHOUSE = 3891;
        TYPE_EMBASSY = 3892;
        TYPE_LIBRARY = 3893;
        TYPE_PRISON = 3894;
        TYPE_TAX_OFFICE = 3895;
        TYPE_PROSECUTORS_OFFICE = 3896;
        TYPE_CONGRESS = 3897;
        TYPE_TOWN_COUNCIL = 3898;
        TYPE_CAPITOL_BUILDING = 3899;
        TYPE_VOTING_FACILITY = 3900;
        TYPE_CHECKPOINT = 3901;
        TYPE_SCHOOL = 244;
        TYPE_UNIVERSITY = 3905;
        TYPE_ORPHANAGE = 3906;
        TYPE_KINDERGARTEN = 3907;
        TYPE_DAYCARE = 3908;
        TYPE_ACADEMY = 3909;
        TYPE_TRADE_SCHOOL = 3910;
        TYPE_SKILL_INSTRUCTION = 3911;
        TYPE_EMERGENCY = 245;
        TYPE_HOSPITAL = 3921;
        TYPE_PHARMACY = 3922;
        TYPE_POLICE = 3923;
        TYPE_FIRE = 3924;
        TYPE_DOCTOR = 3925;
        TYPE_DENTIST = 3926;
        TYPE_VETERINARIAN = 3927;
        TYPE_FIRST_AID = 3928;
        TYPE_CIVIL_DEFENSE = 3929;
        TYPE_TOURIST_DESTINATION = 246;
        TYPE_ECO_TOURIST_DESTINATION = 3937;
        TYPE_BIRD_WATCHING = 62993;
        TYPE_NATURE_RESERVE = 62994;
        TYPE_MUSEUM = 3938;
        TYPE_VISITOR_CENTER = 3939;
        TYPE_OBSERVATION_DECK = 3940;
        TYPE_OBSERVATORY = 3941;
        TYPE_SCENIC_POINT = 3942;
        TYPE_ZOO = 3943;
        TYPE_AQUARIUM = 3944;
        TYPE_AMUSEMENT_PARK = 3945;
        TYPE_MONUMENT = 3946;
        TYPE_PALACE = 3947;
        TYPE_FORT = 3948;
        TYPE_TOWER = 3949;
        TYPE_LIGHTHOUSE = 3950;
        TYPE_TEMPLE = 247;
        TYPE_CHURCH = 3953;
        TYPE_GURUDWARA = 3954;
        TYPE_HINDU_TEMPLE = 3955;
        TYPE_MOSQUE = 3956;
        TYPE_SYNAGOGUE = 3957;
        TYPE_BUDDHIST_TEMPLE = 3958;
        TYPE_JAIN_TEMPLE = 3959;
        TYPE_BAHAI_TEMPLE = 3960;
        TYPE_SHINTO_TEMPLE = 3961;
        TYPE_MORMON_TEMPLE = 3962;
        TYPE_SPORTS_COMPLEX = 248;
        TYPE_STADIUM = 3969;
        TYPE_BOWLING = 3970;
        TYPE_BADMINTON = 3971;
        TYPE_TENNIS = 3972;
        TYPE_TABLE_TENNIS = 3973;
        TYPE_PARK = 249;
        TYPE_LOCAL_PARK = 3985;
        TYPE_NATIONAL_PARK = 3986;
        TYPE_US_NATIONAL_PARK = 63777;
        TYPE_US_NATIONAL_MONUMENT = 63778;
        TYPE_NATIONAL_FOREST = 63779;
        TYPE_NATIONAL_GRASSLAND = 63780;
        TYPE_NATIONAL_PRESERVE = 63781;
        TYPE_NATIONAL_RECREATION_AREA = 63782;
        TYPE_NATIONAL_MONUMENT = 63783;
        TYPE_NATIONAL_HISTORIC_AREA = 63784;
        TYPE_NATIONAL_SCENIC_AREA = 63785;
        TYPE_NATIONAL_SCENIC_ROADWAY_AREA = 1020561;
        TYPE_NATIONAL_SCENIC_RIVER_AREA = 1020562;
        TYPE_PROVINCIAL_PARK = 3987;
        TYPE_PROVINCIAL_FOREST = 63793;
        TYPE_CAMPGROUNDS = 3988;
        TYPE_WILDERNESS_AREA = 3989;
        TYPE_WILDLIFE_AREA = 3990;
        TYPE_BOTANICAL_GARDEN = 3991;
        TYPE_GARDEN = 3992;
        TYPE_ARBORETUM = 3993;
        TYPE_MARINE_PROTECTED_AREA = 3994;
        TYPE_AIRPORT = 4000;
        TYPE_TARMAC = 64001;
        TYPE_HELIPORT = 64002;
        TYPE_SEAPLANE_BASE = 64003;
        TYPE_MILITARY_AIRBASE = 64004;
        TYPE_CEMETERY = 4001;
        TYPE_MILITARY = 4002;
        TYPE_ENCLOSED_TRAFFIC_AREA = 4003;
        TYPE_PARKING = 64049;
        TYPE_OFF_ROAD_AREA = 64050;
        TYPE_POST_OFFICE = 4004;
        TYPE_HOUSING_DEVELOPMENT = 4005;
        TYPE_BRIDGE = 4006;
        TYPE_ARCHAEOLOGICAL = 4007;
        TYPE_HISTORICAL = 4008;
        TYPE_RUINS = 64129;
        TYPE_TUNNEL = 4009;
        TYPE_RESIDENTIAL_DWELLING = 4010;
        TYPE_DETACHED_DWELLING = 64161;
        TYPE_ATTACHED_DWELLING = 64162;
        TYPE_APARTMENT = 1026593;
        TYPE_GATED_COMMUNITY = 64163;
        TYPE_RETIREMENT_HOME = 64164;
        TYPE_TOLL_BOOTH = 4011;
        TYPE_CULTURAL = 4012;
        TYPE_CULTURAL_CENTER = 64193;
        TYPE_OVERPASS = 4013;
        TYPE_REST_ROOM = 4014;
        TYPE_PUBLIC_PHONE = 4015;
        TYPE_PHONE_BOOTH = 64241;
        TYPE_MANNED_PCO = 64242;
        TYPE_RESEARCH_INSTITUTE = 4016;
        TYPE_NON_GOVERNMENTAL_ORGANIZATION = 4017;
        TYPE_OFFICE_PARK = 4018;
        TYPE_MEDITATION_CENTER = 4019;
        TYPE_RELIGIOUS = 4020;
        TYPE_MONASTERY = 64321;
        TYPE_ASHRAM = 64322;
        TYPE_PAGODA = 64323;
        TYPE_MISSION = 64324;
        TYPE_PILGRIM_DESTINATION = 64325;
        TYPE_SOCIAL_SERVICE = 4021;
        TYPE_RANGER_STATION = 4022;
        TYPE_TRANSIT_STATION = 4023;
        TYPE_BUS_STATION = 64369;
        TYPE_TRAMWAY_STATION = 64370;
        TYPE_TRAIN_STATION = 64371;
        TYPE_SUBWAY_STATION = 64372;
        TYPE_FERRY_TERMINAL = 64373;
        TYPE_CABLE_CAR_STATION = 64374;
        TYPE_GONDOLA_LIFT_STATION = 64375;
        TYPE_FUNICULAR_STATION = 64376;
        TYPE_HORSE_CARRIAGE_STATION = 64377;
        TYPE_MONORAIL_STATION = 64378;
        TYPE_SEAPORT = 64379;
        TYPE_NATURAL_FEATURE = 4024;
        TYPE_ELEVATED = 64389;
        TYPE_PEAK = 1030225;
    }
    
    repeated TelephoneProto telephone = 2;
    optional TimeScheduleProto hours = 7;
    optional OpeningHoursProto opening_hours = 13;
    optional BizBuilderReferenceProto bizbuilder_reference = 9;
    optional PriceInfoProto price_info = 10;
    optional ServiceAreaProto service_area = 14;
    optional FeatureIdProto routing_destination = 15;
    
    reserved 3, 4, 5, 6, 8, 11, 12, 500;
}

message BizBuilderReferenceProto {
    optional int64 id = 1;
}
