syntax = "proto2";

package geostore;

import "frameworks/testing/rpcreplay/processors/rpc_replay_field_option.proto";
import "geostore/base/proto/accesspoint.proto";
import "geostore/base/proto/address.proto";
import "geostore/base/proto/anchored_geometry.proto";
import "geostore/base/proto/attribute.proto";
import "geostore/base/proto/bestlocale.proto";
import "geostore/base/proto/border.proto";
import "geostore/base/proto/building.proto";
import "geostore/base/proto/business_chain.proto";
import "geostore/base/proto/cellcovering.proto";
import "geostore/base/proto/data_agent.proto";
import "geostore/base/proto/datasource.proto";
import "geostore/base/proto/display_data.proto";
import "geostore/base/proto/disputed_area.proto";
import "geostore/base/proto/doodle.proto";
import "geostore/base/proto/elevation.proto";
import "geostore/base/proto/elevationmodel.proto";
import "geostore/base/proto/entrance.proto";
import "geostore/base/proto/entrance_reference.proto";
import "geostore/base/proto/establishment.proto";
import "geostore/base/proto/ev_charger.proto";
import "geostore/base/proto/ev_station.proto";
import "geostore/base/proto/existence.proto";
import "geostore/base/proto/existence_confirmation.proto";
import "geostore/base/proto/featureid.proto";
import "geostore/base/proto/featuremetadata.proto";
import "geostore/base/proto/geometry_store_reference.proto";
import "geostore/base/proto/geopolitical.proto";
import "geostore/base/proto/geopolitical_geometry.proto";
import "geostore/base/proto/htmltext.proto";
import "geostore/base/proto/inferred_geometry.proto";
import "geostore/base/proto/internal/internalfeature.proto";
import "geostore/base/proto/intersection.proto";
import "geostore/base/proto/intersectiongroup.proto";
import "geostore/base/proto/knowledgegraphreference.proto";
import "geostore/base/proto/landuse.proto";
import "geostore/base/proto/lane_marker.proto";
import "geostore/base/proto/level.proto";
import "geostore/base/proto/locale.proto";
import "geostore/base/proto/logical_border.proto";
import "geostore/base/proto/median.proto";
import "geostore/base/proto/name.proto";
import "geostore/base/proto/operations.proto";
import "geostore/base/proto/options.proto";
import "geostore/base/proto/parking.proto";
import "geostore/base/proto/point.proto";
import "geostore/base/proto/political.proto";
import "geostore/base/proto/polygon.proto";
import "geostore/base/proto/polyline.proto";
import "geostore/base/proto/pose.proto";
import "geostore/base/proto/property_value_status.proto";
import "geostore/base/proto/rankdetails.proto";
import "geostore/base/proto/rect.proto";
import "geostore/base/proto/regulated_area.proto";
import "geostore/base/proto/relation.proto";
import "geostore/base/proto/restriction_group.proto";
import "geostore/base/proto/road_disruption.proto";
import "geostore/base/proto/road_monitor.proto";
import "geostore/base/proto/roadsign.proto";
import "geostore/base/proto/route.proto";
import "geostore/base/proto/schooldistrict.proto";
import "geostore/base/proto/segment.proto";
import "geostore/base/proto/segmentpath.proto";
import "geostore/base/proto/signpost.proto";
import "geostore/base/proto/skiboundary.proto";
import "geostore/base/proto/skilift.proto";
import "geostore/base/proto/skitrail.proto";
import "geostore/base/proto/socialreference.proto";
import "geostore/base/proto/sourceinfo.proto";
import "geostore/base/proto/threedimensionalmodel.proto";
import "geostore/base/proto/timezone.proto";
import "geostore/base/proto/toll_path.proto";
import "geostore/base/proto/tollcluster.proto";
import "geostore/base/proto/track.proto";
import "geostore/base/proto/transit_line_variant.proto";
import "geostore/base/proto/transitline.proto";
import "geostore/base/proto/transitstation.proto";
import "geostore/base/proto/url.proto";
import "geostore/base/proto/vertical_ordering.proto";
import "geostore/client/attachments/attachment.proto";
import "geostore/ontology/proto/rawgconceptinstancecontainer.proto";
import "google/api/inclusion.proto";
import "google/protobuf/any.proto";
import "java/com/google/apps/jspb/jspb.proto";
import "knowledge/graph/protomesh/protomesh.proto";
import "logs/proto/logs_annotations/logs_annotations.proto";
import "metaweb/data/topictable/topic.proto";
import "net/proto2/bridge/proto/message_set.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "storage/googlesql/public/proto/type_annotation.proto";

option objc_class_prefix = "GS";
option java_package = "com.google.geostore.base.proto";

message FeatureProto {
    required FeatureIdProto id = 1;
    optional RectProto bound = 2;
    optional RectProto preferred_viewport = 59;
    optional float rank = 3;
    repeated NameProto name = 4;
    repeated AddressProto address = 5;
    repeated PointProto point = 6;
    repeated PolyLineProto polyline = 7;
    repeated PolygonProto polygon = 8;
    repeated TrackProto track = 89;
    optional PoseProto pose = 90;
    optional PolygonProto polygon_for_display = 83;
    optional PolygonProto water_removed_polygon = 108;
    optional GeopoliticalGeometryProto geopolitical_geometry = 109;
    repeated FeatureIdProto child = 9;
    repeated FeatureIdProto parent = 14;
    optional PointProto center = 10;
    repeated SourceInfoProto source_info = 12;
    repeated EntranceReferenceProto related_entrance = 86;
    repeated RelationProto related_feature = 13;
    repeated FeatureIdProto related_terminal_point = 88;
    repeated TimezoneProto related_timezone = 85;
    
    optional TypeCategory type = 15;
    enum TypeCategory {
        TYPE_ANY = 0;
        TYPE_TRANSPORTATION = 1;
        TYPE_ROUTE = 17;
        TYPE_DEPRECATED_HIGHWAY_DO_NOT_USE = 273 [deprecated = true];
        TYPE_HIGHWAY = 274;
        TYPE_HIGHWAY_1 = 4385;
        TYPE_HIGHWAY_2 = 4386;
        TYPE_HIGHWAY_3 = 4387;
        TYPE_HIGHWAY_4 = 4388;
        TYPE_HIGHWAY_5 = 4389;
        TYPE_HIGHWAY_6 = 4390;
        TYPE_HIGHWAY_7 = 4391;
        TYPE_HIGHWAY_8 = 4392;
        TYPE_HIGHWAY_9 = 4393;
        TYPE_BICYCLE_ROUTE = 276;
        TYPE_TRAIL = 277;
        TYPE_SEGMENT = 18;
        TYPE_ROAD = 289;
        TYPE_RAILWAY = 291;
        TYPE_STANDARD_TRACK = 4657;
        TYPE_JR_TRACK = 74513;
        TYPE_NARROW_TRACK = 4658;
        TYPE_MONORAIL_TRACK = 4659;
        TYPE_SUBWAY_TRACK = 4660;
        TYPE_LIGHT_RAIL_TRACK = 4661;
        TYPE_BROAD_TRACK = 4662;
        TYPE_HIGH_SPEED_RAIL = 4663;
        TYPE_TROLLEY_TRACK = 4664;
        TYPE_FERRY = 292;
        TYPE_FERRY_BOAT = 4673;
        TYPE_FERRY_TRAIN = 4674;
        TYPE_VIRTUAL_SEGMENT = 293;
        TYPE_INTERSECTION = 19;
        TYPE_TRANSIT = 20;
        TYPE_TRANSIT_STATION = 321 [deprecated = true];
        TYPE_BUS_STATION = 5137 [deprecated = true];
        TYPE_TRAMWAY_STATION = 5138 [deprecated = true];
        TYPE_TRAIN_STATION = 5139 [deprecated = true];
        TYPE_SUBWAY_STATION = 5140 [deprecated = true];
        TYPE_FERRY_TERMINAL = 5141 [deprecated = true];
        TYPE_AIRPORT = 5142 [deprecated = true];
        TYPE_AIRPORT_CIVIL = 82273 [deprecated = true];
        TYPE_AIRPORT_MILITARY = 82274 [deprecated = true];
        TYPE_AIRPORT_MIXED = 82275 [deprecated = true];
        TYPE_HELIPORT = 82276 [deprecated = true];
        TYPE_SEAPLANE_BASE = 82277 [deprecated = true];
        TYPE_AIRSTRIP = 82278 [deprecated = true];
        TYPE_CABLE_CAR_STATION = 5143 [deprecated = true];
        TYPE_GONDOLA_LIFT_STATION = 5144 [deprecated = true];
        TYPE_FUNICULAR_STATION = 5145 [deprecated = true];
        TYPE_SPECIAL_STATION = 5146 [deprecated = true];
        TYPE_HORSE_CARRIAGE_STATION = 82337 [deprecated = true];
        TYPE_MONORAIL_STATION = 5147 [deprecated = true];
        TYPE_SEAPORT = 5148 [deprecated = true];
        TYPE_TRANSIT_STOP = 322 [deprecated = true];
        TYPE_TRANSIT_TRIP = 323 [deprecated = true];
        TYPE_TRANSIT_DEPARTURE = 324 [deprecated = true];
        TYPE_TRANSIT_LEG = 325 [deprecated = true];
        TYPE_TRANSIT_LINE = 326;
        TYPE_TRANSIT_AGENCY_DEPRECATED_VALUE = 327 [deprecated = true];
        TYPE_TRANSIT_TRANSFER = 328 [deprecated = true];
        TYPE_SEGMENT_PATH = 21;
        TYPE_ROAD_SIGN = 337;
        TYPE_INTERSECTION_GROUP = 22;
        TYPE_PATHWAY = 23;
        TYPE_RESTRICTION_GROUP = 24;
        TYPE_TOLL_CLUSTER = 25 [deprecated = true];
        TYPE_POLITICAL = 2;
        TYPE_COUNTRY = 33;
        TYPE_ADMINISTRATIVE_AREA = 34;
        TYPE_ADMINISTRATIVE_AREA1 = 545;
        TYPE_US_STATE = 8721 [deprecated = true];
        TYPE_GB_COUNTRY = 8723 [deprecated = true];
        TYPE_JP_TODOUFUKEN = 8724 [deprecated = true];
        TYPE_ADMINISTRATIVE_AREA2 = 546;
        TYPE_GB_FORMER_POSTAL_COUNTY = 8739 [deprecated = true];
        TYPE_GB_TRADITIONAL_COUNTY = 8740 [deprecated = true];
        TYPE_ADMINISTRATIVE_AREA3 = 547;
        TYPE_ADMINISTRATIVE_AREA4 = 548;
        TYPE_ADMINISTRATIVE_AREA5 = 549;
        TYPE_ADMINISTRATIVE_AREA6 = 550;
        TYPE_ADMINISTRATIVE_AREA7 = 551;
        TYPE_ADMINISTRATIVE_AREA8 = 552;
        TYPE_ADMINISTRATIVE_AREA9 = 553;
        TYPE_COLLOQUIAL_AREA = 35;
        TYPE_RESERVATION = 36;
        TYPE_LOCALITY = 37;
        TYPE_GB_POST_TOWN = 593 [deprecated = true];
        TYPE_JP_GUN = 594 [deprecated = true];
        TYPE_JP_SHIKUCHOUSON = 595 [deprecated = true];
        TYPE_JP_SUB_SHIKUCHOUSON = 596 [deprecated = true];
        TYPE_COLLOQUIAL_CITY = 597;
        TYPE_SUBLOCALITY = 38;
        TYPE_US_BOROUGH = 609 [deprecated = true];
        TYPE_GB_DEPENDENT_LOCALITY = 610 [deprecated = true];
        TYPE_JP_OOAZA = 614 [deprecated = true];
        TYPE_JP_KOAZA = 615 [deprecated = true];
        TYPE_JP_GAIKU = 616 [deprecated = true];
        TYPE_GB_DOUBLE_DEPENDENT_LOCALITY = 617 [deprecated = true];
        TYPE_JP_CHIBAN = 618 [deprecated = true];
        TYPE_JP_EDABAN = 620 [deprecated = true];
        TYPE_SUBLOCALITY1 = 9937;
        TYPE_SUBLOCALITY2 = 9938;
        TYPE_SUBLOCALITY3 = 9939;
        TYPE_SUBLOCALITY4 = 9940;
        TYPE_SUBLOCALITY5 = 9941;
        TYPE_NEIGHBORHOOD = 39;
        TYPE_CONSTITUENCY = 40;
        TYPE_DESIGNATED_MARKET_AREA = 41;
        TYPE_SCHOOL_DISTRICT = 42;
        TYPE_LAND_PARCEL = 43;
        TYPE_DISPUTED_AREA = 44;
        TYPE_POLICE_JURISDICTION = 45;
        TYPE_STATISTICAL_AREA = 11793;
        TYPE_CONSTITUENCY_FUTURE = 738 [deprecated = true];
        TYPE_PARK = 3 [deprecated = true];
        TYPE_GOLF_COURSE = 49 [deprecated = true];
        TYPE_LOCAL_PARK = 50 [deprecated = true];
        TYPE_NATIONAL_PARK = 51 [deprecated = true];
        TYPE_US_NATIONAL_PARK = 817 [deprecated = true];
        TYPE_US_NATIONAL_MONUMENT = 818 [deprecated = true];
        TYPE_NATIONAL_FOREST = 819 [deprecated = true];
        TYPE_PROVINCIAL_PARK = 52 [deprecated = true];
        TYPE_PROVINCIAL_FOREST = 833 [deprecated = true];
        TYPE_CAMPGROUNDS = 53 [deprecated = true];
        TYPE_HIKING_AREA = 54 [deprecated = true];
        TYPE_BUSINESS = 4 [deprecated = true];
        TYPE_GOVERNMENT = 1041 [deprecated = true];
        TYPE_BORDER_CROSSING = 16657 [deprecated = true];
        TYPE_CITY_HALL = 16658 [deprecated = true];
        TYPE_COURTHOUSE = 16659 [deprecated = true];
        TYPE_EMBASSY = 16660 [deprecated = true];
        TYPE_LIBRARY = 16661 [deprecated = true];
        TYPE_SCHOOL = 1042 [deprecated = true];
        TYPE_UNIVERSITY = 16673 [deprecated = true];
        TYPE_EMERGENCY = 1043 [deprecated = true];
        TYPE_HOSPITAL = 16689 [deprecated = true];
        TYPE_PHARMACY = 16690 [deprecated = true];
        TYPE_POLICE = 16691 [deprecated = true];
        TYPE_FIRE = 16692 [deprecated = true];
        TYPE_DOCTOR = 16693 [deprecated = true];
        TYPE_DENTIST = 16694 [deprecated = true];
        TYPE_VETERINARIAN = 16695 [deprecated = true];
        TYPE_TRAVEL_SERVICE = 1044 [deprecated = true];
        TYPE_LODGING = 16705 [deprecated = true];
        TYPE_RESTAURANT = 16706 [deprecated = true];
        TYPE_GAS_STATION = 16707 [deprecated = true];
        TYPE_PARKING = 16708 [deprecated = true];
        TYPE_POST_OFFICE = 16709 [deprecated = true];
        TYPE_REST_AREA = 16710 [deprecated = true];
        TYPE_CASH_MACHINE = 16711 [deprecated = true];
        TYPE_CAR_RENTAL = 16712 [deprecated = true];
        TYPE_CAR_REPAIR = 16713 [deprecated = true];
        TYPE_SHOPPING = 1046 [deprecated = true];
        TYPE_GROCERY = 16737 [deprecated = true];
        TYPE_TOURIST_DESTINATION = 1047 [deprecated = true];
        TYPE_ECO_TOURIST_DESTINATION = 16753 [deprecated = true];
        TYPE_BIRD_WATCHING = 268049 [deprecated = true];
        TYPE_FISHING = 268050 [deprecated = true];
        TYPE_HUNTING = 268051 [deprecated = true];
        TYPE_NATURE_RESERVE = 268052 [deprecated = true];
        TYPE_TEMPLE = 1048 [deprecated = true];
        TYPE_CHURCH = 16769 [deprecated = true];
        TYPE_GURUDWARA = 16770 [deprecated = true];
        TYPE_HINDU_TEMPLE = 16771 [deprecated = true];
        TYPE_MOSQUE = 16772 [deprecated = true];
        TYPE_SYNAGOGUE = 16773 [deprecated = true];
        TYPE_STADIUM = 1049 [deprecated = true];
        TYPE_BAR = 1056 [deprecated = true];
        TYPE_MOVIE_RENTAL = 1058 [deprecated = true];
        TYPE_COFFEE = 1059 [deprecated = true];
        TYPE_GOLF = 1060 [deprecated = true];
        TYPE_BANK = 1061 [deprecated = true];
        TYPE_DOODLE = 5 [deprecated = true];
        TYPE_GROUNDS = 6 [deprecated = true];
        TYPE_AIRPORT_GROUNDS = 97 [deprecated = true];
        TYPE_BUILDING_GROUNDS = 98 [deprecated = true];
        TYPE_CEMETERY = 99 [deprecated = true];
        TYPE_HOSPITAL_GROUNDS = 100 [deprecated = true];
        TYPE_INDUSTRIAL = 101 [deprecated = true];
        TYPE_MILITARY = 102 [deprecated = true];
        TYPE_SHOPPING_CENTER = 103 [deprecated = true];
        TYPE_SPORTS_COMPLEX = 104 [deprecated = true];
        TYPE_UNIVERSITY_GROUNDS = 105 [deprecated = true];
        TYPE_DEPRECATED_TARMAC = 106 [deprecated = true];
        TYPE_ENCLOSED_TRAFFIC_AREA = 108 [deprecated = true];
        TYPE_PARKING_LOT = 1729 [deprecated = true];
        TYPE_PARKING_GARAGE = 1730 [deprecated = true];
        TYPE_OFF_ROAD_AREA = 1731 [deprecated = true];
        TYPE_BORDER = 7;
        TYPE_BUILDING = 8 [deprecated = true];
        TYPE_GEOCODED_ADDRESS = 9;
        TYPE_NATURAL_FEATURE = 10;
        TYPE_TERRAIN = 161;
        TYPE_SAND = 2577;
        TYPE_BEACH = 41233;
        TYPE_DUNE = 41234;
        TYPE_ROCKY = 2578;
        TYPE_ICE = 2579;
        TYPE_GLACIER = 41265;
        TYPE_BUILT_UP_AREA = 2580;
        TYPE_VEGETATION = 2581;
        TYPE_SHRUBBERY = 41297;
        TYPE_WOODS = 41298;
        TYPE_AGRICULTURAL = 41299;
        TYPE_GRASSLAND = 41300;
        TYPE_TUNDRA = 2582;
        TYPE_DESERT = 2583;
        TYPE_SALT_FLAT = 2584;
        TYPE_WATER = 162;
        TYPE_OCEAN = 2593;
        TYPE_BAY = 41489;
        TYPE_BIGHT = 663825;
        TYPE_LAGOON = 663826;
        TYPE_SEA = 41490;
        TYPE_STRAIT = 41491;
        TYPE_INLET = 41492;
        TYPE_FJORD = 663873;
        TYPE_LAKE = 2594;
        TYPE_SEASONAL_LAKE = 41505;
        TYPE_RESERVOIR = 41506;
        TYPE_POND = 41507;
        TYPE_RIVER = 2595;
        TYPE_RAPIDS = 41521;
        TYPE_DISTRIBUTARY = 41522;
        TYPE_CONFLUENCE = 41523;
        TYPE_WATERFALL = 41524;
        TYPE_SPRING = 41525;
        TYPE_GEYSER = 664401;
        TYPE_HOT_SPRING = 664402;
        TYPE_SEASONAL_RIVER = 41526;
        TYPE_WADI = 41527;
        TYPE_ESTUARY = 2596;
        TYPE_WETLAND = 2597;
        TYPE_WATER_NAVIGATION = 2598;
        TYPE_FORD = 41569;
        TYPE_CANAL = 41570;
        TYPE_HARBOR = 41571;
        TYPE_CHANNEL = 41572;
        TYPE_REEF = 41573;
        TYPE_REEF_FLAT = 665169;
        TYPE_REEF_GROWTH = 665170;
        TYPE_REEF_EXTENT = 665171;
        TYPE_REEF_ROCK_SUBMERGED = 665172;
        TYPE_IRRIGATION = 2599;
        TYPE_DAM = 2600 [deprecated = true];
        TYPE_DRINKING_WATER = 2601;
        TYPE_CURRENT = 2603;
        TYPE_WATERING_HOLE = 2604;
        TYPE_TECTONIC = 163;
        TYPE_WATERING_HOLE_DEPRECATED = 2608 [deprecated = true];
        TYPE_VOLCANO = 2609;
        TYPE_LAVA_FIELD = 2610;
        TYPE_FISSURE = 2611;
        TYPE_FAULT = 2612;
        TYPE_LAND_MASS = 164;
        TYPE_CONTINENT = 2625;
        TYPE_ISLAND = 2626;
        TYPE_ATOLL = 42017;
        TYPE_OCEAN_ROCK_EXPOSED = 42018;
        TYPE_CAY = 42019;
        TYPE_PENINSULA = 2627;
        TYPE_ISTHMUS = 2628;
        TYPE_ELEVATED = 165;
        TYPE_PEAK = 2641;
        TYPE_NUNATAK = 42257;
        TYPE_SPUR = 42258;
        TYPE_PASS = 2642;
        TYPE_PLATEAU = 2643;
        TYPE_RIDGE = 2644;
        TYPE_RAVINE = 2646;
        TYPE_CRATER = 2647;
        TYPE_KARST = 42353;
        TYPE_CLIFF = 2648;
        TYPE_VISTA = 2649;
        TYPE_DIGITAL_ELEVATION_MODEL = 2650;
        TYPE_UPLAND = 2651;
        TYPE_TERRACE = 2652;
        TYPE_SLOPE = 2653;
        TYPE_CONTOUR_LINE = 2654;
        TYPE_PAN = 42481;
        TYPE_UNSTABLE_HILLSIDE = 42482;
        TYPE_MOUNTAIN_RANGE = 42483;
        TYPE_UNDERSEA = 166;
        TYPE_SUBMARINE_SEAMOUNT = 2657;
        TYPE_SUBMARINE_RIDGE = 2658;
        TYPE_SUBMARINE_GAP = 42529;
        TYPE_SUBMARINE_PLATEAU = 2659;
        TYPE_SUBMARINE_DEEP = 2660;
        TYPE_SUBMARINE_VALLEY = 2661;
        TYPE_SUBMARINE_BASIN = 2662;
        TYPE_SUBMARINE_SLOPE = 2663;
        TYPE_SUBMARINE_CLIFF = 42609;
        TYPE_SUBMARINE_PLAIN = 2664;
        TYPE_SUBMARINE_FRACTURE_ZONE = 2665;
        TYPE_CAVE = 42753;
        TYPE_ROCK = 42754;
        TYPE_ARCHIPELAGO = 42755;
        TYPE_POSTAL = 11;
        TYPE_POSTAL_CODE = 177;
        TYPE_POSTAL_CODE_PREFIX = 2833;
        TYPE_PREMISE = 179 [deprecated = true];
        TYPE_SUB_PREMISE = 180 [deprecated = true];
        TYPE_SUITE = 2881 [deprecated = true];
        TYPE_POST_TOWN = 182;
        TYPE_POSTAL_ROUND = 183 [deprecated = true];
        TYPE_META_FEATURE = 12;
        TYPE_DATA_SOURCE = 3089;
        TYPE_LOCALE = 194;
        TYPE_TIMEZONE = 195;
        TYPE_BUSINESS_CHAIN = 196;
        TYPE_PHONE_NUMBER_PREFIX = 198;
        TYPE_PHONE_NUMBER_AREA_CODE = 3169;
        TYPE_BUSINESS_CORRIDOR = 199;
        TYPE_ADDRESS_TEMPLATE = 200;
        TYPE_TRANSIT_AGENCY = 3217;
        TYPE_FUTURE_GEOMETRY = 202;
        TYPE_EVENT = 208 [deprecated = true];
        TYPE_EARTHQUAKE = 3329 [deprecated = true];
        TYPE_HURRICANE = 3330 [deprecated = true];
        TYPE_WEATHER_CONDITION = 3331 [deprecated = true];
        TYPE_TRANSIENT = 209;
        TYPE_ENTRANCE = 210;
        TYPE_CARTOGRAPHIC = 211;
        TYPE_HIGH_TENSION = 3377 [deprecated = true];
        TYPE_SKI_TRAIL = 3378;
        TYPE_SKI_LIFT = 3379;
        TYPE_SKI_BOUNDARY = 3380;
        TYPE_WATERSHED_BOUNDARY = 3381;
        TYPE_TARMAC = 865809;
        TYPE_WALL = 865810;
        TYPE_PICNIC_AREA = 865811 [deprecated = true];
        TYPE_PLAY_GROUND = 865812 [deprecated = true];
        TYPE_TRAIL_HEAD = 865813;
        TYPE_GOLF_TEEING_GROUND = 865814;
        TYPE_GOLF_PUTTING_GREEN = 865815;
        TYPE_GOLF_ROUGH = 865816;
        TYPE_GOLF_SAND_BUNKER = 865817;
        TYPE_GOLF_FAIRWAY = 865818;
        TYPE_GOLF_HOLE = 865819;
        TYPE_DEPRECATED_GOLF_SHOP = 865820 [deprecated = true];
        TYPE_CAMPING_SITE = 865821 [deprecated = true];
        TYPE_DESIGNATED_BARBECUE_PIT = 865822;
        TYPE_DESIGNATED_COOKING_AREA = 865823;
        TYPE_CAMPFIRE_PIT = 865824;
        TYPE_WATER_FOUNTAIN = 865825;
        TYPE_LITTER_RECEPTACLE = 865826;
        TYPE_LOCKER_AREA = 865827;
        TYPE_ANIMAL_ENCLOSURE = 865828;
        TYPE_CARTOGRAPHIC_LINE = 865829;
        TYPE_ESTABLISHMENT = 212;
        TYPE_ESTABLISHMENT_GROUNDS = 3393 [deprecated = true];
        TYPE_ESTABLISHMENT_BUILDING = 3394 [deprecated = true];
        TYPE_ESTABLISHMENT_POI = 3395;
        TYPE_ESTABLISHMENT_SERVICE = 54337;
        TYPE_CELESTIAL = 213;
        TYPE_ROAD_MONITOR = 214;
        TYPE_PUBLIC_SPACES_AND_MONUMENTS = 215;
        TYPE_STATUE = 3441;
        TYPE_TOWN_SQUARE = 3442;
        TYPE_LEVEL = 216;
        TYPE_COMPOUND = 217;
        TYPE_COMPOUND_GROUNDS = 3473;
        TYPE_COMPOUND_BUILDING = 3474;
        TYPE_COMPOUND_SECTION = 3475;
        TYPE_TERMINAL_POINT = 218;
        TYPE_REGULATED_AREA = 219;
        TYPE_LOGICAL_BORDER = 220;
        TYPE_GCONCEPT_ONLY = 224;
        TYPE_DO_NOT_USE_RESERVED_TO_CATCH_GENERATED_FILES = 254 [deprecated = true];
        TYPE_UNKNOWN = 255;
    }
    
    optional bool synthetic_geometry = 16 [default = false];
    repeated AccessPointProto access_point = 17;
    optional FeatureIdProto original_id = 19;
    optional double geometry_precision_meters = 20;
    optional RankDetailsProto rank_details = 24;
    optional InternalFeatureProto internal = 71;
    optional .proto2.bridge.MessageSet temporary_data = 25;
    optional CellCoveringProto covering = 26;
    optional CellCoveringProto interior_covering = 27;
    repeated HtmlTextProto html_text = 28 [deprecated = true];
    repeated AttributeProto attribute = 66 [deprecated = true];
    repeated freebase.PropertyValue kg_property = 79;
    optional ExistenceProto status = 67;
    optional OperationsProto operations = 103;
    repeated UrlProto website = 69;
    optional ontology.RawGConceptInstanceContainerProto raw_gconcept_instance_container = 70;
    optional SocialReferenceProto social_reference = 74;
    optional KnowledgeGraphReferenceProto knowledge_graph_reference = 75;
    optional BestLocaleProto best_locale = 76;
    optional RouteProto route = 30;
    optional SegmentProto segment = 31;
    optional IntersectionProto intersection = 32;
    optional RestrictionGroupProto restriction_group = 80;
    optional DataSourceProto data_source = 33;
    optional PoliticalProto political = 34;
    optional TransitLineProto transit_line = 42;
    optional TransitLineVariantProto transit_line_variant = 87;
    optional TransitStationProto transit_station = 105;
    optional BuildingProto building = 43;
    optional BorderProto border = 44;
    optional LogicalBorderProto logical_border = 106;
    optional SegmentPathProto segment_path = 45;
    optional DoodleProto doodle = 46 [deprecated = true];
    optional SchoolDistrictProto school_district = 48;
    optional EntranceProto entrance = 49;
    optional EstablishmentProto establishment = 51;
    optional RoadSignProto sign = 52;
    optional LocaleProto locale = 53;
    optional ThreeDimensionalModelProto three_dim_model = 55;
    optional ElevationModelProto elevation_model = 56;
    optional IntersectionGroupProto intersection_group = 60;
    optional ElevationProto elevation = 61;
    optional SkiBoundaryProto ski_boundary = 62;
    optional SkiLiftProto ski_lift = 63;
    optional SkiTrailProto ski_trail = 64;
    optional LevelProto level = 68;
    optional VerticalOrderingProto vertical_ordering = 98;
    optional ParkingProto parking = 82;
    repeated geostore.attachments.AttachmentProto attachment = 73;
    optional FeatureMetadataProto metadata = 300;
    repeated PropertyValueStatusProto property_value_status = 84;
    optional BusinessChainProto business_chain = 91;
    optional DisplayDataProto display_data = 92;
    optional FeatureIdProto future_geometry = 93;
    optional FeatureIdProto future_geometry_for = 94;
    repeated FeatureIdProto related_border = 95;
    optional RoadMonitorProto road_monitor = 96;
    optional LaneMarkerProto lane_marker = 97;
    optional RegulatedAreaProto regulated_area = 99;
    repeated FeatureIdProto exempt_regulated_area = 100;
    optional InferredGeometryProto inferred_geometry = 101;
    optional TollClusterProto toll_cluster = 102;
    optional AnchoredGeometryProto anchored_geometry = 104;
    optional GeometryStoreReferenceProto geometry_3d = 110;
    optional GeometryStoreReferenceProto detailed_3d_model = 116;
    repeated AnchoredGeometryProto storefront_geometry = 107;
    optional GeometryStoreReferenceProto visualization_area = 111;
    optional GeometryStoreReferenceProto storefront_geometry_model = 112;
    optional DisputedAreaProto disputed_area = 113;
    optional GeopoliticalProto geopolitical = 114;
    optional RoadDisruptionProto road_disruption = 119;
    repeated FeatureIdProto associated_ev_charging_station = 115;
    optional TollPathProto toll_path = 117;
    repeated .google.protobuf.Any experimental_data = 118;
    optional EvChargerProto ev_charger = 122;
    optional EvStationProto ev_station = 120;
    optional MedianProto median = 121;
    repeated DataAgentProto feature_originators = 123;
    repeated ExistenceConfirmationProto existence_confirmations = 126;
    optional LandUseProto land_use = 124;
    optional SignpostProto signpost = 125;
    
    reserved 11, 18, 21, 22, 23, 29, 35, 36, 37, 38, 39, 40, 41, 47, 50, 54, 57, 58, 65, 72, 77, 78, 81, 500, 501;
    
    extend .proto2.bridge.MessageSet {
        optional FeatureProto message_set_extension = 1205891;
    }
}
