syntax = "proto2";

package geostore.fieldtype;

import "google/api/inclusion.proto";

option java_package = "com.google.geostore.base.proto";

enum Type {
    option allow_alias = true;
    NONE = 0;
    ACCESS_POINT = 356;
    ADDRESS = 276;
    ANCHORED_GEOMETRY_GEOMETRY_ID = 83;
    ASSOCIATED_EV_CHARGING_STATION = 102;
    ATTACHMENT = 284;
    BIZBUILDER_REFERENCE = 353;
    BORDER_FEATURE_ID_LEFT = 23;
    BORDER_FEATURE_ID_RIGHT = 24;
    BORDER_OVERRIDE_STATUS = 25;
    BORDER_STATUS = 26;
    BORDER_TYPE = 27;
    BORDER_LOGICAL_BORDER = 85;
    BOUND = 277;
    BUILDING_BASE_HEIGHT_METERS_AGL = 10;
    BUILDING_DEFAULT_DISPLAY_LEVEL = 4915;
    BUILDING_FLOORS = 6;
    BUILDING_HEIGHT_METERS = 11;
    BUILDING_LEVEL = 4913;
    BUILDING_STRUCTURE = 7;
    BUSINESS_CHAIN_CANONICAL_GCONCEPT = 64;
    BUSINESS_HOURS = 4886;
    DATA_SOURCE = 346;
    DETAILED_3D_MODEL = 103;
    DISPLAY_DATA = 65;
    DISPUTED_AREA_ADMINISTERED_BY = 1990;
    DISPUTED_AREA_CLAIMANT = 1991;
    ENTRANCE_ALLOWANCE = 39;
    ENTRANCE_ENTRY_RULE = 156;
    ENTRANCE_QUALIFIER_TEXT = 157;
    ESTABLISHMENT_OPENING_HOURS_EXCEPTION = 18;
    ESTABLISHMENT_OPENING_HOURS_REGULAR_HOURS = 17;
    ESTABLISHMENT_PRICE_INFO = 1;
    ESTABLISHMENT_ROUTING_DESTINATION = 152;
    ESTABLISHMENT_SERVICE_AREA_SERVED_FEATURE = 62;
    EV_CHARGER_CONNECTOR = 124;
    EV_CHARGER_EV_STATION = 125;
    EV_CHARGER_EVSE_ID = 126;
    EV_CHARGER_OPERATOR_UID = 127;
    EV_STATION_ASSOCIATED_HOST = 128;
    EV_STATION_EV_CHARGER = 129;
    EV_STATION_EXTERNAL_ID = 131;
    EV_STATION_GELFS_ID = 154;
    EV_STATION_OCPI_ID = 155;
    EV_STATION_OEM_RESTRICTION = 130;
    EXISTENCE_CONFIRMATION = 151;
    EXISTENCE_STATUS = 343;
    EXPERIMENTAL_DATA = 105;
    FEATURE_AVERAGE_ELEVATION = 2;
    FEATURE_BEST_LOCALE = 9;
    FEATURE_CELL_COVERING = 13;
    FEATURE_CENTER = 282;
    FEATURE_CHILD = 4674;
    FEATURE_EXEMPT_REGULATED_AREA = 300;
    FEATURE_INTERIOR_CELL_COVERING = 14;
    FEATURE_NAME = 273;
    FEATURE_ORIGINATOR = 139;
    FEATURE_PARENT = 4675;
    FEATURE_POSE = 63;
    FEATURE_PREFERRED_VIEWPORT = 4;
    FEATURE_TRACK = 57;
    FEATURE_TYPE = 274;
    FEATURE_WEBSITE = 4887;
    FIELD_RIGHTS = 29;
    FUTURE_GEOMETRY = 66;
    FUTURE_GEOMETRY_FOR = 67;
    GCONCEPT = 283;
    GEOMETRY_3D = 98;
    GEOMETRY_PRECISION_METERS = 350;
    GEOPOLITICAL_CONVEYS_ATTRIBUTION_TO = 1992;
    GEOPOLITICAL_REGION_SPECIFIC_NAME = 1993;
    GEOPOLITICAL_REGIONAL_POLYGON_ADJUSTMENT = 1994;
    GEOPOLITICAL_REGIONAL_POLYGON_COMPOSING_CLAIMS = 1995;
    GEOPOLITICAL_GEOMETRY_REST_OF_WORLD_POLYGON = 90;
    GEOPOLITICAL_GEOMETRY_SELF_POLYGON = 91;
    INFERRED_GEOMETRY_GEOMETRY_COMPOSITION = 93;
    INFERRED_GEOMETRY_DEFINES_GEOMETRY_FOR = 76;
    INTERSECTION = 73988;
    INTERSECTION_GROUP = 4721;
    INTERSECTION_GROUP_CHILD_GROUP = 4739;
    INTERSECTION_GROUP_GROUP_TYPE = 4738;
    INTERSECTION_GROUP_PARENT_GROUP = 4740;
    INTERSECTION_IN_GROUP = 4737;
    INTERSECTION_TOLL_CLUSTER = 77;
    IN_SEGMENT = 4722;
    KNOWLEDGE_GRAPH_PROPERTY = 20;
    LABEL_BACKGROUND_COLOR = 4689;
    LABEL_TEXT_COLOR = 4690;
    LAND_USE = 141;
    LANE_MARKER_BARRIER_MATERIALS = 70;
    LANE_MARKER_CROSSING_PATTERN = 71;
    LANE_MARKER_LINEAR_PATTERN = 72;
    LEVEL_BUILDING = 4916;
    LEVEL_NUMBER = 4914;
    LOCALE_LANGUAGE = 21;
    LOCALE_LOCALIZATION_POLICY_ID = 22;
    LOGICAL_BORDER_BORDER_SEGMENT = 86;
    LOGICAL_BORDER_STATUS = 87;
    MEDIAN_GEOMETRY_SEGMENT_LOOP = 116;
    OPERATIONS_TEMPORARY_CLOSURE = 79;
    PARKING_ALLOWANCE = 33;
    PARKING_ASSOCIATION = 150;
    PARKING_AVAILABLE = 34;
    PARKING_OPENING_HOURS_EXCEPTION = 35;
    PARKING_OPENING_HOURS_REGULAR_HOURS = 36;
    PARKING_PROVIDER_FEATURE = 37;
    PARKING_RESTRICTION = 38;
    PEAK_PROMINENCE = 3;
    PHONE_NUMBER = 4881;
    POINT = 278;
    POLITICAL_CLAIM = 1989;
    POLYGON = 280;
    POLYGON_FOR_DISPLAY = 287;
    POLYLINE = 279;
    RANK = 354;
    RANK_SIGNAL = 355;
    REGULATED_AREA_REQUIRED_EMISSIONS_STICKER = 138;
    REGULATED_AREA_RESTRICTION = 301;
    RELATED_BORDER = 68;
    RELATED_ENTRANCE = 51;
    RELATED_FEATURE = 357;
    RELATED_TERMINAL_POINT = 56;
    RELATED_TIMEZONE = 43;
    RESTRICTION_GROUP_IS_VARIABLE = 147;
    RESTRICTION_GROUP_RELATED_SIGNPOST = 148;
    RESTRICTION_GROUP_SEGMENT = 30;
    RESTRICTION_GROUP_TRAVEL_PATTERN_RESTRICTION = 149;
    ROAD_DISRUPTION_AFFECTED_INTERSECTION_TRAVERSAL = 132;
    ROAD_DISRUPTION_AFFECTED_SEGMENT_PORTIONS = 106;
    ROAD_DISRUPTION_AFFECTED_TRAVEL_MODE = 137;
    ROAD_DISRUPTION_AFFECTED_VEHICLE_FILTER = 140;
    ROAD_DISRUPTION_CAUSE = 107;
    ROAD_DISRUPTION_CURRENT_STATE = 108;
    ROAD_DISRUPTION_FUTURE_STATE = 109;
    ROAD_DISRUPTION_LAST_ACTIVE_START_DATETIME = 110;
    ROAD_DISRUPTION_LAST_INACTIVE_START_DATETIME = 111;
    ROAD_DISRUPTION_PLANNED_SCHEDULE = 112;
    ROAD_DISRUPTION_SCHEDULE_RESUMPTION_TIME = 142;
    ROAD_MONITOR_MONITORED_ROAD = 69;
    ROUTE_CHILD_TYPE = 8;
    SCHOOL_DISTRICT_TYPE = 92;
    SEGMENT_ACCIDENT_PRONE_SPOT = 115;
    SEGMENT_ADVISORY_MAXIMUM_SPEED = 61;
    SEGMENT_AVERAGE_SPEED = 4627;
    SEGMENT_BARRIER = 4635;
    SEGMENT_BICYCLE_FACILITY = 4641;
    SEGMENT_BICYCLE_SAFETY = 4642;
    SEGMENT_CONDITION = 4636;
    SEGMENT_CONSTRUCTION_BEGIN_DATE = 73991;
    SEGMENT_CONSTRUCTION_END_DATE = 73992;
    SEGMENT_CONSTRUCTION_STATUS = 4637;
    SEGMENT_COVERED = 44;
    SEGMENT_DISTANCE_TO_EDGE = 73993;
    SEGMENT_EDGE_FOLLOWS_SEGMENT_BEGIN_FRACTION = 81;
    SEGMENT_EDGE_FOLLOWS_SEGMENT_END_FRACTION = 82;
    SEGMENT_ELEVATION = 4631;
    SEGMENT_ENDPOINT = 4634;
    SEGMENT_GRADE_LEVEL_LIST = 73990;
    SEGMENT_INNER_BARRIER = 119;
    SEGMENT_INTERNAL_DISALLOWED_CONNECTIONS = 95;
    SEGMENT_INTERNAL_DISALLOWED_PRIMARY_CONNECTION = 96;
    SEGMENT_INTERNAL_TRAVEL_ALLOWANCE = 4660;
    SEGMENT_INTERPOLATION_OFFSET_METERS = 52;
    SEGMENT_IS_MAX_PERMITTED_SPEED_DERIVED = 74034;
    SEGMENT_LANE = 4626;
    SEGMENT_LEGAL_MAXIMUM_SPEED = 59;
    SEGMENT_LEGAL_MINIMUM_SPEED = 60;
    SEGMENT_MAX_SPEED = 74033;
    SEGMENT_ON_RIGHT = 73985;
    SEGMENT_OUTER_BARRIER = 120;
    SEGMENT_PATH = 297;
    SEGMENT_PEDESTRIAN_CROSSING = 28;
    SEGMENT_PEDESTRIAN_FACILITY = 4705;
    SEGMENT_PEDESTRIAN_GRADE = 12;
    SEGMENT_PRIORITY = 4633;
    SEGMENT_RAMP_MAX_CONNECTED_PRIORITY = 100;
    SEGMENT_RELATED_MEDIAN = 117;
    SEGMENT_RESTRICTION = 4639;
    SEGMENT_ROAD_CAMERA = 58;
    SEGMENT_ROAD_DISRUPTION = 118;
    SEGMENT_ROAD_ENCLOSURE = 153;
    SEGMENT_ROAD_SIGN = 4679;
    SEGMENT_ROUTE = 4673;
    SEGMENT_ROUTE_ASSOCIATION = 73989;
    SEGMENT_SEPARATED_ROADWAYS = 73986;
    SEGMENT_SIGNPOST = 146;
    SEGMENT_SLOPE = 94;
    SEGMENT_SURFACE = 4632;
    SEGMENT_SWEEP = 53;
    SEGMENT_TOLL_ROAD = 73987;
    SEGMENT_USAGE = 4638;
    SEGMENT_VISIBLE_LANDMARK = 16;
    SIGN_COMPONENT = 4769;
    SIGNPOST_MOVABLE_POST = 143;
    SIGNPOST_SEGMENT = 144;
    SIGNPOST_SIGN = 145;
    SKI_BOUNDARY_TYPE = 133;
    SKI_LIFT_TYPE = 134;
    SKI_TRAIL_DIFFICULTY = 135;
    SKI_TRAIL_TYPE = 136;
    SOCIAL_REFERENCE_CLAIMED_GAIA_ID = 385;
    SOURCE_INFO = 342;
    STATUS_CLOSED = 46;
    STATUS_CLOSE_REASON = 45;
    STATUS_END_AS_OF_DATE = 80;
    STATUS_END_DATE = 47;
    STATUS_PREVENT_REVIVAL = 158;
    STATUS_REMOVED = 48;
    STATUS_REMOVED_REASON = 49;
    STATUS_START_DATE = 50;
    STOREFRONT_GEOMETRY = 88;
    STOREFRONT_GEOMETRY_MODEL = 101;
    SYNTHETIC_GEOMETRY = 347;
    THREE_DIMENSIONAL_MODEL = 285;
    TOLL_CLUSTER_INTERSECTION = 78;
    TOLL_PATH_TOLL_CLUSTER_SEQUENCE = 104;
    TRANSIT_LINE_AGENCY = 41;
    TRANSIT_LINE_STATION = 32;
    TRANSIT_LINE_VARIANT_LINE_CONCEPT = 54;
    TRANSIT_LINE_VARIANT_STOP = 55;
    TRANSIT_LINE_VEHICLE_TYPE = 42;
    TRANSIT_STATION_AGENCY_ASSOCIATION = 97;
    VERTICAL_ORDERING_LEVEL = 73;
    VISUALIZATION_AREA = 99;
    WATER_REMOVED_POLYGON = 89;
    DEPRECATED_DO_NOT_USE_EMAIL_ADDRESS = 4884 [deprecated = true];
    DEPRECATED_DO_NOT_USE_RANK_GEOMETRY = 286 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SEGMENT_INFO = 74769 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SEGMENT_LANE_LIST = 4785 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SEGMENT_WRONG_WAY = 4625 [deprecated = true];
    DEPRECATED_DO_NOT_USE_WEBSITE = 4883 [deprecated = true];
    FEATURE_ATTRIBUTE = 5266 [deprecated = true];
    SOCIAL_REFERENCE = 19 [deprecated = true];
    CATEGORY = 4882 [deprecated = true];
    DEPRECATED_DO_NOT_USE_CAPITAL = 4497 [deprecated = true];
    DEPRECATED_DO_NOT_USE_DESCRIPTION = 4897 [deprecated = true];
    DEPRECATED_DO_NOT_USE_DISTINCT = 352 [deprecated = true];
    DEPRECATED_DO_NOT_USE_DUPLICATE = 345 [deprecated = true];
    EDIT_PRECEDENCE = 349 [deprecated = true];
    DEPRECATED_DO_NOT_USE_EDIT_PRECEDENCE = 349 [deprecated = true];
    DEPRECATED_DO_NOT_USE_ENTRANCE_TARGET = 40 [deprecated = true];
    DEPRECATED_DO_NOT_USE_ESTABLISHMENT_PLACE_ACTION_PAGE = 15 [deprecated = true];
    DEPRECATED_DO_NOT_USE_ESTABLISHMENT_TYPE = 1249823 [deprecated = true];
    DEPRECATED_DO_NOT_USE_EVENT = 5265 [deprecated = true];
    DEPRECATED_DO_NOT_USE_GEOMETRIC_ACCURACY = 337 [deprecated = true];
    DEPRECATED_DO_NOT_USE_HIGHEST_GRADE = 5139 [deprecated = true];
    DEPRECATED_DO_NOT_USE_ID_TO_OVERRIDE = 341 [deprecated = true];
    DEPRECATED_DO_NOT_USE_ISSUE_HISTORY = 370 [deprecated = true];
    DEPRECATED_DO_NOT_USE_ISSUE_METADATA = 369 [deprecated = true];
    DEPRECATED_DO_NOT_USE_KNOWLEDGE_GRAPH_ID = 348 [deprecated = true];
    DEPRECATED_DO_NOT_USE_LOWEST_GRADE = 5138 [deprecated = true];
    DEPRECATED_DO_NOT_USE_PAYMENT_TYPES = 4885 [deprecated = true];
    DEPRECATED_DO_NOT_USE_PHOTO = 4900 [deprecated = true];
    DEPRECATED_DO_NOT_USE_PHOTO_URL = 4898 [deprecated = true];
    DEPRECATED_DO_NOT_USE_PLACE_CLOSED = 4899 [deprecated = true];
    DEPRECATED_DO_NOT_USE_POPULATION = 4498 [deprecated = true];
    DEPRECATED_DO_NOT_USE_RANK_USER = 275 [deprecated = true];
    DEPRECATED_DO_NOT_USE_REMOVE_DUPLICATE = 338 [deprecated = true];
    DEPRECATED_DO_NOT_USE_REMOVE_PLACE = 339 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SCHOOL_TYPE = 5140 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SEGMENT_ELEVATION_BEGIN = 4628 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SEGMENT_ELEVATION_END = 4630 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SEGMENT_ELEVATION_MIDDLE = 4629 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SEGMENT_TOLL_CRITERIA = 114 [deprecated = true];
    DEPRECATED_DO_NOT_USE_SYLLABUS = 5137 [deprecated = true];
    DEPRECATED_DO_NOT_USE_TRACK_CLASS = 4657 [deprecated = true];
    DEPRECATED_DO_NOT_USE_VIEWCODE_INFO = 344 [deprecated = true];
    DEPRECATED_DO_NOT_USE_WORKAREA = 371 [deprecated = true];
    DEPRECATED_DO_NOT_USE_INFERRED_GEOMETRY_INCLUDES_GEOMETRY_OF = 74 [deprecated = true];
    DEPRECATED_DO_NOT_USE_INFERRED_GEOMETRY_EXCLUDES_GEOMETRY_OF = 75 [deprecated = true];
    DEPRECATED_DO_NOT_USE_TRANSIT_STATION_AGENCY = 84 [deprecated = true];
    DEPRECATED_DO_NOT_USE_ELECTRIC_VEHICLE_CHARGING_STATION_EXTERNAL_ID = 113 [deprecated = true];
}
