syntax = "proto2";

package geostore;

import "geostore/base/proto/options.proto";
import "geostore/base/proto/stable_id_options.proto";
import "google/api/inclusion.proto";
import "java/com/google/apps/jspb/jspb.proto";

option objc_class_prefix = "GS";
option java_multiple_files = true;
option java_package = "com.google.geostore.base.proto";

message SignProto {
    optional uint64 sign_id = 1;
    
    optional SignType type = 2;
    enum SignType {
        UNKNOWN = 0;
        AUX_BACKGROUND = 341;
        AUX_BAG_OF_SIGNS = 641;
        AUX_ACCIDENT_AREA = 299;
        AUX_ARROW_DOWN = 416;
        AUX_ARROW_LEFT = 476;
        AUX_ARROW_LEFT_RIGHT = 493;
        AUX_ARROW_RIGHT = 475;
        AUX_ARROW_UP = 415;
        AUX_BICYCLE_AND_BUS_CROSSING = 546;
        AUX_CARAVAN = 306;
        AUX_CONCESSION_ROAD_END = 650;
        AUX_CONCESSION_ROAD_START = 649;
        AUX_CYCLING_IN_THE_OPPOSITE_DIRECTION = 297;
        AUX_DIVERSION_SIGNAGE_CIRCULAR = 293;
        AUX_END_ACCIDENT_AREA = 409;
        AUX_END_SPEED_CAMERA = 537;
        AUX_END_TWO_OPPOSITE_VERTICAL_ARROW = 505;
        AUX_END_TWO_WAY_CYCLE_ROUTE = 535;
        AUX_EXPRESSWAY_DETOUR_DESTINATION = 526;
        AUX_FIRE_EXTINGUISHER = 517;
        AUX_HAZARDOUS_SIDEWIND = 300;
        AUX_INCLUDING_CYCLIST_AND_MOPED_RIDER = 314;
        AUX_INFORMATION_ABOUT_MOTORAIL_FOR_LORRY = 307;
        AUX_INSUFFICIENT_CLEARANCE = 427;
        AUX_LEFT_LANE = 438;
        AUX_LEFT_TURN = 134;
        AUX_LOW_EMISSION_ZONE_STICKER_PERMITTED = 309;
        AUX_MIGRATORY_TOAD_CROSSING = 301;
        AUX_MILITARY_VEHICLE = 136;
        AUX_MILITARY_WEIGHT_CLASS = 302;
        AUX_MOTORWAY_DETOUR_DESTINATION = 555;
        AUX_NATURAL_RESERVE = 140;
        AUX_NON_WORKING_DAY = 473;
        AUX_NO_PARKING_ON_SHOULDER = 315;
        AUX_ONE_WAY_CYCLE_ROUTE = 496;
        AUX_OVERTAKING_AGRICULTURAL_VEHICLES_ALLOWED = 344;
        AUX_OVERTAKING_BICYCLE_DISTANCE = 561;
        AUX_PLAY_STREET = 303;
        AUX_POI = 339;
        AUX_RADIO = 516;
        AUX_REDUCED_VISIBILITY = 648;
        AUX_RIGHT_LANE = 439;
        AUX_RIGHT_OF_WAY_AT_CROSSING = 216;
        AUX_RIGHT_TURN = 135;
        AUX_RISK_OF_COLLISION_WITH_TREES = 428;
        AUX_RIVER = 477;
        AUX_SIDEWALK_LEFT = 291;
        AUX_SIDEWALK_RIGHT = 292;
        AUX_SNOW_OR_ICE = 371;
        AUX_SPEED_BUMP = 495;
        AUX_SPEED_CAMERA = 469;
        AUX_STREET_NAME = 570;
        AUX_TEXTUAL_QUALIFIER_NO_SYMBOL = 311;
        AUX_TO_THE_LEFT = 132;
        AUX_TO_THE_RIGHT = 133;
        AUX_TRAILER = 305;
        AUX_TUNNEL_CATEGORY = 308;
        AUX_TWO_OPPOSING_HORIZONTAL_ARROW = 294;
        AUX_TWO_OPPOSITE_VERTICAL_ARROW = 295;
        AUX_TWO_WAY_BUS_ROUTE = 621;
        AUX_TWO_WAY_CYCLE_ROUTE = 296;
        AUX_VARIABLE_INFORMATION_SIGN = 611;
        AUX_WEEKEND_AND_HOLIDAY = 507;
        AUX_WHEN_WET = 312;
        AUX_WINTER_SPORT = 304;
        AUX_WORKING_DAY = 472;
        DANGER_STRIPED_RAILROAD_CROSSING = 137;
        DANGER_STRIPED_RAILROAD_CROSSING_DISTANCE = 138;
        DIRECTIONAL_AIRPORT = 498;
        DIRECTIONAL_ALTERNATE_OR_BYPASS_ROUTE = 284;
        DIRECTIONAL_APPROACHES_TO_JUNCTION = 253;
        DIRECTIONAL_APPROACHES_TO_JUNCTION_LANE = 254;
        DIRECTIONAL_AUTOMATIC_TRAFFIC_CONTROL = 668;
        DIRECTIONAL_BICYCLE_ROAD = 185;
        DIRECTIONAL_BICYCLE_ROUTE = 241;
        DIRECTIONAL_BLOCK_DETOUR = 523;
        DIRECTIONAL_BREAKDOWN_BAY = 176;
        DIRECTIONAL_BRIDGE = 519;
        DIRECTIONAL_BUS_ROUTE = 532;
        DIRECTIONAL_CAMPSITE = 199;
        DIRECTIONAL_CARAVAN_CAMPSITE = 205;
        DIRECTIONAL_CAR_POOL_LANE = 513;
        DIRECTIONAL_CENTER_LINE = 623;
        DIRECTIONAL_CHARGING_STATION_FOR_ELECTRIC_VEHICLE = 204;
        DIRECTIONAL_CHECKPOINT_TOLL_IN_DISTANCE = 448;
        DIRECTIONAL_CIRCULAR_ROUTE = 670;
        DIRECTIONAL_CITY_DISTANCE_SIGN = 266;
        DIRECTIONAL_COUNTRY_SPEED_LIMIT_BOARD = 209;
        DIRECTIONAL_DETOUR_DIRECTION = 256;
        DIRECTIONAL_DIRECTION_TO_EXPRESSWAY = 547;
        DIRECTIONAL_DIRECTION_TO_MOTORWAY = 249;
        DIRECTIONAL_DISC_PARKING = 174;
        DIRECTIONAL_DO_NOT_CROSS_LANE = 600;
        DIRECTIONAL_DRIVING_DIRECTION_IN_THE_LANE = 501;
        DIRECTIONAL_DRIVING_ON_TRAM_PERMITTED = 624;
        DIRECTIONAL_DUAL_CARRIAGEWAY = 646;
        DIRECTIONAL_ELECTRONIC_TOLL_PAYMENT = 666;
        DIRECTIONAL_EMERGENCY_PHONE = 192;
        DIRECTIONAL_END_BICYCLE_ROAD = 186;
        DIRECTIONAL_END_CAR_POOL_LANE = 514;
        DIRECTIONAL_END_DUAL_CARRIAGEWAY = 647;
        DIRECTIONAL_END_ELECTRONIC_TOLL_PAYMENT = 667;
        DIRECTIONAL_END_METERED_PARKING = 497;
        DIRECTIONAL_END_OF_ALTERNATE_OR_BYPASS_ROUTE = 285;
        DIRECTIONAL_END_OF_DETOUR_OR_BYPASS = 184;
        DIRECTIONAL_END_OF_LOCALITY = 441;
        DIRECTIONAL_END_OF_PARKING_ZONE = 168;
        DIRECTIONAL_END_PASSING_PLACE = 385;
        DIRECTIONAL_END_TOLL_ROAD = 449;
        DIRECTIONAL_END_TOLL_ROAD_FOR_HEAVY_VEHICLE = 207;
        DIRECTIONAL_END_TUNNEL = 412;
        DIRECTIONAL_ENTRANCE = 612;
        DIRECTIONAL_EUROPEAN_EXPRESSWAY_NUMBER = 212;
        DIRECTIONAL_EU_COUNTRY_BORDER = 539;
        DIRECTIONAL_EVACUATION_ROUTE = 673;
        DIRECTIONAL_EXIT = 613;
        DIRECTIONAL_EXIT_NUMBER = 457;
        DIRECTIONAL_EXPRESSWAY_DISTANCE_MARKER = 268;
        DIRECTIONAL_EXPRESSWAY_DISTANCE_SIGN = 270;
        DIRECTIONAL_EXPRESSWAY_JUNCTION_SIGN_LANE = 548;
        DIRECTIONAL_EXPRESSWAY_NUMBER = 210;
        DIRECTIONAL_FIRST_AID = 189;
        DIRECTIONAL_GAS_STATION = 193;
        DIRECTIONAL_HAZARDOUS_CARGO_ROUTE = 225;
        DIRECTIONAL_HEAVY_VEHICLE_ROUTE = 217;
        DIRECTIONAL_HIGHWAY_EXIT = 181;
        DIRECTIONAL_HIGHWAY_EXIT_NAMED = 178;
        DIRECTIONAL_HIGHWAY_EXIT_SERVICE_AREA = 414;
        DIRECTIONAL_HOSPITAL = 444;
        DIRECTIONAL_HOT_LANE = 639;
        DIRECTIONAL_INFORMATION = 200;
        DIRECTIONAL_JUNCTION_DIRECTIONAL = 215;
        DIRECTIONAL_KEEP_LEFT = 588;
        DIRECTIONAL_KEEP_RIGHT = 506;
        DIRECTIONAL_LANES_TRAFFIC_FLOW = 155;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_LIMITED_WIDTH = 156;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_MINIMUM_SPEED = 159;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_MINIMUM_SPEED_END = 429;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_NO_HEAVY_VEHICLES = 158;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_PUBLIC_TRANSPORT_LANE = 426;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_SLIPPERY_ROAD_WHEN_WET = 644;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_SPEED_LIMIT = 157;
        DIRECTIONAL_LANES_TRAFFIC_FLOW_SPEED_LIMIT_END = 160;
        DIRECTIONAL_LANES_USAGE = 614;
        DIRECTIONAL_LAYOUT_OF_DETOUR_OR_BYPASS_ROUTE = 273;
        DIRECTIONAL_METERED_PARKING = 423;
        DIRECTIONAL_METRIC_SIGNAGE = 608;
        DIRECTIONAL_METRO_ENTRANCE = 609;
        DIRECTIONAL_MOTEL = 194;
        DIRECTIONAL_MOTORWAY_BYPASS = 274;
        DIRECTIONAL_MOTORWAY_CAFE = 196;
        DIRECTIONAL_MOTORWAY_DISTANCE_MARKER = 267;
        DIRECTIONAL_MOTORWAY_DISTANCE_SIGN = 269;
        DIRECTIONAL_MOTORWAY_END_OF_SERVICE_AREA = 446;
        DIRECTIONAL_MOTORWAY_EXIT = 180;
        DIRECTIONAL_MOTORWAY_EXIT_NAMED = 177;
        DIRECTIONAL_MOTORWAY_EXIT_SERVICE_AREA = 413;
        DIRECTIONAL_MOTORWAY_HOV_LANE = 594;
        DIRECTIONAL_MOTORWAY_INTERCHANGE_NUMBER = 213;
        DIRECTIONAL_MOTORWAY_JUNCTION_SIGN = 255;
        DIRECTIONAL_MOTORWAY_JUNCTION_SIGN_LANE = 430;
        DIRECTIONAL_MOTORWAY_NUMBER = 211;
        DIRECTIONAL_MOTORWAY_RESTAURANT = 195;
        DIRECTIONAL_MUNICIPAL_BOUNDARY = 422;
        DIRECTIONAL_NO_SIDEWALK_PARKING = 418;
        DIRECTIONAL_NO_SIDEWALK_STOPPING = 536;
        DIRECTIONAL_OVER_HEIGHT_VEHICLE_ROUTE = 626;
        DIRECTIONAL_PARALLEL_RIDING_PERMITTED = 625;
        DIRECTIONAL_PARKING_FOR_HIKER = 173;
        DIRECTIONAL_PARKING_GARAGE = 167;
        DIRECTIONAL_PARK_AND_RIDE = 172;
        DIRECTIONAL_PASSING_PLACE = 354;
        DIRECTIONAL_PAY_PHONE = 191;
        DIRECTIONAL_PEDESTRIAN_CROSSING_PATROL = 188;
        DIRECTIONAL_PEDESTRIAN_OVERPASS = 203;
        DIRECTIONAL_PEDESTRIAN_UNDERPASS = 202;
        DIRECTIONAL_PICNIC_AREA = 445;
        DIRECTIONAL_POLICE = 190;
        DIRECTIONAL_POST_OFFICE = 504;
        DIRECTIONAL_PRIVATE_ROAD = 545;
        DIRECTIONAL_PROVINCIAL_BOUNDARY = 369;
        DIRECTIONAL_PUBLIC_TOILET = 197;
        DIRECTIONAL_RAILWAY_STATION = 499;
        DIRECTIONAL_REPAIR = 201;
        DIRECTIONAL_RIVER = 447;
        DIRECTIONAL_ROAD_CHURCH = 198;
        DIRECTIONAL_SIDEWALK_PARKING = 170;
        DIRECTIONAL_START_OF_DETOUR_OR_BYPASS = 183;
        DIRECTIONAL_START_OF_LOCALITY = 154;
        DIRECTIONAL_STOPPING_PERMITTED = 632;
        DIRECTIONAL_STOP_LINE = 637;
        DIRECTIONAL_TOLL_BOOTH = 520;
        DIRECTIONAL_TOLL_ROAD = 208;
        DIRECTIONAL_TOLL_ROAD_FOR_HEAVY_VEHICLE = 206;
        DIRECTIONAL_TRAM_STOP = 630;
        DIRECTIONAL_TRANSFER_TO_OTHER_LANES_OR_CARRIGEWAY = 286;
        DIRECTIONAL_TRUCK_LANE = 635;
        DIRECTIONAL_TUNNEL = 175;
        DIRECTIONAL_URBAN_DIRECTION_SIGN = 251;
        DIRECTIONAL_URBAN_JUNCTION_SIGN = 431;
        DIRECTIONAL_URBAN_JUNCTION_SIGN_LANE = 432;
        DIRECTIONAL_URBAN_ROAD_EXIT = 182;
        DIRECTIONAL_URBAN_ROAD_EXIT_NAMED = 179;
        DIRECTIONAL_WATER_POLLUTANT_CARGO_ROUTE = 233;
        DIRECTIONAL_WATER_PROTECTION_ZONE = 187;
        LOCATION_QUALIFIER_APPLIES_IN_DISTANCE = 120;
        LOCATION_QUALIFIER_APPLIES_UNTIL_DISTANCE = 118;
        LOCATION_QUALIFIER_APPLIES_WITHIN_DISTANCE = 458;
        LOCATION_QUALIFIER_FOR_FURTHER_DISTANCE = 119;
        LOCATION_QUALIFIER_STOP_IN_DISTANCE = 121;
        MANDATORY_ADDITIONAL_LANE = 377;
        MANDATORY_BICYCLE_AND_BUS_LANE = 529;
        MANDATORY_BICYCLE_AND_CAR_LANE = 530;
        MANDATORY_BICYCLE_CROSSING = 631;
        MANDATORY_BICYCLE_DISMOUNT = 606;
        MANDATORY_BICYCLE_LANE = 515;
        MANDATORY_BICYCLE_ONLY = 111;
        MANDATORY_BICYCLE_PARKING = 607;
        MANDATORY_BICYCLE_ZONE = 91;
        MANDATORY_BUS_CROSSING = 424;
        MANDATORY_BUS_LANE = 92;
        MANDATORY_CAR_ONLY = 410;
        MANDATORY_CYCLE_AND_MOPED_ONLY = 383;
        MANDATORY_DRIVE_ON_SHOULDER = 107;
        MANDATORY_EMERGENCY_ESCAPE_LANE = 357;
        MANDATORY_END_BICYCLE_AND_BUS_LANE = 531;
        MANDATORY_END_BICYCLE_AND_CAR_LANE = 549;
        MANDATORY_END_BICYCLE_LANE = 538;
        MANDATORY_END_BICYCLE_ONLY = 351;
        MANDATORY_END_BUS_LANE = 386;
        MANDATORY_END_CAR_ONLY = 411;
        MANDATORY_END_CYCLE_AND_MOPED_ONLY = 384;
        MANDATORY_END_DRIVE_ON_SHOULDER = 109;
        MANDATORY_END_EQUESTRIAN_ONLY = 368;
        MANDATORY_END_HEADLIGHTS = 400;
        MANDATORY_END_HEAVY_VEHICLE_ONLY = 403;
        MANDATORY_END_MOTORCYCLE_ONLY = 405;
        MANDATORY_END_OF_ROAD_WORK = 419;
        MANDATORY_END_ONE_WAY_FORWARD = 490;
        MANDATORY_END_PARKING = 492;
        MANDATORY_END_PEDESTRIAN_BICYCLE_ONLY = 359;
        MANDATORY_END_PEDESTRIAN_BICYCLE_ONLY_SEPARATE_PATH = 360;
        MANDATORY_END_PEDESTRIAN_ONLY = 358;
        MANDATORY_END_PRIORITY_TO_POST_BUS = 356;
        MANDATORY_EQUESTRIAN_ONLY = 112;
        MANDATORY_HEADLIGHTS = 399;
        MANDATORY_HEAVY_VEHICLE_ONLY = 402;
        MANDATORY_HORN = 634;
        MANDATORY_INDICATOR_LIGHTS = 669;
        MANDATORY_LANE_ENDS = 376;
        MANDATORY_LEFT_OR_RIGHT_AHEAD = 100;
        MANDATORY_LEFT_RIGHT_STRAIGHT_AHEAD = 550;
        MANDATORY_MOTORCYCLE_ONLY = 404;
        MANDATORY_NO_THROUGH_ROAD = 106;
        MANDATORY_NO_THROUGH_ROAD_IN_SIDE_STREET = 442;
        MANDATORY_ONE_WAY_FORWARD = 352;
        MANDATORY_ONE_WAY_LEFT = 102;
        MANDATORY_ONE_WAY_RIGHT = 103;
        MANDATORY_PARKING = 162;
        MANDATORY_PARKING_IN_DISTANCE = 163;
        MANDATORY_PARKING_ZONE = 161;
        MANDATORY_PASS_EITHER_SIDE = 375;
        MANDATORY_PASS_ON_THE_LEFT = 105;
        MANDATORY_PASS_ON_THE_RIGHT = 104;
        MANDATORY_PEDESTRIAN_BICYCLE_ONLY = 114;
        MANDATORY_PEDESTRIAN_BICYCLE_ONLY_SEPARATE_PATH = 115;
        MANDATORY_PEDESTRIAN_CROSSING = 108;
        MANDATORY_PEDESTRIAN_EQUESTRIAN_ONLY = 619;
        MANDATORY_PEDESTRIAN_ONLY = 113;
        MANDATORY_PRIORITY_TO_POST_BUS = 355;
        MANDATORY_PROCEED_LEFT = 97;
        MANDATORY_PROCEED_RIGHT = 96;
        MANDATORY_RESERVED_PARKING = 590;
        MANDATORY_RIGHT_TURN_FROM_LEFT_ONLY = 658;
        MANDATORY_ROUNDABOUT = 101;
        MANDATORY_SEPARATE_PATH = 620;
        MANDATORY_SNOWMOBILE_ONLY = 551;
        MANDATORY_STRAIGHT_AHEAD = 95;
        MANDATORY_STRAIGHT_OR_TURN_LEFT = 99;
        MANDATORY_STRAIGHT_OR_TURN_RIGHT = 98;
        MANDATORY_STRAIGHT_OR_U_TURN = 565;
        MANDATORY_STRAIGHT_TO_THE_LEFT = 544;
        MANDATORY_STRAIGHT_TO_THE_RIGHT = 543;
        MANDATORY_TIME_LIMITED_PARKING = 591;
        MANDATORY_TURN_LEFT = 94;
        MANDATORY_TURN_LEFT_OR_U_TURN = 593;
        MANDATORY_TURN_RIGHT = 93;
        MANDATORY_TWO_STAGE_RIGHT_TURN_FOR_MOPED = 633;
        MANDATORY_TWO_WAY_STREET = 382;
        MANDATORY_U_TURN = 363;
        MANDATORY_VACATE_SHOULDER = 110;
        PRIORITY_ALL_WAY = 577;
        PRIORITY_PRIORITY_OVER_ONCOMING_VEHICLE = 5;
        PRIORITY_PRIORITY_ROAD = 3;
        PRIORITY_PRIORITY_ROAD_END = 4;
        PRIORITY_STOP = 2;
        PRIORITY_YIELD = 1;
        PRIORITY_YIELD_BICYCLE = 596;
        PRIORITY_YIELD_TO_ONCOMING_VEHICLE = 6;
        PROHIBITORY_BIKE_OVERTAKING_RESTRICTION_FOR_CAR = 152;
        PROHIBITORY_CUSTOM_AREA_ZONE = 488;
        PROHIBITORY_END_CUSTOM_AREA_ZONE = 489;
        PROHIBITORY_END_HEAVY_VEHICLE_PROHIBITED_OVERTAKING = 50;
        PROHIBITORY_END_MAXIMUM_WEIGHT_ZONE = 542;
        PROHIBITORY_END_OF_ALL_RESTRICTION = 51;
        PROHIBITORY_END_OF_BIKE_OVERTAKING_RESTRICTION_FOR_CAR = 153;
        PROHIBITORY_END_OF_RESTRICTED_ACCESS_ZONE = 671;
        PROHIBITORY_END_PROHIBITED_CRUISE_CONTROL = 388;
        PROHIBITORY_END_PROHIBITED_HORN = 394;
        PROHIBITORY_END_PROHIBITED_OVERTAKING = 49;
        PROHIBITORY_END_PROHIBITED_OVERTAKING_BY_MOTORCYCLE = 392;
        PROHIBITORY_END_PROHIBITED_PARKING = 401;
        PROHIBITORY_END_PROHIBITED_STOPPING_ZONE = 522;
        PROHIBITORY_END_PROHIBITED_TRUCK = 459;
        PROHIBITORY_END_PROHIBITED_TRUCK_PARKING = 566;
        PROHIBITORY_END_RESTRICTED_PARKING_ZONE = 37;
        PROHIBITORY_MAXIMUM_WEIGHT_ZONE = 450;
        PROHIBITORY_MAXIMUM_WIDTH_ZONE = 451;
        PROHIBITORY_PROHIBITED_AGRICULTURAL_VEHICLE = 40;
        PROHIBITORY_PROHIBITED_ANIMAL_DRAWN_VEHICLE = 146;
        PROHIBITORY_PROHIBITED_AXLE_WEIGHT_OVER = 44;
        PROHIBITORY_PROHIBITED_BICYCLE = 31;
        PROHIBITORY_PROHIBITED_BICYCLE_PARKING = 541;
        PROHIBITORY_PROHIBITED_BIKE_AND_MOTORCYCLE = 393;
        PROHIBITORY_PROHIBITED_BIKE_AND_PEDESTRIAN = 509;
        PROHIBITORY_PROHIBITED_BUS = 32;
        PROHIBITORY_PROHIBITED_CATTLE = 147;
        PROHIBITORY_PROHIBITED_CROSSING_CENTER_LINE = 629;
        PROHIBITORY_PROHIBITED_CRUISE_CONTROL = 387;
        PROHIBITORY_PROHIBITED_DANGEROUS_CARGO = 42;
        PROHIBITORY_PROHIBITED_DOUBLE_RIDING = 628;
        PROHIBITORY_PROHIBITED_EQUESTRIAN = 145;
        PROHIBITORY_PROHIBITED_ESCOOTER = 510;
        PROHIBITORY_PROHIBITED_EXPLOSIVE_CARGO = 364;
        PROHIBITORY_PROHIBITED_FOLLOWING_DISTANCE_UNDER = 24;
        PROHIBITORY_PROHIBITED_FOUR_WHEELER = 417;
        PROHIBITORY_PROHIBITED_HAND_CART = 365;
        PROHIBITORY_PROHIBITED_HEAVY_VEHICLE_OVERTAKING = 26;
        PROHIBITORY_PROHIBITED_HEIGHT_OVER = 46;
        PROHIBITORY_PROHIBITED_HORN = 362;
        PROHIBITORY_PROHIBITED_LEFT_OR_U_TURN = 578;
        PROHIBITORY_PROHIBITED_LEFT_STRAIGHT = 599;
        PROHIBITORY_PROHIBITED_LEFT_TURN = 166;
        PROHIBITORY_PROHIBITED_LENGTH_OVER = 47;
        PROHIBITORY_PROHIBITED_LITTERING = 597;
        PROHIBITORY_PROHIBITED_MOPED = 144;
        PROHIBITORY_PROHIBITED_MOPED_AND_BICYCLE = 406;
        PROHIBITORY_PROHIBITED_MOPED_BICYCLE_AND_AGRICULTURAL_VEHICLE = 665;
        PROHIBITORY_PROHIBITED_MOTORCYCLE = 143;
        PROHIBITORY_PROHIBITED_MOTOR_VEHICLE = 29;
        PROHIBITORY_PROHIBITED_MOTOR_VEHICLE_EXCEPT_MOTORCYCLE = 28;
        PROHIBITORY_PROHIBITED_NON_MOTOR_VEHICLE = 567;
        PROHIBITORY_PROHIBITED_NO_ENTRY = 48;
        PROHIBITORY_PROHIBITED_OVERTAKING = 25;
        PROHIBITORY_PROHIBITED_OVERTAKING_BY_MOTORCYCLE = 391;
        PROHIBITORY_PROHIBITED_PARKING = 34;
        PROHIBITORY_PROHIBITED_PARKING_LOADING_ZONE = 657;
        PROHIBITORY_PROHIBITED_PARKING_SNOW_ROUTE = 638;
        PROHIBITORY_PROHIBITED_PEDESTRIAN = 41;
        PROHIBITORY_PROHIBITED_PHOTOGRAPH = 518;
        PROHIBITORY_PROHIBITED_RIGHT_STRAIGHT = 598;
        PROHIBITORY_PROHIBITED_RIGHT_TURN = 149;
        PROHIBITORY_PROHIBITED_ROAD_CLOSED = 627;
        PROHIBITORY_PROHIBITED_ROLLERSKATING = 345;
        PROHIBITORY_PROHIBITED_SKIING = 347;
        PROHIBITORY_PROHIBITED_SLEDGING = 346;
        PROHIBITORY_PROHIBITED_SNOWMOBILE = 452;
        PROHIBITORY_PROHIBITED_STOPPING = 35;
        PROHIBITORY_PROHIBITED_STRAIGHT_AHEAD = 579;
        PROHIBITORY_PROHIBITED_STUDDED_TIRES = 552;
        PROHIBITORY_PROHIBITED_THRU_TRAFFIC_TRUCKS = 640;
        PROHIBITORY_PROHIBITED_TRAILER = 38;
        PROHIBITORY_PROHIBITED_TRUCK = 30;
        PROHIBITORY_PROHIBITED_TRUCK_AND_BUS = 378;
        PROHIBITORY_PROHIBITED_TRUCK_PARKING = 568;
        PROHIBITORY_PROHIBITED_TRUCK_WITH_TRAILER = 39;
        PROHIBITORY_PROHIBITED_TURN_ON_RED = 580;
        PROHIBITORY_PROHIBITED_U_TURN = 23;
        PROHIBITORY_PROHIBITED_VEHICLE = 27;
        PROHIBITORY_PROHIBITED_WATER_POLLUTANT_CARGO = 22;
        PROHIBITORY_PROHIBITED_WEIGHT_OVER = 43;
        PROHIBITORY_PROHIBITED_WIDTH_OVER = 45;
        PROHIBITORY_RESTRICTED_ACCESS_ZONE = 672;
        PROHIBITORY_START_PROHIBITED_STOPPING_ZONE = 521;
        PROHIBITORY_START_RESTRICTED_PARKING_ZONE = 36;
        PROHIBITORY_START_RESTRICTED_PARKING_ZONE_HEAVY_VEHICLE = 486;
        PROHIBITORY_WRONG_WAY = 585;
        REGULATORY_CHAIN_UP_AREA = 617;
        REGULATORY_CONTROLLED_BY_OFFICER = 643;
        REGULATORY_EMERGENCY_EXIT = 425;
        REGULATORY_EMERGENCY_MEDIAN_CROSSING = 663;
        REGULATORY_END_BICYCLE_ZONE = 142;
        REGULATORY_END_LOW_EMISSION_ZONE = 151;
        REGULATORY_END_MANDATORY_SNOW_CHAIN = 353;
        REGULATORY_END_OF_NO_ESCOOTER_ZONE = 482;
        REGULATORY_END_OF_NO_PARKING_ZONE_FOR_ESCOOTER = 480;
        REGULATORY_FASTEN_SEAT_BELT = 674;
        REGULATORY_GIVE_WAY_BUSES = 660;
        REGULATORY_LOW_EMISSION_ZONE = 150;
        REGULATORY_MANDATORY_SNOW_CHAIN = 148;
        REGULATORY_NO_ESCOOTER_ZONE = 481;
        REGULATORY_NO_PARKING_ZONE_FOR_ESCOOTER = 479;
        REGULATORY_ONCOMING_BICYCLES = 440;
        REGULATORY_PROHIBITED_MOBILE_PHONE_USE = 651;
        REGULATORY_PUBLIC_TRANSPORTATION_STOP = 139;
        REGULATORY_SHARED_ZONE = 652;
        REGULATORY_TAXI_STAND = 141;
        REGULATORY_TRANSIT_OR_EV_LANE = 653;
        REGULATORY_UNUSABLE_SHOULDER = 433;
        REGULATORY_UNUSABLE_SHOULDER_FOR_HEAVY_VEHICLE = 434;
        REGULATORY_VEHICLES_GET_TOWED = 437;
        ROAD_EQUIPMENT_BARRIER_BOARD = 287;
        ROAD_EQUIPMENT_CURVE_INDICATOR = 165;
        ROAD_EQUIPMENT_GUIDE_CONE = 288;
        ROAD_EQUIPMENT_MOVEABLE_ROAD_BARRIER = 289;
        ROAD_EQUIPMENT_OBSTACLE_INDICATOR_BOARD = 338;
        ROAD_EQUIPMENT_POSITION_DISTANCE_INDICATOR = 340;
        SPEED_ADVISORY_SPEED_LIMIT = 372;
        SPEED_ADVISORY_SPEED_ZONE = 508;
        SPEED_END_ADVISORY_SPEED_LIMIT = 373;
        SPEED_END_ADVISORY_SPEED_ZONE = 487;
        SPEED_END_MAXIMUM_SPEED_ZONE_FOR_ESCOOTER = 484;
        SPEED_END_OF_BUILT_UP_AREA = 14;
        SPEED_END_OF_MAXIMUM_SPEED = 16;
        SPEED_END_OF_MAX_SPEED_ZONE = 20;
        SPEED_END_OF_MINIMUM_SPEED = 18;
        SPEED_END_OF_RESERVED_ROAD = 421;
        SPEED_END_PEDESTRIAN_ZONE = 117;
        SPEED_END_TEXT_QUALIFIED_SPEED_LIMIT = 656;
        SPEED_EXIT_SPEED_LIMIT = 642;
        SPEED_EXPRESSWAY = 9;
        SPEED_EXPRESSWAY_END = 10;
        SPEED_HECTOMETER_POST = 571;
        SPEED_HIGHWAY_U_TURN = 664;
        SPEED_HOME_ZONE_END = 408;
        SPEED_HOME_ZONE_START = 407;
        SPEED_MAXIMUM_SPEED = 15;
        SPEED_MAXIMUM_SPEED_FOR_TRUCKS_AND_CARS = 474;
        SPEED_MAXIMUM_SPEED_ZONE = 19;
        SPEED_MAXIMUM_SPEED_ZONE_FOR_ESCOOTER = 483;
        SPEED_MAXIMUM_WITH_QUALIFIER_SPEED = 573;
        SPEED_MINIMUM_SPEED = 17;
        SPEED_MOTORWAY = 7;
        SPEED_MOTORWAY_END = 8;
        SPEED_PEDESTRIAN_ZONE = 116;
        SPEED_RADAR_SPEED = 622;
        SPEED_RESIDENTIAL_END = 12;
        SPEED_RESIDENTIAL_START = 11;
        SPEED_SCHOOL_ZONE_END = 471;
        SPEED_SCHOOL_ZONE_SPEED_LIMIT = 584;
        SPEED_SCHOOL_ZONE_START = 470;
        SPEED_START_OF_BUILT_UP_AREA = 13;
        SPEED_START_OF_RESERVED_ROAD = 420;
        SPEED_TEXT_QUALIFIED_ADVISORY_SPEED_LIMIT = 575;
        SPEED_TEXT_QUALIFIED_SPEED_LIMIT = 574;
        SPEED_VARIABLE_MAXIMUM_SPEED = 21;
        SYMBOLS_BICYCLE = 318;
        SYMBOLS_BUS = 324;
        SYMBOLS_CAMPERVAN = 329;
        SYMBOLS_CARSHARING_VEHICLE = 337;
        SYMBOLS_CATTLE = 322;
        SYMBOLS_CHILDREN = 466;
        SYMBOLS_DRAWN_CARRIAGE = 335;
        SYMBOLS_ELDERLY_PEOPLE = 464;
        SYMBOLS_ELECTRICALLY_POWERED_VEHICLE = 336;
        SYMBOLS_ELECTRIC_VEHICLE = 334;
        SYMBOLS_END_OF_PASSENGER_VEHICLE_WITH_TRAILER = 645;
        SYMBOLS_EQUESTRIANISM = 321;
        SYMBOLS_E_BIKE = 333;
        SYMBOLS_FERRY = 636;
        SYMBOLS_FREIGHT_BICYCLE = 319;
        SYMBOLS_LOADING = 618;
        SYMBOLS_MOTORCYCLE = 331;
        SYMBOLS_MOTORIZED_BICYCLE = 332;
        SYMBOLS_MULTI_TRACK_MOTOR_VEHICLE = 316;
        SYMBOLS_PASSENGER_VEHICLE = 325;
        SYMBOLS_PASSENGER_VEHICLES = 326;
        SYMBOLS_PASSENGER_VEHICLE_WITH_A_TRAILER = 327;
        SYMBOLS_PEDESTRIAN = 320;
        SYMBOLS_ROAD_WORK = 465;
        SYMBOLS_TRACTOR = 330;
        SYMBOLS_TRAM = 323;
        SYMBOLS_TRUCK = 317;
        SYMBOLS_TRUCK_WITH_A_TRAILER = 328;
        SYMBOLS_WILD_ANIMAL = 467;
        TIME_QUALIFIER_DISC_PARKING = 500;
        TIME_QUALIFIER_METERED_PARKING = 494;
        TIME_QUALIFIER_PROHIBITED_PARKING = 610;
        TIME_QUALIFIER_TIME_RESTRICTION = 129;
        TIME_QUALIFIER_TIME_RESTRICTION_DAY_OF_THE_WEEK = 525;
        TIME_QUALIFIER_TIME_RESTRICTION_WEEKEND_AND_HOLIDAY = 502;
        TIME_QUALIFIER_TIME_RESTRICTION_WORKDAY = 503;
        VEHICLE_QUALIFIER_BICYCLE_PERMITTED = 124;
        VEHICLE_QUALIFIER_BUS = 468;
        VEHICLE_QUALIFIER_CAMPERVAN = 478;
        VEHICLE_QUALIFIER_CAR = 485;
        VEHICLE_QUALIFIER_DANGEROUS_GOODS = 130;
        VEHICLE_QUALIFIER_ELECTRIC_BICYCLE_PERMITTED = 125;
        VEHICLE_QUALIFIER_ESCOOTER = 512;
        VEHICLE_QUALIFIER_EXPLOSIVE_CARGO = 443;
        VEHICLE_QUALIFIER_HAND_CART = 533;
        VEHICLE_QUALIFIER_HEIGHT = 553;
        VEHICLE_QUALIFIER_INCLUDING_BUS_AND_CAR_WITH_TRAILER = 123;
        VEHICLE_QUALIFIER_MOPED = 126;
        VEHICLE_QUALIFIER_MOPED_PERMITTED = 127;
        VEHICLE_QUALIFIER_SNOWMOBILE = 554;
        VEHICLE_QUALIFIER_TRUCK_AND_CAR_WITH_TRAILER = 343;
        VEHICLE_QUALIFIER_TRUCK_BUS_AND_CAR_WITH_TRAILER = 342;
        VEHICLE_QUALIFIER_VEHICLE_HANDICAPPED = 122;
        VEHICLE_QUALIFIER_WATER_POLLUTANT_CARGO = 131;
        VEHICLE_QUALIFIER_WEIGHT = 456;
        VEHICLE_QUALIFIER_WIDTH = 455;
        WARNING_AGRICULTURAL_VEHICLE = 396;
        WARNING_AMPHIBIAN = 85;
        WARNING_ANIMAL_CROSSING = 87;
        WARNING_BICYCLE = 67;
        WARNING_BICYCLIST = 66;
        WARNING_BLIND_SPOT = 397;
        WARNING_CHANGING_ROAD_SURFACE = 491;
        WARNING_CHECKPOINT = 90;
        WARNING_CHILDREN = 54;
        WARNING_CROSSROAD = 57;
        WARNING_CROSSROAD_DUAL_CARRIAGEWAY = 564;
        WARNING_CROSSROAD_RIGHT_OF_WAY = 70;
        WARNING_CROSSROAD_WITH_TRACK = 595;
        WARNING_CURVE_LEFT = 58;
        WARNING_CURVE_RIGHT = 59;
        WARNING_CYCLISTS_FOR_TRACKS = 655;
        WARNING_DANGER_OF_ACCIDENT = 379;
        WARNING_DANGER_POINT = 75;
        WARNING_DIP = 389;
        WARNING_DISASTER_RESPONSE_ROUTE = 603;
        WARNING_DIVIDED_HIGHWAY_CROSSING = 659;
        WARNING_DIVIDED_ROAD = 563;
        WARNING_DIVIDED_ROAD_END = 586;
        WARNING_DOGSLED_CROSSING = 601;
        WARNING_DOUBLE_CURVE_LEFT = 60;
        WARNING_DOUBLE_CURVE_RIGHT = 61;
        WARNING_ELDERLY_PEOPLE_CROSSING = 398;
        WARNING_ELECTRIFIED_OVERHEAD_CABLE = 461;
        WARNING_END_DUAL_CARRIAGEWAY = 460;
        WARNING_END_OF_ROAD = 602;
        WARNING_EQUESTRIANISM = 86;
        WARNING_ESCOOTER = 524;
        WARNING_FALLING_DEBRIS = 79;
        WARNING_FORKLIFT = 654;
        WARNING_GATED_RAIL_CROSSING = 88;
        WARNING_HEARING_IMPAIRED = 616;
        WARNING_HEAVY_VEHICLE = 592;
        WARNING_HIGH_WIND = 68;
        WARNING_HUMPBACK_BRIDGE = 534;
        WARNING_INSUFFICIENT_CLEARANCE = 83;
        WARNING_LOOP = 562;
        WARNING_LOOSE_ROAD_SURFACE = 81;
        WARNING_LOW_AIRPLANE = 76;
        WARNING_MAXIMUM_AXLE_WEIGHT = 560;
        WARNING_MAXIMUM_HEIGHT = 528;
        WARNING_MAXIMUM_LENGTH = 557;
        WARNING_MAXIMUM_WEIGHT = 559;
        WARNING_MAXIMUM_WIDTH = 558;
        WARNING_MERGING_TRAFFIC = 348;
        WARNING_MILITARY_VEHICLE = 511;
        WARNING_NARROWING_ROAD_BOTH_SIDES = 69;
        WARNING_NARROWING_ROAD_LEFT_SIDE = 72;
        WARNING_NARROWING_ROAD_RIGHT_SIDE = 71;
        WARNING_NARROW_BRIDGE = 576;
        WARNING_OPENING_BRIDGE = 56;
        WARNING_OPPOSING_TRAFFIC = 52;
        WARNING_PEDESTRIAN = 77;
        WARNING_PEDESTRIAN_CROSSING = 78;
        WARNING_PEDESTRIAN_OR_BICYCLE = 581;
        WARNING_RAIL_CROSSING_ANDREWS_CROSS = 73;
        WARNING_REDUCED_VISIBILITY = 381;
        WARNING_RETRACTABLE_BOLLARD = 380;
        WARNING_RISK_OF_FIRE = 367;
        WARNING_RISK_OF_GROUNDING = 462;
        WARNING_ROAD_BUMP = 164;
        WARNING_ROAD_CLOSED = 540;
        WARNING_ROAD_WORK = 74;
        WARNING_ROUNDABOUT = 128;
        WARNING_ROUNDABOUT_DIRECTIONAL_LANE = 661;
        WARNING_RUMBLE_STRIPS = 662;
        WARNING_SCHOOL_BUS_STOP = 583;
        WARNING_SCHOOL_ZONE = 55;
        WARNING_SHARED_ROAD_BICYCLE_VEHICLE = 604;
        WARNING_SKIER_CROSSING = 453;
        WARNING_SLIPPERY_ROAD_SURFACE = 65;
        WARNING_SNOWMOBILE = 454;
        WARNING_SNOW_OR_ICE = 80;
        WARNING_SOFT_VERGES = 366;
        WARNING_SPEED_BUMP = 390;
        WARNING_SPEED_LIMIT_AHEAD = 582;
        WARNING_STEEP_DECLINE = 62;
        WARNING_STEEP_INCLINE = 63;
        WARNING_STOP_AHEAD = 171;
        WARNING_TEXTUAL = 463;
        WARNING_TRAFFIC_JAM = 84;
        WARNING_TRAFFIC_LIGHT = 53;
        WARNING_TRAM_CROSSING = 349;
        WARNING_TRUCK_ROLLOVER = 587;
        WARNING_TUNNEL = 395;
        WARNING_UNEVEN_ROAD = 64;
        WARNING_UNGATED_RAIL_CROSSING = 89;
        WARNING_UNPROTECTED_WATER = 82;
        WARNING_U_TURN_CURVE = 589;
        WARNING_VISUALLY_IMPAIRED = 615;
        WARNING_WATER_ON_ROAD = 605;
        WARNING_WINDING_ROAD = 527;
        WARNING_WRONG_WAY_DRIVER = 361;
        WARNING_YIELD_AHEAD = 169;
    }
    
    optional PositionProto position = 3;
    message PositionProto {
        optional int32 column = 1;
        optional int32 row = 2;
    }
    
    optional bool is_invalidated = 4 [default = false];
    optional string text = 5;
}
