syntax = "editions";

package geotracker;

option java_package = "com.google.geo.imagery.geotracker.proto";

enum ObservationTag {
    option features = enum_type: CLOSED
    ;
    UNDEFINED_OBSERVATION_TAG = 0;
    BASE = 1;
    CENTROID = 2;
    CENTROID_FROM_CYCLOP = 84;
    CENTROID_FROM_SURFEL = 86;
    CENTROID_FROM_FACADE = 3;
    CENTROID_FROM_BUILDING = 4;
    CENTROID_FROM_SNAPPED = 186;
    CENTROID_FROM_POINT_CLOUD = 196;
    CENTROID_FROM_VOXELS = 283;
    SENSOR = 5;
    DETECTION = 56;
    PLATFORM = 57;
    MAPFACTS_DIFF = 6;
    PERFUME_IMPRESSIONS = 7;
    PERFUME_DIRECTIONS_REQUESTS = 8;
    COLLECTION_IDS = 32;
    ISSUE_CREATES = 10;
    ISSUE_MODIFIES = 11;
    ISSUE_DELETES = 12;
    METERS_TO_NEAREST_MAPFACTS_BUILDING = 13;
    EVENT_TIME = 14;
    IMAGERY_TIME = 67;
    CHURN_END = 110;
    STREETVIEW_METRIC = 16;
    MAPFACTS_DIFF_HIGH_CONFIDENCE_TILES = 19;
    MAPFACTS_DIFF_OVERALL_CONFIDENCE = 20;
    MAPFACTS_DIFF_BUILDINGS_ONLY_CONFIDENCE = 39;
    MOSAIC_BADNESS_V2 = 48;
    MOSAIC_METRIC = 21;
    MOSAIC_BUILDINGS_ONLY_METRIC = 40;
    MOSAIC_METRIC_V2 = 47;
    MOSAIC_METRIC_V3 = 100;
    MAPFACTS_DIFF_BUILDINGS_ONLY_TILES = 41;
    BUILDING_PRESENCE = 22;
    ROAD_PRESENCE = 23;
    WATER_PRESENCE = 24;
    TREE_PRESENCE = 25;
    CLOUD_PRESENCE = 37;
    BUILDING_NON_PRESENCE = 134;
    BUILDING_CHURN = 26;
    BUILDING_SEMANTIC_F1 = 331;
    ICA_TOTAL_TAG_DETECTIONS = 31;
    ARIADNE_AVERAGE_DIRECTION = 34;
    ARIADNE_AVERAGE_ANGLE_CONFIDENCE_SEMI_INTERVAL = 35;
    ARIADNE_PEDESTRIAN_TRACES = 36;
    MAPFACTS_ADDRESS_FEATURES_AWAY_FROM_BUILDINGS = 38;
    EXAMPLE_OBSERVATION_COUNT = 43;
    GLS_SNAP_QUALITY = 44;
    GLS_POINTS = 45;
    MAPFACTS_ROAD_METERS_TO_EDGE = 46;
    DETECTION_CONFIDENCE = 49;
    SELECTION_CONFIDENCE = 133;
    CAPTURE_TIME = 50;
    BUILDING_HEIGHT = 51;
    CBDB_RUN_CREATION_TIME = 52;
    POPULATION = 53;
    WALDO_DETECTION_CONFIDENCE = 54;
    MAPFACTS_ROADS = 55;
    MAPFACTS_BUILDINGS = 272;
    MISSING_ROADS = 58;
    ROAD_COVERAGE = 59;
    EMF_IMPORTANCE = 60;
    EMF_DATA_BADNESS = 61;
    EMF_PIXEL_BADNESS = 62;
    EMF_STALENESS = 63;
    AGGREGATION_START_TIME = 72;
    AGGREGATION_END_TIME = 73;
    QUERY_COUNT = 75;
    NAVIGATION_DEVIATIONS = 76;
    NAVIGATION_COMPLIANCES = 77;
    DEVIATION_DAYS = 78;
    SATELLITE_TASKING_TIME = 79;
    SATELLITE_TASKING_EXPIRE_TIME = 99;
    OPERATOR_IMAGERY_REQUEST_TIME = 80;
    IMAGERY_REQUEST_PROCESSING_TIME = 188;
    IMAGERY_ORDER_TIME = 189;
    IMAGERY_ORDER_PLACEMENT_TIME = 195;
    ISSUE_FIX_TIME = 190;
    SATELLITE_IMAGERY_METRIC = 81;
    SATELLITE_ORDER_METRIC = 160;
    SATELLITE_ORDER_PER_SQ_KM_METRIC = 177;
    SATELLITE_ORDER_WEIGHTED_METRIC = 201;
    GLS_SNAPSCORE = 82;
    OPERATOR_IMAGERY_REQUESTS = 83;
    TASKABLE_OPERATOR_IMAGERY_REQUESTS = 184;
    DEVIATION_AREA = 85;
    REGIONS_WITH_BUILDING_DETECTIONS = 87;
    REGIONS_WITH_MAPFACTS_BUILDINGS = 88;
    REGIONS_WITH_BUILDINGS = 89;
    BUILDING_COVERAGE = 90;
    MAPFACTS_BUILDING_COVERAGE = 163;
    AUTOGEN_BUILDING_COVERAGE = 164;
    POLYGONS_AREA = 91;
    POLYGON_FEATURES = 101;
    UNION_OF_POLYGONS = 92;
    NEAREST_H1_PANO_LOCATION = 93;
    NEAREST_R5_PANO_LOCATION = 94;
    NEAREST_R7_PANO_LOCATION = 95;
    NEAREST_H1_PANO_TIME = 96;
    NEAREST_R5_PANO_TIME = 97;
    NEAREST_R7_PANO_TIME = 98;
    INTERSECTION_OVER_UNION = 114;
    ROUTABILITY_SUCCESS = 115;
    ROUTES = 116;
    POLYGONS_AUTOGEN = 135;
    FEATURES_AUTOGEN = 270;
    POLYGONS_AUGMENTED_AUTOGEN = 193;
    POLYGONS_MAPFACTS = 136;
    POLYGONS_GOLDEN = 330;
    FEATURES_MAPFACTS = 271;
    POLYGONS_AUGMENTED_MAPFACTS = 194;
    INTERSECTION_OF_POLYGONS = 119;
    AIR_O3_PPB = 120;
    AIR_NO2_PPB = 121;
    AIR_NO_PPB = 122;
    AIR_NOX_UG_M3 = 173;
    AIR_CO_PPM = 199;
    AIR_CO2_PPM = 150;
    AIR_CH4_PPM = 123;
    AIR_SO2_PPB = 151;
    AIR_BLACK_CARBON_UG_M3 = 124;
    AIR_PN1_COUNT_LITER = 125;
    AIR_PN2_COUNT_LITER = 126;
    AIR_PN3_COUNT_LITER = 127;
    AIR_PN4_COUNT_LITER = 128;
    AIR_PN5_COUNT_LITER = 129;
    AIR_PN7_COUNT_LITER = 197;
    AIR_PN8_COUNT_LITER = 198;
    AIR_PN6_COUNT_LITER = 149;
    AIR_PM1_UG_M3 = 174;
    AIR_PM2_5_UG_M3 = 171;
    AIR_PM4_UG_M3 = 175;
    AIR_PM10_UG_M3 = 176;
    AIR_ULTRAFINE = 152;
    AIR_CAR_SPEED_M_S = 130;
    TERRAIN_ALTITUDE_METERS = 131;
    STRUCTURE_TOP_ALTITUDE_METERS = 132;
    MOSAIC_IMPORTANCE_V1 = 137;
    MOSAIC_IMPORTANCE_V2 = 138;
    AUTOGEN_AND_MAPFACTS_SUBCELLS = 139;
    AUTOGEN_ONLY_SUBCELLS = 140;
    AUTOGEN_MISSING_SUBCELLS = 168;
    MAPFACTS_ONLY_SUBCELLS = 141;
    AUTOGEN_XOR_MAPFACTS_SUBCELLS = 142;
    NO_OVERLAP_SUBCELLS = 143;
    DIFF_SUBCELLS = 144;
    NUM_AUTOGEN_DETECTION_VALIDATIONS = 153;
    NUM_AUTOGEN_DETECTION_INVALIDATIONS = 154;
    NUM_AUTOGEN_RECENT_CONSECUTIVE_VALIDATIONS = 155;
    NUM_AUTOGEN_RECENT_CONSECUTIVE_INVALIDATIONS = 156;
    AUTOGEN_DETECTION_VALIDATION = 157;
    BUILDING_MEASUREMENT_FROM_SURFELS = 158;
    BUILDING_MEASUREMENT_FROM_DSM = 159;
    NUM_CBDB_IMAGES = 161;
    FLYEYE_POINT = 162;
    MODEL_DETECTIONS_LIMIT = 165;
    NUM_AUTOGEN_DETECTIONS = 166;
    NUM_FILTERED_AUTOGEN_DETECTIONS = 269;
    NUM_DETECTION_CONTOUR_SETS = 264;
    NUM_DETECTION_CONTOUR_SETS_DROPPED = 265;
    NUM_DETECTION_CONTOUR_SETS_DROPPED_BELOW_AREA_THRESHOLD = 266;
    NUM_DETECTION_CONTOUR_SETS_DROPPED_MULTI_LOOP = 267;
    NUM_DETECTION_CONTOUR_SETS_DROPPED_EMPTY_CONTOUR = 268;
    AUTOGEN_TILES = 167;
    MAP_TILE_VIEWS = 169;
    BUILDING_MEASUREMENT_FROM_MAPFACTS = 170;
    BUILDING_MEASUREMENT_FROM_EOS = 172;
    BUILDING_MEASUREMENT_FROM_CANDID = 200;
    BUILDING_MEASUREMENT_FROM_CANDID_MODEL = 362;
    BUILDING_MEASUREMENT_FROM_SENTINEL2 = 335;
    DYNAMIC_WORLD_DIFF_PIXELS = 178;
    DYNAMIC_WORLD_PIXELS = 179;
    DYNAMIC_WORLD_RASTER_DIFF = 180;
    IMAGERY_ISSUES_METRIC = 181;
    FEATURE_IMPORTANCE_METRIC = 182;
    MAPFACTS_IMAGERY_EVIDENCE_TASKING_METRIC = 183;
    MAPFACTS_3PDP_TASKING_METRIC = 230;
    GMM_AVERAGE_USERS = 185;
    AUTOGEN_TILE_COMPLETENESS = 187;
    TEST_TAG = 191;
    PLANET_TASKER_PRIORITY = 192;
    IMAGERY_REQUEST_AREA_FULFILLMENT = 202;
    RAP_ROAD_ISSUES = 203;
    ROAD_CONFLATION_METRICS_TOTAL = 204;
    ROAD_CONFLATION_METRICS_PROXIMITY = 205;
    ROAD_CONFLATION_METRICS_DIRECTION = 206;
    ROAD_CONFLATION_METRICS_TOPOLOGY = 207;
    ROAD_CONFLATION_METRICS_COVERAGE = 208;
    DRIVEWAY_PRESENCE = 209;
    GROUND_NATURAL_PRESENCE = 210;
    PARKING_LOT_PRESENCE = 211;
    ROAD_PAVED_PRESENCE = 212;
    ROAD_UNPAVED_PRESENCE = 213;
    SIDEWALK_PRESENCE = 214;
    TRAIL_PRESENCE = 215;
    OTHER_HUMAN_MADE_PRESENCE = 216;
    CROSSWALK_PRESENCE = 227;
    TENNIS_COURT_PRESENCE = 257;
    BASKETBALL_COURT_PRESENCE = 258;
    SWIMMING_POOL_PRESENCE = 259;
    RAILWAY_TRACK_PRESENCE = 260;
    SOLAR_PANEL_PRESENCE = 285;
    OIL_PUMPJACK_PRESENCE = 251;
    GAS_WELLHEAD_PRESENCE = 252;
    STORAGE_TANK_PRESENCE = 253;
    HORIZONTAL_VESSEL_PRESENCE = 254;
    WELL_PAD_PRESENCE = 284;
    SIMPLE_WELL_PAD_PRESENCE = 255;
    COMPLEX_WELL_PAD_PRESENCE = 256;
    BUCKET = 217;
    MAPFACTS_3PDP_ROADS = 218;
    MAPFACTS_3PDP_GEOCODES = 219;
    DATA_UPLOAD_TIME = 220;
    MAPFACTS_IMPORT_TIME = 221;
    MAPFACTS_3PDP_UPLOADS = 222;
    IMAGERY_TO_3PDP_UPLOAD_DELTA_DAYS = 223;
    MAPFACTS = 224;
    MODEL_PROCESSED = 225;
    MAPFACTS_OUTSIDE_MODEL_PROCESSED = 226;
    INVALID_FOOTPRINT = 228;
    CONFIRMED_FOOTPRINT = 363;
    INVALID_FOOTPRINT_FISHFOOD = 336;
    INVALID_FOOTPRINT_PIERCED = 337;
    INVALID_FOOTPRINT_NON_PIERCED = 338;
    INVALID_FOOTPRINT_PIERCED_FISHFOOD = 339;
    INVALID_FOOTPRINT_NON_PIERCED_FISHFOOD = 340;
    IMAGERY_RESOLUTION = 231;
    IMAGERY_QUALITY = 232;
    TOTAL_PIXELS = 246;
    TOTAL_VALID_PIXELS = 274;
    ARGMAX_BUILDING_PIXELS = 275;
    ARGMAX_ROAD_PAVED_PIXELS = 276;
    ARGMAX_ROAD_UNPAVED_PIXELS = 302;
    ARGMAX_DRIVEWAY_PIXELS = 310;
    ARGMAX_PARKING_LOT_PIXELS = 311;
    NOCOVER_ARGMAX_BUILDING_PIXELS = 279;
    NOCOVER_ARGMAX_ROAD_PAVED_PIXELS = 280;
    NOCOVER_ARGMAX_ROAD_UNPAVED_PIXELS = 303;
    NOCOVER_ARGMAX_DRIVEWAY_PIXELS = 312;
    NOCOVER_ARGMAX_PARKING_LOT_PIXELS = 313;
    MISMATCH_ARGMAX_BUILDING_PIXELS = 286;
    MISMATCH_ARGMAX_ROAD_PAVED_PIXELS = 287;
    MISMATCH_ARGMAX_ROAD_UNPAVED_PIXELS = 304;
    MISMATCH_ARGMAX_DRIVEWAY_PIXELS = 314;
    MISMATCH_ARGMAX_PARKING_LOT_PIXELS = 315;
    COVERING_ARGMAX_PIXELS = 288;
    COVERING_THRESHOLDED_PIXELS = 289;
    MAPFACTS_BUILDING_PIXELS = 290;
    MAPFACTS_ROAD_PIXELS = 291;
    MAPFACTS_BUILDING_UNION_PIXELS = 292;
    MAPFACTS_ROAD_UNION_PIXELS = 293;
    MODEL_BUILDING_PIXELS = 327;
    MODEL_BUILDING_UNION_PIXELS = 328;
    THRESHOLDED_BUILDING_PIXELS = 277;
    THRESHOLDED_ROAD_PAVED_PIXELS = 278;
    THRESHOLDED_ROAD_UNPAVED_PIXELS = 305;
    THRESHOLDED_DRIVEWAY_PIXELS = 318;
    THRESHOLDED_PARKING_LOT_PIXELS = 319;
    THRESHOLDED_TREE_PIXELS = 329;
    NOCOVER_THRESHOLDED_BUILDING_PIXELS = 281;
    NOCOVER_THRESHOLDED_ROAD_PAVED_PIXELS = 282;
    NOCOVER_THRESHOLDED_ROAD_UNPAVED_PIXELS = 306;
    NOCOVER_THRESHOLDED_DRIVEWAY_PIXELS = 320;
    NOCOVER_THRESHOLDED_PARKING_LOT_PIXELS = 321;
    MISMATCH_THRESHOLDED_BUILDING_PIXELS = 307;
    MISMATCH_THRESHOLDED_ROAD_PAVED_PIXELS = 308;
    MISMATCH_THRESHOLDED_ROAD_UNPAVED_PIXELS = 309;
    MISMATCH_THRESHOLDED_DRIVEWAY_PIXELS = 322;
    MISMATCH_THRESHOLDED_PARKING_LOT_PIXELS = 323;
    TOTAL_VALID_PIXELS_START = 234;
    HUMAN_CLASS_PIXELS_START = 235;
    TOTAL_VALID_PIXELS_END = 236;
    HUMAN_CLASS_PIXELS_END = 237;
    TOTAL_PIXELS_SHARED = 238;
    HUMAN_CLASS_CHANGE_PIXELS = 243;
    HUMAN_CLASS_CHANGE_PIXELS_FILTERED = 239;
    SAR_CHANGE_PIXELS = 244;
    BUILDING_CHANGE_PIXELS = 247;
    ROAD_PAVED_CHANGE_PIXELS = 248;
    PARKING_LOT_CHANGE_PIXELS = 249;
    SAR_CHANGE_FREQUENCY_PIXELS = 332;
    SAR_NORMALIZED_LAST_CHANGE_TIME = 333;
    COMPLETE_TASKING_ORDER_COVERAGE = 240;
    PENDING_AND_COMPLETE_TASKING_ORDER_COVERAGE = 241;
    DELIVERED_GT_IMAGERY_COVERAGE = 242;
    FIELD_PRESENCE = 245;
    TREE_CROP_PRESENCE = 348;
    FEATURE_PRESENCE = 250;
    MODEL_DETECTIONS = 261;
    ESTIMATED_TOTAL_FEATURES = 262;
    EXACT_2D_SHAPE_MAPFACTS = 263;
    MODEL_TOKEN_SCORE = 273;
    UNSTITCHED_EDGES = 294;
    R2_POLYGON_EDGES = 316;
    STITCHING_QUALITY_AREA_PENALTY = 295;
    CV_POLYGON_CREATION_FAILURE = 296;
    POLYGON_LESS_THAN_THREE_POINTS_FAILURE = 297;
    COLLINEAR_POLYGON_FAILURE = 298;
    R2_TRANSFORMATION_FAILURE = 299;
    OBSERVATION_CREATION_FAILURE = 300;
    INFERENCE_ERROR_STATUS = 301;
    SELF_INTERSECTION_FAILURE = 326;
    LIKELY_INCOMPLETE_TILES = 317;
    ASSET_PUBLISH_TIME = 324;
    ASSET_REJECTION_TIME = 325;
    BOUNDING_REGION = 334;
    VISUAL_QUALITY = 341;
    VISUAL_QUALITY_PRE_GEOMETRY_CLEAN = 342;
    VISUAL_QUALITY_POST_SIMPLIFY = 344;
    VISUAL_QUALITY_POST_DESPIKE = 345;
    VISUAL_QUALITY_POST_SQUARE_UP = 346;
    VISUAL_QUALITY_POST_EDGE_STRAIGHTEN = 347;
    POLYGON_VERTEX_ANGLE = 343;
    VISUAL_BADNESS_SHORT_NEEDLES = 349;
    VISUAL_BADNESS_MEDIUM_NEEDLES = 350;
    VISUAL_BADNESS_LONG_NEEDLES = 351;
    VISUAL_BADNESS_SHORT_NARROW_SPIKES = 352;
    VISUAL_BADNESS_MEDIUM_NARROW_SPIKES = 353;
    VISUAL_BADNESS_LONG_NARROW_SPIKES = 354;
    VISUAL_BADNESS_SHORT_WIDE_SPIKES = 355;
    VISUAL_BADNESS_MEDIUM_WIDE_SPIKES = 356;
    VISUAL_BADNESS_LONG_WIDE_SPIKES = 357;
    VISUAL_BADNESS_ALL_SPIKES = 358;
    VISUAL_BADNESS_IS_TRIANGLE = 359;
    VISUAL_BADNESS_NARROW_CORRIDORS = 360;
    VISUAL_BADNESS_OUTER_SHELLS = 361;
    ORTHO_SHIFT_NORM = 364;
    ORTHO_SHIFT_UNIT_X = 367;
    ORTHO_SHIFT_UNIT_Y = 368;
    ORTHO_SHIFT_X = 369;
    ORTHO_SHIFT_Y = 370;
    FILTERED_ORTHO_SHIFT_NORM = 365;
    ESTIMATED_ORTHO_SHIFT_NORM = 372;
    ALL_FEATURES_FILTERED_ORTHO_SHIFT_NORM = 366;
    ALIGNMENT_CONFIDENCE = 371;
    BUCKET_HORIZON = 373;
}
