syntax = "editions";

package geo_serving_proto.photos;

import "java/com/google/apps/jspb/jspb.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "third_party/java/protobuf/java_features.proto";
import "third_party/protobuf/cpp_features.proto";

option features = field_presence: EXPLICIT
enum_type: CLOSED
;
option objc_class_prefix = "GSPPH";
option java_multiple_files = true;
option java_outer_classname = "ColorDetectionResultProto";
option java_package = "com.google.geo.serving.proto.photos";

message ColorDetectionResult {
    optional Type type = 1;
    enum Type {
        UNKNOWN_TYPE = 0;
        CUSTOM = 1;
        FOREGROUND = 2;
        UNIFORM = 3;
        BACKGROUND = 4;
    }
    
    repeated PerColorResult per_color_result = 2;
    message PerColorResult {
        optional fixed32 rgb = 1;
    }
}
