syntax = "proto2";

package google.internal.earth.v1.terrain;

import "google/internal/earth/v1/shared.proto";
import "net/proto2/contrib/validator/annotations.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "wireless/android/privacy/annotations/proto/collection_basis_annotations.proto";

option objc_class_prefix = "RTH";
option java_multiple_files = true;
option java_package = "com.google.internal.earth.v1.terrain";

message BatchGetElevationsByPointRequestWrapper {
    optional ClientMetadata client_metadata = 1 [deprecated = true];
    optional BatchGetElevationsByPointRequest request = 2;
}

message BatchGetElevationsByPointRequest {
    repeated LatitudeLongitude points = 2;
}

message BatchGetElevationsByPointResponse {
    repeated double elevations_m = 1 [packed = true];
}
