syntax = "proto2";

package google.internal.earth.v1.user_settings;

import "google/internal/earth/v1/shared.proto";
import "google/protobuf/field_mask.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "wireless/android/privacy/annotations/proto/collection_basis_annotations.proto";

option objc_class_prefix = "RTH";
option java_multiple_files = true;
option java_package = "com.google.geo.earth.earth.v1.service.usersettings";

message UserSettings {
    optional EarthUserIndustries user_industries = 1;
    optional EarthUserCountryCodes country_codes = 2;
    optional EarthUserGeographicScales geographic_scales = 3;
    optional bool opted_in_ux_research = 4;
    optional bool opted_in_feature_announcements = 5;
    optional EarthUserPrimaryUse primary_use = 6;
    optional EarthUserMAPUseCases map_use_cases = 7;
}

message EarthUserIndustries {
    repeated EarthUserIndustry industries = 1 [packed = true];
}

message EarthUserMAPUseCases {
    repeated EarthUserMAPUseCase map_use_cases = 1 [packed = true];
}

message EarthUserCountryCodes {
    repeated string codes = 1;
}

message EarthUserGeographicScales {
    repeated EarthUserGeographicScale scales = 1 [packed = true];
}

message GetUserSettingsRequest {
    optional ClientMetadata client_metadata = 1 [deprecated = true];
}

message UpdateUserSettingsRequest {
    optional ClientMetadata client_metadata = 1 [deprecated = true];
    optional UserSettings user_settings = 2;
    optional protobuf.FieldMask update_mask = 3;
}

enum EarthUserMAPUseCase {
    MAP_USE_CASE_UNKNOWN = 0;
    MAP_USE_CASE_METHANE_EMISSIONS_REDUCTION = 1;
    MAP_USE_CASE_BATTERY_STORAGE_CAPACITY_OR_OPERATIONS = 2;
    MAP_USE_CASE_DISTRIBUTED_SOLAR_PV = 3;
    MAP_USE_CASE_UTILITY_SCALE_SOLAR_PV = 4;
    MAP_USE_CASE_WIND_POWER = 5;
    MAP_USE_CASE_GEOTHERMAL_ENERGY = 6;
    MAP_USE_CASE_GRID_EFFICIENCY = 7;
    MAP_USE_CASE_NUCLEAR_POWER = 8;
    MAP_USE_CASE_HYDROPOWER = 9;
    MAP_USE_CASE_EQUIPMENT_AND_OPERATIONS_ELECTRIFICATION = 10;
    MAP_USE_CASE_ENERGY_EXTRACTION_ELECTRIFICATION = 11;
    MAP_USE_CASE_ENERGY_TRANSMISSION_ELECTRIFICATION = 12;
    MAP_USE_CASE_ENERGY_GENERATION_EFFICIENCY = 13;
    MAP_USE_CASE_ENERGY_EFFICIENT_OPERATIONS = 14;
    MAP_USE_CASE_ENERGY_EFFICIENT_BUILDING_MATERIALS = 15;
    MAP_USE_CASE_INDUSTRIAL_DECARBONIZATION = 16;
    MAP_USE_CASE_WASTE_MANAGEMENT_AND_CIRCULAR_ECONOMY = 17;
    MAP_USE_CASE_NATURE_BASED_SOLUTIONS = 18;
    MAP_USE_CASE_REDUCING_WASTE_RUNOFF_OR_CLEANING_PROCESSING_WASTE = 19;
    MAP_USE_CASE_SHIFTING_TO_HYBRID_OR_ELECTRIC_VEHICLE_OPERATIONS = 20;
    MAP_USE_CASE_REDUCING_TRAVEL_DISTANCE_OR_NUMBER_OF_TRIPS = 21;
    MAP_USE_CASE_REDUCING_VEHICLE_SIZES_AND_FUEL_USAGE = 22;
    MAP_USE_CASE_SHIFT_TO_NON_DRIVING_MODES = 23;
    MAP_USE_CASE_REDUCING_AIRPLANE_CONTRAILS = 24;
    MAP_USE_CASE_SHIFTING_TO_LOWER_EMISSION_FUELS = 25;
    MAP_USE_CASE_VEHICLE_SAFETY_FEATURES = 26;
    MAP_USE_CASE_AUTONOMOUS_OR_SEMI_AUTONOMOUS_DRIVING_OPERATION = 27;
    MAP_USE_CASE_POLICIES_OR_ROAD_DESIGNS_TO_REDUCE_DRIVING_SPEED = 28;
    MAP_USE_CASE_POLICIES_AND_ROAD_DESIGNS_TO_IMPROVE_ROAD_USER_AWARENESS = 29;
    MAP_USE_CASE_REDUCE_DRIVING_VIA_PUBLIC_TRANSIT = 30;
    MAP_USE_CASE_REDUCE_DRIVING_VIA_ROUTING = 31;
    MAP_USE_CASE_REDUCE_DRIVING_VIA_OPERATIONS = 32;
    MAP_USE_CASE_REDUCING_IDLING_VIA_ROAD_DESIGN_OPERATIONS_OR_POLICIES = 33;
    MAP_USE_CASE_URBAN_GREENING_INITIATIVES = 34;
    MAP_USE_CASE_URBAN_HEAT_ISLAND_MITIGATION = 35;
    MAP_USE_CASE_AIR_QUALITY_FORECAST_OR_IMPROVEMENT = 36;
    MAP_USE_CASE_WILDFIRE_DETECTION_OR_MANAGEMENT = 37;
    MAP_USE_CASE_WILDFIRE_RISK_EVALUATION = 38;
    MAP_USE_CASE_FLOOD_RISK_EVALUATION = 39;
    MAP_USE_CASE_ONSITE_RENEWABLE_ENERGY = 40;
    MAP_USE_CASE_FLOOD_PREVENTION_AND_MANAGEMENT = 41;
    MAP_USE_CASE_FIRE_PREVENTION_AND_MANAGEMENT = 42;
    MAP_USE_CASE_MANAGED_RETREAT = 43;
    MAP_USE_CASE_DEFENSIBLE_SPACE_REGULATIONS = 44;
    MAP_USE_CASE_DENSIFICATION = 45;
    MAP_USE_CASE_MIXED_USE_DEVELOPMENT = 46;
    MAP_USE_CASE_POLICY_AND_FINANCE = 47;
    MAP_USE_CASE_GRID_RESILIENCE = 48;
    MAP_USE_CASE_EMISSIONS_FROM_ANIMALS = 49;
    MAP_USE_CASE_MANAGED_SOILS_AND_PASTURES = 50;
    MAP_USE_CASE_METHANE_FROM_RICE = 51;
    MAP_USE_CASE_FERTILIZER_APPLICATION = 52;
    MAP_USE_CASE_MANURE_MANAGEMENT = 53;
    MAP_USE_CASE_CROP_RESIDUE_MANAGEMENT = 54;
    MAP_USE_CASE_FISHING_VESSEL_EFFICIENCY = 55;
    MAP_USE_CASE_FOREST_RESTORATION = 56;
    MAP_USE_CASE_SUSTAINABLE_WOOD_PRODUCTS = 57;
    MAP_USE_CASE_SPECIALIZED_FOREST_ECOSYSTEM_PROTECTION = 58;
    MAP_USE_CASE_SUSTAINABLE_AG_AND_WATER_MANAGEMENT = 59;
    MAP_USE_CASE_LAND_ECOSYSTEM_FORESTS_PEATLANDS_GRASSLANDS_MANAGEMENT = 60;
    MAP_USE_CASE_COASTAL_ECOSYSTEMS_PROTECTION = 61;
    MAP_USE_CASE_LEAK_DETECTION_AND_REPAIR_LDAR = 62;
    MAP_USE_CASE_REDUCING_VENTING_AND_FLARING = 63;
    MAP_USE_CASE_LANDFILL_MANAGEMENT = 64;
    MAP_USE_CASE_AGRICULTURE_AND_REFRIGERANT = 65;
    MAP_USE_CASE_MINERALIZATION_FOR_CARBON_REMOVAL = 66;
    MAP_USE_CASE_REHABILITATING_DEGRADED_LAND = 67;
    MAP_USE_CASE_VOLUNTARY_CARBON_MARKET_VCM_INTEGRITY = 68;
    MAP_USE_CASE_MONITORING_REPORTING_AND_VERIFICATION_MRV_SYSTEMS = 69;
    MAP_USE_CASE_JURISDICTIONAL_REDDPLUS_APPROACHES = 70;
    MAP_USE_CASE_PROJECT_BASED_REDDPLUS_APPROACHES = 71;
    MAP_USE_CASE_SUPPORTING_LOCAL_COMMUNITIES = 72;
    MAP_USE_CASE_SUSTAINABLE_AQUACULTURE_AND_FISHING_PRACTICES = 73;
    MAP_USE_CASE_MARINE_PROTECTED_AREA_MPA_CONSERVATION = 74;
    MAP_USE_CASE_AQUATIC_ECOSYSTEMS_PROTECTION = 75;
    MAP_USE_CASE_SEAFLOOR_PROTECTION = 76;
    MAP_USE_CASE_LAND_AND_COASTAL_PROTECTION_AND_MANAGEMENT = 77;
    MAP_USE_CASE_WATER_INFRASTRUCTURE_DECARBONIZATION = 78;
}

enum EarthUserPrimaryUse {
    PRIMARY_USE_UNKNOWN = 0;
    PRIMARY_USE_WORK = 1;
    PRIMARY_USE_LEISURE = 2;
    PRIMARY_USE_PUBLIC_SECTOR = 3;
    PRIMARY_USE_ACADEMIC = 4;
    PRIMARY_USE_ACADEMIC_RESEARCHER = 5;
    PRIMARY_USE_ACADEMIC_STUDENT_OR_TEACHER = 6;
}

enum EarthUserGeographicScale {
    GEOGRAPHIC_SCALE_UNKNOWN = 0;
    GEOGRAPHIC_SCALE_LOCAL = 1;
    GEOGRAPHIC_SCALE_REGIONAL = 2;
    GEOGRAPHIC_SCALE_STATE_PROVINCIAL = 3;
    GEOGRAPHIC_SCALE_NATIONAL = 4;
    GEOGRAPHIC_SCALE_MULTI_NATIONAL = 6;
    GEOGRAPHIC_SCALE_GLOBAL = 5;
}

enum EarthUserIndustry {
    INDUSTRY_UNKNOWN = 0;
    INDUSTRY_ADVERTISING_OR_MARKET_RESEARCH = 1;
    INDUSTRY_AGRICULTURE = 2;
    INDUSTRY_AIR_QUALITY_POLLUTION = 3;
    INDUSTRY_ARCHITECTURE_URBAN_DESIGN = 4;
    INDUSTRY_ARTIFICIAL_INTELLIGENCE_AND_MACHINE_LEARNING = 5;
    INDUSTRY_ASSET_VALUATION = 6;
    INDUSTRY_AUTOMOTIVE = 7;
    INDUSTRY_BATTERY_STORAGE_TECHNOLOGY = 8;
    INDUSTRY_BUSINESS_AND_PROFESSIONAL_SERVICES = 9;
    INDUSTRY_CITY_URBAN_REGIONAL_PLANNING = 10;
    INDUSTRY_CLASSROOM_OR_EDUCATION = 11;
    INDUSTRY_CONSTRUCTION = 12;
    INDUSTRY_CONSULTING = 13;
    INDUSTRY_DISASTER_AND_CRISIS_RESPONSE = 14;
    INDUSTRY_ECONOMIC_DEVELOPMENT = 15;
    INDUSTRY_ELECTRICAL_GRID_UTILITIES_OPERATIONS = 16;
    INDUSTRY_ENERGY_NON_RENEWABLE = 17;
    INDUSTRY_ENERGY_OTHER_RENEWABLE = 18;
    INDUSTRY_EQUITY_AND_INCLUSION = 19;
    INDUSTRY_FISHING = 20;
    INDUSTRY_FLEET_MANAGEMENT_AND_GPS_TRACKING = 21;
    INDUSTRY_FORESTRY = 22;
    INDUSTRY_FRESHWATER = 23;
    INDUSTRY_HEALTH_CARE_SOCIAL_WORK = 24;
    INDUSTRY_HOUSING_AND_URBAN_DEVELOPMENT = 25;
    INDUSTRY_HUMAN_RIGHTS = 26;
    INDUSTRY_HUMANITARIAN_AID = 27;
    INDUSTRY_INDIGENOUS_RIGHTS_AND_INTERESTS = 28;
    INDUSTRY_INDUSTRIAL_GOODS_AND_MANUFACTURING = 29;
    INDUSTRY_INSURANCE = 30;
    INDUSTRY_JOURNALISM_AND_MEDIA = 31;
    INDUSTRY_LAND_AND_COASTAL_ECOSYSTEMS_MANAGEMENT_AND_CONSERVATION = 32;
    INDUSTRY_LAND_RIGHTS = 33;
    INDUSTRY_LOCAL_RIDES_AND_MOBILITY = 34;
    INDUSTRY_MANUFACTURING_AND_INDUSTRIAL = 35;
    INDUSTRY_METHANE_DETECTION = 36;
    INDUSTRY_MINING_QUARRYING = 37;
    INDUSTRY_NATURAL_DISASTERS_CLIMATE_RISK = 38;
    INDUSTRY_NATURE_BASED_SOLUTIONS = 39;
    INDUSTRY_NAVIGATION_AND_MOBILITY = 40;
    INDUSTRY_OCEANS_ECOSYSTEMS_AND_CONSERVATION = 41;
    INDUSTRY_PUBLIC_HEALTH = 42;
    INDUSTRY_REAL_ESTATE_DEVELOPMENT = 43;
    INDUSTRY_REAL_ESTATE_SERVICES = 44;
    INDUSTRY_RETAIL_AND_WHOLESALE = 45;
    INDUSTRY_ROUTING = 46;
    INDUSTRY_SAFETY = 47;
    INDUSTRY_SCIENTIFIC_RESEARCH_AND_DEVELOPMENT = 48;
    INDUSTRY_SOFTWARE_AND_INTERNET_SERVICES = 49;
    INDUSTRY_SOLAR_COMMERCIAL_AND_INDUSTRIAL = 50;
    INDUSTRY_SOLAR_RESIDENTIAL = 51;
    INDUSTRY_SOLAR_UTILITY_SCALE = 52;
    INDUSTRY_SUSTAINABLE_SOURCING = 53;
    INDUSTRY_TELECOMS = 54;
    INDUSTRY_TOURISM_AND_LEISURE = 55;
    INDUSTRY_TRANSPORTATION_INFRASTRUCTURE = 56;
    INDUSTRY_TRANSPORTATION_LOGISTICS = 57;
    INDUSTRY_TRANSPORTATION_PLANNING = 58;
    INDUSTRY_TRAVEL = 59;
    INDUSTRY_UTILITIES_PLANNING_OR_OPERATIONS = 60;
    INDUSTRY_WIND_ENERGY = 61;
    INDUSTRY_OTHER = 62;
}
