syntax = "proto2";

package knowledge.verticals.crisisresponse.sos.proto;

import "google/api/inclusion.proto";
import "logs/proto/logs_annotations/logs_annotations.proto";
import "net/proto2/proto/descriptor.proto";

option java_multiple_files = true;
option java_outer_classname = "EventTypeProto";
option java_package = "com.google.knowledge.verticals.crisisresponse.sos.proto";

enum EventType {
    UNKNOWN_EVENT_TYPE = 0;
    ACCIDENT = 49;
    ACID_RAIN = 78;
    AFTERSHOCK = 79;
    AIRCRAFT_HIJACKING = 50;
    AIR_POLLUTION = 112;
    AIR_STAGNATION = 113;
    AMBER_ALERT = 118;
    ARSON = 80;
    ASSASSINATION = 51;
    AVALANCHE = 52;
    AVIATION_ACCIDENTS_AND_INCIDENTS = 53;
    BIOTERRORISM = 1;
    BLIZZARD = 2;
    BLOWING_SNOW = 81;
    BOIL_WATER_ADVISORY = 3;
    BOMB = 54;
    BOMBING = 55;
    BUILDING_COLLAPSE = 56;
    BUSHFIRE = 4;
    CAR_BOMB = 57;
    CHEMICAL_EMERGENCY = 5;
    CHILD_ABDUCTION = 115;
    CIVIL_EMERGENCY = 6;
    COASTAL_FLOOD = 82;
    COASTAL_HAZARD = 83;
    COLD = 84;
    CONFLAGRATION = 36;
    CRIMINAL_INVESTIGATION = 125;
    CYCLONE = 44;
    DAM_FAILURE = 58;
    DEBRIS_FLOW = 122;
    DERAILMENT = 59;
    DISEASE_OUTBREAK = 109;
    DROUGHT = 60;
    DUST_STORM = 45;
    EARTHQUAKE = 7;
    EMERGENCY_EVACUATION = 8;
    ENERGY_CRISIS = 106;
    EXPLOSION = 61;
    EXPLOSIVE = 9;
    EXTRATROPICAL_CYCLONE = 46;
    FIRE = 10;
    FIRE_WEATHER = 40;
    FLASH_FLOOD = 11;
    FLOOD = 12;
    FOG = 107;
    FOOD_POISONING = 119;
    FREEZING = 85;
    FREEZING_AIR_TEMPERATURE = 86;
    FREEZING_DRIZZLE = 87;
    FREEZING_RAIN = 88;
    FREEZING_SPRAY = 116;
    FROST = 89;
    GALE = 47;
    GAS_EXPLOSION = 62;
    GAS_LEAK = 13;
    GEOMAGNETIC_STORM = 126;
    GLAZE = 90;
    HAIL = 48;
    HAZARDOUS_SEAS = 14;
    HAZE = 110;
    HEAT = 38;
    HUMIDITY = 108;
    HURRICANE = 15;
    ICE_STORM = 16;
    INDUSTRIAL_FIRE = 91;
    KIDNAPPING = 121;
    LAKE_EFFECT_SNOW = 17;
    LANDSLIDE = 42;
    LAW_ENFORCEMENT = 18;
    MARITIME_DISASTER = 63;
    MASS_CASUALTY_INCIDENT = 19;
    MISSING_PERSON = 41;
    MONSOON = 92;
    MUDDY_FLOOD = 93;
    MUDSLIDE = 124;
    NOISE_POLLUTION = 127;
    NUCLEAR_POWER_PLANT = 20;
    NUCLEAR_WARFARE = 21;
    OIL_SPILL = 64;
    OUTFLOW = 94;
    PLANE_CRASH = 65;
    POWER_OUTAGE = 22;
    PUBLIC_UTILITY_FAILURE = 120;
    RADIATION = 23;
    RAIL_DISASTER = 66;
    RAIN = 24;
    RIP_CURRENT = 114;
    RIVER_FLOODING = 95;
    ROAD_CLOSURE = 39;
    SCHOOL_SHOOTING = 67;
    SEARCH_AND_RESCUE = 123;
    SEVERE_THUNDERSTORM_WARNING = 96;
    SHELTER_IN_PLACE = 25;
    SHIP_COLLISION = 68;
    SHOOTING = 69;
    SNOW = 26;
    SNOWDRIFT = 117;
    SNOWSQUALL = 97;
    SOIL_CONTAMINATION = 128;
    STABBING = 70;
    STORM = 71;
    STORM_SURGE = 105;
    STRUCTURE_FIRE = 72;
    TERRORIST_ATTACK = 73;
    THUNDER = 98;
    THUNDERSTORM = 27;
    TORNADO = 28;
    TORNADO_WARNING = 99;
    TOXIC_WASTE = 129;
    TRAFFIC_COLLISION = 74;
    TRAIN_WRECK = 75;
    TROPICAL_CYCLONE = 43;
    TROPICAL_CYCLONE_WARNINGS_AND_WATCHES = 100;
    TROPICAL_DISTURBANCE = 111;
    TROPICAL_STORM = 35;
    TSUNAMI = 29;
    TSUNAMI_HAZARD_ZONES = 101;
    TYPHOON = 30;
    VEHICLE_RAMMING_ATTACK = 76;
    VIOLENCE = 77;
    VOLCANIC_ASH = 102;
    VOLCANIC_ERUPTION = 37;
    VOLCANIC_GAS = 103;
    WATER_POLLUTION = 130;
    WILDFIRE = 31;
    WIND = 32;
    WIND_CHILL = 104;
    WIND_WAVE = 33;
    WINTER_STORM = 34;
}

extend .proto2.EnumValueOptions {
    optional bool affects_navigation = 535801356;
}
