syntax = "editions";

package maps_paint;

option objc_class_prefix = "GMP";
option java_multiple_files = true;
option java_package = "com.google.maps.paint";

message SdkFeatureTypeInfo {
    repeated CustomStyleFeatureTag feature_tag_list = 1;
}

enum CustomStyleFeatureTag {
    option features = enum_type: CLOSED
    ;
    CSFT__UNSPECIFIED = 0;
    CSFT_ALL = 1;
    CSFT_ADMINISTRATIVE = 100;
    CSFT_BASE_CITY = 101;
    CSFT_COUNTRY = 102;
    CSFT_INTERNATIONAL_BORDER = 103;
    CSFT_NEIGHBORHOOD = 104;
    CSFT_SUBLOCALITY = 105;
    CSFT_TOP_LEVEL_ADMIN = 106;
    CSFT_DISPUTED_INTERNATIONAL_BORDER = 110;
    CSFT_TREATY_OR_PROVISIONAL_INTERNATIONAL_BORDER = 111;
    CSFT_ALL_BUILDINGS = 200;
    CSFT_COMMERCIAL_BUILDINGS = 210;
    CSFT_BUILDING_NUMBER = 220;
    CSFT_ENTRANCE = 230;
    CSFT_INDOOR = 240;
    CSFT_ARCHIPELAGO = 300;
    CSFT_BACKGROUND = 400;
    CSFT_ISLAND = 401;
    CSFT_PENINSULA = 402;
    CSFT_CONTINENT = 500;
    CSFT_CORRIDOR = 600;
    CSFT_LAND_COVER = 700;
    CSFT_BUILT_UP_AREA = 701;
    CSFT_LANDSAT_VEGETATION = 702;
    CSFT_DRY_CROPS = 703;
    CSFT_ICE = 704;
    CSFT_MIXED_CROPS = 705;
    CSFT_MIXED_FOREST = 706;
    CSFT_SAND = 707;
    CSFT_SHRUB = 708;
    CSFT_TUNDRA = 709;
    CSFT_SALT_FLAT = 710;
    CSFT_TERRAIN_SHADING = 720;
    CSFT_PARCEL = 800;
    CSFT_POI = 900;
    CSFT_AIRPORT = 901;
    CSFT_BRIDGE = 902;
    CSFT_EMERGENCY = 903;
    CSFT_FIRE = 904;
    CSFT_HOSPITAL = 905;
    CSFT_PHARMACY = 906;
    CSFT_ENTERTAINMENT = 907;
    CSFT_AMUSEMENT = 908;
    CSFT_ARTS = 909;
    CSFT_CASINO = 910;
    CSFT_CINEMA = 911;
    CSFT_HISTORIC = 912;
    CSFT_MUSEUM = 913;
    CSFT_TOURIST = 914;
    CSFT_FOOD_AND_DRINK = 915;
    CSFT_BAR = 916;
    CSFT_CAFE = 917;
    CSFT_RESTAURANT = 918;
    CSFT_WINERY = 919;
    CSFT_GOVERNMENT = 920;
    CSFT_LIBRARY = 921;
    CSFT_LIGHTHOUSE = 922;
    CSFT_LODGING = 923;
    CSFT_MILITARY = 924;
    CSFT_OUTDOOR_AREA_OR_POINT = 925;
    CSFT_BEACH = 926;
    CSFT_BOATING = 927;
    CSFT_CEMETERY = 928;
    CSFT_FISHING = 929;
    CSFT_GOLF_COURSE = 930;
    CSFT_HOTSPRING = 931;
    CSFT_NATURE_RESERVE = 932;
    CSFT_PARK = 933;
    CSFT_PEAK = 934;
    CSFT_SPORTS_COMPLEX = 935;
    CSFT_SPORTS_FIELD = 936;
    CSFT_TRAILHEAD = 937;
    CSFT_ZOO = 938;
    CSFT_POLICE = 939;
    CSFT_POST_OFFICE = 940;
    CSFT_REST_STOP = 941;
    CSFT_RETAIL = 942;
    CSFT_GROCERY = 943;
    CSFT_SHOPPING = 944;
    CSFT_SCHOOL = 945;
    CSFT_SCHOOL_AREA = 946;
    CSFT_SERVICES = 947;
    CSFT_ATM = 948;
    CSFT_BANK = 949;
    CSFT_CAR_RENTAL = 950;
    CSFT_EV_CHARGING_STATION = 951;
    CSFT_GAS_STATION = 952;
    CSFT_PARKING_LOT = 953;
    CSFT_RESTROOM = 954;
    CSFT_TEMPLE = 955;
    CSFT_BUDDHIST = 971;
    CSFT_CHRISTIAN = 972;
    CSFT_HINDU = 973;
    CSFT_ISLAMIC = 974;
    CSFT_JAIN = 975;
    CSFT_JUDAIC = 976;
    CSFT_MORMON = 977;
    CSFT_SHINTO = 978;
    CSFT_SIKH = 979;
    CSFT_TOWN_SQUARE = 956;
    CSFT_TRANSIT_GROUNDS = 957;
    CSFT_TRANSIT_POI = 958;
    CSFT_OTHER_POI = 959;
    CSFT_ICONIC_ICON_POI = 960;
    CSFT_POSTAL_CODE = 1000;
    CSFT_RAIL = 1100;
    CSFT_RAIL_CONCEPTUAL = 1101;
    CSFT_RAIL_PHYSICAL = 1102;
    CSFT_TARMAC = 1110;
    CSFT_RESERVATION = 1200;
    CSFT_ROAD = 1300;
    CSFT_NON_TRAFFIC = 1301;
    CSFT_PEDESTRIAN_MALL = 1302;
    CSFT_TRAIL = 1303;
    CSFT_TRAIL_PAVED = 1315;
    CSFT_TRAIL_UNPAVED = 1316;
    CSFT_NORMAL_SEGMENT = 1304;
    CSFT_ARTERIAL = 1305;
    CSFT_HIGH_PRIORITY = 1306;
    CSFT_LOCAL_OR_OVERPASS = 1307;
    CSFT_TERMINAL = 1308;
    CSFT_PARKING_AISLE = 1309;
    CSFT_ROAD_SHIELD = 1310;
    CSFT_ROAD_SIGN = 1314;
    CSFT_DETAILED_ROAD = 1317;
    CSFT_DETAILED_ROAD_SURFACE = 1318;
    CSFT_DETAILED_ROAD_LANE = 1319;
    CSFT_DETAILED_ROAD_CROSSWALK = 1320;
    CSFT_DETAILED_ROAD_MARKING = 1324;
    CSFT_DETAILED_ROAD_SIDEWALK = 1321;
    CSFT_DETAILED_INTERSECTION = 1322;
    CSFT_DETAILED_ROAD_LANE_MARKER = 1325;
    CSFT_DETAILED_ROAD_LANE_MARKER_CROSSABLE = 1326;
    CSFT_DETAILED_ROAD_LANE_MARKER_TURN = 1327;
    CSFT_DIRECTION_ARROW = 1323;
    CSFT_DETAILED_ROAD_PRIVATE = 2003;
    CSFT_DETAILED_ROAD_HIGHWAY = 2004;
    CSFT_DETAILED_ROAD_TUNNEL = 2005;
    CSFT_FERRY = 1311;
    CSFT_RAMP = 1312;
    CSFT_MAJOR_RAMP = 1313;
    CSFT_TRANSIT_STATION_OR_ENTRANCE = 1400;
    CSFT_MONORAIL_STATION = 1401;
    CSFT_RAIL_STATION = 1402;
    CSFT_SUBWAY_STATION = 1403;
    CSFT_BICYCLE_SHARING_LOCATION = 1404;
    CSFT_BUS_STATION = 1405;
    CSFT_FERRY_TERMINAL = 1406;
    CSFT_FUNICULAR_STATION = 1407;
    CSFT_GONDOLA_STATION = 1408;
    CSFT_TRAM_STATION = 1409;
    CSFT_WATER = 1500;
    CSFT_CHANNEL = 1501;
    CSFT_LAKE = 1502;
    CSFT_MISC_WATER = 1503;
    CSFT_OCEAN = 1504;
    CSFT_RIVER = 1505;
    CSFT_LAND = 2000;
    CSFT_TRANSPORTATION = 2001;
    CSFT_TRAVEL = 2002;
}
