syntax = "proto2";

package photos;

import "photos/protobuff/status/retryable_extension.proto";
import "util/task/contrib/proto_status/proto_status.proto";

option objc_class_prefix = "PHTS";
option java_package = "com.google.photos.fife";

message FIFEStatus {
    enum Code {
        SUCCESS = 0;
        NOT_FOUND = 101;
        NOT_FOUND_NEVER_EXISTED = 228;
        NOT_MODIFIED = 102;
        ACCESS_DENIED = 114;
        UNKNOWN = 230;
        DEADLINE_EXCEEDED = 241;
        INVALID_REQUEST = 1;
        INVALID_CONTENT_REF = 107;
        INVALID_CONTENT_DATA_URL = 231;
        INVALID_URL = 108;
        CONTENT_URL_DECRYPTION_FAILED = 222;
        LEGACY_URL_BAD_SIGNATURE = 223;
        LEGACY_URL_HE_SIGNATURE_MISSING = 224;
        LEGACY_URL_BAD_HE_SIGNATURE = 225;
        CONTENT_URL_SECRET_MISSING = 226;
        CONTENT_URL_SECRET_MISMATCH = 227;
        INVALID_VERSION_NUMBER = 110;
        NOT_IMAGE = 12;
        BAD_IMAGE = 13;
        IMAGE_TOO_BIG = 14;
        CONTENT_HASH_MISMATCH = 15;
        ROLE_THROTTLED = 235;
        SERVICE_NOT_AVAILABLE = 4;
        BACKEND_APPLICATION_ERROR = 6;
        APPLICATION_ERROR = 105;
        REQUEST_BECAME_STALE = 106;
        METADATA_DATA_INCONSISTENCY = 115;
        BAD_METADATA = 237;
        MISSING_EXIF_METADATA = 238;
        CLIENT_DISCONNECTED = 111;
        REJECTED_GLOBAL_LIMIT = 112;
        REJECTED_IP_LIMIT = 113;
        RATE_LIMITED = 116;
        COSMO_RATE_LIMITED = 229;
        STREAMING_URLS_RATE_LIMITED = 233;
        STREAMING_URLS_FEATURE_DISABLED = 242;
        CHEMIST_REQUEST_RATE_LIMITED = 234;
        HARPOON_REQUEST_RATE_LIMITED = 239;
        HARPOON_RESOURCE_EXHAUSTED = 240;
        REFERER_RATE_LIMITED = 247;
        INTERNAL_ERROR = 117;
        CONDITIONAL_FAILURE = 203;
        THUMBNAILER_TRANSFORM_ERROR = 204;
        QUOTA_EXCEEDED = 119;
        DECRYPTION_ERROR = 120;
        THROTTLED = 8;
        OVERLOADED = 236;
        BLOBSTORE_TOO_MANY_RETRIES = 243;
        FAILED_PRECONDITION = 244;
        INVALID_EDITLIST = 245;
        DEPRECATED_VERSION_EXISTS = 2;
        DEPRECATED_BAD_DATACENTER_NUMBER = 3;
        DEPRECATED_DATA_CORRUPTION = 5;
        DEPRECATED_CONTENT_ALREADY_DELETED = 7;
        DEPRECATED_INVALID_REQUEST = 118;
        DEPRECATED_SERVICE_NOT_AVAILABLE = 104;
        DEPRECATED_NOT_LOCAL = 103;
        INVALID_STABLE_URL_DATA = 248;
        AGENT_RESOURCE_EXHAUSTED = 249;
    }
}
