syntax = "proto2";

package photos;

import public "photos/serving/integrations/identifiers/signing_keys/request_signing_key_info.proto";
import "devtools/staticanalysis/pipeline/analyzers/proto_best_practices/proto/optouts.proto";
import "logs/proto/logs_annotations/logs_annotations.proto";
import "net/proto2/proto/descriptor.proto";
import "photos/fife/fife_status.proto";
import "util/task/contrib/proto_status/proto_status.proto";

option objc_class_prefix = "PHTS";
option java_package = "com.google.photos.fife";

message ImageAccess {
    enum Scope {
        UNKNOWN = 0;
        PUBLIC = 1;
        UNLISTED = 2;
        PROTECTED = 3;
        AUTO_BACKUP = 4;
        ALBUMLESS = 5;
        OWNER_ONLY = 6;
        ACL_ENFORCED = 7;
    }
}

message CacheLookup {
    enum ResultType {
        UNKNOWN_RESULT = 0;
        HIT = 1;
        EXPIRED = 3;
        RETIRED = 12;
        DELETED = 7;
        MAYBE_DELETED = 10;
        REJECTED = 11;
        MISS = 8;
        NO_CACHE = 15;
        DEPRECATED_CACHE_LARGER_HIT = 2;
        DEPRECATED_CACHE_LARGER_EXPIRED = 4;
        DEPRECATED_CACHE_EXACT_EXPIRED_CHANGED = 5;
        DEPRECATED_CACHE_LARGER_EXPIRED_CHANGED = 6;
        DEPRECATED_CACHE_OLD_HIT = 9;
        DEPRECATED_STUB = 13;
        DEPRECATED_CACHED_ERROR = 14;
    }
}

message MetadataCacheLookup {
    enum Result {
        UNKNOWN_RESULT = 0;
        HIT = 1;
        RETIRED = 2;
        MISS = 3;
        SKIPPED = 4;
        ERROR = 5;
        FALLBACK = 6;
    }
}

message AuthRequirement {
    enum Decision {
        UNKNOWN = 0;
        PASS = 1;
        SKIP_ACL = 2;
        CHECK = 3;
        ACL = 4;
        DENY = 5;
    }
}

message InputAuthDecision {
    enum Factor {
        UNKNOWN = 0;
        SKIP = 1;
        CHECK_GAIA_AUTH = 2;
        SECRET_BYPASS = 3;
        AUTH = 4;
        AUTH_NONPUBLIC = 5;
        AUTH_SKIP_SECRET = 9;
    }
}

message BackendAuthDecision {
    enum Factor {
        UNKNOWN = 0;
        STRICT_AUTH = 1;
        AUTH = 2;
        AUTH_OR_SECRET = 3;
        SKIP_OR_CHECK = 4;
        PASS_OR_CHECK = 5;
        PUBLIC = 6;
        DENY = 7;
        FORCE_CHECK = 8;
        FORCE = 9;
    }
}

message AuthMechanism {
    enum Type {
        UNKNOWN_TYPE = 0;
        EMBEDDED_DAT = 1;
        OAUTH_ACCESS_TOKEN = 2;
        OSID_COOKIE = 3;
        GOOGLE_COOKIE_FOR_REDIRECT = 4;
        EMBEDDED_AUTH_GAIA_ID = 5;
        EMBEDDED_VIEWER_GAIA_ID = 6;
    }
}

message RequestStatusInfo {
    optional Type type = 1;
    enum Type {
        UNKNOWN_ERROR = 0;
        NOT_FOUND = 1;
        ACCESS_DENIED = 2;
        IMAGE_NOT_ALLOWED = 3;
        INVALID_URL = 4;
        OK = 5;
        ACCESS_DENIED_ALLOW_REDIRECTS = 6;
        TOO_MANY_REQUESTS = 7;
        BAD_REQUEST = 8;
        DEADLINE_EXCEEDED = 9;
    }
    
    optional FIFEStatus.Code fife_status = 2;
    
    reserved 3;
}

message FifeAuthenticationRequirement {
    enum Policy {
        UNKNOWN = 0;
        FORCE_PUBLIC = 1;
        AUTH_OR_SECRET = 2;
        STRICT_AUTH = 3;
        SELECTED_FOR_SEPARATION = 4;
        PUBLIC_IF_URL_MATCHES = 5;
    }
}

message RequestStatus {
    enum Code {
        SUCCESS = 0;
        UNKNOWN = 47;
        NOT_FOUND = 12;
        NOT_FOUND_NEVER_EXISTED = 237;
        DEADLINE_EXCEEDED = 280;
        NOT_MODIFIED = 19;
        CONTENT_DELETED = 1;
        BOGUS_IMAGE_VERSION = 5;
        CLIENT_DISCONNECTED_BEFORE_PROCESSING = 8;
        ACCOUNT_DISABLED = 11;
        CONTENT_DISABLED = 13;
        APPHOSTING_CLIENT_DISABLED = 229;
        REQUEST_BECAME_STALE = 14;
        HARPOON_NOT_FOUND = 205;
        HARPOON_IMAGE_TOO_BIG = 210;
        HARPOON_RESOURCE_EXHAUSTED = 281;
        BLACKLISTED_REFERER = 15;
        URL_EXPIRED = 16;
        REGION_TAKEDOWN = 17;
        PROTECTED_TILE_DENIED = 18;
        REFERER_RATE_LIMITED = 37;
        COSMO_ACL_DENIED = 39;
        COSMO_RATE_LIMITED = 244;
        STREAMING_URLS_RATE_LIMITED = 252;
        STREAMING_URLS_FEATURE_DISABLED = 282;
        CHEMIST_REQUEST_RATE_LIMITED = 257;
        HARPOON_REQUEST_RATE_LIMITED = 279;
        MEDIA_SERVICE_ACL_DENIED = 214;
        RAW_STREAM_ACL_DENIED = 285;
        MEDIA_SERVICE_ACL_DENIED_UNENFORCED = 250;
        VIEWER_NOT_OWNER_DENIED = 231;
        AUTH_GAIA_ID_DENIED = 40;
        FOCUS_DENIED = 260;
        BLOCK_BEFORE_VERSION_DENIED = 41;
        INTERNAL_ONLY_DENIED = 43;
        DASHER_RESTRICTED_CONTENT_DENIED = 242;
        TECH_BLOB_DENIED = 212;
        VERDICT_DENIED = 45;
        BLOBSTORE_ACCESS_DENIED = 207;
        BLOBSTORE_BLOCKED = 208;
        BOLD_LAST_HOP_ERROR = 254;
        BOLD_FIRST_HOP_INTERNAL_ERROR = 255;
        BOLD_FIRST_HOP_LOOKUP_ERROR = 256;
        DENIED_BY_CLIENT_REQUEST = 209;
        MISSING_CREDENTIALS = 215;
        MISSING_CREDENTIALS_INTERNAL = 247;
        MISSING_AUTH_OR_SECRET = 236;
        MISSING_AUTH_OR_SECRET_INTERNAL = 248;
        MISSING_CREDENTIALS_RPC = 228;
        MISSING_CREDENTIALS_UNENFORCED = 221;
        MISSING_CREDENTIALS_UNENFORCED_INTERNAL = 246;
        MISSING_BACKEND_SECRET_UNENFORCED = 232;
        MISSING_CREDENTIALS_UNENFORCED_AND_MISSING_BACKEND_SECRET_UNENFORCED = 233;
        MISSING_AUTH_OR_SECRET_UNENFORCED = 234;
        MISSING_AUTH_OR_SECRET_UNENFORCED_INTERNAL = 235;
        EXPIRED_CREDENTIALS_UNNEEDED = 273;
        EXPIRED_CREDENTIALS_UNNEEDED_INTERNAL = 267;
        EXPIRED_CREDENTIALS = 268;
        EXPIRED_CREDENTIALS_INTERNAL = 274;
        EXPIRED_CREDENTIALS_UNENFORCED = 270;
        EXPIRED_CREDENTIALS_UNENFORCED_INTERNAL = 269;
        EXPIRED_CREDENTIALS_REDIRECTED = 271;
        EXPIRED_CREDENTIALS_REDIRECTED_INTERNAL = 272;
        REDIRECTED_TO_LOGIN = 277;
        DASHER_RESTRICTED_CONTENT_DENIED_UNENFORCED = 243;
        CHECK_MISSING_CREDENTIALS_SAMPLED = 238;
        CHECK_MISSING_CREDENTIALS_PRESENT = 239;
        CHECK_MISSING_CREDENTIALS_MISSING = 240;
        CHECK_MISSING_CREDENTIALS_WRONG = 241;
        GET_DAT_FAILED = 217;
        DAT_TO_MINT_FAILED = 218;
        VALIDATE_CREDS_FAILED = 219;
        INVALID_CREDENTIALS = 245;
        LEGACY_URL_HE_SIGNATURE_MISSING = 224;
        LEGACY_URL_BAD_HE_SIGNATURE = 225;
        CONTENT_URL_SECRET_MISSING = 226;
        CONTENT_URL_SECRET_MISMATCH = 227;
        INVALID_REQUEST = 2;
        INVALID_CONTENT_REF = 103;
        INVALID_CONTENT_DATA_URL = 251;
        INSECURE_URL = 278;
        INVALID_URL = 104;
        CONTENT_URL_DECRYPTION_FAILED = 222;
        LEGACY_URL_BAD_SIGNATURE = 223;
        NOT_IMAGE = 106;
        BAD_IMAGE = 107;
        IMAGE_TOO_BIG = 108;
        THROTTLED = 211;
        ROLE_THROTTLED = 265;
        SERVICE_NOT_AVAILABLE = 109;
        BACKEND_APPLICATION_ERROR = 111;
        APPLICATION_ERROR = 112;
        METADATA_DATA_INCONSISTENCY = 114;
        CLIENT_DISCONNECTED = 115;
        REJECTED_GLOBAL_LIMIT = 6;
        REJECTED_IP_LIMIT = 7;
        RATE_LIMITED = 116;
        INTERNAL_ERROR = 117;
        GAIA_MINT_RPC_ERROR = 119;
        CONDITIONAL_FAILURE = 203;
        THUMBNAILER_TRANSFORM_ERROR = 204;
        QUOTA_EXCEEDED = 118;
        CLIENT_SIDE_THROTTLED = 220;
        OVERLOADED = 266;
        DECRYPTION_ERROR = 120;
        PHOTOS_SYNC_REJECTED = 20;
        CONTENT_HASH_MISMATCH = 213;
        VIDEO_CID_NOT_FOUND = 216;
        DEBUG_ACCESS_DENIED = 249;
        DOMAIN_ACCESS_DENIED = 253;
        RPC_ACCESS_DENIED = 262;
        AGENT_ACCESS_DENIED = 286;
        UNKNOWN_ACCESS_DENIED = 46;
        VIDEO_MANIFEST_ERROR = 261;
        SILO_DENIED_BY_POLICY = 263;
        SILO_REQUIRES_POLICY = 264;
        BAD_METADATA = 275;
        MISSING_EXIF_METADATA = 276;
        BLOBSTORE_TOO_MANY_RETRIES = 283;
        BLOBSTORE_WRITE_CRC32C_HASH_MISMATCH = 284;
        FAILED_PRECONDITION = 287;
        INVALID_EDITLIST = 288;
        INVALID_METADATA_FOR_THUMBNAILER = 290;
        INVALID_STABLE_URL_DATA = 289;
        INVALID_AGENT_RESPONSE = 291;
        FORCE_REDIRECT_SUCCESS = 292;
        FORCE_REDIRECT_DENIED = 293;
        INCORRECT_OLYMPUS_JURISDICTION = 294;
        GLOVEBOX_PERMISSION_DENIED = 295;
        AGENT_RESOURCE_EXHAUSTED = 296;
    }
}

message RequestType {
    enum Code {
        CONTENT_URL = 1;
        LEGACY_URL = 2;
        FAVICON_URL = 3;
        INVALID_URL = 4;
        INVALID_URL_RPC = 16;
        CROSSDOMAIN_URL = 5;
        GET_CONTENT_RPC = 6;
        GFE_LOGGING_REQUEST = 8;
        GET_RPC = 9;
        CONTENT_URL_RPC = 10;
        LEGACY_URL_RPC = 11;
        GUESSABLE_URL = 12;
        GUESSABLE_URL_RPC = 13;
        SECURE_URL = 14;
        SECURE_URL_RPC = 15;
        SECURE_GFE_LOGGING_REQUEST = 17;
    }
}

message StorageType {
    enum Code {
        UNKNOWN = 0;
        PHOTOS_SERVICE = 1;
        COSMO = 2;
        SHOEBOX = 3;
        FASTNET = 4;
        CONTENT_DATA = 6;
        MONOGRAM_VISUAL = 8;
        STATIC_REF = 9;
        PROFILE_SERVICE = 10;
        TEST = 11;
        DOPLAR = 12;
        CONTRIB_SERVICE = 13;
        AUTHENTICATED_BLOB = 14;
        SOCIAL_GRAPH = 15;
        DROPPER = 16;
    }
}

message ContentDataType {
    enum Code {
        UNKNOWN = 0;
        V1_BLOBREF = 1;
        V2_BLOBREF = 2;
        V2_BLOBID = 4;
        TECH_BLOB = 3;
    }
}

message GaiaCacheLookup {
    enum ResultType {
        GAIA_CACHE_HIT = 1;
        GAIA_CACHE_NEGATIVE_HIT = 2;
        GAIA_CACHE_MISS = 3;
    }
}

message RequestServer {
    enum Type {
        FIFE_SERVER = 1;
        CLIENT_SERVER = 2;
        INTERNAL_SERVER = 4;
        DEBUG_SERVER = 5;
        DEPRECATED_GWS_SERVER = 3;
    }
}

message RequestHost {
    enum Code {
        HOST_OTHER = 0;
        HOST_BLOGGER = 1;
        HOST_DISTILLER = 2;
        HOST_PHOTOS_SYNC = 3;
    }
}

message RequestDomain {
    enum Type {
        UNKNOWN = 0;
        NO_DOMAIN = 1;
        SANDBOX_DOMAIN = 2;
        GOOGLE_COOKIE_DOMAIN = 3;
        COOKIE_SERVING_DOMAIN = 4;
    }
}

message BackendSecretPresence {
    enum Code {
        UNKNOWN = 0;
        NONE = 1;
        OPTIONAL = 2;
        MISSING = 3;
        REQUIRED = 4;
        UNNECESSARY = 5;
    }
}

message NotifyOtf {
    enum Status {
        UNKNOWN = 0;
        SUCCESS = 1;
        NULL_CLIENT = 2;
        NOT_PHOTOS = 3;
        FAILURE = 4;
    }
}

message RequestSigningKey {
    enum Code {
        UNKNOWN = 0;
        NONE = 1;
        DEV = 2;
        PROD = 3;
        MONOGRAM_AUTOKEY = 4;
        MEDIA_KEY = 5;
        COSMO_KEY = 6;
        FIFE_AUTH_REDIRECT_KEY = 69;
        FALLBACK_OLYMPUS_KEY = 376;
        PHOTOS_ANDROID_GUESSABLE_PHOTOSREF_KEY = 79;
        PHOTOS_IOS_GUESSABLE_PHOTOSREF_KEY = 147;
        PHOTOS_IOS_WIDGET_GUESSABLE_PHOTOSREF_KEY = 89;
        PHOTOS_WEB_GUESSABLE_PHOTOSREF_KEY = 68;
        AVATAR_KEY = 7;
        FALLBACK_AVATAR_KEY = 8;
        ADMIN_AVATAR_KEY = 175;
        FAKE_KEY = 9;
        FAKE_STABLE_KEY = 360;
        FAKE_GUESSABLE_KEY = 394;
        SECONDARY_FAKE_KEY = 13;
        MISSING_FAKE_KEY = 18;
        PHOTOS_OSID_TEST_KEY = 217;
        PHOTOS_OSID_GUESSABLE_TEST_KEY = 351;
        FAKE_CUSTOM_MEDIA_GUESSABLE_KEY = 66;
        FAKE_CUSTOM_DOC_GUESSABLE_KEY = 67;
        FAKE_CUSTOM_CONTRIB_SERVICE_GUESSABLE_KEY = 331;
        FAKE_STITCH_WITHGOOGLE_COM_OSID_TEST_KEY = 396;
        FUZZING_FIFE_GUESSABLE_KEY = 209;
        CONTRIB_SERVICE_FITBIT_P11_KEY = 263;
        GEO_PHOTO_SERVICE_PHOTOSREF_KEY = 151;
        GEO_PHOTO_SERVICE_PROXY_KEY = 152;
        GEO_PHOTO_SERVICE_GUESSABLE_KEY = 200;
        GEO_PHOTO_SERVICE_CS_SECURE_KEY = 304;
        GEO_PHOTO_SERVICE_CS_GUESSABLE_KEY = 305;
        GEO_PHOTO_SERVICE_CS_GUESSABLE_STALE_KEY = 384;
        GEO_PHOTO_SERVICE_CS_SECURE_STALE_KEY = 361;
        GEO_PHOTO_METADATA_SERVICE_GUESSABLE_KEY = 201;
        GEO_PHOTO_METADATA_SERVICE_CS_SECURE_KEY = 317;
        GEO_PHOTO_METADATA_SERVICE_CS_SECURE_LONG_TTL_KEY = 348;
        GEO_PHOTO_METADATA_SERVICE_CS_GUESSABLE_KEY = 318;
        GEO_PHOTO_METADATA_SERVICE_CS_SECURE_STALE_KEY = 363;
        GEO_PHOTO_SIGNAL_SERVICE_CS_SECURE_KEY = 334;
        GEO_PHOTO_VENUS_PHOTOS_GUESSABLE_KEY = 300 [deprecated = true];
        GEO_PHOTO_VENUS_PHOTOS_STABLE_SECURE_KEY = 308;
        GEO_PHOTO_VENUS_CS_SECURE_KEY = 357;
        GEO_PHOTO_VENUS_CS_SECURE_STALE_KEY = 413;
        GEO_PHOTO_VENUS_CS_LONG_TTL_SECURE_KEY = 347;
        GMAIL_ATTACHMENT_PHOTOSREF_KEY = 112;
        GMAIL_ATTACHMENT_PROXY_KEY = 113;
        GMAIL_DATAREF_KEY = 10;
        GMAIL_DRIVE_SIGNATURE_IMAGE_URL_KEY = 131;
        GMAIL_PHOTOS_THEME_PHOTOSREF_KEY = 183;
        GMAIL_DOC_PREVIEW_GUESSABLE_KEY = 178;
        PHOTOS_ADMIN_DATAREF_KEY = 11;
        CONTRIB_SERVICE_GMS_KEY = 333;
        ARKADIA_DINNERF_GUESSABLE_KEY = 265;
        CROWDSOURCE_CAPABILITY_PHOTOSREF_KEY = 352;
        CROWDSOURCE_PHOTOSREF_KEY = 247;
        PHOTOS_CROWDSOURCE_PHOTOSREF_KEY = 20;
        CROWDSOURCE_BEYOND_PHOTOSREF_KEY = 227;
        PHOTOS_MAGIC_EDITOR_DATAREF_KEY = 223;
        PHOTOS_ANIMATED_POPOUT_DATAREF_KEY = 353;
        PHOTOS_LIBRARY_PHOTOSREF_KEY = 12;
        PHOTOS_PARTNER_PHOTOSREF_KEY = 16;
        NOT_VERIFIED = 14;
        CLOUDCAST_PHOTOSREF_KEY = 15;
        CLOUDCAST_DEV_PHOTOSREF_KEY = 126;
        CLOUDCAST_STAGING_PHOTOSREF_KEY = 128;
        CLOUDCAST_PREPROD_PHOTOSREF_KEY = 129;
        YOUTUBE_SHOPPING_PROXY_KEY = 21;
        PAYMENTS_CARD_3D_SECURE2_PROXY_KEY = 22;
        PHOTOS_BENCHMARKS_PHOTOSREF_KEY = 23;
        DOCS_DRIVE_KEY = 24;
        DOCS_PUBLIC_DRIVE_KEY = 219;
        DOCS_DATA_REF_KEY = 194;
        DOCS_URL_BACKED_IMAGES_PROXY_KEY = 63;
        CHANGELING_DRIVE_KEY = 26;
        DRIVE_STORAGE_SERVER_DRIVE_KEY = 206;
        CHANGELING_VAULT_DRIVE_KEY = 27;
        DOCS_DOPLAR_STABLE_KEY = 271;
        DOCS_DOPLAR_KEY = 132;
        DOCS_DOPLAR_QUAL_KEY = 309;
        DOCS_DOPLAR_QUAL_STABLE_KEY = 319;
        SHEETS_DOPLAR_STABLE_KEY = 270;
        SHEETS_DOPLAR_KEY = 156;
        SHEETS_DOPLAR_QUAL_KEY = 310;
        SHEETS_DOPLAR_QUAL_STABLE_KEY = 320;
        SLIDES_DOPLAR_STABLE_KEY = 269;
        SLIDES_DOPLAR_KEY = 157;
        SLIDES_DOPLAR_QUAL_KEY = 311;
        SLIDES_DOPLAR_QUAL_STABLE_KEY = 321;
        VIDEOS_DOPLAR_STABLE_KEY = 268;
        VIDEOS_DOPLAR_KEY = 220;
        VIDEOS_DOPLAR_QUAL_KEY = 312;
        VIDEOS_DOPLAR_QUAL_STABLE_KEY = 322;
        DRAWINGS_DOPLAR_STABLE_KEY = 267;
        DRAWINGS_DOPLAR_KEY = 166;
        DRAWINGS_DOPLAR_QUAL_KEY = 313;
        DRAWINGS_DOPLAR_QUAL_STABLE_KEY = 323;
        DOCS_DOPLAR_COOKIE_SERVING_US_KEY = 420;
        DOCS_DOPLAR_COOKIE_SERVING_EU_KEY = 421;
        DOCS_DOPLAR_COOKIE_SERVING_QUAL_KEY = 438;
        SHEETS_DOPLAR_COOKIE_SERVING_US_KEY = 422;
        SHEETS_DOPLAR_COOKIE_SERVING_EU_KEY = 423;
        SHEETS_DOPLAR_COOKIE_SERVING_QUAL_KEY = 439;
        SLIDES_DOPLAR_COOKIE_SERVING_US_KEY = 424;
        SLIDES_DOPLAR_COOKIE_SERVING_EU_KEY = 425;
        SLIDES_DOPLAR_COOKIE_SERVING_QUAL_KEY = 440;
        DRAWINGS_DOPLAR_COOKIE_SERVING_US_KEY = 426;
        DRAWINGS_DOPLAR_COOKIE_SERVING_EU_KEY = 427;
        DRAWINGS_DOPLAR_COOKIE_SERVING_QUAL_KEY = 441;
        FORMS_DOPLAR_COOKIE_SERVING_US_KEY = 428;
        FORMS_DOPLAR_COOKIE_SERVING_EU_KEY = 429;
        FORMS_DOPLAR_COOKIE_SERVING_QUAL_KEY = 442;
        VIDEOS_DOPLAR_COOKIE_SERVING_US_KEY = 430;
        VIDEOS_DOPLAR_COOKIE_SERVING_EU_KEY = 431;
        VIDEOS_DOPLAR_COOKIE_SERVING_QUAL_KEY = 443;
        PICTURES_DOPLAR_COOKIE_SERVING_US_KEY = 448;
        PICTURES_DOPLAR_COOKIE_SERVING_EU_KEY = 449;
        PICTURES_DOPLAR_COOKIE_SERVING_QUAL_KEY = 450;
        ATARI_DOPLAR_STABLE_KEY = 266;
        ATARI_DOPLAR_KEY = 168;
        ATARI_DOPLAR_QUAL_KEY = 314;
        ATARI_DOPLAR_QUAL_STABLE_KEY = 324;
        ATARI_VIEWER_DOPLAR_STABLE_KEY = 369;
        ATARI_VIEWER_DOPLAR_QUAL_STABLE_KEY = 370;
        ATARI_VIEWER_DOPLAR_KEY = 301;
        ATARI_VIEWER_QUAL_DOPLAR_KEY = 371;
        JAM_DOPLAR_KEY = 169;
        JAM_DOPLAR_QUAL_KEY = 315;
        JAM_DOPLAR_QUAL_STABLE_KEY = 325;
        JAM_DOPLAR_STABLE_KEY = 273;
        JAM_EXPORT_KEY = 250;
        JAM_WEBRENDER_KEY = 262;
        FREEBIRD_DOPLAR_KEY = 170;
        FREEBIRD_DOPLAR_QUAL_KEY = 316;
        FREEBIRD_DOPLAR_QUAL_STABLE_KEY = 326;
        FREEBIRD_DOPLAR_STABLE_KEY = 272;
        LYNX_DOPLAR_STABLE_KEY = 389;
        LYNX_DOPLAR_KEY = 390;
        LYNX_DOPLAR_QUAL_KEY = 391;
        LYNX_DOPLAR_QUAL_STABLE_KEY = 392;
        FREEBIRD_TEMP_DRIVE_FORMS_GUESSABLE_KEY = 205;
        CONTRIB_SERVICE_AI_SANDBOX_KEY = 335;
        CONTRIB_SERVICE_AI_SANDBOX_QUAL_KEY = 336;
        CONTRIB_SERVICE_AIDA_CODEFX_KEY = 378;
        CONTRIB_SERVICE_AIDA_CODEFX_PUBLIC_NON_ROTATING_KEY = 386;
        CONTRIB_SERVICE_AREA120_NOEB_KEY = 189;
        CONTRIB_SERVICE_AREA120_SPLASH_KEY = 190;
        CONTRIB_SERVICE_AREA120_SPLASH_QUAL_KEY = 198;
        CONTRIB_SERVICE_ARTS_CULTURE_STUDIO_KEY = 366;
        CONTRIB_SERVICE_ASTRA_KEY = 346;
        CONTRIB_SERVICE_ASTRA_QUAL_KEY = 354;
        CONTRIB_SERVICE_BAD_HARVEST_KEY = 212;
        CONTRIB_SERVICE_BARD_STORAGE_KEY = 224;
        CONTRIB_SERVICE_BARD_STORAGE_PUBLIC_NON_ROTATING_KEY = 246;
        CONTRIB_SERVICE_CROWDSOURCE_MEDIA_KEY = 382;
        CONTRIB_SERVICE_FLYBY_PUBLIC_NON_ROTATING_KEY = 284;
        CONTRIB_SERVICE_FLYBY_KEY = 293;
        CONTRIB_SERVICE_GEMINI_KEY = 280;
        CONTRIB_SERVICE_GEMINI_CONTENT_PLATFORM_KEY = 470;
        CONTRIB_SERVICE_GEMINI_CONTENT_PLATFORM_QUAL_KEY = 473;
        CONTRIB_SERVICE_GEMINI_EVAL_KEY = 296;
        CONTRIB_SERVICE_GEMINI_PUBLIC_NON_ROTATING_KEY = 281;
        CONTRIB_SERVICE_GEMINI_DATA_LOCATION_KEY = 367;
        CONTRIB_SERVICE_GEO_CONTRIBUTION_SERVICE_KEY = 249;
        CONTRIB_SERVICE_GEO_PLACES_API_KEY = 342;
        CONTRIB_SERVICE_GEO_PHOTO_UPLOADER_KEY = 349;
        CONTRIB_SERVICE_GOOGLE_TV_KEY = 295;
        CONTRIB_SERVICE_GPS_GENERATIONS_KEY = 260;
        CONTRIB_SERVICE_GPS_GENERATIONS_QUAL_KEY = 285;
        CONTRIB_SERVICE_JULES_KEY = 414;
        CONTRIB_SERVICE_ILLUMINATE_KEY = 388;
        CONTRIB_SERVICE_KARTO_KEY = 356;
        CONTRIB_SERVICE_LABS_DELAWARE_MEDIA_STABLE_KEY = 276;
        CONTRIB_SERVICE_LTLJ_CHAT_HISTORY_KEY = 362;
        CONTRIB_SERVICE_NOTEBOOKLM_KEY = 278;
        CONTRIB_SERVICE_NOTEBOOKLM_QUAL_KEY = 279;
        CONTRIB_SERVICE_PIXEL_MERLIN_KEY = 244;
        CONTRIB_SERVICE_PLAY_GAMES_SERVICES_KEY = 237;
        CONTRIB_SERVICE_PLAY_GAMES_SERVICES_QUAL_KEY = 238;
        CONTRIB_SERVICE_PLAY_STORE_REVIEWS_KEY = 286;
        CONTRIB_SERVICE_PLAY_STORE_REVIEWS_QUAL_KEY = 287;
        CONTRIB_SERVICE_PLAY_STORE_REVIEWS_PUBLIC_NON_ROTATING_KEY = 338;
        CONTRIB_SERVICE_PODIUM_PLAYGROUND_KEY = 264;
        CONTRIB_SERVICE_RSVP_FILES_KEY = 241;
        CONTRIB_SERVICE_LENS_HISTORY_KEY = 302;
        CONTRIB_SERVICE_COLLECTIONS_KEY = 197;
        CONTRIB_SERVICE_METAL_KEY = 179;
        CONTRIB_SERVICE_METAL_SHARED_KEY = 344;
        CONTRIB_SERVICE_METAL_QUAL_KEY = 341;
        CONTRIB_SERVICE_METAL_SHARED_QUAL_KEY = 385;
        CONTRIB_SERVICE_METAL_PUBLIC_NON_ROTATING_KEY = 229;
        CONTRIB_SERVICE_RECEIPTS_KEY = 240;
        CONTRIB_SERVICE_REGIONAL_KEY = 372;
        CONTRIB_SERVICE_ROAM_KEY = 188;
        CONTRIB_SERVICE_SEARCH_BOBA_MEDIA_KEY = 225;
        CONTRIB_SERVICE_SEARCH_BOBA_MEDIA_QUAL_KEY = 226;
        CONTRIB_SERVICE_SEARCH_BOBA_MEDIA_PUBLIC_NON_ROTATING_KEY = 282;
        CONTRIB_SERVICE_SEARCH_BOBA_MEDIA_QUAL_PUBLIC_NON_ROTATING_KEY = 283;
        CONTRIB_SERVICE_SEARCH_FEEDBACK_KEY = 245;
        CONTRIB_SERVICE_SEARCH_HAMSA_MEDIA_KEY = 329;
        CONTRIB_SERVICE_SHOPSTREAM_KEY = 290;
        CONTRIB_SERVICE_SHOPSTREAM_QUAL_KEY = 291;
        CONTRIB_SERVICE_UPDRAFT_KEY = 254;
        CONTRIB_SERVICE_UPDRAFT_PUBLIC_NON_ROTATING_KEY = 255;
        CONTRIB_SERVICE_UPDRAFT_QUAL_KEY = 358;
        CONTRIB_SERVICE_UPDRAFT_PUBLIC_NON_ROTATING_QUAL_KEY = 359;
        CONTRIB_SERVICE_WALLET_CARDCENTRIC_KEY = 397;
        CONTRIB_SERVICE_WALLET_VALUABLES_KEY = 373;
        CONTRIB_SERVICE_WALLET_VALUABLES_QUAL_KEY = 374;
        CONTRIB_SERVICE_WAYMO_SIMHUB_KEY = 298;
        CONTRIB_SERVICE_WAYMO_SIMHUB_QUAL_KEY = 299;
        CONTRIB_SERVICE_WORKSPACE_GEN_AI_KEY = 274;
        CONTRIB_SERVICE_WORKSPACE_GEN_AI_QUAL_KEY = 275;
        CLASSROOM_THUMBNAILS_DATA_KEY = 28;
        MULTIMEDIA_NEWS_SETTINGS_PROXY_KEY = 29;
        CUSTOM_SEARCH_ENGINES_PROXY_KEY = 30;
        LENS_PHOTOSREF_KEY = 31;
        GEO_LOCAL_SHOPPING_PROXY_KEY = 32;
        BUGANIZER_PROXY_KEY = 33;
        DYNAMITE_ROOM_AVATAR_KEY = 34;
        PLACE_PHOTOSREF_KEY = 35;
        PHOTOS_ABUSE_PHOTOSREF_KEY = 36;
        GPAY_CAMPUS_ID_PHOTOS_KEY = 37;
        PAYMENTS_SELF_ORDER_PROXY_KEY = 38;
        GPAY_MOVIES_MICROAPP_PROXY_KEY = 39;
        GOOGLE_ONE_SMUI_KEY = 40;
        PHOTOS_BACKEND_SAMPLE_CLIENT_PHOTOSREF_KEY = 41;
        PLACE_LOCAL_PHOTOSREF_KEY = 42;
        DISCOVER_PROXY_KEY = 43;
        TINYTASK_PHOTOSREF_KEY = 44;
        GPAY_IMAGE_PROXY_KEY = 45;
        YOUTUBE_IDENTITY_KEY = 46;
        MATERIAL_GALLERY_PHOTOS_KEY = 47;
        KWYJIBO_DATAREF_KEY = 48;
        ANDROID_TV_CHANNELS_PROXY_KEY = 49;
        GPAY_VERTICALS_PROXY_KEY = 50;
        ONE_GOOGLE_WEB_KEY = 51;
        GOOGLE_PODCASTS_PROXY_KEY = 52;
        THINGS_TO_DO_UGC_PHOTOSREF_KEY = 53;
        ONEPHOTO_STATS_FLUME_KEY = 54;
        PHOTOS_ADMIN_EXPORT_PHOTOSREF_KEY = 55;
        PHOTOS_AMBIENT_CAST_PHOTOSREF_KEY = 202;
        PHOTOS_WEB_PHOTOSREF_KEY = 56;
        PHOTOS_WEB_UNFILTERED_PHOTOSREF_KEY = 176;
        SHOPPING_PROPERTY_PROXY_KEY = 57;
        CONTACT_MONOGRAM_KEY = 58;
        CULTURAL_EVENT_PROXY_KEY = 59;
        ORBIT_PHOTOS_KEY = 61;
        SYSTEM1_PHOTOSREF_KEY = 62;
        RTB_KEY = 64;
        PHOTOS_CINEMATIC_MEMORIES_PHOTOSREF_KEY = 65;
        GEO_LOCAL_SHOPPING_GMB_PHOTOSREF_KEY = 70;
        FOOD_ORDERING_PROXY_KEY = 71;
        GEO_FOOD_GMB_PHOTOSREF_KEY = 72;
        SMART_DEVICE_MANAGEMENT_PHOTOSREF_KEY = 73;
        RECEIPTS_PHOTOSREF_KEY = 74;
        GPAY_MERCHANT_IMAGE_KEY = 75;
        GPLUS_PHOTOSREF_KEY = 76;
        GPLUS_PROXY_KEY = 77;
        HANGOUTS_PHOTOSREF_KEY = 78;
        FIFE_GET_RPC_KEY = 80;
        YOUTUBE_CHANNELS_AVATAR_KEY = 81;
        YOUTUBE_MUSIC_RECAP_PHOTOSREF_KEY = 192;
        GEO_HCE_ROUTER_GUESSABLE_KEY = 297;
        GEO_MYMAPS_HOSTED_KEY = 288;
        GEO_MYMAPS_PROXY_KEY = 82;
        GEO_UGC_SERVICES_GUESSABLE_KEY = 83;
        GEO_UGC_SERVICES_CS_SECURE_KEY = 306;
        GEO_UGC_SERVICES_CS_GUESSABLE_KEY = 307;
        GEO_UGC_IMPACT_EMAIL_GUESSABLE_KEY = 134;
        GEO_UGC_BULK_PHOTO_UPLOAD_PHOTOSREF_KEY = 163;
        GEO_UGC_TAKEDOWN_EMAIL_GUESSABLE_KEY = 144;
        CLOUDCAST_CAPTURE_AUTOPUSH_PHOTOSREF_KEY = 84;
        HOTEL_ROOM_PROXY_KEY = 85;
        HANGOUTS_STICKERS_PHOTOSREF_KEY = 86;
        KEEP_BLOBSTORE_BLOB_SERVING_KEY = 87;
        KEEP_MEDIA_ASSET_PROXYING_KEY = 88;
        TAKEOUT_LIS_PHOTOSREF_KEY = 90;
        SHOPS_KAHANI_KEY = 91;
        MDF_TOOL_RESULTS_DATAREF_KEY = 92;
        HANGOUTS_TAKEOUT_GUESSABLE_PHOTOSREF_KEY = 93;
        PHOTOS_PRINTING_PHOTOSREF_KEY = 94;
        PHOTOS_PRINTING_WITH_DAT_PHOTOSREF_KEY = 133;
        PHOTOS_DATA_VALIDATION_GUESSABLE_PHOTOSREF_KEY = 141;
        PHOTOS_HORCHATA_PHOTOSREF_KEY = 95;
        PHOTOS_LIBRARY_DTP_PHOTOSREF_KEY = 96;
        PHOTOS_3P_AMBIENT_PHOTOSREF_KEY = 253;
        PHOTOS_3P_PICKER_PHOTOSREF_KEY = 277;
        FBS_CONTACT_PHOTOSREF_KEY = 97;
        ARCHIVED_PROFILE_IMAGE_KEY = 191;
        ASSISTANT_MEDIA_UAR_KEY = 99;
        GMAIL_ADS_FE_PROXY_KEY = 100;
        ONEPICK_DRIVE_GUESSABLE_KEY = 230;
        ONEPICK_PHOTOS_GUESSABLE_KEY = 242;
        ONEPICK_PHOTOSREF_KEY = 101;
        ONEPICK_PROXY_KEY = 182;
        ASSISTANT_PHOTOS_MEMORIES_PHOTOSREF_KEY = 102;
        BLOGGER_GUESSABLE_PHOTOSREF_KEY = 103;
        BLOGGER_IMAGE_SERVER_PHOTOSREF_KEY = 104;
        CONTRIB_SERVICE_BLOGGER_MEDIA_KEY = 380;
        GEO_MAPS_TIMELINE_PHOTOSREF_KEY = 105;
        DYNAMITE_CUSTOM_EMOJIS_DATAREF_KEY = 106;
        ASSISTANT_PHOTOS_PHOTOSREF_KEY = 107;
        CHROME_NTP_PHOTOSREF_KEY = 108;
        DYNAMITE_IMAGE_ATTACHMENT_DATAREF_KEY = 109;
        CLOUDSEARCH_3P_DRIVE_KEY = 110;
        CLASSROOM_COURSE_THEMES_PHOTOS_KEY = 111;
        DYNAMITE_PROXY_KEY = 114;
        CALENDAR_FEAPI_PROXY_KEY = 115;
        PEOPLE_CONTACTS_AVATAR_KEY = 116;
        GEO_DISCOVERY_PHOTOSREF_KEY = 117;
        GMAIL_PROMO_PROXY_KEY = 118;
        CHROMECAST_PRIVATE_PHOTOSREF_KEY = 119;
        GEO_OFFERS_DEAL_IMAGE_KEY = 120;
        BASEMAP_PHOTOPINS_PHOTOSREF_KEY = 121;
        GEO_MAPS_TIMELINE_EMAIL_PHOTOSREF_KEY = 122;
        DATA_STUDIO_PROXY_KEY = 123;
        PHOTOS_BEYOND_PLAYGROUND_PHOTOSREF_KEY = 124;
        BLOGGER_IMAGE_SERVER_PROXY_KEY = 125;
        SPUR = 127;
        SHOEBOX_DEFAULT_KEY = 135;
        SEARCH_ENGAGEMENT_HIGHLIGHT_SHOEBOX_KEY = 136;
        CHROME_OS_PHOTOSREF_KEY = 137;
        DASHER_SECURE_DATA_MONOGRAM_KEY = 138;
        TOWNSQUARE_PROXY_KEY = 139;
        SEARCH_PHOTOPINS_GUESSABLE_KEY = 140;
        PHOTOS_ALBUM_ARCHIVE_PHOTOSREF_KEY = 142;
        PHOTOS_LEGAL_EXPORTS_TAKEOUT_GUESSABLE_PHOTOSREF_KEY = 214;
        PHOTOS_WEB_DOWNLOADS_TAKEOUT_GUESSABLE_PHOTOSREF_KEY = 215;
        PHOTOS_CONSUMER_TAKEOUT_GUESSABLE_PHOTOSREF_KEY = 216;
        GOOGLE_ACCOUNT_PHOTOSREF_KEY = 143;
        GMAIL_IMAGE_ATTACHMENTS_DATAREF_KEY = 145;
        GMAIL_API_IMAGE_ATTACHMENTS_DATAREF_KEY = 365;
        GMAIL_EXTERNAL_IMAGE_PROXY_KEY = 193;
        GMAIL_EXTERNAL_IMAGE_PROXY_STABLE_KEY = 257;
        GEO_PHOTO_UPLOADER_PHOTOSREF_KEY = 146;
        GEO_PLATFORM_ADAPTERS_GUESSABLE_PHOTOSREF_KEY = 148;
        GOOGLE_PHOTOS_WEB_ABUSE_TAKEDOWN_URL_PHOTOSREF_KEY = 150;
        CULTURAL_INSTITUTE_SHOEBOX_KEY = 153;
        PLAY_GAMES_SERVICES_PHOTOSREF_KEY = 154;
        ROHAN_WATCHFACE_PHOTOSREF_KEY = 155;
        SERVICES_IMMERSIVE_DESKTOP_COVER_PHOTO_PHOTOSREF_KEY = 171;
        SERVICES_IMMERSIVE_LIST_IMAGE_CAROUSEL_PHOTOSREF_KEY = 172 [deprecated = true];
        SERVICES_IMMERSIVE_ORGANIC_PROFILE_PHOTO_CAROUSEL_PHOTOSREF_KEY = 173;
        SERVICES_IMMERSIVE_JUSTIFICATION_ICONS_PHOTOSREF_KEY = 174;
        SHOPPING_ONSEARCH_MONOGRAM_KEY = 161;
        BLOGGER_SHOEBOX_KEY = 164;
        BROWSE_TO_DECIDE_MAP_PHOTOPINS_GUESSABLE_KEY = 165;
        TRAVEL_UBERVERSAL_SHOEBOX_KEY = 167;
        COMMERCE_GBP_PHOTOS_MIGRATION_GUESSABLE_PHOTOSREF_KEY = 177;
        GPAY_MANDATES_MONOGRAM_KEY = 180;
        PLAY_ADS_PROXY_KEY = 181;
        GEO_MADDEN_SHOEBOX_KEY = 184;
        PHOTOS_ANDROID_MEDIA_ITEM_SECURE_PHOTOSREF_KEY = 185;
        GSUITE_ADDONS_PROXY_KEY = 186;
        DRIVE_VIEWER_KEY = 187;
        HINDSIGHT_FC_KEY = 196;
        MEETINGS_MONOGRAM_VISUAL_KEY = 199;
        HINDSIGHT_FC_PROXY_KEY = 203;
        YOUTUBE_VIA_AVATAR_KEY = 204;
        YOUTUBE_PODCASTS_INGESTION_PROXY_KEY = 207;
        CONTRIB_SERVICE_PHOTOS_SAMPLE_CLIENT_KEY = 208;
        MERCHANT_CENTER_PROXY_KEY = 210;
        MERCHANT_IDENTITY_KEY = 256;
        GEOMP_LERNA_CLIENT_KEY = 211;
        PHOTOS_PROJECT_ELLMANN_CLIENT_KEY = 213;
        UCP_CONTENT_SERVER_SHOEBOX_KEY = 218;
        BARD_IMAGE_PROXY_KEY = 221;
        ACEP_PLATFORM_MONOGRAM_KEY = 222;
        LOCAL_REVIEWS_MONOGRAM_KEY = 228;
        GMAIL_PROMO_SHOEBOX_KEY = 231;
        OBAKE_PHOTOSREF_KEY = 232;
        GRASS_PROXY_KEY = 233;
        GRASS_PHOTOSREF_KEY = 234;
        GRASS_CS_SECURE_KEY = 327;
        GRASS_CS_GUESSABLE_KEY = 328;
        VAULT_DRIVE_KEY = 235;
        GPAY_ACTOR_PROFILE_MONOGRAM_KEY = 236;
        YOUTUBE_STUDIO_PODCAST_PROXY_KEY = 239;
        LENS_BACKEND_GUESSABLE_KEY = 243;
        PRIVATE_WEB_APPS_MONOGRAM_KEY = 248;
        WALLET_CARD_ART_PROXY_KEY = 251;
        CONTRIB_SERVICE_YOUTUBE_AI_FEEDBACK_KEY = 252;
        AIXI_GUESSABLE_KEY = 258;
        MADDEN_PROXY_KEY = 259;
        PAST_PROFILE_PHOTOS = 289;
        EPHEMERAL_PHOTOS = 337;
        FOOSTOCK_IMAGE_PROXY_KEY = 292;
        DRIVE_USERCONTENT_KEY = 294;
        CONTACT_PHOTOS = 303;
        CONTRIB_SERVICE_YT_SHOPPING_MERCHANT_KEY = 330;
        CONTRIB_SERVICE_YT_SHOPPING_MERCHANT_QUAL_KEY = 332;
        CONTRIB_SERVICE_CASA_VISUAL_SEARCH_KEY = 339;
        ASK_PHOTOS_KEY = 340;
        LOCAL_CAT_AND_NAV_PREWARM_KEY = 343;
        LOCAL_CAT_MERCHANT_PHOTOS_KEY = 379;
        SGBE_ABUSE_PHOTOS = 345;
        SEARCH_EVAL_AUTORATER_KEY = 350;
        BLOB_TOKEN_DOWNLOAD = 355;
        MAPS_JS_API_CS_GUESSABLE_KEY = 364;
        EARTH_CS_GUESSABLE_KEY = 368;
        BACKGROUND_CONTACT_PHOTOS = 387;
        BACKGROUND_PROFILE_PHOTOS = 375;
        CONTRIB_SERVICE_STREETVIEW_RAP_MEDIA_KEY = 377;
        CONTRIB_SERVICE_MOMA_PROFILE_PHOTOS_KEY = 381;
        SV_CS_GUESSABLE_KEY = 383;
        PHOTOS_MAGIC_EDITOR_DROPPER_GUESSABLE_KEY = 393;
        CONTRIB_SERVICE_GRDT_KEY = 395;
        CONTRIB_SERVICE_GRDT_QUAL_KEY = 405;
        MARKETPLACE_SDK_STORE_LISTING_KEY = 398;
        CONTRIB_SERVICE_CS_PLAYGROUND_KEY = 399;
        CONTRIB_SERVICE_SEARCH_CREATORPROFILE_KEY = 400;
        CONTRIB_SERVICE_SEARCH_CREATORPROFILE_QUAL_KEY = 401;
        ENZO_PROXY_KEY = 402;
        CONTRIB_SERVICE_WALLET_CARDCENTRIC_QUAL_KEY = 403;
        CONTRIB_SERVICE_COURSE_THEMES_KEY = 404;
        CONTRIB_SERVICE_SHOPPING_WARDROBE_KEY = 406;
        CONTRIB_SERVICE_SHOPPING_WARDROBE_QUAL_KEY = 407;
        CONTRIB_SERVICE_ADSSUPPORTAUTOMATION_KEY = 408;
        CONTRIB_SERVICE_ADSSUPPORTAUTOMATION_QUAL_KEY = 409;
        CONTRIB_SERVICE_CREATIVE_STUDIO_KEY = 410;
        CONTRIB_SERVICE_CS_PLAYGROUND_QUAL_KEY = 411;
        CONTRIB_SERVICE_CHALET_MM_SEARCH_KEY = 412;
        CONTRIB_SERVICE_PHOTOS_PREVIEWS_PUBLIC_NON_ROTATING_KEY = 415;
        CONTRIB_SERVICE_ATELIER_KEY = 416;
        CONTRIB_SERVICE_ATELIER_QUAL_KEY = 417;
        PHOTOS_DOWNLOADS_SERVER_GUESSABLE_KEY = 418;
        CONTRIB_SERVICE_STREETVIEW_RAP_MEDIA_QUAL_KEY = 419;
        CORTO_SIGNATURE_IMAGE_URL_KEY = 432;
        CONTRIB_SERVICE_ABUSE_GENAI_KEY = 433;
        CONTRIB_SERVICE_ABUSE_GENAI_QUAL_KEY = 434;
        PHOTOS_GENMEDIA_DATAREF_KEY = 435;
        CONTRIB_SERVICE_GHD_KEY = 436;
        CONTRIB_SERVICE_GHD_QUAL_KEY = 437;
        CONTRIB_SERVICE_GOOGLE_DAM_PUBLIC_NON_ROTATING_KEY = 444;
        BEYOND_FILE_PROCESSING_SERVICE_GUESSABLE_PHOTOSREF_KEY = 445;
        RWJ_PARTNER_LIVE_QUERY_PROXY_KEY = 446;
        GOOGLE_TV_PHOTOS_SEARCH_PHOTOSREF_KEY = 447;
        CONTRIB_SERVICE_POLICY_STUDIO_KEY = 451;
        CONTRIB_SERVICE_PLAY_GAMES_PLAYGROUND_KEY = 452;
        CONTRIB_SERVICE_PLAY_GAMES_PLAYGROUND_QUAL_KEY = 453;
        CONTRIB_SERVICE_DATAMINER_KEY = 454;
        PHOTOS_ELLMANN_WARDROBE_PHOTOSREF_KEY = 455;
        CONTRIB_SERVICE_LABS_COSCIENTIST_KEY = 456;
        CONTRIB_SERVICE_LABS_COSCIENTIST_QUAL_KEY = 457;
        CONTRIB_SERVICE_FP_GAIA_SEARCH_KEY = 458;
        CONTRIB_SERVICE_FP_GAIA_SEARCH_QUAL_KEY = 459;
        CONTRIB_SERVICE_BUSINESS_VIDEOS_KEY = 460;
        CONTRIB_SERVICE_FITBIT_FILE_MANAGER_KEY = 461;
        PHOTOS_PRINTING_WEBSTORE_PHOTOSREF_KEY = 462;
        CONTRIB_SERVICE_AIMODE_SHARE_KEY = 463;
        CONTRIB_SERVICE_AIMODE_SHARE_QUAL_KEY = 464;
        CONTRIB_SERVICE_LOTUS_KEY = 465;
        CONTRIB_SERVICE_LOTUS_QUAL_KEY = 466;
        PHOTOS_EDITING_TOOLS_DATAREF_KEY = 467;
        AIM_AGENTIC_ECOSYSTEM_PROXY_KEY = 468;
        YOUTUBE_FANTASY_SPORTS_KEY = 469;
        WALLET_WEB_PROXY_KEY = 471;
        CONTRIB_SERVICE_FITBIT_FILE_MANAGER_QUAL_KEY = 472;
        CONTRIB_SERVICE_ADS_ADVISOR_KEY = 474;
        CONTRIB_SERVICE_ADS_ADVISOR_QUAL_KEY = 475;
        PHOTOS_STORYTELLING_GENMEDIA_EXTERNAL_PHOTOSREF_KEY = 476;
        CONTRIB_SERVICE_SEARCH_SHARE_KEY = 477;
        SPORTS_LIVE_ANALYST_PROXY_KEY = 478;
    }
}

message ClientType {
    enum Code {
        UNKNOWN_CLIENT = 0;
        UNKNOWN_CLIENT_RPC = 1;
        FIFE_CLIENT = 17;
        FIFE_CLIENT_GMAIL = 20;
        FIFE_CLIENT_ABUSE_PROD = 66;
        FIFE_CLIENT_VISUAL_SEARCH = 67;
        FIFE_CLIENT_ABUSE_STAGING = 68;
        FIFE_CLIENT_PHOTOS_BATCH = 69;
        FIFE_CLIENT_PHOTOS_SEARCH_PEOPLE = 70;
        FIFE_CLIENT_TRIX = 71;
        FIFE_CLIENT_GAIA_ACCOUNT_NOTIFIER = 72;
        FIFE_CLIENT_CHANGELING = 73;
        FIFE_CLIENT_CHANGELING_WORKER_DEFAULT = 301;
        FIFE_CLIENT_CHANGELING_WORKER_QDOM = 302;
        FIFE_CLIENT_CHANGELING_WORKER_RITZ = 303;
        FIFE_CLIENT_CHANGELING_WORKER_TRIX = 304;
        FIFE_CLIENT_CHANGELING_WORKER_ASPOSE = 385;
        FIFE_CLIENT_CULTURAL_THUMBNAILER = 641;
        FIFE_CLIENT_SOCIAL_FRONTEND = 75;
        FIFE_CLIENT_MOMA_TEAMS_PHOTOS_FRONTEND_HTTP = 562;
        OAUTH2_GOOGLE_PHOTOS_ANDROID = 257;
        OAUTH2_GOOGLE_PHOTOS_IOS = 258;
        OAUTH2_GOOGLE_PLUS_ANDROID = 259;
        OAUTH2_GOOGLE_PLUS_IOS = 260;
        OAUTH2_GOOGLE_DRIVE_ANDROID = 261;
        OAUTH2_GOOGLE_DRIVE_IOS = 262;
        OAUTH2_BIGTOP = 263;
        OAUTH2_GOOGLE_DOCS_IOS = 264;
        OAUTH2_GOOGLE_CHROME = 265;
        OAUTH2_GOOGLE_SHEETS_IOS = 266;
        OAUTH2_YOUTUBE_GAMING = 267;
        OAUTH2_GOOGLE_SLIDES_IOS = 268;
        OAUTH2_CHROMECAST = 269;
        OAUTH2_CLASSROOM = 270;
        OAUTH2_GMAIL_IOS = 272;
        OAUTH2_GOOGLE_KEEP = 276;
        OAUTH2_GOOGLE_MAPS_MOBILE = 358;
        OAUTH2_FAMILY_LINK = 359;
        OAUTH2_GOOGLE_DRIVE_FS = 427;
        OAUTH2_GOOGLE_CALENDAR = 429;
        OAUTH2_GOOGLE_DYNAMITE = 431;
        SHOEBOX_ADS_APP_METADATA = 605;
        SHOEBOX_ADS_APP_PROMOTION = 80;
        SHOEBOX_CHROME_EXTENSION = 79;
        SHOEBOX_FINSKY_TEST = 78;
        SHOEBOX_FINSKY_VIDEO = 81;
        SHOEBOX_SKYJAM_INGESTION = 82;
        SHOEBOX_SOCIAL_MAGAZINES = 83;
        SHOEBOX_CULTURAL_IMAX = 84;
        SHOEBOX_YOUTUBE_BACKSTAGE = 606;
        SHOEBOX_YOUTUBE_CHANNELS = 607;
        SHOEBOX_YOUTUBE_HOUSE_CHANNELS = 85;
        SHOEBOX_YOUTUBE_MUSIC_CORPUS = 608;
        SHOEBOX_YOUTUBE_TV_SERVICE = 609;
        SHOEBOX_APPENGINE = 706;
        SHOEBOX_RESERVED_86 = 86;
        SHOEBOX_RESERVED_87 = 87;
        SHOEBOX_SIDEKICK = 88;
        SHOEBOX_RESERVED_89 = 89;
        SHOEBOX_RESERVED_90 = 90;
        SHOEBOX_CULTURAL = 564;
        SHOEBOX_ADS_TRAVEL = 92;
        SHOEBOX_SKYJAM = 93;
        SHOEBOX_RESERVED_94 = 94;
        SHOEBOX_SJAP = 95;
        SHOEBOX_S_GOOGLE_COM_DOODLE_CANNON = 96;
        SHOEBOX_RESERVED_97 = 97;
        SHOEBOX_FINSKY_CHINA_PUBLISHER = 398;
        SHOEBOX_SOCIAL_COLLEXIONS_BATCH_JOBS = 399;
        SHOEBOX_MAPS_PERSONALISATION = 400;
        SHOEBOX_RESERVED_401 = 401;
        SHOEBOX_SEARCH_ENGAGEMENT_HIGHLIGHT = 402;
        SHOEBOX_ARTPROJECT = 403;
        SHOEBOX_SIGHTLI = 433;
        SHOEBOX_ANDROID_VIDEO_INGESTION = 610;
        SHOEBOX_VIDEO_MEDIA_INGESTION = 611;
        SHOEBOX_PLAY_TRIDENT_DATA = 612;
        SHOEBOX_B_TRILL_V8G3T = 613;
        SHOEBOX_S_KINTARO_CONTENT_SERVER = 614;
        SHOEBOX_RESERVED_615 = 615;
        SHOEBOX_RESERVED_616 = 616;
        SHOEBOX_CONNECT_SALES_SEARCH_KNOWLEDGE = 740;
        SHOEBOX_GMAIL_THEMEDIALOG = 886;
        SHOEBOX_KIDS_API_SHOEBOX = 932;
        SHOEBOX_UCP_CONTENT_SERVER = 970;
        SOCIAL_PROFILE_PHOTOS = 4;
        TAKEOUT_HANGOUTS = 690;
        SHOEBOX_I18N_SHAREDIMAGE = 1050;
        ABUSE_PROXY = 114;
        ADELPHI_PROXY = 111;
        ADS = 47;
        ADS_REFERED = 466;
        ADS_DDM_PROXY = 287;
        CONTENT_ADS_PROXY = 342;
        ENZO_PROXY = 1134;
        ALLO_CONTENT_DECORATION_PROXY = 341;
        ALLO_CONTENT_WIZARD_PROXY = 305;
        ANDROID_DIALER = 22;
        ANDROID_HANGOUTS = 23;
        ANDROID_PAY_PROXY = 209;
        ANDROID_PLAY_ENTERTAINMENT_PROXY = 339;
        ANDROID_TV_SEARCH_PROXY = 212;
        ANDROID_TV_CHANNELS_PROXY = 593;
        ANDROIDONE_TAILORMADE = 56;
        APIARY = 18;
        ARCHIVED_PROFILE_IMAGE = 930;
        ARCHIVED_PROFILE_IMAGE_DAT = 1080;
        SGBE_PHOTOS_MIGRATION_STORAGE_PHOTOS_BE = 1082;
        SGBE_PHOTOS_MIGRATION_STORAGE_SGBE = 1083;
        ARKADIA_DINNERF_GUESSABLE = 1041;
        ASK_PHOTOS = 1081;
        ASSISTANT_3P_PROXY = 348;
        ASSISTANT_SE_PROXY = 390;
        ASSISTANT_MEALS_PROXY = 437;
        ASSISTANT_MEDIA_PROXY = 395;
        ASSISTANT_MEDIA_UAR = 695;
        ASSISTANT_PERSONAL_PHOTOS_SERVICE = 408;
        ASSISTANT_PERSONAL_PHOTOS_SERVICE_SECURE = 748;
        ASSISTANT_PERSONAL_PHOTOS_SERVICE_SECURE_LEGACY_CLIENTS = 749;
        ASSISTANT_PHOTOS_MEMORIES = 698;
        ASSISTANT_SERVER = 284;
        ASSISTANT_SERVER_SECURE = 746;
        ASSISTANT_SERVER_SECURE_LEGACY_CLIENTS = 747;
        ATARI_EDITOR_PROXY_SCARY = 1131;
        ATARI_EDITOR_PROXY_CORP = 1130;
        ATARI_EDITOR_PROXY = 1129;
        ATARI_EDITOR_SCARY = 642;
        ATARI_EDITOR_CORP = 643;
        ATARI_EDITOR = 28;
        ATARI_VIEWER = 29;
        ATARI_VIEWER_PROXY = 1128;
        ATARI_DRIVE = 719;
        ATARI_DRIVE_SCARY = 1000;
        ATARI_DRIVE_CORP = 1001;
        ATARI_LYNX_DRIVE = 743;
        ATARI_LYNX_DRIVE_SCARY = 1002;
        ATARI_LYNX_DRIVE_CORP = 1003;
        BEYOND_FILE_PROCESSING_SERVICE = 1157;
        BASEMAP_PHOTOPINS = 722;
        BLOGGER = 3;
        BLOGGER_HOST = 453;
        BLOGGER_IMAGE = 704;
        BLOGGER_IMAGE_PROXY = 727;
        BLOGGER_SHOEBOX = 892;
        BLOGGER_VISTAAR_MIGRATION = 677;
        BLOGGER_GUESSABLE = 699;
        BLOGSPOT = 2;
        BLOGGER_REFERRED = 360;
        BLOGSPOT_FACEPILE_PROXY = 345;
        BLOGSPOT_PROXY = 211;
        BROWSE_TO_DECIDE_MAP_PHOTOPINS = 893;
        BUGANIZER_PROXY = 563;
        CALENDAR = 100;
        CALENDAR_FEAPI_PROXY = 713;
        CHANGELING = 545;
        CHIME_PROXY = 340;
        CHROME_NTP = 708;
        CHROME_OS = 754;
        CHROME_STORE = 46;
        CHROMECAST = 41;
        CHROMECAST_PROXY = 108;
        CHROMECAST_PRIVATE = 498;
        CHROMECAST_PRIVATE_SECURE = 724;
        CHROMECAST_PRIVATE_TEST = 601;
        SHOEBOX_CHROMECAST_PUBLIC = 701;
        CHROMECAST_PRIVATE_SECURE_DAT = 739;
        CHROMECAST_PRIVATE_SETTINGS_SECURE = 751;
        CHROMECAST_PRIVATE_SETTINGS_SECURE_DAT = 752;
        CHROMECAST_PRIVATE_CURATED_PHOTO_SECURE_DAT = 881;
        CINEMATIC_MEMORIES = 638;
        CLASSROOM_COURSE_THEMES = 710;
        CLASSROOM_THUMBNAILS = 500;
        CLOUDCAST_CAPTURE = 436;
        CLOUDCAST_CAPTURE_MOBILE = 501;
        CLOUDCAST_CAPTURE_DEV = 728;
        CLOUDCAST_CAPTURE_DEV_MOBILE = 729;
        CLOUDCAST_CAPTURE_AUTOPUSH = 679;
        CLOUDCAST_CAPTURE_AUTOPUSH_MOBILE = 685;
        CLOUDCAST_CAPTURE_STAGING = 731;
        CLOUDCAST_CAPTURE_STAGING_MOBILE = 732;
        CLOUDCAST_CAPTURE_PREPROD = 733;
        CLOUDCAST_CAPTURE_PREPROD_MOBILE = 734;
        CLOUDSEARCH_3P = 709;
        CONTACT_PHOTOS = 1063;
        CONTRIB_SERVICE_AI_SANDBOX = 1076;
        CONTRIB_SERVICE_AIDA_CODEFX = 1113;
        CONTRIB_SERVICE_AIDA_CODEFX_PUBLIC_NON_ROTATING = 1121;
        CONTRIB_SERVICE_AREA120_NOEB = 926;
        CONTRIB_SERVICE_AREA120_SPLASH = 927;
        CONTRIB_SERVICE_ASTRA = 1090;
        CONTRIB_SERVICE_BAD_HARVEST = 960;
        CONTRIB_SERVICE_BARD_STORAGE = 976;
        CONTRIB_SERVICE_BARD_STORAGE_NO_CORP = 1148;
        CONTRIB_SERVICE_BARD_STORAGE_EVAL = 1057;
        CONTRIB_SERVICE_BARD_STORAGE_EVAL_CORS_DEGRADED = 1136;
        CONTRIB_SERVICE_BARD_STORAGE_PUBLIC_NON_ROTATING = 1020;
        CONTRIB_SERVICE_BARD_STORAGE_CONTENT_PLATFORM = 1192;
        CONTRIB_SERVICE_BLOGGER_MEDIA = 1115;
        CONTRIB_SERVICE_CASA_VISUAL_SEARCH = 1079;
        CONTRIB_SERVICE_CROWDSOURCE_MEDIA = 1117;
        CONTRIB_SERVICE_LENS_HISTORY = 1060;
        CONTRIB_SERVICE_COLLECTIONS = 941;
        CONTRIB_SERVICE_FITBIT_P11_KEY = 1039;
        CONTRIB_SERVICE_FLYBY = 1055;
        CONTRIB_SERVICE_FLYBY_PUBLIC_NON_ROTATING = 1047;
        CONTRIB_SERVICE_GEO_CONTRIBUTION_SERVICE = 1022;
        CONTRIB_SERVICE_GEO_CONTRIBUTION_SERVICE_ORION = 1193;
        CONTRIB_SERVICE_GEO_CONTRIBUTION_SERVICE_CYGNUS = 1194;
        CONTRIB_SERVICE_GEO_PLACES_API = 1087;
        CONTRIB_SERVICE_GOOGLE_TV = 1056;
        CONTRIB_SERVICE_GPS_GENERATIONS = 1035;
        CONTRIB_SERVICE_ILLUMINATE = 1123;
        CONTRIB_SERVICE_JULES = 1143;
        CONTRIB_SERVICE_KARTO = 1101;
        CONTRIB_SERVICE_LABS_DELAWARE_MEDIA = 1043;
        CONTRIB_SERVICE_LTLJ_CHAT_HISTORY = 1103;
        CONTRIB_SERVICE_PIXEL_MERLIN = 1018;
        CONTRIB_SERVICE_PLAY_GAMES_SERVICES = 1007;
        CONTRIB_SERVICE_PLAY_STORE_REVIEWS = 1048;
        CONTRIB_SERVICE_PLAY_STORE_REVIEWS_PUBLIC_NON_ROTATING = 1078;
        CONTRIB_SERVICE_PODIUM_PLAYGROUND = 1040;
        CONTRIB_SERVICE_METAL = 901;
        CONTRIB_SERVICE_METAL_PUBLIC_NON_ROTATING = 981;
        CONTRIB_SERVICE_MOMA_PROFILE_PHOTOS = 1116;
        CONTRIB_SERVICE_NOTEBOOKLM = 1045;
        CONTRIB_SERVICE_RECEIPTS = 1014;
        CONTRIB_SERVICE_GRDT = 1125;
        CONTRIB_SERVICE_REGIONAL = 1107;
        CONTRIB_SERVICE_ROAM = 925;
        CONTRIB_SERVICE_RSVP_FILES = 1015;
        CONTRIB_SERVICE_SAMPLE_CLIENT = 956;
        CONTRIB_SERVICE_SEARCH_BOBA_MEDIA = 977;
        CONTRIB_SERVICE_SEARCH_BOBA_MEDIA_PUBLIC_NON_ROTATING = 1046;
        CONTRIB_SERVICE_SEARCH_FEEDBACK = 1019;
        CONTRIB_SERVICE_SEARCH_HAMSA_MEDIA = 1070;
        CONTRIB_SERVICE_SHOPSTREAM = 1051;
        CONTRIB_SERVICE_STREETVIEW_RAP_MEDIA = 1111;
        CONTRIB_SERVICE_STREETVIEW_RAP_MEDIA_QUAL = 1147;
        CONTRIB_SERVICE_UPDRAFT = 1029;
        CONTRIB_SERVICE_UPDRAFT_PUBLIC_NON_ROTATING = 1030;
        CONTRIB_SERVICE_WALLET_CARDCENTRIC = 1126;
        CONTRIB_SERVICE_WALLET_VALUABLES = 1109;
        CONTRIB_SERVICE_WAYMO_SIMHUB = 1059;
        CONTRIB_SERVICE_WORKSPACE_GEN_AI = 1042;
        CONTRIB_SERVICE_YOUTUBE_AI_FEEDBACK = 1027;
        CONTRIB_SERVICE_YT_SHOPPING_MERCHANT = 1071;
        CONTRIB_SERVICE_GEO_PHOTO_UPLOADER = 1093;
        COMMERCE_GBP_PHOTOS_MIGRATION = 899;
        CORP_COMMAND_LINE_TOOL = 285;
        CRASSUS_PROXY = 405;
        CROWDSOURCE = 404;
        CROWDSOURCE_PERSONAL = 468;
        CROWDSOURCE_BEYOND = 978;
        CSE_PROXY = 543;
        CULTURAL_PROXY = 91;
        CULTURAL_EVENT_PROXY = 631;
        CULTURAL_INSTITUTE = 877;
        CULTURAL_INSTITUTE_ARTPROJECT = 922;
        CULTURAL_INSTITUTE_IMAX = 923;
        CULTURAL_INSTITUTE_STUDIO = 1108;
        DASHER_SECURE_DATA_MONOGRAM = 753;
        DASHER_UNIFIED_APPS_MONOGRAM = 660;
        DATA_STUDIO_PROXY = 365;
        KIX_DECOUPLED_DOCS = 362;
        KIX_DRIVE_DECOUPLED_DOCS = 556;
        PUNCH_DECOUPLED_DOCS = 363;
        PUNCH_DRIVE_DECOUPLED_DOCS = 557;
        RITZ_DECOUPLED_DOCS = 364;
        RITZ_DRIVE_DECOUPLED_DOCS = 558;
        SKETCHY_DECOUPLED_DOCS = 394;
        SKETCHY_DRIVE_DECOUPLED_DOCS = 559;
        DEPRECATED_AVATAR = 116;
        DEPRECATED_FALLBACK_AVATAR = 255;
        DEFAULT_AVATAR = 384;
        DISCOVER_PROXY = 587;
        DOCS_EXPLORE_PREVIEW_PROXY = 295;
        DOCS_LINK_PREVIEWS_PROXY = 451;
        DOCS_URL_BACKED_IMAGES_PROXY = 636;
        DOCS_URL_BACKED_IMAGES_PROXY_CORP = 933;
        DOCS_URL_BACKED_IMAGES_PROXY_SCARY = 934;
        DOCS_URL_PROXY = 958;
        DRIVE = 24;
        DRIVE_EXPLORER = 952;
        DRIVE_GENOA = 953;
        DRIVE_STORAGE_SERVER = 954;
        DRIVE_STORAGE_SERVER_CROSS_ORIGIN_RESOURCE = 1120;
        DRIVE_REFERED = 461;
        DRIVE_USERCONTENT = 1054;
        DRX_VIDEO_PROXY = 432;
        DYNAMITE = 245;
        DYNAMITE_CUSTOM_EMOJIS = 703;
        DYNAMITE_PROXY = 452;
        DYNAMITE_ROOM_AVATARS = 544;
        DYNAMITE_DATAREF = 711;
        DYNAMITE_SECUREURL_PROXY = 712;
        EXPRESS = 107;
        FOCUS_BACKEND = 356;
        FBS_PRIVATE_LEGACY = 414;
        FBS_PUBLIC_LEGACY = 415;
        FBS_PRIVATE = 416;
        FBS_PUBLIC = 417;
        FBS_MONOGRAM = 418;
        FBS_DEFAULT = 419;
        FBS_ADMIN = 897;
        FBS_CONTACT_PHOTO_CORP_HEADERS = 984;
        FBS_CORP_HEADERS = 979;
        FBS_SURESHOT_PRIVATE_LEGACY = 420;
        FBS_SURESHOT_PUBLIC_LEGACY = 421;
        FBS_SURESHOT_PRIVATE = 422;
        FBS_SURESHOT_PUBLIC = 423;
        FBS_SURESHOT_MONOGRAM = 424;
        FBS_SURESHOT_DEFAULT = 425;
        FBS_CONTACT_PHOTO = 693;
        FIFE_INTERNAL = 15;
        FIFE_RPC_LOG = 357;
        FIFE_FOR_GWS = 16;
        FIFE_INTEGRATION_TEST = 499;
        FIFE_PRIVACY_TEST = 49;
        FIFE_CONTENT_DATA_PROBER = 288;
        FIFE_PROBER_PROXY = 289;
        FIFE_AUTH_REJECTED = 290;
        FLIX_SCARY = 967;
        FLIX_CORP = 968;
        FLIX = 969;
        PIX_SCARY = 1159;
        PIX_CORP = 1160;
        PIX = 1161;
        FLIX_DRIVE = 965;
        FLIX_DRIVE_SCARY = 996;
        FLIX_DRIVE_CORP = 997;
        FREEBIRD_SCARY = 644;
        FREEBIRD_CORP = 645;
        FREEBIRD = 33;
        FREEBIRD_DRIVE = 671;
        FREEBIRD_DRIVE_SCARY = 994;
        FREEBIRD_DRIVE_CORP = 995;
        FREEBIRD_REFERED = 464;
        FOOD_ORDERING_PROXY = 389;
        FOOSTOCK_IMAGE_PROXY = 1053;
        FUZZING_FIFE = 957;
        GAIA_FRONTEND = 469;
        GBOARD = 102;
        GEO_DISCOVERY = 717;
        GEO_EARTH_STUDIO_PROXY = 350;
        GEO_HCE_ROUTER = 1058;
        GEO_OFFERS_DEAL_IMAGE = 721;
        GEO_PHOTO_SERVICE = 98;
        GEO_PHOTO_SERVICE_DEFAULT_CACHE = 104;
        GEO_PHOTO_SERVICE_INTERNET_PHOTOS = 105;
        GEO_PHOTO_SERVICE_PHOTOSREF_SECURE = 878;
        GEO_PHOTO_SERVICE_PROXY_SECURE = 879;
        GEO_PHOTO_SERVICE_GUESSABLE = 945;
        GEO_PHOTO_SERVICE_CS_SECURE = 1061;
        GEO_PHOTO_SERVICE_CS_GUESSABLE = 1062;
        GEO_PHOTO_SERVICE_CS_GUESSABLE_STALE = 1119;
        GEO_PHOTO_SIGNAL_SERVICE_CS_SECURE = 1075;
        GEO_PHOTO_METADATA_SERVICE_GUESSABLE = 946;
        GEO_PHOTO_METADATA_SERVICE_CS_SECURE = 1066;
        GEO_PHOTO_METADATA_SERVICE_CS_GUESSABLE = 1067;
        GEO_PHOTO_METADATA_SERVICE_CS_SECURE_LONG_TTL = 1092;
        GEO_PHOTO_VENUS = 634;
        GEO_PHOTO_VENUS_CS_SECURE = 1141;
        GEO_PHOTO_VENUS_CS_SECURE_STALE = 1142;
        GEO_PHOTO_VENUS_CS_LONG_TTL_SECURE = 1091;
        GEO_PLATFORM_ADAPTERS = 875;
        GEO_MAPS_TAXI_PROXY = 352;
        GEO_MAPS_TIMELINE_WEB = 583;
        GEO_MAPS_TIMELINE_IOS = 584;
        GEO_MAPS_TIMELINE_ANDROID = 585;
        GEO_MAPS_TIMELINE_SECURE = 700;
        GEO_MAPS_TIMELINE_EMAIL_SECURE = 723;
        GEO_MAPS_UGC_BULK_PHOTO_UPLOAD_WEB = 598;
        GEO_MAPS_UGC_BULK_PHOTO_UPLOAD_IOS = 599;
        GEO_MAPS_UGC_BULK_PHOTO_UPLOAD_ANDROID = 600;
        GEO_MAPS_UGC_BULK_PHOTO_UPLOAD_WEB_SECURE = 889;
        GEO_MAPS_UGC_BULK_PHOTO_UPLOAD_IOS_SECURE = 890;
        GEO_MAPS_UGC_BULK_PHOTO_UPLOAD_ANDROID_SECURE = 891;
        GEO_UGC_GUESSABLE = 678;
        GEO_UGC_CS_SECURE = 1064;
        GEO_UGC_CS_GUESSABLE = 1065;
        GEO_UGC_IMPACT_EMAIL_GUESSABLE = 741;
        GEO_UGC_TAKEDOWN_EMAIL_GUESSABLE = 760;
        GEO_MAPS_SCHEMATIC_MAPS_PROXY = 409;
        GEO_MYMAPS_HOSTED = 118;
        GEO_MYMAPS_PROXY = 119;
        GEO_SOPRANO = 32;
        GEO_STREET_VIEW_PUBLISH = 620;
        GEO_LOCAL_SHOPPING_GMB = 659;
        GEO_LOCAL_SHOPPING_PROXY = 560;
        GEO_FOOD_GMB = 663;
        GOOGLE_MAPS_CRAWLED = 109;
        GOOGLE_MAPS_PROXIED = 110;
        GLASS_BACKEND = 374;
        GLOVEBOX_ABUSE_I_AM = 252;
        GMAIL = 6;
        GMAIL_DOC_PREVIEW = 900;
        GMAIL_DRIVE_IMAGE_URL_REPLACEMENT = 738;
        GMAIL_EXTERNAL_IMAGE_PROXY_SECURE = 935;
        GMAIL_EXTERNAL_IMAGE_PROXY_STABLE = 1032;
        GMAIL_IMAGE_ATTACHMENTS = 10;
        GMAIL_IMAGE_ATTACHMENTS_HOST = 455;
        GMAIL_IMAGE_ATTACHMENTS_LOCKER = 382;
        GMAIL_IMAGE_ATTACHMENTS_SECURE = 761;
        GMAIL_IMAGE_REPLACEMENT = 702;
        GMAIL_PHOTOS_THEME = 920;
        GMAIL_PROXY = 7;
        GMAIL_PROXY_HOST = 454;
        GMAIL_COB = 286;
        GMAIL_ADS_FE = 696;
        GMAIL_PROMO = 720;
        GMAIL_PROMO_PREVIEW = 983;
        GMS_AUTOMOD = 1072;
        GMS_FIREBOLT = 1073;
        GMS_FACTUAL_QUALITY = 1110;
        GPAY_CAMPUS_ID = 575;
        GPAY_MANDATES_MONOGRAM_AVATAR = 898;
        GPAY_MERCHANT_IMAGE = 666;
        GPAY_MOVIES_MICROAPP_PROXY = 580;
        GPAY_IMAGE_PROXY = 589;
        GPAY_VERTICALS_PROXY = 594;
        GPAY_ACTOR_PROFILE_MONOGRAM_AVATAR = 1006;
        GPLUS_ANDROID = 63;
        GPLUS_IOS = 64;
        GPLUS_WEB = 65;
        GPLUS_WEB_REFERED = 298;
        GPLUS_WEB_PROXY = 297;
        GPLUS_ENTITY_TRANSFER = 406;
        GPLUS_PHOTOS = 13;
        GPLUS_PHOTOS_SECURE = 667;
        GPLUS_PROXY_SECURE = 668;
        GPU_UNKNOWN_PHOTO_SOURCE = 764;
        GPU_GMM_ANDROID = 765;
        GPU_GMM_IOS = 766;
        GPU_TACTILE = 767;
        GPU_DRAGONFLY_API = 768;
        GPU_PHOTOSPHERE_IOS = 769;
        GPU_MAPS_ACTIVITY = 770;
        GPU_VIEWS = 771;
        GPU_FOODEYES = 772;
        GPU_GOCHISOPHOTO = 773;
        GPU_GSA_IOS = 774;
        GPU_STREET_VIEW_ANDROID = 775;
        GPU_STREET_VIEW_IOS = 776;
        GPU_LOCAL_UNIVERSAL_MOBILE = 777;
        GPU_LOCAL_UNIVERSAL_MOBILE_RAP = 778;
        GPU_LOCAL_UNIVERSAL_MOBILE_AAP = 779;
        GPU_LOCAL_UNIVERSAL_DESKTOP = 780;
        GPU_LOCAL_UNIVERSAL_RAP_ON_BOQ = 781;
        GPU_FOOTPRINT = 782;
        GPU_GMM_ANDROID_RAP = 783;
        GPU_GMM_ANDROID_AAP = 784;
        GPU_PHOTO_TRANSFER = 785;
        GPU_QUICKSILVER = 786;
        GPU_STREET_VIEW_PUBLISH_API = 787;
        GPU_STREET_VIEW_IMAGERY_MANAGEMENT_PLATFORM = 788;
        GPU_TEST_APP_ANDROID = 789;
        GPU_LOCAL_GUIDES_WEB_APP = 790;
        GPU_LEGACY_INNERSPACE = 791;
        GPU_LEGACY_PANORAMIO = 792;
        GPU_GMM_IOS_SHARE_EXTENSION_MEDIA_UPLOAD = 793;
        GPU_TEST_PROBER = 794;
        GPU_STREET_VIEW_DATA_EXTRACTION = 795;
        GPU_THINGS_TO_DO = 796;
        GPU_MAPS_LITE = 797;
        GPU_HOTELS_IMMERSIVE = 798;
        GPU_UGC_SERVICES = 799;
        GPU_KARTO = 800;
        GPU_GMM_ANDROID_PHOTO_POST = 801;
        GPU_GMM_IOS_PHOTO_POST = 802;
        GPU_TACTILE_PHOTO_POST = 1149;
        GPU_LOCAL_UNIVERSAL_DESKTOP_PHOTO_POST = 1150;
        GPU_LOCAL_UNIVERSAL_MOBILE_PHOTO_POST = 1151;
        GPU_GMM_ANDROID_REVIEW_POST = 803;
        GPU_GMM_IOS_REVIEW_POST = 804;
        GPU_LOCAL_GUIDES_WEB_APP_REVIEW_POST = 805;
        GPU_LOCAL_UNIVERSAL_DESKTOP_REVIEW_POST = 806;
        GPU_LOCAL_UNIVERSAL_MOBILE_REVIEW_POST = 807;
        GPU_TACTILE_REVIEW_POST = 808;
        GPU_HOTELS_IMMERSIVE_REVIEW_POST = 929;
        GPU_MAPS_LITE_REVIEW_POST = 936;
        GPU_THIRD_PARTY_REVIEWS_WIDGET_REVIEW_POST = 943;
        GPU_GMB_ANDROID = 809;
        GPU_GMB_IOS = 810;
        GPU_GMB_WEB = 811;
        GPU_GMBL = 812;
        GPU_GMB_API = 813;
        GPU_GMB_ASSISTANT_DUPLEX = 1146;
        GPU_FEET_ON_STREET = 1163;
        GPU_GMB_ON_GMM_ANDROID = 814;
        GPU_GMB_ON_GMM_IOS = 815;
        GPU_GMB_ON_TACTILE = 816;
        GPU_GMB_ON_LOCAL_UNIVERSAL_MOBILE = 817;
        GPU_GMB_ON_LOCAL_UNIVERSAL_DESKTOP = 818;
        GPU_MERCHANT_PANEL_ACTION_BAR = 819;
        GPU_MERCHANT_PANEL_TODO_LIST = 820;
        GPU_GMB_ADS_GO_NMX_LU_DESKTOP = 821;
        GPU_GMB_ADS_GO_NMX_LU_MOBILE = 822;
        GPU_GMB_ADS_GO_NMX_GSA_ANDROID = 823;
        GPU_GMB_ADS_GO_NMX_GSA_IOS = 824;
        GPU_GMB_POSTS_ANDROID = 825;
        GPU_GMB_POSTS_IOS = 826;
        GPU_GMB_POSTS_WEB = 827;
        GPU_GMB_POSTS_API = 828;
        GPU_GMB_POSTS_NMX_LU_DESKTOP = 829;
        GPU_GMB_POSTS_NMX_LU_MOBILE = 830;
        GPU_GMB_POSTS_NMX_GMM_ANDROID = 831;
        GPU_GMB_POSTS_NMX_GMM_IOS = 832;
        GPU_GMB_PRODUCTS_ANDROID = 833;
        GPU_GMB_PRODUCTS_IOS = 834;
        GPU_GMB_PRODUCTS_WEB = 835;
        GPU_GMB_PRODUCTS_API = 836;
        GPU_GMB_ONBOARDING_WEB = 837;
        GPU_GMB_ONBOARDING_GMM_IOS = 838;
        GPU_GMB_ONBOARDING_GMM_ANDROID = 839;
        GPU_GMB_ONBOARDING_TACTILE = 840;
        GPU_GMB_MENU_EDITOR_WEB = 841;
        GPU_GMB_MENU_EDITOR_NMX_LU = 842;
        GPU_GMB_MENU_EDITOR_NMX_GMM_ANDROID = 843;
        GPU_GMB_MENU_EDITOR_NMX_GMM_IOS = 844;
        GPU_GPAY_MYSHOP_MOBILE_WEB = 845;
        GPU_GPAY_MYSHOP_MOBILE_ANDROID = 846;
        GPU_GPAY_MYSHOP_MOBILE_IOS = 847;
        GPU_GPAY_MERCHANT_APP_FLUTTER = 1099;
        GPU_AR_UGC = 938;
        GSA_PROXY = 372;
        GOOGLE_ACCOUNT = 759;
        GOOGLE_ADMIN = 254 [deprecated = true];
        GOOGLE_GROUPS = 21;
        GOOGLE_NEWS_PROXY_INSECURE = 672;
        GOOGLE_ONE_SMUI = 582;
        GOOGLE_PODCASTS_PROXY = 597;
        GOOGLE_PRIVACY_DASHBOARD = 246;
        GOOGLE_SEARCH_RESULTS_PAGE = 449;
        GOOGLE_UV_CRAWLED = 112;
        GOOGLE_UV_PROXIED = 113;
        GOOGLE_VOICE = 379;
        GSUITE_ADDONS_PROXY = 438;
        HANGOUTS_USERAGENT = 457;
        HANGOUTS_IOS_USERAGENT = 669;
        HANGOUTS_REFERED = 460;
        HANGOUTS = 19;
        HANGOUTS_CAPABILITY = 673;
        HANGOUTS_SECURE = 674;
        HANGOUTS_STICKERS = 681;
        SHOEBOX_HINDSIGHT_FC = 939;
        PROXY_HINDSIGHT_FC = 948;
        HOTEL_ROOM_PHOTOS = 680;
        DEPRECATED_HOTELS_BOG = 735;
        IMAGE_SEARCH_PROXY = 25;
        ICE_T = 292;
        JAM_SCARY = 646;
        JAM_CORP = 647;
        JAM = 166;
        JAM_DRIVE = 676;
        JAM_DRIVE_SCARY = 998;
        JAM_DRIVE_CORP = 999;
        JAM_EXPORT = 1023;
        JAM_EXPORT_CORP = 1024;
        JAM_EXPORT_SCARY = 1025;
        JAM_WEBRENDER = 1036;
        JAM_WEBRENDER_CORP = 1037;
        JAM_WEBRENDER_SCARY = 1038;
        JETSET = 344;
        KEEP = 39;
        KEEP_BLOBSTORE_BLOB_SERVING = 682;
        KEEP_MEDIA_ASSET_PROXYING = 683;
        DEPRECATED_KINDYGRAM = 387;
        DEPRECATED_KINDYGRAM_MONOGRAM = 632;
        KIX_SCARY = 648;
        KIX_CORP = 649;
        KIX = 34;
        KIX_REFERED = 462;
        KIX_DRIVE = 552;
        KIX_DRIVE_SCARY = 986;
        KIX_DRIVE_CORP = 987;
        KWYJIBO_ALLOWED_LOCATION = 592;
        LENSLETS_PREVIEW_PROXY = 448;
        LENS_BACKEND = 1017;
        LENS_FRONTEND = 549;
        LOCAL_STREAM_PROXY = 426;
        LOCAL_CAT_AND_NAV_PREWARM = 1088;
        LOCAL_CAT_MERCHANT_PHOTOS = 1114;
        MAPS = 43;
        MATERIAL_GALLERY_DESIGNS = 591;
        MDF_TOOL_RESULTS = 689;
        MEDIA_SERVICE_PHOTOS_READONLY = 121;
        MEDIA_SERVICE_SOCIAL_FRONTEND = 122;
        MEDIA_SERVICE_SOCIAL_PEOPLE_DATA = 123;
        MEDIA_SERVICE_SOCIAL_DATA_MIXER = 124;
        MEDIA_SERVICE_APPS_PICKER = 125;
        MEDIA_SERVICE_BEQUT = 203;
        MEDIA_SERVICE_CHROME_DONGLE = 126;
        MEDIA_SERVICE_CHROMECAST = 127;
        MEDIA_SERVICE_CHROMECAST_ALPHA = 128;
        MEDIA_SERVICE_CHROMECAST_BORGCRON = 204;
        MEDIA_SERVICE_CHROMECAST_ENG = 129;
        MEDIA_SERVICE_DRAGONFLY_PROD = 130;
        MEDIA_SERVICE_GEO_UGC_PHOTOS_TEST = 131;
        MEDIA_SERVICE_SOCIAL_PERFECT_STREAM = 134;
        MEDIA_SERVICE_MAPS_ACTIVITIES_CORE = 135;
        MEDIA_SERVICE_GLASS_PROD = 136;
        MEDIA_SERVICE_ACCOUNT_CENTRAL = 137;
        MEDIA_SERVICE_IDENTITY_FRONTEND_DATA = 138;
        MEDIA_SERVICE_ONEPICK_SERVER = 619;
        MEDIA_SERVICE_PHOTO_SEARCH_PEOPLE = 140;
        MEDIA_SERVICE_PHOTOS_BATCH = 205;
        MEDIA_SERVICE_PHOTOS_IMAGE = 141;
        MEDIA_SERVICE_PHOTOS_SEARCH_EVAL = 142;
        MEDIA_SERVICE_PHOTOS_STORAGE_POLICY_CONVERSION = 143;
        MEDIA_SERVICE_VISUAL_SEARCH_PHOTOS = 144;
        MEDIA_SERVICE_SOCIAL_DEBUG_TOOL = 206;
        MEDIA_SERVICE_SOCIAL_PHOTOS_ANALYTICS = 145;
        MEDIA_SERVICE_SUGGEST_PERSONALIZATION = 146;
        MEDIA_SERVICE_SUGGEST_PERSONALIZATION_BUILDING = 147;
        MEDIA_SERVICE_SUGGEST_PERSONALIZATION_DEV = 207;
        MEDIA_SERVICE_KWYJIBO = 148;
        MEDIA_SERVICE_PHOTOS_STORIES_NOW = 149;
        MEDIA_SERVICE_SOCIAL_ENTITY_GRAPH = 150;
        MEDIA_SERVICE_GEO_TACTILE = 153;
        MEDIA_SERVICE_WEBSEARCH_PROD = 154;
        MEDIA_SERVICE_SOCIAL_CO_STREAM_DELIVERY = 155;
        MEDIA_SERVICE_SOCIAL_DISCOVERY = 156;
        MEDIA_SERVICE_SOCIAL_DISCOVERY_DEV_JOBS = 157;
        MEDIA_SERVICE_KIDS_API = 158;
        MEDIA_SERVICE_GPS = 159;
        MEDIA_SERVICE_GPS_TEST = 160;
        MEDIA_SERVICE_PHOTOS = 161;
        MEDIA_SERVICE_PHOTOS_DATA = 162;
        MEDIA_SERVICE_SOCIAL_DATA = 163;
        MEDIA_SERVICE_PHOTOS_FIFE_PROBER = 411;
        MEDIA_SERVICE_PHOTOS_MON = 200;
        MEDIA_SERVICE_PHOTOS_INDEX_BUILDER = 213;
        MEDIA_SERVICE_TAHITI = 443;
        MEDIA_SERVICE_SOCIAL_BOQ_PLUSAPI_MEDIA_SERVER = 445;
        MEDIA_SERVICE_GEO_PHOTO_GEOTAGGER_PROD = 132;
        MEDIA_SERVICE_GEO_PHOTO_GEOTAGGER_BATCH = 133;
        MEDIA_SERVICE_GEO_PHOTO_GEOTAGGER_DEV = 497;
        MEDIA_SERVICE_PHOTOS_GUNS_RENDERER = 139;
        MEDIA_SERVICE_GWS_PROD = 151;
        MEDIA_SERVICE_GWS_TEAM = 152;
        MEDIA_SERVICE_GWS_TEST = 490;
        MEDIA_SERVICE_GWS_DEV = 495;
        MEDIA_SERVICE_GEO_MAPS_TIMELINE = 470;
        MEDIA_SERVICE_SEARCH_SUPERROOT_ASSISTANT = 471;
        MEDIA_SERVICE_SEARCH_QUALITY_NLP = 569;
        MEDIA_SERVICE_SOCIAL_GRAPH_PROFILE = 472;
        MEDIA_SERVICE_RTC_CONVERSATION = 473;
        MEDIA_SERVICE_SOCIAL_CONTACTS_PLUS = 474;
        MEDIA_SERVICE_PHOTOS_HORCHATA = 475;
        MEDIA_SERVICE_GEO_STREET_VIEW_PUBLISH = 476;
        MEDIA_SERVICE_VILLAGE_CROWDSOURCE_PLATFORM_API = 477;
        MEDIA_SERVICE_PHOTOS_LEGACY_OZ = 478;
        MEDIA_SERVICE_DATALIBERATION = 479;
        MEDIA_SERVICE_DATALIBERATION_LEGAL = 480;
        MEDIA_SERVICE_RTC_GUSS_API = 481;
        MEDIA_SERVICE_SOCIAL_MONITORING = 482;
        MEDIA_SERVICE_ARES_PROD = 483;
        MEDIA_SERVICE_AMT_OFFLINE_SALES_RECEIPTS = 484;
        MEDIA_SERVICE_ASSISTANT_FULFILLMENT = 485;
        MEDIA_SERVICE_ASSISTANT_FOUNDATION = 496;
        MEDIA_SERVICE_MAPS_ACTIVITIES = 486;
        MEDIA_SERVICE_NBU_SOCIETY = 487;
        MEDIA_SERVICE_PHOTOS_FIESTA = 488;
        MEDIA_SERVICE_PHOTOS_FIRST_PARTY = 489;
        MEDIA_SERVICE_ASSISTANT_PHOTOS_PIPELINE = 567;
        MEDIA_SERVICE_PUBSUB_STUBBY_GATEWAY = 568;
        MEDIA_SERVICE_SOCIAL_NOTIFICATIONS = 578;
        MEDIA_SERVICE_SAMPLE_CLIENT = 586;
        MEDIA_SERVICE_NBU_TINYTASK = 588;
        MEDIA_SERVICE_AVATAR_SECURE_URLS = 715;
        BOQ_CONTENT_URL_GENERATOR_UNKNOWN = 164;
        MEETINGS_PROXY = 291;
        MEETINGS_MONOGRAM_VISUAL = 294;
        MERCHANT_CENTER_PROXY = 944;
        MERCHANT_IDENTITY = 1031;
        MOONSHINE = 8;
        MULTIMEDIA_NEWS_SETTINGS = 502;
        NARRATIVE_NEWS = 208;
        NOW = 99;
        OBAKE_SECURE = 985;
        ORBIT = 633;
        ONE_GOOGLE_WEB = 450;
        ONE_GOOGLE_WEB_SECURE = 595;
        ONE_GOOGLE_WEB_CUSTOM_CACHE = 657;
        ONE_GOOGLE_WEB_SECURE_CORP = 942;
        ONEPHOTO_STATS_FLUME = 603;
        ONEPICK_DRIVE = 982;
        ONEPICK_PHOTOS = 1016;
        ONEPICK_PROXY = 57;
        ONEPICK_UNKNOWN_PROXY = 296;
        ONEPICK = 76;
        ONEPICK_UI_SECURE = 714;
        ONEPICK_THIRDPARTY = 77;
        ONEPICK_ACCOUNT_CENTRAL = 312;
        ONEPICK_ASSISTANT_CONSOLE = 621;
        ONEPICK_ATARI = 313;
        ONEPICK_BIZBUILDER = 314;
        ONEPICK_BLOGGER = 247;
        ONEPICK_CALENDAR = 315;
        ONEPICK_DEFAULT = 622;
        ONEPICK_DEVELOPER_CONSOLE = 623;
        ONEPICK_DRAWING = 316;
        ONEPICK_EARTH = 684;
        ONEPICK_FORMS = 317;
        ONEPICK_GMAIL = 248;
        ONEPICK_GOOGLE_VOICE = 624;
        ONEPICK_GROUPS = 318;
        ONEPICK_GVOTES = 625;
        ONEPICK_HANGOUT = 319;
        ONEPICK_HOMEROOM = 320;
        ONEPICK_KIX = 249;
        ONEPICK_MAPS = 321;
        ONEPICK_MAYFLOWER = 626;
        ONEPICK_MOMA_TEAMS = 627;
        ONEPICK_ONEGOOGLEBAR = 322;
        ONEPICK_OZ = 323;
        ONEPICK_PUNCH = 250;
        ONEPICK_PWA = 628;
        ONEPICK_RITZ = 251;
        ONEPICK_SITES = 324;
        ONEPICK_TESTING = 629;
        DEPRECATED_ONEPICK_TOURBUILDER = 325;
        ONEPICK_UNKNOWN_CLIENT = 326;
        ONEPICK_YOUTUBE = 327;
        ONEPICK_THIRDPARTY_SECURE = 849;
        ONEPICK_ACCOUNT_CENTRAL_SECURE = 850;
        ONEPICK_ASSISTANT_CONSOLE_SECURE = 851;
        ONEPICK_ATARI_SECURE = 852;
        ONEPICK_BIZBUILDER_SECURE = 853;
        ONEPICK_BLOGGER_SECURE = 854;
        ONEPICK_CALENDAR_SECURE = 855;
        ONEPICK_DEVELOPER_CONSOLE_SECURE = 856;
        ONEPICK_DRAWING_SECURE = 857;
        ONEPICK_EARTH_SECURE = 858;
        ONEPICK_FLIX_SECURE = 1008;
        ONEPICK_PIX_SECURE = 1162;
        ONEPICK_FORMS_SECURE = 859;
        ONEPICK_GMAIL_SECURE = 860;
        ONEPICK_GOOGLE_VOICE_SECURE = 861;
        ONEPICK_GVOTES_SECURE = 862;
        ONEPICK_HANGOUT_SECURE = 863;
        ONEPICK_HOMEROOM_SECURE = 864;
        ONEPICK_KIX_SECURE = 865;
        ONEPICK_MAPS_SECURE = 866;
        ONEPICK_MAYFLOWER_SECURE = 867;
        ONEPICK_MOMA_TEAMS_SECURE = 868;
        ONEPICK_ONEGOOGLEBAR_SECURE = 869;
        ONEPICK_PUNCH_SECURE = 870;
        ONEPICK_RITZ_SECURE = 871;
        ONEPICK_SITES_SECURE = 872;
        ONEPICK_TESTING_SECURE = 873;
        ONEPICK_YOUTUBE_SECURE = 874;
        ONEPICK_PROXY_SECURE = 917;
        ON_THE_GO = 103;
        PAIDTASKS_SURVEY_IMAGE_LIFECYCLE_SYSTEM = 726;
        PANORAMIO = 48;
        PAST_PROFILE_PHOTOS = 1052;
        EPHEMERAL_PHOTOS = 1077;
        SGBE_ABUSE_PHOTOS = 1089;
        BACKGROUND_CONTACT_PHOTOS = 1122;
        BACKGROUND_PROFILE_PHOTOS = 1112;
        PAYMENTS = 396;
        PAYMENTS_CARD_3D_SECURE2 = 493;
        PAYMENTS_ORCHESTRATION2_CARD_3D_SECURE2 = 662;
        PAYMENTS_SELF_ORDER_PROXY = 576;
        PEOPLE_API = 439;
        PEOPLE_API_BLOCKED_MONOGRAM = 928;
        PEOPLE_API_CONTACT_MONOGRAM = 637;
        PEOPLE_API_CONTACT_MONOGRAM_CORP_HEADERS = 1100;
        PEOPLE_API_EXTENSION_MONOGRAM = 670;
        PEOPLE_API_PEOPLE_FRONTEND_MONOGRAM = 736;
        PEOPLE_API_AUTOCOMPLETE_MONOGRAM = 737;
        PEOPLE_API_AUTOCOMPLETE_MONOGRAM_CORP_HEADERS = 1098;
        PEOPLE_CONTACTS = 716;
        PLACES_API_PHOTOS = 565;
        PLAY = 45;
        PLAY_GAMES_PROXY = 391;
        PLAY_ADS_PROXY = 919;
        PLAY_GAMES_SERVICES = 639;
        PLAY_MOVIES_PROXY = 300;
        PHOTOS_ABUSE_REPORT = 548;
        PHOTOS_ALBUM_ARCHIVE = 197;
        PHOTOS_ALBUM_ARCHIVE_SECURE = 758;
        PHOTOS_ANIMATED_POPOUT = 1095;
        PHOTOS_LEGAL_EXPORTS_TAKEOUT = 962;
        PHOTOS_WEB_DOWNLOADS_TAKEOUT = 963;
        PHOTOS_CONSUMER_TAKEOUT = 964;
        PHOTOS_ABUSE_I_AM = 546;
        PHOTOS_AMBIENT_CAST = 947;
        PHOTOS_ARES = 566;
        PHOTOS_BENCHMARKS = 494;
        PHOTOS_BEYOND_PLAYGROUND = 725;
        PHOTOS_CHINA = 5;
        PHOTOS_CURATION = 283;
        PHOTOS_DOWNLOAD_SERVER = 355;
        PHOTOS_DOWNLOAD_FULFILLER = 434;
        PHOTOS_EVAL_FLUME = 366;
        PHOTOS_FACE_CLUSTERING_METRICS_CONSOLE = 375;
        PHOTOS_FINGERPRINTING_SERVICE = 755;
        PHOTOS_FIRST_PARTY_API = 378;
        PHOTOS_GENMEDIA = 1155;
        BOQ_PHOTOS_GUNS_RENDERER_SOCIAL_NOTIFICATIONS = 199;
        BOQ_PHOTOS_GUNS_RENDERER_SOCIAL_NOTIFICATIONS_AVATARS = 579;
        PHOTOS_GUNS_IOS = 306;
        PHOTOS_GUNS_IOS_LEGACY = 307;
        PHOTOS_GUNS_ANDROID = 308;
        PHOTOS_GUNS_ANDROID_LEGACY = 309;
        PHOTOS_GUNS_WEB = 310;
        PHOTOS_HORCHATA = 577;
        PHOTOS_HORCHATA_SECURE = 707;
        PHOTOS_INFER_USER_STYLE = 383;
        PHOTOS_LEARNING_PET_CLUSTER_FLUME = 368;
        PHOTOS_LEARNING_PEOPLE_CLUSTER_FLUME = 369;
        PHOTOS_LEARNING_TUNE_COARSE_CLASSIFIER_FLUME = 370;
        PHOTOS_LEARNING_ICA_FALSE_POSITIVE_FLUME = 371;
        PHOTOS_LEARNING_PHILEAS_EVAL_FLUME = 392;
        PHOTOS_LEARNING_LOCATION_FLUME = 377;
        PHOTOS_LEARNING_SUGGESTED_ACTION_FLUME = 407;
        PHOTOS_LEARNING_ROTATE_PHOTO_FLUME = 413;
        PHOTOS_LIBRARY = 388;
        PHOTOS_LIBRARY_DTP = 692;
        PHOTOS_LIBRARY_PARTNER = 442;
        PHOTOS_3P_AMBIENT = 1028;
        PHOTOS_3P_PICKER = 1044;
        PHOTOS_MAGIC_EDITOR = 975;
        PHOTOS_MONITORING = 202;
        PHOTOS_OSID_ROLLOUT_TEST = 966;
        PHOTOS_PAGEVIEW_OP = 547;
        PHOTOS_PARTNER = 440;
        PHOTOS_PRINTING_SERVICE = 277;
        PHOTOS_SEND_NOTIFICATION_SERVER_EMAIL = 367;
        PHOTOS_SERVICE_ADWORDS_DISPLAYADS_SUGGESTIONS = 167;
        PHOTOS_SERVICE_APPS_COMMON_STORAGE = 504;
        PHOTOS_SERVICE_APPS_COMMON_STORAGE_PHOTO_SYNC = 218;
        PHOTOS_SERVICE_APPS_DRIVE_FIXERS = 505;
        PHOTOS_SERVICE_APPS_DRIVE_PSYNCHO_SUBSCRIBER = 506;
        PHOTOS_SERVICE_APPS_EXPLORER = 507;
        PHOTOS_SERVICE_APPS_JAM = 508;
        PHOTOS_SERVICE_APPS_PICKER = 168;
        PHOTOS_SERVICE_ARES_PROD = 509;
        PHOTOS_SERVICE_BIZBUILDER_ADMIN = 169;
        PHOTOS_SERVICE_BIZBUILDER_BULK = 170;
        PHOTOS_SERVICE_BIZBUILDER_DASHBOARD = 171;
        PHOTOS_SERVICE_BIZBUILDER_FRONTEND = 172;
        PHOTOS_SERVICE_BIZBUILDER_PHOTOS = 173;
        PHOTOS_SERVICE_BIZBUILDER_BACKEND = 220;
        PHOTOS_SERVICE_CLOUDCAST_CAPTURE = 510;
        PHOTOS_SERVICE_DATALIBERATION = 176;
        PHOTOS_SERVICE_DATALIBERATION_LEGAL = 511;
        PHOTOS_SERVICE_GEO_IMAGES_REFERENCE_EXPORTER_PROD = 178 [deprecated = true];
        PHOTOS_SERVICE_GEO_MERCHANT_API = 512;
        PHOTOS_SERVICE_GEO_MERCHANT_FRONTEND_DATA = 513;
        PHOTOS_SERVICE_GEO_PHOTO_CATALOG = 514;
        PHOTOS_SERVICE_GEO_PHOTO_GEOTAGGER_PROD = 179;
        PHOTOS_SERVICE_GEO_PHOTO_UPLOADER_PROD = 180;
        PHOTOS_SERVICE_GEO_PHOTO_VENUS = 661;
        PHOTOS_SERVICE_GEO_TACTILE = 515;
        PHOTOS_SERVICE_GWS_PROD = 226;
        PHOTOS_SERVICE_JOTSPOT = 516;
        PHOTOS_SERVICE_KWYJIBO = 517;
        PHOTOS_SERVICE_MOMA_FRONTEND = 518;
        PHOTOS_SERVICE_NBU_SOCIETY_BACKEND = 519;
        PHOTOS_SERVICE_PHOTOS = 183;
        PHOTOS_SERVICE_PHOTOS_ASSISTANT = 520;
        PHOTOS_SERVICE_PHOTOS_BATCH = 184;
        PHOTOS_SERVICE_PHOTOS_DATA = 185;
        PHOTOS_SERVICE_PHOTOS_FIESTA = 521;
        PHOTOS_SERVICE_PHOTOS_IMAGE = 230;
        DEPRECATED_PHOTOS_SERVICE_PHOTOS_KINDYGRAM = 522;
        DEPRECATED_PHOTOS_SERVICE_PHOTOS_KINDYGRAM_ASYNC_QUEUEPROCESSOR = 523;
        PHOTOS_SERVICE_PHOTOS_LEGACY_OZ = 742;
        PHOTOS_SERVICE_PHOTOS_LIBRARY_API = 524;
        PHOTOS_SERVICE_PHOTOS_QUEUE_PROCESSOR = 525;
        PHOTOS_SERVICE_PHOTOS_STORAGE_POLICY_CONVERSION = 526;
        PHOTOS_SERVICE_PHOTOS_TIME_MACHINE = 527;
        PHOTOS_SERVICE_PHOTOS_UI = 528;
        PHOTOS_SERVICE_PHOTOS_SEEDING = 572;
        PHOTOS_SERVICE_PHOTOS_VENOM_SUBSCRIBER = 573;
        PHOTOS_SERVICE_RTC_CONSERVER = 529;
        PHOTOS_SERVICE_RTC_CONVERSATION = 530;
        PHOTOS_SERVICE_RTC_HOTROD_API = 531;
        PHOTOS_SERVICE_SOCIAL_ALBUM_ARCHIVE_UI = 532;
        PHOTOS_SERVICE_SOCIAL_COLLEXIONS = 237;
        PHOTOS_SERVICE_SOCIAL_FRONTEND = 189;
        PHOTOS_SERVICE_SOCIAL_GRAPH_API = 533;
        PHOTOS_SERVICE_SOCIAL_MONITORING = 534;
        PHOTOS_SERVICE_SOCIAL_PLUS_LEGAL_WIPEOUT = 535;
        PHOTOS_SERVICE_SOCIAL_SQUARES = 536;
        PHOTOS_SERVICE_TAKEOUT = 537;
        PHOTOS_SERVICE_TEAMS = 538;
        PHOTOS_SERVICE_INGESTION = 539;
        PHOTOS_SERVICE_CROWDSOURCE_PLATFORM_API = 540;
        PHOTOS_SERVICE_YOUTUBE_CREATOR_PUBLIC_FIGURES_BOQ = 541;
        PHOTOS_SERVICE_YOUTUBE_MUSIC_CORPUS = 542;
        PHOTOS_SERVICE_GSA_UNIVERSAL = 550;
        PHOTOS_SERVICE_CROWDSOURCE_BACKEND = 570;
        PHOTOS_SERVICE_NEWS_BULLETIN_FEATURES = 571;
        PHOTOS_SERVICE_NUTRITION_FRONTEND = 574;
        PHOTOS_SERVICE_ABUSE_I_AM = 214;
        PHOTOS_SERVICE_ARES = 441;
        PHOTOS_SERVICE_AUTO_CURATE = 278;
        PHOTOS_SERVICE_GPNS_NOTIFICATION_BUILDER = 279;
        PHOTOS_SERVICE_GPLUS_EVENTS = 280;
        PHOTOS_SERVICE_NO_CLIENT_SET = 281;
        PHOTOS_SERVICE_GPLUS_PHOTOS = 282;
        PHOTOS_SERVICE_SCOTTY_AGENT = 215;
        PHOTOS_SERVICE_ONEPICK_SERVER = 630;
        PHOTOS_SERVICE_BLOGGER = 174;
        PHOTOS_SERVICE_CHAT_BACKEND_ENG = 175;
        PHOTOS_SERVICE_DRAGONFLY_PROD = 177;
        PHOTOS_SERVICE_GEO_UGC_PHOTOS_TEST = 181;
        PHOTOS_SERVICE_MAPS_STREETVIEW_PLACES_PROD = 182;
        PHOTOS_SERVICE_PHOTOS_PWA = 186;
        PHOTOS_SERVICE_SOCIAL_DATA = 187;
        PHOTOS_SERVICE_SOCIAL_DEBUG_TOOL = 188;
        PHOTOS_SERVICE_SOCIAL_STORIES_DEBUGSERVER = 190;
        PHOTOS_SERVICE_YOUTUBE = 191;
        PHOTOS_SERVICE_YOUTUBE_CANARY = 192;
        PHOTOS_SERVICE_YOUTUBE_PREPROD_QA = 193;
        PHOTOS_SERVICE_PHOTOS_FIFE_PROBER = 412;
        PHOTOS_SERVICE_PHOTOS_MON = 201;
        PHOTOS_SERVICE_ABUSE_PROD = 216;
        PHOTOS_SERVICE_ABUSE_STAGING = 217;
        PHOTOS_SERVICE_BEQUT = 219;
        PHOTOS_SERVICE_COMMERCE_INSTORE = 221;
        PHOTOS_SERVICE_COMMERCE_INSTORE_QA = 222;
        PHOTOS_SERVICE_FOCUS_BACKEND = 223;
        PHOTOS_SERVICE_GLASS_PROD = 224;
        PHOTOS_SERVICE_GMAIL = 225;
        PHOTOS_SERVICE_IMAGE_ALBUMS = 227;
        PHOTOS_SERVICE_KIDS_API = 228;
        PHOTOS_SERVICE_OFFLINE_SALES_RECEIPTS = 503;
        PHOTOS_SERVICE_PANORAMIO = 229;
        PHOTOS_SERVICE_PHOTOS_INDEX_BUILDER = 231;
        PHOTOS_SERVICE_PHOTOS_MR = 232;
        PHOTOS_SERVICE_PHOTOS_PUBSUB_PROBER = 233;
        PHOTOS_SERVICE_PRIVATE_UNIVERSAL_FAKEACCOUNTS = 234;
        PHOTOS_SERVICE_PRIVATE_UNIVERSAL_TESTING = 235;
        PHOTOS_SERVICE_SOCIAL_ANNOTATION = 236;
        PHOTOS_SERVICE_SOCIAL_BOQ_PLUSAPI_MEDIA_SERVER = 446;
        PHOTOS_SERVICE_SOCIAL_PROMO = 238;
        PHOTOS_SERVICE_SOCIAL_SPACES = 239;
        PHOTOS_SERVICE_SOCIAL_STANZA = 240;
        PHOTOS_SERVICE_SOCIAL_SUPERROOT = 241;
        PHOTOS_SERVICE_TAHITI = 444;
        PHOTOS_SERVICE_USER_PRIVACY_SUMMARY = 242;
        PHOTOS_SERVICE_VIDEOCONF_API = 243;
        PHOTOS_SERVICE_WRITE_ACTION_PROFILE_PHOTO = 551;
        PHOTOS_SERVICE_YOUTUBE_UPLOAD_IMPORTER = 244;
        PHOTOS_SERVICE_UNKNOWN = 194;
        PHOTOS_SYNC = 12;
        PICASA = 52;
        PICASA_USERAGENT = 458;
        PICASAWEB = 42;
        PWA_API = 115;
        PICASAWEB_REFERED = 165;
        GOOGLE_PHOTOS_ADMIN_SERVICE = 349;
        GOOGLE_PHOTOS_ADMIN_SERVICE_EXPORT = 604;
        GOOGLE_PHOTOS_ANDROID = 53;
        GOOGLE_PHOTOS_ANDROID_GUESSABLE = 675;
        GOOGLE_PHOTOS_ANDROID_USERAGENT = 456;
        GOOGLE_PHOTOS_ANDROID_MEDIA_ITEM_SECURE = 921;
        GOOGLE_PHOTOS_IOS = 50;
        GOOGLE_PHOTOS_IOS_GUESSABLE = 848;
        GOOGLE_PHOTOS_IOS_WIDGET = 686;
        GOOGLE_PHOTOS_WEB = 51;
        GOOGLE_PHOTOS_WEB_SECURE = 617;
        GOOGLE_PHOTOS_WEB_SECURE_UNFILTERED = 895;
        GOOGLE_PHOTOS_WEB_GUESSABLE = 887;
        GOOGLE_PHOTOS_WEB_REFERED = 459;
        GOOGLE_PHOTOS_WEB_ABUSE_TAKEDOWN_URL = 876;
        GOOGLE_PHOTOS_SEARCH_EVAL = 120;
        GOOGLE_PHOTOS_PROJECT_ELLMANN = 961;
        GOOGLE_PHOTOS_SEARCH_EVAL_AUTORATER = 1094;
        PHOTOS_SEARCH_PHOTOS_MEDIA = 328;
        PHOTOS_SEARCH_PHOTOS_PROD = 329;
        PHOTOS_SEARCH_GWS_PROD = 330;
        PHOTOS_SEARCH_FUZZYDICE = 331;
        PHOTOS_SEARCH_PRIVATE_UNIVERSAL_TESTING = 332;
        PHOTOS_SEARCH_GWS_TEST = 333;
        PHOTOS_SEARCH_GWS_TEAM = 334;
        PHOTOS_SEARCH_MERGESERVER = 335;
        PHOTOS_SEARCH_GBOT_INTERNAL = 336;
        PHOTOS_SEARCH_GWSDIFF_TEAM = 337;
        PHOTOS_SEARCH_SEARCHUI = 338;
        PHOTOS_THETA = 1186;
        PHYSICAL_WEB_PROXY = 117;
        PRIVATE_WEB_APPS_MONOGRAM = 1021;
        PROFILE_SERVICE_COVER_PHOTO = 386;
        PULSAR = 9;
        PUNCH_SCARY = 650;
        PUNCH_CORP = 651;
        PUNCH = 35;
        PUNCH_REFERED = 465;
        PUNCH_API_THUMBNAIL = 343;
        PUNCH_API_THUMBNAIL_DOPLAR_SECURE = 937;
        PUNCH_DRIVE = 553;
        PUNCH_DRIVE_SCARY = 990;
        PUNCH_DRIVE_CORP = 991;
        RECEIPTS = 397;
        RECEIPTS_MANAGER = 665;
        RITZ_SCARY = 652;
        RITZ_CORP = 653;
        RITZ = 36;
        RITZ_REFERED = 463;
        RITZ_DRIVE = 554;
        RITZ_DRIVE_SCARY = 988;
        RITZ_DRIVE_CORP = 989;
        ROHAN_WATCHFACE = 880;
        RTB = 354;
        RTB_PROXY = 640;
        RWJ_PARTNER_LIVE_QUERY = 1158;
        SCOTTY_AGENT_ONEPICK_REVIEWS_WIDGET = 902;
        SCOTTY_AGENT_ONEPICK_ACCOUNT_CENTRAL_SECURE = 903;
        SCOTTY_AGENT_ONEPICK_ASSISTANT_CONSOLE_SECURE = 916;
        SCOTTY_AGENT_ONEPICK_BLOGGER_SERCURE = 904;
        SCOTTY_AGENT_ONEPICK_DEVELOPER_CONSOLE_SECURE = 905;
        SCOTTY_AGENT_ONEPICK_GMAIL_PROFILE_SECURE = 906;
        SCOTTY_AGENT_ONEPICK_GOOGLE_VOICE_SECURE = 907;
        SCOTTY_AGENT_ONEPICK_HANGOUTS_SECURE = 908;
        SCOTTY_AGENT_ONEPICK_HOMEROOM_AVATAR_SECURE = 909;
        SCOTTY_AGENT_ONEPICK_HOMEROOM_COUTSE_PHOTO_UPLOAD_SECURE = 910;
        SCOTTY_AGENT_ONEPICK_MAYFLOWER_SECURE = 911;
        SCOTTY_AGENT_ONEPICK_MOMA_TEAMS_SECURE = 912;
        SCOTTY_AGENT_ONEPICK_ONEGOOGLEBAR_SECURE = 915;
        SCOTTY_AGENT_ONEPICK_V2_ASSISTANT_FASTTRACK_INSERT_IMAGE = 949;
        SCOTTY_AGENT_ONEPICK_V2_MIGRATED_FREEBIRD_THEMES = 950;
        SCOTTY_AGENT_ONEPICK_V2_MIGRATED_HOMEROOM_COURSE_PHOTO_UPLOAD_SECURE = 1074;
        SCOTTY_AGENT_GOOGLE_PLUS_SECURE = 913;
        SCOTTY_AGENT_HANGOUTS_SECURE = 914;
        SEARCH = 44;
        SEARCH_PHOTOPINS = 757;
        SEARCH_REFERED = 467;
        SEARCH_SOS_ALERTS_PROXY = 299;
        SEARCH_ENGAGEMENT_HIGHLIGHT = 750;
        SERVICES_IMMERSIVE_LIST_IMAGE_CAROUSEL = 882;
        SERVICES_IMMERSIVE_ORGANIC_PROFILE_PHOTO_CAROUSEL = 883;
        SERVICES_IMMERSIVE_JUSTIFICATION_ICONS = 884;
        SERVICES_IMMERSIVE_DESKTOP_COVER_PHOTO = 896;
        SHAREDADDRESSBOOK_PRIVATE_PHOTO_URL = 561;
        SHAREDADDRESSBOOK_PRIVATE_PHOTO_URL_CORP_HEADERS = 1096;
        SHAREDADDRESSBOOK_MONOGRAM_PHOTO_URL = 656;
        SHAREDADDRESSBOOK_MONOGRAM_PHOTO_URL_CORP_HEADERS = 1097;
        SHOEBOX_DEFAULT_SECURE_URL_CLIENT = 744;
        SHOPPING_PROPERTY = 618;
        SHOPPING_ONSEARCH = 885;
        SHOPS_KAHANI = 688;
        SKETCHY_SCARY = 654;
        SKETCHY_CORP = 655;
        SKETCHY = 37;
        SKETCHY_DRIVE = 555;
        SKETCHY_DRIVE_SCARY = 992;
        SKETCHY_DRIVE_CORP = 993;
        SMART_DEVICE_MANAGEMENT = 664;
        SPUR = 730;
        STARLIGHT_PRIVATE_PHOTO_URL = 447;
        STARLIGHT_PUBLIC_PHOTO_URL = 691;
        STARLIGHT_CONTACT_PHOTO = 718;
        STARLIGHT_CORP_HEADERS_PRIVATE_PHOTO_URL = 1084;
        STARLIGHT_CORP_HEADERS_PUBLIC_PHOTO_URL = 1085;
        STARLIGHT_CORP_HEADERS_CONTACT_PHOTO_URL = 1086;
        SOCIAL_FRONTEND_ABSTRACT_AUTO_COMPLETE_ITEMS = 373;
        SOCIAL_PAGE_RENDER = 210;
        SOCIAL_SPACES_PROXY = 198;
        SONOS = 14;
        STERLING_COOPER = 30;
        STREET_VIEW_ANDROID = 195;
        STREET_VIEW_IOS = 196;
        STREET_VIEW_GMM = 1118;
        STYX = 27;
        SYSTEM1 = 635;
        TAKEOUT = 55;
        TAKEOUT_LIS = 687;
        TENOR_CLIENT_PROFILE = 697;
        TEXMEX = 40;
        DRIVE_VIEWER = 924;
        TOOL_RESULTS = 31;
        TOWNSQUARE = 756;
        TRAVEL_BOOKING_PROXY = 376;
        TRAVEL_DESTINATION_EXPLORE_PROXY = 351;
        THINGS_TO_DO_UGC = 602;
        TRAVEL_UBERVERSAL = 894;
        TRIX = 38;
        TWIZZLER = 347;
        UCP_CONTENT_SERVER = 971;
        UNKNOWN_CLIENT_COSMO = 58;
        UNKNOWN_CLIENT_HARPOON = 59;
        UNKNOWN_CLIENT_CONTENT_DATA = 60;
        UNKNOWN_CLIENT_STATIC_REF = 596;
        UNKNOWN_CLIENT_PHOTOS_SERVICE = 61;
        UNKNOWN_CLIENT_PROFILE_SERVICE = 658;
        UNKNOWN_CLIENT_SHOEBOX = 62;
        UNKNOWN_CLIENT_MONOGRAM_VISUAL = 293;
        UNKNOWN_CLIENT_TILEINFO_RENDERER = 346;
        UNKNOWN_CLIENT_PHOTOS_SERVICE_GUESSABLE = 581;
        UNKNOWN_CLIENT_COSMO_GUESSABLE = 106;
        UNKNOWN_CLIENT_TEST_REF = 705;
        UNKNOWN_CLIENT_DOPLAR = 745;
        UNKNOWN_CLIENT_CONTRIB_SERVICE = 918;
        UNKNOWN_CLIENT_AUTHENTICATED_BLOB = 972;
        UNKNOWN_CLIENT_SOCIAL_GRAPH = 1049;
        UNKNOWN_CLIENT_DROPPER = 1124;
        VAULT = 410;
        WALLET_CARD_ART_PROXY = 1026;
        WEARABLE_LINKS = 380;
        WERNICKE_PROXY = 361;
        WHITMAN_SOCIAL = 101;
        WIFI_ACCESS_CAPTIVE_PORTAL = 26;
        YOUTUBE_SANITIZED = 11;
        YOUTUBE_BACKSTAGE = 311;
        YOUTUBE_CHANNELS = 381;
        YOUTUBE_DIRECTOR = 393;
        YOUTUBE_EDITOR = 54;
        YOUTUBE_IDENTITY = 590;
        YOUTUBE_REACTR = 435;
        YOUTUBE_SHOPPING = 492;
        YOUTUBE_MUSIC_FAN_ENGAGEMENT = 931;
        YOUTUBE_VIA = 951;
        YOUTUBE_PODCASTS_INGESTION = 955;
        YOUTUBE_PODCAST_PROXY = 1013;
        GEOMP_LERNA = 959;
        BARD_IMAGE_PROXY = 973;
        ACEP_PLATFORM = 974;
        LOCAL_REVIEWS = 980;
        GRASS = 1004;
        GRASS_PROXY = 1005;
        GRASS_MVS = 1009;
        GRASS_MVS_PROXY = 1010;
        GRASS_LENS = 1011;
        GRASS_LENS_PROXY = 1012;
        GRASS_CS_SECURE = 1068;
        GRASS_CS_GUESSABLE = 1069;
        GRASS_CS_SECURE_STALE = 1104;
        AIXI_BACKEND = 1033;
        GEO_MADDEN_BACKEND = 1034;
        MAPS_JS_API = 1105;
        GOOGLE_EARTH = 1106;
        MARKETPLACE_SDK = 1127;
        CONTRIB_SERVICE_CS_PLAYGROUND = 1132;
        CONTRIB_SERVICE_SEARCH_CREATORPROFILE = 1133;
        CONTRIB_SERVICE_COURSE_THEMES = 1135;
        CONTRIB_SERVICE_SHOPPING_WARDROBE = 1137;
        CONTRIB_SERVICE_ADSSUPPORTAUTOMATION = 1138;
        CONTRIB_SERVICE_CREATIVE_STUDIO = 1139;
        CONTRIB_SERVICE_CHALET_MM_SEARCH = 1140;
        CONTRIB_SERVICE_PHOTOS_PREVIEWS_PUBLIC_NON_ROTATING = 1144;
        CONTRIB_SERVICE_ATELIER = 1145;
        CORTO_SIGNATURE_IMAGE_URL = 1152;
        CONTRIB_SERVICE_ABUSE_GENAI = 1153;
        CONTRIB_SERVICE_GHD = 1154;
        CONTRIB_SERVICE_GOOGLE_DAM_PUBLIC_NON_ROTATING = 1156;
        GOOGLE_TV_PHOTOS_SEARCH = 1164;
        CONTRIB_SERVICE_POLICY_STUDIO = 1165;
        PHOTOS_ELLMANN_PHOTOS_SIMULATE_USER_FLUME = 1166;
        PHOTOS_ELLMANN_AUTO_AWESOME = 1167;
        PHOTOS_ELLMANN_ZONDA = 1168;
        PHOTOS_ELLMANN_BARD = 1169;
        PHOTOS_ELLMANN_SIAN_MEMORA = 1170;
        PHOTOS_ELLMANN_SIAN_BARD = 1171;
        PHOTOS_ELLMANN_SIAN_BARD_EVAL = 1172;
        PHOTOS_ELLMANN_SIAN_SEARCH = 1173;
        PHOTOS_ELLMANN_SIAN_SEARCH_EVAL = 1174;
        PHOTOS_ELLMANN_SIAN_LOADTEST = 1175;
        PHOTOS_ELLMANN_SIAN_LOTUS = 1176;
        PHOTOS_ELLMANN_SIAN_PROBER = 1177;
        PHOTOS_ELLMANN_TRY_ON_YOU = 1178;
        PHOTOS_ELLMANN_TRY_ON_YOU_AIM = 1199;
        PHOTOS_ELLMANN_WARDROBE = 1181;
        CONTRIB_SERVICE_PLAY_GAMES_PLAYGROUND = 1179;
        CONTRIB_SERVICE_DATAMINER = 1180;
        CONTRIB_SERVICE_LABS_COSCIENTIST = 1182;
        CONTRIB_SERVICE_FP_GAIA_SEARCH = 1183;
        CONTRIB_SERVICE_BUSINESS_VIDEOS = 1184;
        CONTRIB_SERVICE_FITBIT_FILE_MANAGER = 1185;
        CONTRIB_SERVICE_AIMODE_SHARE = 1187;
        CONTRIB_SERVICE_LOTUS = 1188;
        PHOTOS_EDITING_TOOLS = 1189;
        AIM_AGENTIC_ECOSYSTEM_PROXY = 1190;
        YOUTUBE_FANTASY_SPORTS = 1191;
        WALLET_WEB = 1195;
        CONTRIB_SERVICE_ADS_ADVISOR = 1196;
        PHOTOS_STORYTELLING_GENMEDIA_EXTERNAL = 1197;
        CONTRIB_SERVICE_SEARCH_SHARE = 1198;
        SPORTS_LIVE_ANALYST = 1200;
    }
}

message UrlSource {
    enum Tag {
        URL_CONTEXT_TAG_UNKNOWN = 0;
        ALBUM_REPLY_BUILDER_PHOTO_SNIPPET = 1;
        ALBUM_REPLY_BUILDER_COVER_PHOTO = 2;
        FIFE_TILEINFO_RENDERER = 3;
        PSSR_UTIL = 4;
        QUERY_COMMENT = 5;
        QUERY_PHOTO_ACTION_HANDLER = 6;
        QUERY_PHOTO_ACTION_HANDLER_DELETED = 7;
        QUERY_PHOTO_ACTION_HANDLER_SHAPES = 35;
        QUERY_SAPPHIRE = 8;
        QUERY_GLOBAL = 9;
        ALBUM_REPLY_BUILDER_BANNER = 10;
        PHOTO_REPLY_BUILDER = 11;
        SHAPE_URL = 12;
        BOQ_PHOTO_URL_GENERATOR = 13;
        FEATURED_PHOTOS_SELECTOR = 14;
        PHOTO_ENTITIES_UTIL = 15;
        CURATION_PHOTO_HTML_RENDERER = 16;
        EDIT_ALBUM = 17;
        CREATE_ALBUM = 18;
        QUERY_ACCOUNT = 19;
        QUERY_ALBUM_ACTION_HANDLER = 20;
        QUERY_ALBUM_ACTION_HANDLER_BY_LABELS = 21;
        SUGGESTED_SHARING_CLUSTER = 22;
        SHARE = 23;
        FIFE_REDIRECT_FOR_CHECK_GAIA_AUTH = 24;
        FIFE_REDIRECT_FOR_AUTHENTICATION = 25;
        FIFE_REDIRECT_WITH_NEW_CREDENTIALS = 26;
        PHOTO_REPLY_UTIL = 27;
        REMOVE_ACTION_HANDLER = 28;
        CREATE_PHOTO_ACTION_HANDLER = 29;
        SHARE_ACTION_HANDLER = 30;
        EDIT_PHOTO_ACTION_HANDLER = 31;
        EDIT_PHOTOS_ACTION_HANDLER = 32;
        QUERY_ACCOUNT_PHOTOS_ACTION_HANDLER = 33;
        QUERY_GLOBAL_ACTION_HANDLER = 34;
        EVENT_PHOTO_FETCHER = 36;
        FIFE_REDIRECT_WITH_ANONYMOUS_CREDENTIALS = 37;
        FIFE_REDIRECT_FOR_OLYMPUS_COMPLIANCE = 80;
        DOCS_MODEL = 38;
        DOCS_EMBED = 39;
        DOCS_EDIT = 40;
        DOCS_PUBLISHED = 41;
        DOCS_RENDER_DATA = 42;
        DOCS_MOBILE_PRESENT = 43;
        DOCS_PREVIEW = 44;
        DOCS_HTML_VIEW = 45;
        DOCS_MOBILE_EDIT = 46;
        DOCS_VIEW_PAGE = 47;
        DOCS_GET_PRESENTATION = 48;
        DOCS_PRESENT = 49;
        DOCS_GET_SPREADSHEET = 50;
        DOCS_MOBILE_BASIC = 51;
        DOCS_PUBLISHED_HTML_VIEW = 52;
        DOCS_PUBLISHED_VIEW_ACTION_V2 = 53;
        DOCS_EXPORT = 54;
        DOCS_GRADING = 55;
        DOCS_EXPORT_DOCUMENTS = 56;
        DOCS_MOBILE_BOOTSTRAP = 57;
        DOCS_GET_DOCUMENT = 58;
        DOCS_PUBLISHED_SHEETHTMLVIEW = 59;
        DOCS_MINIMAL_STATIC = 60;
        DOCS_SHOW_REVISION = 61;
        DOCS_HTML_EMBED_SHEET = 62;
        DOCS_PREVIEW_SHEET = 63;
        DOCS_GET_PAGE_THUMBNAIL = 64;
        DOCS_GET_SLIDE_LIBRARY_CONTENT_HTTP = 65;
        DOCS_GET_SPREADSHEET_BY_DATA_FILTER = 66;
        DOCS_FETCH = 67;
        DOCS_ADMIN_PREVIEW = 68;
        DOCS_PUBLISHED_VIEW = 69;
        DOCS_BATCH_UPDATE_SPREADSHEET = 70;
        DOCS_GET_SLIDE_LIBRARY_CONTENT_RPC = 71;
        DOCS_SOCIAL_MARKUP_THUMBNAIL = 78;
        DOCS_DOCUMENT_THUMBNAIL = 79;
        DOCS_MODEL_ANDROID = 82;
        DOCS_MODEL_IOS = 83;
        DOCS_RENDER_DATA_ANDROID = 84;
        DOCS_RENDER_DATA_IOS = 85;
        DOCS_MOBILE_EDIT_ANDROID = 86;
        DOCS_MOBILE_EDIT_IOS = 87;
        DOCS_PUBLISHED_EMBED = 89;
        PROFILE_PHOTO_PUBLIC = 72;
        PROFILE_PHOTO_PRIVATE = 73;
        PROFILE_PHOTO_HIGH_RES = 74;
        PROFILE_PHOTO_LOW_RES = 75;
        PROFILE_PHOTO_MONOGRAM = 76;
        PROFILE_PHOTO_SILHOUETTE = 77;
        DRIVE_STORAGE_SERVER_MEET = 81;
        DRIVE_STORAGE_SERVER_THUMBNAIL = 88;
    }
}

extend .proto2.EnumValueOptions {
    optional RequestStatusInfo status_info = 100507575;
}
