syntax = "editions";

package geo_serving_proto.electricvehicle;

import "geo/serving/proto/electricvehicle/charging_architecture.proto";
import "java/com/google/apps/jspb/jspb.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "third_party/java/protobuf/java_features.proto";
import "third_party/protobuf/cpp_features.proto";

option features = field_presence: EXPLICIT
enum_type: CLOSED
;
option objc_class_prefix = "GSPEV";
option java_multiple_files = true;
option java_outer_classname = "ChargingArchitectureSpecProto";
option java_package = "com.google.geo.serving.proto.electricvehicle";

message ChargingArchitectureSpec {
    repeated SupportedChargingArchitecture supported_charging_architectures = 1;
    message SupportedChargingArchitecture {
        optional ChargingArchitecture architecture = 1;
        optional int32 max_power_watts = 2;
    }
}
