syntax = "editions";

package maps_dynamicworld;

import "storage/datapol/annotations/proto/semantic_annotations.proto";

option java_multiple_files = true;
option java_outer_classname = "MajorEventCategoryProto";
option java_package = "com.google.maps.dynamicworld.proto";

enum GeoEventCategory {
    option features = enum_type: CLOSED
    ;
    EVENT_CATEGORY_UNKNOWN = 0;
    EVENT_CATEGORY_SPORTS = 1;
    EVENT_CATEGORY_RACE = 17;
    EVENT_CATEGORY_RUNNING_RACE = 273;
    EVENT_CATEGORY_CAR_RACE = 274;
    EVENT_CATEGORY_HORSE_RACE = 275;
    EVENT_CATEGORY_CYCLING_RACE = 276;
    EVENT_CATEGORY_FITNESS = 18;
    EVENT_CATEGORY_SPORTS_MATCH = 19;
    EVENT_CATEGORY_BASEBALL = 305;
    EVENT_CATEGORY_BASKETBALL = 306;
    EVENT_CATEGORY_AMERICAN_FOOTBALL = 307;
    EVENT_CATEGORY_SOCCER = 308;
    EVENT_CATEGORY_CRICKET = 309;
    EVENT_CATEGORY_ICE_HOCKEY = 310;
    EVENT_CATEGORY_GROUP_SPORTS = 20;
    EVENT_CATEGORY_CELEBRATION = 2;
    EVENT_CATEGORY_RELIGIOUS_CELEBRATION = 33;
    EVENT_CATEGORY_PARADE = 34;
    EVENT_CATEGORY_FAIR = 35;
    EVENT_CATEGORY_MUSIC = 3;
    EVENT_CATEGORY_CONCERT = 49;
    EVENT_CATEGORY_MUSIC_FESTIVAL = 50;
    EVENT_CATEGORY_MUSIC_CLASS = 51;
    EVENT_CATEGORY_ART = 4;
    EVENT_CATEGORY_FASHION_SHOW = 65;
    EVENT_CATEGORY_FILM = 66;
    EVENT_CATEGORY_THEATER = 67;
    EVENT_CATEGORY_COMEDY_SHOW = 68;
    EVENT_CATEGORY_FOOD_AND_DRINK = 5;
    EVENT_CATEGORY_WINE = 81;
    EVENT_CATEGORY_BEER = 82;
    EVENT_CATEGORY_CONVENTION = 6;
    EVENT_CATEGORY_CRISIS = 7;
    EVENT_CATEGORY_COMMUNITY = 8;
    EVENT_CATEGORY_PEDESTRIAN_STREET = 9;
}
