syntax = "proto2";

package search.rendering.xuikit.elements;

import "google/api/inclusion.proto";
import "google/protobuf/any.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option objc_class_prefix = "XUI";
option java_multiple_files = true;
option java_package = "com.google.search.rendering.xuikit.elements";

message DataStoreMutationPayload {
    optional google.protobuf.Any payload = 1;
    
    extensions 2, 3, 4, 5, 6, 7, 9, 10, 11;
    
    reserved 8;
}
