syntax = "editions";

package localsearch.lite;

import "logs/proto/logs_annotations/logs_annotations.proto";
import "net/proto2/bridge/proto/message_set.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option java_package = "com.google.localsearch.lite";

message IntentScore {
    optional IntentType intent = 3;
    optional float score = 2;
    
    reserved 1;
}

message IntentScoreList {
    repeated IntentScore intent_scores = 1;
    
    extend .proto2.bridge.MessageSet {
        optional IntentScoreList message_set_extension = 165945336;
    }
}

enum IntentType {
    option features = enum_type: CLOSED
    ;
    INVALID = 0;
    AADHAR_CENTERS = 413;
    ACAI_SHOPS = 432;
    ACARAJE_RESTAURANTS = 440;
    AERIAL_INSTALLATION_SERVICE = 215;
    AIRPODS = 385;
    AIRPORTS = 378;
    AIR_CONDITIONING_CONTRACTORS = 217;
    AIR_DUCT_CLEANING_SERVICE = 225;
    AMERICAN_RESTAURANTS = 171;
    AMUSEMENT_CENTERS = 15;
    AMUSEMENT_PARKS = 16;
    AMUSEMENT_PARK_RIDES = 17;
    ANGANWADI_CENTERS = 417;
    ANIMAL_SHELTERS = 387;
    APARTMENTS = 404;
    APERITIVO = 157;
    APPLIANCE_REPAIR_SERVICE = 244;
    ART_GALLERIES = 18;
    ART_MUSEUMS = 146;
    ART_SCHOOLS = 19;
    ASIAN_RESTAURANTS = 399;
    ASPHALT_CONTRACTORS = 247;
    ASSAMESE_RESTAURANTS = 429;
    ATMS = 131;
    ATTRACTIONS = 20;
    AUTO_BODY_SHOPS = 338;
    AUTO_GLASS_SHOPS = 214;
    AUTO_PARTS_STORES = 290;
    AUTO_REPAIR_SHOPS = 275;
    AUTO_RESTORATION_SERVICE = 339;
    AUTO_RICKSHAW_STAND = 421;
    AYAM_PENYET_RESTAURANTS = 447;
    BABY_STORES = 462;
    BAGELS = 392;
    BAKERIES = 148;
    BANGLE_SHOPS = 414;
    BANKS = 130;
    BANQUET_HALLS = 194;
    BARBECUE_RESTAURANTS = 172;
    BARBER_SHOPS = 291;
    BARS = 3;
    BATHROOM_REMODELERS = 266;
    BATIK_CLOTHING_STORES = 419;
    BEACHES = 105;
    BEAUTY_SALONS = 21;
    BEAUTY_SUPPLIES = 11;
    BEER_STORES = 292;
    BENTO = 151;
    BIKESHARE = 406;
    BIKE_SHOPS = 386;
    BIKE_WASH = 416;
    BIKING = 106;
    BINGO_HALLS = 22;
    BOARDING_SCHOOLS = 455;
    BOAT_RAMPS = 458;
    BOAT_RENTALS = 107;
    BOOK_STORES = 23;
    BOUNCY_CASTLE_HIRE = 268;
    BOWLING_ALLEYS = 24;
    BREAKFAST = 80;
    BREWERIES = 187;
    BRUNCH = 84;
    BUBBLE_TEA = 293;
    BUFFETS = 294;
    CABARET_CLUBS = 25;
    CAFES = 2;
    CAKE = 295;
    CAMPGROUNDS = 108;
    CANNABIS_DISPENSARIES = 296;
    CARPENTERS = 235;
    CARPET_CLEANING_SERVICE = 203;
    CAR_DEALERS = 150;
    CAR_DETAILING_SERVICE = 340;
    CAR_LEASING_SERVICE = 341;
    CAR_RENTALS = 132;
    CAR_REPAIR = 133;
    CAR_WASH = 134;
    CASINOS = 26;
    CATERING_SERVICE = 197;
    CATHOLIC_CHURCHES = 297;
    CATHOLIC_SCHOOLS = 449;
    CBD = 396;
    CELL_PHONE_STORES = 460;
    CENDOL_RESTAURANTS = 446;
    CHARTER_SCHOOLS = 450;
    CHILDRENS_PARTY_BUFFETS = 212;
    CHILDRENS_PARTY_SERVICE = 223;
    CHIMNEY_SWEEPS = 206;
    CHINESE_RESTAURANTS = 173;
    CHIROPRACTORS = 383;
    CHOP_BARS = 435;
    CHURCHES = 298;
    CIRCUSES = 27;
    CLEANERS = 232;
    CLEANING_SERVICE = 274;
    CLINICS = 137;
    CLOTHING_STORES = 5;
    COFFEE = 83;
    COFFEE_SHOPS = 403;
    COMMERCIAL_PRINTERS = 342;
    COMMUNITY_CENTERS = 121;
    COMPUTER_REPAIR_SERVICE = 219;
    COMPUTER_SUPPORT_SERVICE = 343;
    CONCRETE_CONTRACTORS = 273;
    CONSTRUCTION_COMPANIES = 205;
    CONTRACTORS = 261;
    CONVENIENCE_STORES = 12;
    CORPORATE_OFFICES = 405;
    COURIER_SERVICES = 299;
    CULINARY_SCHOOLS = 28;
    CYCLE_RICKSHAW_STAND = 422;
    DANCE_CLUBS = 29;
    DANCE_SCHOOLS = 109;
    DAY_CARE_CENTERS = 344;
    DEBRIS_REMOVAL_SERVICE = 269;
    DECK_BUILDERS = 192;
    DELIVERY = 87;
    DENTISTS = 300;
    DERMATOLOGISTS = 301;
    DESSERT = 85;
    DIGITAL_PRINTERS = 345;
    DINERS = 393;
    DINNER = 82;
    DISCOS = 30;
    DJS = 270;
    DMV = 302;
    DOCTORS = 303;
    DOG_DAY_CARE_CENTERS = 249;
    DOG_TRAINERS = 209;
    DOLLAR_STORES = 304;
    DONBURI = 153;
    DONUT_SHOPS = 289;
    DRIVING_SCHOOLS = 305;
    DRONE_SHOPS = 412;
    DRUGSTORES = 168;
    DRY_CLEANERS = 135;
    DRY_WALL_CONTRACTORS = 276;
    DUTY_FREE_STORES = 461;
    ELECTRICIANS = 165;
    ELECTRIC_VEHICLE_CHARGING = 160;
    ELECTRONICS = 9;
    ELECTRONICS_REPAIR_SHOPS = 239;
    ENT_DOCTORS = 306;
    EQUIPMENT_RENTAL_AGENCIES = 346;
    ESCAPE_ROOMS = 389;
    EVENT_MANAGEMENT_COMPANIES = 218;
    EVENT_PLANNERS = 202;
    EYE_DOCTORS = 384;
    FARMERS_MARKETS = 31;
    FAST_FOOD_RESTAURANTS = 174;
    FENCE_CONTRACTORS = 229;
    FISHING_AND_HUNTING = 33;
    FITNESS_CENTERS = 32;
    FLEA_MARKETS = 34;
    FLOORING_CONTRACTORS = 191;
    FLOWERS = 373;
    FOOD = 334;
    FRENCH_RESTAURANTS = 175;
    FURNITURE_STORES = 374;
    GARAGE_DOOR_SUPPLIERS = 347;
    GARBAGE_DUMPS = 307;
    GARDENERS = 237;
    GAS_STATIONS = 129;
    GAY_BARS = 308;
    GENERAL_CONTRACTORS = 238;
    GLASS_REPAIR_SERVICE = 196;
    GOLF_COURSES = 110;
    GOVERNMENT_RATION_SHOPS = 410;
    GO_KART_TRACKS = 35;
    GRAMMAR_SCHOOLS = 451;
    GRAPHIC_DESIGNERS = 241;
    GROCERIES = 7;
    GUNS = 400;
    GUTTER_CLEANING_SERVICE = 259;
    GYMNASTICS_CENTERS = 36;
    GYMS = 70;
    GYNECOLOGISTS = 309;
    HAIRCUT = 372;
    HAIR_SALONS = 286;
    HALAL_RESTAURANTS = 310;
    HALLOWEEN_COSTUMES = 376;
    HAMBURGER_RESTAURANTS = 176;
    HANDICRAFT_FAIRS = 37;
    HANDYMAN = 262;
    HARDWARE_STORES = 285;
    HAUNTED_HOUSES = 38;
    HEALTH_AND_BEAUTY_SHOPS = 365;
    HEATING_CONTRACTORS = 278;
    HEATING_EQUIPMENT_SUPPLIERS = 231;
    HIKING = 311;
    HISTORICAL_LANDMARKS = 40;
    HISTORIC_SITES = 39;
    HOBBY_CLASSES = 41;
    HOME_CLEANERS = 163;
    HOME_IMPROVEMENT_STORES = 8;
    HOME_INSPECTORS = 348;
    HOSPITALS = 136;
    HOTELS = 128;
    HVAC_SERVICE = 164;
    ICE_CREAM = 188;
    INDIAN_RESTAURANTS = 177;
    INDIAN_SWEETS_SHOPS = 407;
    INSTRUCTORS = 42;
    INSULATION_CONTRACTORS = 226;
    INSURANCE_AGENCIES = 349;
    INTERIOR_DESIGNERS = 350;
    INTERNET_CAFES = 312;
    INTERNET_MARKETING_SERVICE = 351;
    IPHONE = 380;
    ITALIAN_RESTAURANTS = 178;
    IZAKAYA = 149;
    JAPANESE_RESTAURANTS = 179;
    JAZZ_CLUBS = 43;
    JEWELRY_STORES = 367;
    JUICE_SHOPS = 156;
    JUNKYARDS = 401;
    KARAOKES = 44;
    KEY_DUPLICATION_SERVICE = 216;
    KINDERGARTENS = 448;
    KOSHARI_RESTAURANTS = 444;
    LANDSCAPERS = 199;
    LANDSCAPE_DESIGNERS = 250;
    LASER_TAG_CENTERS = 45;
    LAUNDRY = 313;
    LAWN_CARE_SERVICE = 230;
    LAWN_SPRINKLER_SYSTEM_CONTRACTORS = 280;
    LECHON_RESTAURANTS = 445;
    LIBRARIES = 122;
    LIMOUSINE_SERVICE = 279;
    LIQUOR_STORES = 189;
    LIVE_MUSIC_VENUES = 46;
    LOAN_AGENCIES = 352;
    LOCKSMITHS = 193;
    LOCK_STORES = 411;
    LUNCH = 81;
    MAGICIANS = 255;
    MAIL = 138;
    MAKEUP_ARTISTS = 353;
    MALLS = 314;
    MARINE_PARKS = 47;
    MARRIAGE_COUNSELORS = 354;
    MARTIAL_ARTS = 111;
    MASONRY_CONTRACTORS = 236;
    MASSAGE = 48;
    MATTRESSES = 394;
    MAZES = 49;
    MECHANICS = 213;
    MEDITATION_CENTERS = 50;
    MEDITERRANEAN_RESTAURANTS = 180;
    MEXICAN_RESTAURANTS = 181;
    MIDDLE_SCHOOLS = 456;
    MINIATURE_GOLF_COURSES = 51;
    MOBILE_PHONE_REPAIR_SHOPS = 265;
    MOMO_RESTAURANTS = 428;
    MONTESSORI_SCHOOLS = 452;
    MOSQUES = 315;
    MOTELS = 382;
    MOTORCYCLE_REPAIR_SHOPS = 355;
    MOVIES = 88;
    MOVING_AND_STORAGE_SERVICE = 204;
    MOVING_COMPANIES = 228;
    MUSALLA = 423;
    MUSEUMS = 53;
    MUSIC = 116;
    MUSICAL_INSTRUMENT_REPAIR_SHOPS = 263;
    MUSIC_AND_ART_SCHOOLS = 54;
    MUSIC_INSTRUCTORS = 257;
    MUSIC_SCHOOLS = 272;
    NAIL_SALONS = 117;
    NASI_RESTAURANTS = 424;
    NIGHTLIFE = 144;
    NIGHT_CLUBS = 55;
    NIGHT_MARKETS = 56;
    ODIA_RESTAURANTS = 430;
    OIL_CHANGE = 316;
    OUTDOOR_ACTIVITIES = 57;
    OUTDOOR_LEISURE = 58;
    PAAN_SHOPS = 408;
    PAINTBALL_CENTERS = 59;
    PAINTERS = 246;
    PAISA_RESTAURANTS = 443;
    PANIPURI_SHOPS = 437;
    PARKING = 140;
    PARKS = 60;
    PARTY_EQUIPMENT_RENTAL_SERVICE = 271;
    PARTY_PLANNERS = 195;
    PAVING_CONTRACTORS = 198;
    PAWN_SHOPS = 317;
    PAY_BY_WEIGHT_RESTAURANTS = 434;
    PERFORMING_ARTS = 61;
    PERFORMING_ARTS_THEATERS = 123;
    PEST_CONTROL_SERVICE = 211;
    PET_BOARDING_SERVICE = 243;
    PET_CARE = 260;
    PET_GROOMERS = 224;
    PET_SITTERS = 245;
    PET_STORES = 318;
    PHARMACIES = 13;
    PHO = 319;
    PHONE_REPAIR_SERVICE = 256;
    PHOTOGRAPHERS = 227;
    PHOTOGRAPHY_STUDIOS = 320;
    PHYSICAL_THERAPISTS = 321;
    PICNIC_GROUNDS = 62;
    PIERCING = 390;
    PIZZA = 159;
    PLANETARIUMS = 63;
    PLAYGROUNDS = 64;
    PLUMBERS = 166;
    POKE = 398;
    POKE_BARS = 433;
    POOL_CLEANING_SERVICE = 201;
    POOL_HALLS = 65;
    PORTRAIT_STUDIOS = 356;
    POST_OFFICES = 287;
    PRESSURE_WASHING_SERVICE = 207;
    PRIMARY_SCHOOLS = 335;
    PRIVATE_SCHOOLS = 453;
    PRIVATE_TUTORS = 420;
    PUBLIC_SCHOOLS = 454;
    PUBS = 147;
    RAMEN = 152;
    REALTORS = 381;
    RECREATION_CENTERS = 118;
    REMODELERS = 253;
    RENOVATION_CONTRACTORS = 258;
    REPAIR_SERVICE = 281;
    RESERVATIONS = 369;
    RESTAURANTS = 1;
    REST_STOPS = 190;
    RODEOS = 67;
    ROOFERS = 162;
    SANDWICH_SHOPS = 183;
    SAREE_SHOPS = 409;
    SCHOOLS = 322;
    SCREEN_REPAIR_SERVICE = 233;
    SEAFOOD_RESTAURANTS = 184;
    SEA_SIDE_WALK = 68;
    SEBLAK_RESTAURANTS = 426;
    SECONDARY_SCHOOLS = 336;
    SECURITY_SYSTEM_INSTALLERS = 251;
    SELF_STORAGE = 323;
    SEX_TOYS = 388;
    SHAWARMA_RESTAURANTS = 436;
    SHIPPING = 139;
    SHOE_STORES = 366;
    SHOPPING = 14;
    SHOPPING_CENTERS = 6;
    SKIING = 112;
    SKI_RESORTS = 71;
    SMOKE_SHOPS = 324;
    SMOOTHIES = 402;
    SOCCER_CLUBS = 113;
    SOTO_RESTAURANTS = 427;
    SPANISH_RESTAURANTS = 185;
    SPAS = 69;
    SPECIAL_EDUCATION_SCHOOLS = 457;
    SPORTING_GOODS_STORES = 10;
    SPORTS_BARS = 391;
    STADIUMS = 368;
    STEAK_RESTAURANTS = 186;
    STORES = 377;
    STRIP_CLUBS = 325;
    SUPERMARKETS = 169;
    SUSHI_RESTAURANTS = 182;
    SWIMMING = 114;
    SWIMMING_INSTRUCTORS = 267;
    SWIMMING_POOL_REPAIR_SERVICE = 264;
    TACACA_RESTAURANTS = 441;
    TACOS = 326;
    TAILORS = 357;
    TAKEOUT = 86;
    TAPAS = 155;
    TATTOO_SHOPS = 375;
    TAXI = 397;
    TEGAL_RESTAURANTS = 425;
    TEISHOKU = 154;
    TELEVISION_REPAIR_SERVICE = 210;
    TEMAKI_RESTAURANTS = 439;
    THAI_RESTAURANTS = 170;
    THRIFT_STORES = 327;
    TIFFIN_CENTERS = 431;
    TIRE_REPAIR_SHOPS = 415;
    TIRE_SHOPS = 328;
    TORTILLA_SHOPS = 442;
    TOURIST_ATTRACTIONS = 119;
    TOURIST_INFORMATION_CENTERS = 72;
    TOURS = 120;
    TOWING_SERVICE = 358;
    TRADITIONAL_MARKETS = 73;
    TRAILS = 125;
    TRAINING_COURSES = 74;
    TRAMPOLINE_PARKS = 115;
    TRANSPORTATION_SERVICE = 200;
    TRAVEL_AGENCIES = 359;
    TREE_SERVICE = 221;
    TRUCK_STOPS = 288;
    UNIVERSITIES = 337;
    UPHOLSTERY_CLEANING_SERVICE = 240;
    URGENT_CARE = 371;
    USED_CAR_DEALERS = 329;
    UTILITY_CONTRACTORS = 222;
    VAPE_SHOPS = 330;
    VEGAN_RESTAURANTS = 331;
    VEGETARIAN_RESTAURANTS = 332;
    VETERINARIANS = 379;
    VETERINARY_CARE = 459;
    VIDEO_ARCADES = 75;
    VINYL_SIGN_SHOPS = 418;
    VISTA_POINTS = 76;
    WASHER_AND_DRYER_REPAIR_SERVICE = 220;
    WASTE_MANAGEMENT_SERVICE = 360;
    WATER_DAMAGE_RESTORATION_SERVICE = 242;
    WATER_PARKS = 77;
    WEBSITE_DESIGNERS = 361;
    WEDDING_BUFFETS = 234;
    WEDDING_PHOTOGRAPHERS = 248;
    WEDDING_PLANNERS = 362;
    WEDDING_SERVICE = 363;
    WEDDING_VENUES = 364;
    WINDOW_CLEANING_SERVICE = 252;
    WINDOW_INSTALLATION_SERVICE = 208;
    WINDOW_SUPPLIERS = 254;
    WINDOW_TINTING_SERVICE = 277;
    WINERIES = 395;
    WINE_STORES = 333;
    YAKISOBA_RESTAURANTS = 438;
    YOGA = 124;
    ZOOS = 78;
    DINING = 4;
    THINGS_TO_DO = 79;
    ART = 145;
    OUTDOORS = 89;
    FITNESS_AND_SPORTS = 90;
    ARTS_AND_CULTURE = 100;
    ATTRACTIONS_COMPOUND = 101;
    NIGHTLIFE_COMPOUND = 102;
    GAMES_AND_ARCADES = 103;
    WELLNESS_AND_BEAUTY = 104;
    BANKS_AND_ATMS = 141;
    HOSPITALS_AND_CLINICS = 142;
    MAIL_AND_SHIPPING = 143;
    ICONIC_PLACES = 158;
    POPULAR_PLACES_NOW = 161;
    STRUCTURED_CHAIN = 370;
}
