syntax = "proto2";

package maps_tactile;

import "google/api/inclusion.proto";
import "logs/proto/logs_annotations/logs_annotations.proto";

option objc_class_prefix = "GMTT";
option java_multiple_files = true;
option java_outer_classname = "LoggingCommonProto";
option java_package = "com.google.maps.tactile";

enum GeoProduct {
    PROPERTY_UNKNOWN = 0;
    PROPERTY_GOOGLE = 1;
    PROPERTY_HOTELS = 74;
    PROPERTY_GMM_OLD = 78;
    PROPERTY_GMM = 89;
    PROPERTY_TACTILE = 81;
    PROPERTY_TACTILE_EMBED = 90;
    PROPERTY_HANGOUTS = 93;
    PROPERTY_MAPS_ACTIVITIES = 94;
    PROPERTY_EARTH = 96;
    PROPERTY_MAPS_API_V3 = 98;
    PROPERTY_CUSTOM_ANALYSIS = 100;
    PROPERTY_GOOGLE_PLUS_LOCAL = 101;
    PROPERTY_PLACES_API = 103;
    PROPERTY_LOCAL_ACTIONS_BATCH = 104;
    PROPERTY_LOCAL_GROWTH_IME_BATCH = 202;
    PROPERTY_MAPS_LITE_DESKTOP = 107 [deprecated = true];
    PROPERTY_MAPS_LITE_MOBILE = 108 [deprecated = true];
    PROPERTY_GOOGLE_NOW = 111;
    PROPERTY_REVIEWS_WIDGET = 112;
    PROPERTY_REVIEWS_WIDGET_BASIC_HTML = 127 [deprecated = true];
    PROPERTY_BIGTOP = 113;
    PROPERTY_GEOCODING_API = 114;
    PROPERTY_IMAGERY_VIEWER = 115;
    PROPERTY_TRAVEL_HOTELS_GCS_REVIEWS_BATCH = 116;
    PROPERTY_GOOGLE_MY_BUSINESS = 120;
    PROPERTY_GOOGLE_MY_BUSINESS_API = 124;
    PROPERTY_LOCAL_SEARCH_UI_OWNER_REPLY = 146;
    PROPERTY_GOOGLE_MY_BUSINESS_DASHBOARD = 147;
    PROPERTY_GOOGLE_MY_BUSINESS_REVIEWS_CENTRE = 148;
    PROPERTY_GOOGLE_MY_BUSINESS_ANDROID = 149;
    PROPERTY_GOOGLE_MY_BUSINESS_IOS = 150;
    PROPERTY_NOTIFICATIONS_BATCH = 122;
    PROPERTY_ASSISTANT = 125;
    PROPERTY_ONTHEGO = 128;
    PROPERTY_GEO_METRIC = 129;
    PROPERTY_PRESTO = 131;
    PROPERTY_IOS_GSA = 132;
    PROPERTY_PLACE_QA_NOTIFICATIONS = 134;
    PROPERTY_GEO_AR = 135;
    PROPERTY_MERCHANT_NOTIFICATIONS_GSA = 138;
    PROPERTY_MAPS_LITE_PWA = 140;
    PROPERTY_GEO_DISCOVERY_NOTIFICATION = 143;
    PROPERTY_ANDROID_ONBOARDING = 151;
    PROPERTY_RIDDLER_FOLLOW_ON = 152;
    PROPERTY_GEO_DISCOVERY_EXEMPLAR_FLOW = 153;
    PROPERTY_TAKEOUT = 154;
    PROPERTY_LOCAL_SERVICES_API = 156;
    PROPERTY_USER_POSTS_RAP = 157;
    PROPERTY_GEO_REVIEW_AT_A_PLACE_NOTIFICATION = 158;
    PROPERTY_MY_ACCOUNT = 160;
    PROPERTY_HOTELS_SEARCH = 161;
    PROPERTY_MAPS_COMPANION = 162;
    PROPERTY_ADS_INTEGRITY = 163;
    PROPERTY_LENS_APP = 164;
    PROPERTY_UGC_BADGES = 165;
    PROPERTY_GEO_SERVICE_RECOMMENDATION_POST_INTERACTION_NOTIFICATION = 167 [deprecated = true];
    PROPERTY_INTERNAL_TESTING = 168;
    PROPERTY_MAPS_PERSONALIZATION_SERVER = 169;
    PROPERTY_TRAVEL_DESTINATIONS = 170;
    PROPERTY_CHATTY_QUOTES = 171;
    PROPERTY_GEO_UGC_CONTENT_FEEDBACK = 174;
    PROPERTY_GEO_PEOPLE_FOLLOW = 176;
    PROPERTY_POST_REVIEW_THUMBS_UP_NOTIFICATION = 177;
    PROPERTY_ADS_BATCH = 181;
    PROPERTY_ROADS_UGC_EDITOR = 184;
    PROPERTY_PHOTOS = 32;
    PROPERTY_GMB_REVIEWS_SUPPORT_SERVICE = 185;
    PROPERTY_ONE_TRAVEL = 186;
    PROPERTY_DOCS_EDITORS = 187;
    PROPERTY_AMBIENT_ASSISTANT = 188;
    PROPERTY_MADDEN_FRONTEND = 189;
    PROPERTY_LEGAL_REMOVALS_TOOL = 190;
    PROPERTY_PRAYOG = 191;
    PROPERTY_NEW_ROMAN = 194;
    PROPERTY_BWB = 195;
    PROPERTY_WGMM = 196;
    PROPERTY_KARTO = 197;
    PROPERTY_DUPLEX = 198;
    PROPERTY_GSR_ISA = 199;
    PROPERTY_GOOGLE_PAY_FOR_BUSINESS = 200;
    PROPERTY_ARTS_AND_CULTURE = 201;
    PROPERTY_BARD_WEB = 203;
    PROPERTY_GOOGLE_PAY_CONSUMER_APP = 204;
    PROPERTY_SEARCH_FEEDBACK = 206;
    PROPERTY_LEGAL_TAKEOUT = 207;
    PROPERTY_STREET_VIEW_PUBLISH_API = 208;
    PROPERTY_PIXEL_SPOON_SERVING = 209;
    PROPERTY_GEOVIBES = 210;
    PROPERTY_ASK_MAPS_WORLD_SIMULATION_BATCH = 211;
    PROPERTY_MAPS_BOTS_UI = 212;
    PROPERTY_YOUTUBE_MAPS_CONTENT_VIDEOS_BATCH = 213;
}

enum ParkingDifficultyLevel {
    UNKNOWN_PARKING_DIFFICULTY = 0;
    EASY = 1;
    MEDIUM = 2;
    HARD = 3;
}
