syntax = "editions";

package geo.earth.app;

import "java/com/google/apps/jspb/jspb.proto";
import "logs/proto/geo/earth/app/deeplink_event.proto";
import "logs/proto/geo/earth/app/earthfeed_event.proto";
import "logs/proto/geo/earth/app/experiment_flags.proto";
import "logs/proto/geo/earth/app/mirthstats_event.proto";
import "logs/proto/geo/earth/app/nativelibraryload_event.proto";
import "logs/proto/geo/earth/app/settings_event.proto";
import "logs/proto/geo/earth/app/startupfinished_event.proto";
import "logs/proto/geo/earth/app/usersettings_event.proto";
import "privacy/pattributes/annotations/proto_field.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";
import "third_party/protobuf/cpp_features.proto";

option features = enum_type: CLOSED
utf8_validation: NONE
;
option objc_class_prefix = "RTH";
option java_outer_classname = "EarthLogProto";
option java_package = "com.google.geo.earth.app";

message EarthEvent {
    optional Type type = 1;
    enum Type {
        UNKNOWN = 0;
        CRASH = 1;
        LOAD_COMPLETE = 2;
        STARTUP_FINISHED = 3;
        GRAPHICS_CONTEXT_LOST = 4;
        STARTUP_UNFINISHED = 5;
        NOT_ENOUGH_MEMORY_TO_START = 6;
        CONFIG_REQUEST_SUCCESS = 7;
        CONFIG_REQUEST_FAILURE = 8;
        NETWORK_REQUEST_FAILURE = 9;
        DELAYED_STARTUP_FINISHED_STD_PLAN = 10;
        DELAYED_STARTUP_FINISHED_PRO_PLAN = 11;
        DELAYED_STARTUP_FINISHED_PRO_ADV_PLAN = 12;
        SESSION_START = 101;
        SESSION_END = 102;
        IOS_APP_STORE_REDIRECT = 103;
        ANDROID_APP_STORE_REDIRECT = 104;
        USER_CANCEL_MOBILE_REDIRECT = 105;
        LOW_MEMORY_WARNING = 106;
        CLEAR_CACHE = 107;
        CACHE_SIZE_CHANGED = 108;
        HELP_OPENED = 109;
        FEEDBACK_OPENED = 110;
        FEEDBACK_COMPLETED = 111;
        SETTINGS_OPENED = 112;
        ACCESSIBILITY_ENABLED = 113;
        CONFIGURATION_PHONE = 114;
        CONFIGURATION_TABLET = 115;
        CONFIGURATION_PORTRAIT = 116;
        CONFIGURATION_LANDSCAPE = 117;
        LAYOUT_DIRECTION_LTR = 118;
        LAYOUT_DIRECTION_RTL = 119;
        SETTINGS_CHANGED = 120;
        CONFIGURATION_MULTITASKING = 121;
        SHORTCUT_VOYAGER = 122;
        SHORTCUT_FEELINGLUCKY = 123;
        SHORTCUT_MYLOCATION = 124;
        BACKGROUND_OUT_OF_MEMORY_TERMINATION = 125;
        FOREGROUND_OUT_OF_MEMORY_TERMINATION = 126;
        KC_OPENED = 201;
        KC_AUTO_CLOSED = 202;
        KC_CLOSED_NORMAL = 203;
        KC_CLOSED_COLLAPSED = 204;
        KC_OPEN_COLLAPSED = 205;
        KC_EXPAND = 206;
        KC_COLLAPSED_EXPANDED = 207;
        KC_SWIPE_NEXT = 208;
        KC_SWIPE_PREVIOUS = 209;
        KC_SWIPE_NEXT_EXPANDED = 210;
        KC_SWIPE_PREVIOUS_EXPANDED = 211;
        KC_FLYTO = 212;
        KC_SCROLL_EXPANDED = 213;
        KC_ATTRIBUTION_CLICK = 214;
        KC_MAPS_CLICK = 215;
        KC_NORMAL_COLLAPSED = 216;
        KC_SEE_ANOTHER_FUN_FACT_CLICK = 217;
        DROPPED_PIN_MEASURE_ACTION_SELECTED = 218;
        DROPPED_PIN_OPENED = 219;
        KC_ADD_TO_PROJECT = 220;
        DROPPED_PIN_CLOSE_SELECTED = 221;
        KC_REPLACE_CONTENTS = 222;
        SEARCH_OPEN = 301;
        SEARCH_CLOSED = 302;
        SEARCH_SUGGESTION_CLICK = 303;
        SEARCH_START = 304;
        SEARCH_RESULT_CLICK = 305 [deprecated = true];
        SEARCH_NEXT_PAGE = 306;
        SEARCH_PREVIOUS_PAGE = 307;
        SEARCH_PIN_CLICK = 308;
        VOYAGER_SEARCH_SUGGESTION_CLICK = 309;
        SEARCH_HISTORY_SUGGESTION_CLICK = 310;
        VOICE_SEARCH_START = 311;
        CLEAR_SEARCH_HISTORY_CLICK = 312;
        SEARCH_FEELING_LUCKY_CLICK = 313;
        SEARCH_OPEN_VOYAGER_GRID_CLICK = 314;
        SEARCH_VIEW_SEARCH_HISTORY_CLICK = 315;
        SEARCH_SUGGEST_RESULT_GROUP_IMPRESSION = 316;
        SEARCH_SUGGEST_RESULT_GROUP_CLICK = 317;
        SEARCH_RESULT_GROUP_CLICK = 318;
        SEARCH_ZERO_STATE_SHOWN = 319;
        SEARCH_SUGGEST_GROUP_ACTION_CLICK = 320;
        SEARCH_ERROR = 321;
        SEARCH_KNOWLEDGE_CARD_OPENED = 322;
        SEARCH_CLOUD_PROJECT_OPENED = 323;
        SEARCH_LOCAL_PROJECT_OPENED = 324;
        SEARCH_PERFORM_SEARCH_FROM_HISTORY = 325;
        EARTH_FEED_GRID_OPENED = 401;
        EARTH_FEED_GRID_CLOSED = 402;
        TOUR_STARTED = 403;
        TOUR_STOPPED = 404;
        TOUR_ENDED = 405;
        TOUR_DISMISSED = 406;
        EARTH_FEED_ITEM_CLICKED = 407;
        EARTH_FEED_CAROUSEL_ITEM_CLICKED = 408;
        EARTH_FEED_CAROUSEL_PREVIOUS_CLICKED = 409;
        EARTH_FEED_CAROUSEL_NEXT_CLICKED = 410;
        EARTH_FEED_FEATURE_OPENED = 411;
        EARTH_FEED_ITEM_DEEP_LINK = 412;
        EARTH_FEED_NON_KML_LINK_CLICKED = 413;
        PANEL_BALLOON_COLLAPSED = 414;
        PANEL_BALLOON_MIDDLE = 415;
        PANEL_BALLOON_FULLSCREEN = 416;
        PANEL_BALLOON_YOUTUBE_PLAYED = 417;
        PANEL_BALLOON_YOUTUBE_APP_LAUNCHED = 418;
        STREET_VIEW_ENTER = 501;
        STREET_VIEW_LEAVE = 502;
        STREET_VIEW_COVERAGE_ON = 503;
        STREET_VIEW_COVERAGE_OFF = 504;
        PEGMAN_DRAGGED = 505;
        PEGMAN_DRAGGED_TO_EDGE_AND_PAN_VIEW = 506;
        STREET_VIEW_SLINGSHOT_ACTIVATED = 507;
        STREET_VIEW_COVERAGE_TOAST_DISMISSED = 508;
        STREET_VIEW_PANO_CHANGED = 509;
        STREET_VIEW_PANO_CAPTURED = 510;
        STREET_VIEW_PANO_SHARED = 511;
        STREET_VIEW_TIMELINE_ENTER = 512;
        STREET_VIEW_TIMELINE_EXIT = 513;
        STREET_VIEW_TIMELINE_NEXT = 514;
        STREET_VIEW_TIMELINE_PREVIOUS = 515;
        STREET_VIEW_TIMELINE_DATE_SELECTED = 516;
        STREET_VIEW_TIMELINE_COLLAPSED = 517;
        STREET_VIEW_TIMELINE_EXPANDED = 518;
        MAP_STYLE_ITEM_SELECTED = 601;
        MAP_STYLE_CATEGORY_TOGGLE = 602;
        MAP_STYLE_THREE_D_IMAGERY_TOGGLE = 603;
        MAP_STYLE_THREE_D_IMAGERY_TOGGLE_PROMOTION_TOAST_SHOWN = 604;
        MAP_STYLE_THREE_D_IMAGERY_TOGGLE_PROMOTION_TOAST_TAPPED = 605;
        MAP_STYLE_CLOUD_ANIMATION_TOGGLE = 606;
        MAP_STYLE_THREE_D_IMAGERY_TOGGLE_OFF = 607;
        MAP_STYLE_THREE_D_IMAGERY_TOGGLE_ON = 608;
        MAP_STYLE_GRIDLINES_TOGGLE = 609;
        MAP_STYLE_CLOUD_ANIMATION_TOGGLE_OFF = 610;
        MAP_STYLE_CLOUD_ANIMATION_TOGGLE_ON = 611;
        MAP_STYLE_GRIDLINES_TOGGLE_NONE = 612;
        MAP_STYLE_GRIDLINES_TOGGLE_LAT_LON = 613;
        MAP_STYLE_ANIMATED_CLOUDS_ON = 614;
        MAP_STYLE_ANIMATED_CLOUDS_OFF = 615;
        MAP_STYLE_TIMELAPSE_ON = 616;
        MAP_STYLE_TIMELAPSE_OFF = 617;
        MAP_STYLE_THREE_D_COVERAGE_LAYER_ON = 618;
        MAP_STYLE_THREE_D_COVERAGE_LAYER_OFF = 619;
        MAP_STYLE_UPDATED_IMAGERY_LAYER_ON = 620;
        MAP_STYLE_UPDATED_IMAGERY_LAYER_OFF = 621;
        MAP_STYLE_HISTORICAL_IMAGERY_ON = 622;
        MAP_STYLE_HISTORICAL_IMAGERY_OFF = 623;
        MAP_STYLE_EV_CHARGERS_DEMO_LAYER_ON = 624 [deprecated = true];
        MAP_STYLE_EV_CHARGERS_DEMO_LAYER_OFF = 625 [deprecated = true];
        MAP_STYLE_EV_DEMAND_LAYER_ON = 626 [deprecated = true];
        MAP_STYLE_EV_DEMAND_LAYER_OFF = 627 [deprecated = true];
        MAP_STYLE_EV_HOUSEHOLD_INCOME_LAYER_ON = 628 [deprecated = true];
        MAP_STYLE_EV_HOUSEHOLD_INCOME_LAYER_OFF = 629 [deprecated = true];
        MAP_STYLE_ABSTRACT_ON = 630;
        MAP_STYLE_ABSTRACT_OFF = 631;
        MAP_STYLE_PINNED_PROJECTS_ON = 632;
        MAP_STYLE_PINNED_PROJECTS_OFF = 633;
        MAP_STYLE_SHOW_PROJECT = 634;
        MAP_STYLE_HIDE_PROJECT = 635;
        BASE_LAYER_TOGGLE = 651;
        MY_LOCATION_TAPPED = 711;
        MY_LOCATION_FAILED = 712;
        MY_LOCATION_TRACKING_STARTED = 713;
        MY_LOCATION_TRACKING_RECENTERED = 714;
        MY_LOCATION_TRACKING_STOPPED = 715;
        MY_LOCATION_TRACKING_AUTO_STOPPED = 716;
        COMPASS_TAPPED = 721;
        COMPASS_DRAGGED = 722;
        COMPASS_HEADING_RING_DRAGGED = 723;
        NAVGLOBE_DOUBLE_TAPPED = 731;
        NAVGLOBE_DRAGGED = 732;
        NAVGLOBE_TAPPED = 733;
        TWO_D_THREE_D_BUTTON_TAPPED = 741;
        RANDOM_CARD_TAPPED = 751;
        ZOOM_IN_TAPPED = 761;
        ZOOM_OUT_TAPPED = 762;
        LEFT_NAV_OPENED = 763;
        PEGMAN_TAPPED = 764;
        TIME_CONTROLS_PLAY_CLICKED = 801;
        TIME_CONTROLS_PAUSE_CLICKED = 802;
        TIME_CONTROLS_SLIDER_INTERACTED = 803;
        PHOTOS_LAYER_ON = 900;
        PHOTOS_LAYER_OFF = 901;
        PHOTOS_LAYER_REQUEST_THUMBNAILS = 902;
        PHOTOS_LAYER_THUMBNAIL_CLICKED = 903;
        IMAGE_SAVE = 1001;
        DRIVE_OPEN_KML = 1002;
        SHARE_LINK = 1003;
        OPEN_MENU_PANEL = 1004;
        CREATE_KML_BOOKMARK = 1005;
        DEEP_LINK_OPENED = 1006;
        CRASH_REPORTING_ACCEPTED = 1007;
        CRASH_REPORTING_DECLINED = 1008;
        SKIP_LINK_ACTIVATED = 1009;
        GEO_URI_OPENED = 1010;
        SCREENSHOT_TAKEN = 1011;
        VIEW_STATUS_EXPANDED = 1012;
        MIRTH_STATS = 1013;
        PRINT_PREVIEW_OPENED = 1014;
        THIRD_PARTY_DOMAIN_WARNING_SHOWN = 1015;
        THIRD_PARTY_DOMAIN_WARNING_DISMISSED = 1016;
        SHARE_URL_LINK_COPIED = 1017;
        SHARE_URL_QR_CODE_COPIED = 1018;
        SHARE_SYSTEM_SHARE_OPEN = 1019;
        GLOBE_SHOWN_WITH_NO_FOCUSED_PROJECT = 1020;
        GLOBE_SHOWN_WITH_FOCUSED_PROJECT = 1021;
        GLOBE_PASTE_FEATURE = 1022;
        PASTE_FEATURE_SUCCESS = 1023;
        PASTE_FEATURE_FAILURE = 1024;
        OUT_OF_BOX_NEXT_CLICKED = 1100;
        OUT_OF_BOX_SKIP_CLICKED = 1101;
        OUT_OF_BOX_RESTART_CLICKED = 1102;
        OUT_OF_BOX_REOPENED = 1103;
        OUT_OF_BOX_DONE_CLICKED = 1104;
        MEASURE_TOOL_STARTED = 1110;
        MEASURE_TOOL_STOPPED = 1111;
        MEASURE_TOOL_DISTANCE = 1112;
        MEASURE_TOOL_AREA = 1113;
        MEASURE_TOOL_ADD_POINT = 1114;
        MEASURE_TOOL_UNDO = 1115;
        MEASURE_TOOL_RESTART = 1116;
        MEASURE_TOOL_HELP_CLICKED = 1117;
        MEASURE_TOOL_DISTANCE_COPIED = 1118;
        MEASURE_TOOL_PERIMETER_COPIED = 1119;
        MEASURE_TOOL_AREA_COPIED = 1120;
        MEASURE_TOOL_DISTANCE_UNIT_MENU_OPENED = 1121;
        MEASURE_TOOL_DISTANCE_UNIT_MENU_DISMISSED = 1122;
        MEASURE_TOOL_DISTANCE_UNIT_SELECTED = 1123;
        MEASURE_TOOL_AREA_UNIT_MENU_OPENED = 1124;
        MEASURE_TOOL_AREA_UNIT_MENU_DISMISSED = 1125;
        MEASURE_TOOL_AREA_UNIT_SELECTED = 1126;
        MEASURE_TOOL_AREA_SAVE_TO_PROJECT = 1127 [deprecated = true];
        MEASURE_TOOL_DISTANCE_SAVE_TO_PROJECT = 1128 [deprecated = true];
        MEASURE_TOOL_ACTIVATED = 1129;
        MEASURE_TOOL_SLOPE_UNIT_MENU_OPENED = 1130;
        MEASURE_TOOL_SLOPE_UNIT_SELECTED = 1131;
        LIGHTBOX_OPENED = 1200;
        LIGHTBOX_CLOSED_BUTTON = 1201;
        LIGHTBOX_CLOSED_SWIPED = 1202;
        LIGHTBOX_NEXT = 1203;
        LIGHTBOX_PREVIOUS = 1204;
        LIGHTBOX_CANCELLED = 1205;
        LIGHTBOX_GALLERY_OPENED = 1206;
        LIGHTBOX_GALLERY_IMAGE_CLICKED = 1207;
        LIGHTBOX_OPENED_AT_IMAGE_INDEX = 1208;
        HI_MODE_ENTER = 1250;
        HI_MODE_EXIT = 1251;
        HI_UI_COLLAPSE = 1252;
        HI_UI_EXPAND = 1253;
        HI_DATE_SELECT = 1254;
        HI_STEP_BACKWARD = 1255;
        HI_STEP_FORWARD = 1256;
        HI_SHOW_LATEST = 1257;
        HI_SHOW_HELP_CLICKED = 1258;
        HI_SWITCH_TO_TIMELAPSE = 1259;
        TIMELAPSE_MODE_ENTER = 1275;
        TIMELAPSE_MODE_EXIT = 1276;
        TIMELAPSE_UI_COLLAPSE = 1277;
        TIMELAPSE_UI_EXPAND = 1278;
        TIMELAPSE_PAUSE = 1279;
        TIMELAPSE_PLAY = 1280;
        TIMELAPSE_CHANGE_SPEED = 1281;
        TIMELAPSE_SWITCH_TO_HI = 1282;
        TIMELAPSE_SHOW_HELP_CLICKED = 1283;
        MYPLACES_OPENED = 1300;
        MYPLACES_CLOSED = 1301;
        MYPLACES_FLYTO_CLICKED = 1302;
        ATOMIC_VIEW_OPENED = 1310;
        ATOMIC_VIEW_CLOSED = 1311;
        MY_PLACES_IMPORTED_KML_FROM_FILE = 1312;
        MY_PLACES_IMPORTED_KML_FROM_DRIVE = 1313;
        MY_PLACES_DOCUMENT_DISCARDED = 1314;
        MY_PLACES_DOCUMENT_SAVED_TO_BROWSER_STORAGE = 1315;
        MY_PLACES_DOCUMENT_VISIBILITY_SHOWN = 1316;
        MY_PLACES_DOCUMENT_VISIBILITY_HIDDEN = 1317;
        MY_PLACES_DOCUMENT_SHOW_BALLOON = 1318;
        MY_PLACES_FLY_TO_DOCUMENT_WITH_DOUBLE_CLICK = 1319;
        MY_PLACES_IMPORTED_TO_CLOUD = 1320;
        PLAY_MODE_START = 1350;
        PLAY_MODE_EXIT = 1351;
        PLAY_MODE_RESTART = 1352;
        PLAY_MODE_RECENTER = 1353;
        PLAY_MODE_NEXT = 1354;
        PLAY_MODE_PREVIOUS = 1355;
        PLAY_MODE_TOC_OPEN = 1356;
        PLAY_MODE_TOC_CLOSE = 1357;
        PLAY_MODE_TOC_SELECT = 1358;
        PLAY_MODE_SHARE = 1359;
        PLAY_MODE_PICK_PLACEMARK = 1360;
        PLAY_MODE_PICK_LINE = 1361;
        PLAY_MODE_PICK_POLYGON = 1362;
        NOTIFICATION_ENROLLMENT_ACCEPTED = 1400;
        NOTIFICATION_ENROLLMENT_DECLINED = 1401;
        NOTIFICATION_TOPIC_SUBSCRIBED = 1402;
        NOTIFICATION_TOPIC_UNSUBSCRIBED = 1403;
        NOTIFICATION_RECEIVED_IN_FOREGROUND = 1404;
        NOTIFICATION_ENROLLMENT_DIALOG_PRESENTED = 1405;
        FLY_ANIMATION_DISABLED = 1500 [deprecated = true];
        FLY_ANIMATION_ENABLED = 1501 [deprecated = true];
        FLY_END_ANIMATION_SETTING_UPDATED = 1502 [deprecated = true];
        TOOLBAR_HOME_SELECTED = 1600;
        TOOLBAR_SEARCH_SELECTED = 1601;
        TOOLBAR_FEED_SELECTED = 1602;
        TOOLBAR_FEELING_LUCKY_SELECTED = 1603;
        TOOLBAR_MY_LOCATION_SELECTED = 1604;
        TOOLBAR_MEASURE_TOOL_UNDO_SELECTED = 1605;
        TOOLBAR_MEASURE_TOOL_CONFIRM_SELECTED = 1606;
        TOOLBAR_MEASURE_TOOL_RESTART_SELECTED = 1607;
        TOOLBAR_POSTCARD_SELECTED = 1608;
        TOOLBAR_REPORT_A_PROBLEM_SELECTED = 1609;
        TOOLBAR_RESTART_EARTH_FEED_ITEM_SELECTED = 1610;
        TOOLBAR_SHARE_SELECTED = 1611;
        TOOLBAR_MEASURE_SELECTED = 1612;
        TOOLBAR_SHARE_STORY_SELECTED = 1613;
        TOOLBAR_FEEDBACK_SELECTED = 1614;
        SHORTCUT_EARTH_FEED_GRID_OPENED = 1615;
        SHORTCUT_FEELING_LUCKY_SELECTED = 1616;
        SHORTCUT_MY_LOCATION_SELECTED = 1617;
        SHORTCUT_FOCUS_GLOBE_SELECTED = 1618;
        TOOLBAR_TIME_MACHINE_SELECTED = 1619;
        SHORTCUT_COPY_FEATURES_SELECTED = 1620;
        SHORTCUT_PASTE_FEATURES_SELECTED = 1621;
        NAV_MENU_SEARCH_SELECTED = 1700;
        NAV_MENU_EXPLORE_SELECTED = 1701;
        NAV_MENU_MY_PLACES_SELECTED = 1702;
        NAV_MENU_MAP_STYLE_SELECTED = 1703;
        NAV_MENU_PHOTOS_LAYER_SELECTED = 1704;
        NAV_MENU_SETTINGS_SELECTED = 1705;
        NAV_MENU_FEEDBACK_SELECTED = 1706;
        NAV_MENU_TUTORIAL_SELECTED = 1707 [deprecated = true];
        NAV_MENU_HELP_SELECTED = 1708;
        NAV_MENU_TERMS_OF_SERVICE_SELECTED = 1709;
        NAV_MENU_PRIVACY_SELECTED = 1710;
        NAV_MENU_OPEN_SOURCE_LICENSES_SELECTED = 1711;
        NAV_MENU_DEBUG_EXPERIMENTS_SELECTED = 1712;
        NAV_MENU_DEBUG_FIREBASE_TOKEN_SELECTED = 1713;
        NAV_MENU_TERMS_OF_SERVICE_GCP_SELECTED = 1714;
        NAV_MENU_WHATS_NEW_SELECTED = 1715;
        NAV_MENU_WHATS_NEW_ACCOUNT_SELECTED = 1716;
        NAV_MENU_KEYBOARD_SHORTCUTS_SELECTED = 1717;
        NAV_MENU_DOCUMENTATION_SELECTED = 1718;
        NAV_MENU_VIDEOS_SELECTED = 1719;
        NAV_MENU_COMMUNITY_FORUM_SELECTED = 1720;
        NATIVE_LIBRARY_LOAD = 1800;
        NATIVE_LIBRARY_LOAD_IO_EXCEPTION = 1801;
        NATIVE_LIBRARY_LOAD_NULL_POINTER_EXCEPTION = 1802;
        PROMO_CARMEN1_BUTTON_TAPPED = 1900 [deprecated = true];
        PROMO_CARMEN1_ACCEPTED = 1901 [deprecated = true];
        PROMO_CARMEN1_DECLINED = 1902 [deprecated = true];
        PROMO_CARMEN2_BUTTON_TAPPED = 1903 [deprecated = true];
        PROMO_CARMEN2_ACCEPTED = 1904 [deprecated = true];
        PROMO_CARMEN2_DECLINED = 1905 [deprecated = true];
        PROMO_CARMEN3_BUTTON_TAPPED = 1906 [deprecated = true];
        PROMO_CARMEN3_ACCEPTED = 1907 [deprecated = true];
        PROMO_CARMEN3_DECLINED = 1908 [deprecated = true];
        PROMO_CONTENT_CREATION_ACCEPTED = 1909;
        PROMO_CONTENT_CREATION_DECLINED = 1910;
        PROJECTS_VIEW_OPEN = 2000;
        PROJECTS_VIEW_CREATE_CLOUD_PROJECT = 2001;
        PROJECTS_VIEW_CREATE_LOCAL_PROJECT = 2002;
        PROJECTS_VIEW_IMPORT_KML_START = 2003;
        PROJECTS_VIEW_IMPORT_KML_CANCEL = 2004;
        PROJECTS_VIEW_IMPORT_KML_DONE = 2005;
        PROJECTS_VIEW_OPEN_PINNED_PROJECT = 2006;
        PROJECTS_VIEW_OPEN_RECENT_PROJECT = 2007;
        PROJECTS_VIEW_OPEN_FROM_DRIVE = 2008;
        PROJECTS_VIEW_DELETE_PROJECT_START = 2009;
        PROJECTS_VIEW_UNPIN_PROJECT = 2010;
        PROJECTS_VIEW_PIN_PROJECT = 2011;
        PROJECTS_VIEW_SHOW_PROJECT = 2012;
        PROJECTS_VIEW_HIDE_PROJECT = 2013;
        PROJECTS_VIEW_IMPORT_CSV_START = 2014;
        PROJECTS_VIEW_IMPORT_CSV_CANCEL = 2015;
        PROJECTS_VIEW_IMPORT_CSV_DONE = 2016;
        DELETE_PROJECT_CONFIRM = 2100;
        DELETE_PROJECT_CANCEL = 2101;
        DOC_VIEW_BACK = 2200;
        DOC_VIEW_SHARE = 2201;
        DOC_VIEW_DELETE = 2202;
        DOC_VIEW_EXPORT = 2203;
        DOC_VIEW_EDIT_TITLE = 2204;
        DOC_VIEW_ADD_FEATURE = 2205;
        DOC_VIEW_ADD_FEATURE_BRUSH = 2226;
        DOC_VIEW_ADD_FEATURE_PLACEMARK = 2206;
        DOC_VIEW_ADD_FEATURE_LINE = 2207;
        DOC_VIEW_ADD_FEATURE_SLIDE = 2208;
        DOC_VIEW_ADD_FEATURE_TILE_OVERLAY = 2223;
        DOC_VIEW_ADD_FEATURE_FOLDER = 2224;
        DOC_VIEW_PRESENT = 2209 [deprecated = true];
        DOC_VIEW_CHOOSE_FEATURE = 2210;
        DOC_VIEW_REORDER_FEATURE = 2211;
        DOC_VIEW_DELETE_FEATURE = 2212;
        DOC_VIEW_EDIT_FEATURE = 2213;
        DOC_VIEW_HIDE_FEATURE = 2214;
        DOC_VIEW_SHOW_FEATURE = 2215;
        DOC_VIEW_OPENED = 2216;
        DOC_VIEW_CAPTURE_STREET_VIEW = 2217;
        DOC_VIEW_SEARCH_TO_ADD_FEATURE = 2218;
        DOC_VIEW_RELOAD_DOCUMENT = 2219;
        DOC_VIEW_COPY_DOCUMENT = 2220;
        DOC_VIEW_CANCEL_COPY_DOCUMENT = 2221;
        DOC_VIEW_CONFIRM_COPY_DOCUMENT = 2222;
        DOC_VIEW_REPARENT_FEATURE = 2225;
        DOC_VIEW_PASTE_FEATURE = 2227;
        DOC_VIEW_COPY_FEATURE = 2228;
        DOC_VIEW_COPY_SELECTION = 2229;
        DOC_VIEW_PASTE_INTO_FOLDER = 2230;
        DOC_VIEW_ASK_GOOGLE_EARTH = 2231;
        DOC_VIEW_SEARCH_FEATURES = 2232;
        CC_TOOLBAR_ADD_PIN_START = 2300;
        CC_TOOLBAR_ADD_PIN_CANCEL = 2301;
        CC_TOOLBAR_ADD_LINE_START = 2302;
        CC_TOOLBAR_ADD_LINE_CANCEL = 2303;
        CC_TOOLBAR_CAPTURE_STREET_VIEW = 2304;
        CC_TOOLBAR_ADD_BRUSH_START = 2305;
        CC_TOOLBAR_ADD_BRUSH_CANCEL = 2306;
        DROP_PLACEMARK = 2400;
        DROP_PLACEMARK_CANCEL = 2401;
        DROP_PLACEMARK_ACTIVATED = 2402;
        DRAW_LINE_FIRST_POINT = 2500;
        DRAW_LINE_ADD_SUBSEQUENT_POINT = 2501;
        DRAW_LINE_FINISH_CLICK = 2502;
        DRAW_LINE_COMPLETE_POLYGON = 2503;
        DRAW_LINE_CANCEL = 2504;
        DRAW_LINE_FINISH_ENTER_KEY = 2505;
        DRAW_LINE_ACTIVATED = 2506;
        SAVE_TO_PROJ_EXPAND_PROJECT_COMBO = 2600;
        SAVE_TO_PROJ_NEW_PROJECT = 2601;
        SAVE_TO_PROJ_SWITCH_PROJECT = 2602;
        SAVE_TO_PROJ_SAVE_AND_EDIT = 2603;
        SAVE_TO_PROJ_SAVE = 2604;
        SAVE_TO_PROJ_CANCEL_BY_CLICK_OUTSIDE = 2605;
        SAVE_TO_PROJ_CLOSE = 2606;
        SAVE_TO_PROJ_ESC = 2607;
        SAVE_TO_PROJ_CHANGE_TITLE = 2608;
        CC_CREATED_PLACEMARK = 2700;
        CC_CREATED_LINE = 2701;
        CC_CREATED_POLYGON = 2702;
        CC_CREATED_SLIDE = 2703;
        CC_CREATED_CLOUD_DOC = 2704;
        CC_CREATED_LOCAL_DOC = 2705;
        CC_VIEW_SET_2D = 2706;
        CC_VIEW_SET_3D = 2707;
        CC_PICK_PLACEMARK = 2708;
        CC_PICK_LINE = 2709;
        CC_PICK_POLYGON = 2710;
        CC_CREATED_LAYER = 2711;
        CC_CREATED_FOLDER = 2712;
        CC_CREATED_MEASUREMENT_DISTANCE = 2713;
        CC_CREATED_MEASUREMENT_AREA = 2714;
        CC_CREATED_TILE_OVERLAY = 2715;
        CC_CREATED_NETWORK_LINK = 2716;
        FEATURE_PREVIEW_CARD_EDIT = 2800;
        FEATURE_PREVIEW_CARD_FLY = 2801;
        FEATURE_PREVIEW_CARD_CLOSE = 2802;
        FEATURE_PREVIEW_CARD_PRESENT = 2803;
        CARD_BALLOON_EDIT = 2900;
        CARD_BALLOON_FLY_TO = 2901;
        CARD_BALLOON_CLOSE = 2902;
        PANEL_BALLOON_EDIT = 3000;
        PANEL_BALLOON_FLY = 3001;
        PANEL_BALLOON_CLOSE = 3002;
        BALLOON_OPEN_SINGLE_EDIT = 3050;
        BALLOON_OPEN_BULK_EDIT = 3051;
        BALLOON_ASK_GOOGLE_EARTH = 3052;
        PE_BACK = 3100;
        PE_PREVIEW = 3101;
        PE_TITLE_CHANGED = 3102;
        PE_DESCRIPTION_CHANGED = 3103;
        PE_SWITCH_TO_HTML = 3104;
        PE_SWITCH_TO_TEMPLATE = 3105;
        PE_HTML_CHANGED = 3106;
        PE_CREATE_LINK = 3107;
        PE_STYLE_CHANGE_FROM_NONE = 3108;
        PE_STYLE_CHANGE_FROM_SMALL = 3109;
        PE_STYLE_CHANGE_FROM_LARGE = 3110;
        PE_STYLE_CHANGE_TO_NONE = 3111;
        PE_STYLE_CHANGE_TO_SMALL = 3112;
        PE_STYLE_CHANGE_TO_LARGE = 3113;
        PE_ADD_PHOTO_START = 3114;
        PE_ADD_PHOTO_DONE = 3115;
        PE_ADD_PHOTO_CANCEL = 3116;
        PE_REPLACE_PHOTO_START = 3117;
        PE_REPLACE_PHOTO_DONE = 3118;
        PE_REPLACE_PHOTO_CANCEL = 3119;
        PE_DELETE_PHOTO = 3120;
        PE_PLACEMARK_SIZE_CHANGED = 3121;
        PE_PLACEMARK_COLOR_STANDARD = 3122;
        PE_PLACEMARK_SHOW_COLOR_PICKER = 3123;
        PE_PLACEMARK_SHOW_ICON_PICKER = 3124;
        PE_PLACEMARK_CUSTOM_ICON_START = 3125;
        PE_PLACEMARK_CUSTOM_ICON_DONE = 3126;
        PE_PLACEMARK_CUSTOM_ICON_CANCEL = 3127;
        PE_PLACEMARK_RECENT = 3128;
        PE_PLACEMARK_SHOW_ADVANCED = 3129;
        PE_PLACEMARK_HIDE_ADVANCED = 3130;
        PE_PLACEMARK_LABEL_SHOW = 3131;
        PE_PLACEMARK_LABEL_HIDE = 3132;
        PE_PLACEMARK_LABEL_COLOR_CHANGED = 3133;
        PE_PLACEMARK_LABEL_SIZE_CHANGED = 3134;
        PE_PLACEMARK_LATITUDE_CHANGED = 3135;
        PE_PLACEMARK_LONGITUDE_CHANGED = 3136;
        PE_PLACEMARK_ALTITUDE_CHANGED = 3137;
        PE_PLACEMARK_ALTITUDE_MODE_CHANGED = 3138;
        PE_SNAPSHOT_VIEW = 3139;
        PE_MANUAL_VIEW_EXPAND = 3140;
        PE_MANUAL_VIEW_COLLAPSE = 3141;
        PE_MANUAL_VIEW_RESET = 3142;
        PE_MANUAL_VIEW_ALTITUDE_CHANGED = 3143;
        PE_MANUAL_VIEW_LATITUDE_CHANGED = 3144;
        PE_MANUAL_VIEW_LONGITUDE_CHANGED = 3145;
        PE_MANUAL_VIEW_HEADING_CHANGED = 3146;
        PE_MANUAL_VIEW_TILT_CHANGED = 3147;
        PE_MANUAL_VIEW_RANGE_CHANGED = 3148;
        PE_LINE_COLOR_STANDARD = 3149;
        PE_LINE_SHOW_COLOR_PICKER = 3150;
        PE_LINE_WIDTH_CHANGED = 3151;
        PE_POLYGON_OUTLINE_COLOR_STANDARD = 3152;
        PE_POLYGON_OUTLINE_SHOW_COLOR_PICKER = 3153;
        PE_POLYGON_OUTLINE_WIDTH_CHANGED = 3154;
        PE_POLYGON_FILL_COLOR_STANDARD = 3155;
        PE_POLYGON_FILL_SHOW_COLOR_PICKER = 3156;
        PE_POLYGON_FILL_OPACITY_CHANGED = 3157;
        PE_PROPERTY_EDITED = 3158;
        PE_THREED_MODEL_LATITUDE_CHANGED = 3159;
        PE_THREED_MODEL_LONGITUDE_CHANGED = 3160;
        PE_THREED_MODEL_ALTITUDE_CHANGED = 3161;
        PE_THREED_MODEL_ALTITUDE_MODE_CHANGED = 3162;
        PE_THREED_MODEL_HEADING_CHANGED = 3163;
        PE_THREED_MODEL_TILT_CHANGED = 3164;
        PE_THREED_MODEL_ROLL_CHANGED = 3165;
        PE_THREED_MODEL_SCALE_X_CHANGED = 3166;
        PE_THREED_MODEL_SCALE_Y_CHANGED = 3167;
        PE_THREED_MODEL_SCALE_Z_CHANGED = 3168;
        PE_THREED_MODEL_NUDGED = 3169;
        PE_THREED_MODEL_SNAPSHOT_LOCATION = 3170;
        PE_THREED_MODEL_TRANSFORM_RESET = 3171;
        PE_EDIT_PHOTO_TITLE_DONE = 3172;
        PE_THREED_MODEL_SIZE_CHANGED = 3173;
        ICON_PICKER_SELECT = 3500;
        ICON_PICKER_CANCEL = 3501;
        ICON_PICKER_TEXT_SEARCH = 3502;
        ICON_PICKER_BROWSE_ALL = 3503;
        LINK_DIALOG_URL = 3600;
        LINK_DIALOG_FEATURE_LINK = 3601;
        LINK_DIALOG_CANCEL = 3602;
        MAP_MOVE_PLACEMARK = 3700;
        MAP_MOVE_LINE_POINT = 3701;
        MAP_MOVE_LINE_MIDPOINT = 3702;
        MAP_MOVE_POLYGON_POINT = 3703;
        MAP_MOVE_POLYGON_MIDPOINT = 3704;
        MAP_MOVE_THREED_MODEL = 3705;
        COLOR_PICKER_SELECT = 3800;
        COLOR_PICKER_CANCEL = 3801;
        QUICK_SHARING_COPY = 3900;
        QUICK_SHARING_FACEBOOK = 3901;
        QUICK_SHARING_TWITTER = 3902;
        DRAWING_TOOL_AREA = 4000;
        DRAWING_TOOL_DISTANCE = 4001;
        DRAWING_TOOL_AREA_SAVE_TO_PROJECT = 4002;
        DRAWING_TOOL_DISTANCE_SAVE_TO_PROJECT = 4003;
        DOCUMENT_KML_IMPORT_SUCCESS = 4050;
        DOCUMENT_KML_IMPORT_FAILURE = 4051;
        DOCUMENT_KML_EXPORT = 4052;
        DOCUMENT_CLOUD_OPEN_SUCCESS = 4053;
        DOCUMENT_CLOUD_OPEN_FAILURE = 4054;
        DOCUMENT_CLOUD_SHARE = 4055;
        DOCUMENT_CLOUD_KML_IMPORT_SUCCESS = 4056;
        DOCUMENT_MY_MAP_IMPORT_SUCCESS = 4057;
        DOCUMENT_CLOUD_KML_IMPORT_INTERNAL_ERROR = 4060;
        DOCUMENT_CLOUD_KML_IMPORT_UMS_ERROR = 4061;
        DOCUMENT_CLOUD_KML_IMPORT_INVALID_URL = 4062;
        DOCUMENT_CLOUD_KML_IMPORT_USER_SIGNED_OUT_ERROR = 4063;
        DOCUMENT_CLOUD_KML_IMPORT_FEATURE_COUNT_LIMIT_REACHED = 4064;
        DOCUMENT_CLOUD_KML_IMPORT_UNSUPPORTED_FILE_TYPE = 4065;
        DOCUMENT_CLOUD_KML_IMPORT_UNKNOWN_ERROR = 4066;
        DOCUMENT_CLOUD_KML_IMPORT_CANCELLED = 4067;
        DOCUMENT_STYLE_COPY_POINT = 4068;
        DOCUMENT_STYLE_COPY_LINE = 4069;
        DOCUMENT_STYLE_COPY_POLYGON = 4070;
        DOCUMENT_STYLE_PASTE_POINT = 4071;
        DOCUMENT_STYLE_PASTE_LINE = 4072;
        DOCUMENT_STYLE_PASTE_POLYGON = 4073;
        DOCUMENT_STYLE_RESET = 4074;
        HOMESCREEN_SHOWN = 4117;
        HOMESCREEN_STREAMLINED_NAV_SHOWN = 4152;
        HOMESCREEN_DISMISS = 4100;
        HOMESCREEN_DISMISS_COMMAND = 4101;
        HOMESCREEN_RETURN_HOME = 4102;
        HOMESCREEN_CREATE_NEW_DRIVE_PROJECT_START = 4103;
        HOMESCREEN_CREATE_NEW_KML_FILE_START = 4104;
        HOMESCREEN_OPEN_DRIVE_PROJECT_START = 4105;
        HOMESCREEN_OPEN_KML_FILE_START = 4106;
        HOMESCREEN_CREATE_NEW_DRIVE_DESIGN_PROJECT_START = 4107;
        HOMESCREEN_OPEN_COMMAND = 4109;
        HOMESCREEN_EXPORT_TO_KML = 4111;
        HOMESCREEN_MAKE_COPY = 4112;
        HOMESCREEN_PASTE_INTO_PROJECT = 4113;
        HOMESCREEN_SHARE_START = 4114;
        HOMESCREEN_PIN_PROJECT = 4115;
        HOMESCREEN_UNPIN_PROJECT = 4116;
        HOMESCREEN_FOCUS_DRIVE_PROJECT = 4118;
        HOMESCREEN_FOCUS_KML_FILE = 4119;
        HOMESCREEN_FOCUS_IN_PLAY_MODE = 4120;
        HOMESCREEN_FOCUS_WHILE_PINNED = 4123;
        HOMESCREEN_DELETE_PROJECT = 4121;
        HOMESCREEN_RENAME_PROJECT = 4122;
        HOMESCREEN_SORT_KML_BY_TITLE = 4124 [deprecated = true];
        HOMESCREEN_SORT_KML_BY_LAST_MODIFIED = 4125 [deprecated = true];
        HOMESCREEN_SORT_DRIVE_BY_TITLE = 4126 [deprecated = true];
        HOMESCREEN_SORT_DRIVE_BY_LAST_MODIFIED = 4127 [deprecated = true];
        HOMESCREEN_SORT_DRIVE_BY_LAST_MODIFIED_BY_USER = 4128 [deprecated = true];
        HOMESCREEN_SORT_DRIVE_BY_LAST_ACCESSED_OR_STARRED_BY_USER = 4129 [deprecated = true];
        HOMESCREEN_SORT_DRIVE_BY_LAST_ACCESSED_BY_USER = 4130 [deprecated = true];
        HOMESCREEN_SORT_DRIVE_BY_LAST_SHARED = 4131 [deprecated = true];
        HOMESCREEN_SET_PEOPLE_FILTER = 4132 [deprecated = true];
        HOMESCREEN_SET_LAST_MODIFIED_TIME_FILTER = 4133 [deprecated = true];
        HOMESCREEN_SET_PINNED_FILTER = 4134 [deprecated = true];
        HOMESCREEN_CLEAR_PEOPLE_FILTER = 4135 [deprecated = true];
        HOMESCREEN_CLEAR_LAST_MODIFIED_TIME_FILTER = 4136 [deprecated = true];
        HOMESCREEN_CLEAR_PINNED_FILTER = 4137 [deprecated = true];
        HOMESCREEN_SWITCH_TO_KML_LIST = 4138 [deprecated = true];
        HOMESCREEN_SWITCH_TO_DRIVE_LIST = 4139 [deprecated = true];
        HOMESCREEN_SET_MAP_TYPE_FILTER = 4140;
        HOMESCREEN_CLEAR_MAP_TYPE_FILTER = 4141;
        HOMESCREEN_PLUS_BUTTON_DRIVE_CREATE_NEW_PROJECT = 4142;
        HOMESCREEN_PLUS_BUTTON_DRIVE_IMPORT_DRIVE_KML = 4143;
        HOMESCREEN_PLUS_BUTTON_DRIVE_IMPORT_LOCAL_KML = 4144;
        HOMESCREEN_PLUS_BUTTON_LOCAL_CREATE_NEW_KML_FILE = 4145;
        HOMESCREEN_PLUS_BUTTON_LOCAL_OPEN_KML_FILE = 4146;
        HOMESCREEN_PLUS_BUTTON_OPEN_DRIVE_PICKER = 4147;
        HOMESCREEN_PLUS_BUTTON_OPEN_KML_EDITOR = 4158;
        HOMESCREEN_SUGGESTED_ACTION_DRIVE_CREATE_NEW_PROJECT = 4148;
        HOMESCREEN_SUGGESTED_ACTION_DRIVE_IMPORT_LOCAL_KML = 4149;
        HOMESCREEN_SUGGESTED_ACTION_LOCAL_CREATE_NEW_KML_FILE = 4150;
        HOMESCREEN_SUGGESTED_ACTION_LOCAL_OPEN_KML_FILE = 4151;
        HOMESCREEN_STARTER_COPY_STARTED = 4153;
        HOMESCREEN_STARTER_COPY_REQUESTED = 4154;
        HOMESCREEN_STARTER_COPY_FAILED = 4155;
        HOMESCREEN_STARTER_COPY_SUCCESS = 4156;
        HOMESCREEN_STARTER_SIGN_IN_STARTED = 4157;
        FEATURE_UPDATE_MEDIA = 5000;
        DELVE_START = 5050 [deprecated = true];
        DELVE_BUILDING_STUDY_START = 5051 [deprecated = true];
        DELVE_BUILDING_PARCEL_DRAWING_COMPLETE = 5052 [deprecated = true];
        DELVE_GENERATE_BUILDING_DESIGN = 5053 [deprecated = true];
        DELVE_SOLAR_STUDY_START = 5054 [deprecated = true];
        DELVE_SOLAR_PARCEL_DRAWING_COMPLETE = 5055 [deprecated = true];
        DELVE_GENERATE_SOLAR_DESIGN = 5056 [deprecated = true];
        DELVE_CANCELLED = 5057 [deprecated = true];
        DELVE_BUILDING_STUDY_CANCELLED = 5058 [deprecated = true];
        DELVE_BUILDING_DESIGN_CANCELLED = 5059 [deprecated = true];
        DELVE_SOLAR_STUDY_CANCELLED = 5060 [deprecated = true];
        DELVE_SOLAR_DESIGN_CANCELLED = 5061 [deprecated = true];
        DELVE_OPEN_KML_DOCUMENT_COMMAND = 5062;
        DND_DOWNLOAD_KMZ = 5063;
        DND_DOWNLOAD_FINANCIAL_MODEL = 5064;
        DND_DOWNLOAD_RHINO_FILE = 5065;
        DND_DOWNLOAD_AUTOCAD_DXF = 5066;
        DND_DOWNLOAD_3D_BUILDINGS_IMAGE = 5067;
        DND_DOWNLOAD_PARTI_DIAGRAM_IMAGE = 5068;
        DND_DOWNLOAD_DEFAULT_IMAGE = 5069;
        DND_DOWNLOAD_UNKNOWN = 5070;
        DND_DESIGN_NEW_BUILD_INPUT_HELP_CLICKED = 5071;
        DND_DESIGN_SOLAR_INPUT_HELP_CLICKED = 5072;
        DND_DESIGN_VIEWER_HELP_CLICKED = 5073;
        DND_INPUT_USING_TAX_LOTS = 5074;
        DND_INPUT_USING_PARCEL_DRAWING = 5075;
        DND_NAV_FINISH_SITE_SELECTION = 5076;
        DND_NAV_SELECT_INDIVIDUAL_DESIGN = 5077;
        DND_NAV_SITE_STUDY_FROM_HOME_STREAMLINED = 5078 [deprecated = true];
        DND_NAV_SITE_STUDY_FROM_HOME_LEFT_NAV = 5079 [deprecated = true];
        DND_NAV_SITE_STUDY_FROM_HOME_EXPLORE = 5080;
        DND_NAV_SITE_STUDY_FROM_BANNER_ICON = 5081;
        DND_NAV_SITE_STUDY_FROM_FILE_MENU = 5082;
        DND_DESIGN_EXPORT_TO_EARTH_MAP = 5083;
        DND_START = 5084;
        DND_INPUT_BUILDING_REC_FAILED = 5085;
        DND_ENABLED = 5086;
        DND_NEW_BUILD_GENERATE = 5087;
        DND_SOLAR_GENERATE = 5088;
        DND_NEW_BUILD_STARTED = 5089;
        DND_SOLAR_STARTED = 5090;
        DND_RESET_ZONING = 5091;
        DND_DEFAULT_ZONING_FAILED = 5092;
        DND_NAV_VIEW_PRESET_CHANGED = 5093;
        DND_DESIGN_VIEWER_VIEW_OPENED = 5094;
        DND_SUGGESTED_ACTION_DRIVE_CREATE_SITE_STUDY = 5095 [deprecated = true];
        DND_INPUT_PARKING_CHANGE = 5096;
        DND_INPUT_SUSTAINABILITY_CHANGE = 5097;
        DND_INPUT_USE_TYPE_CHANGE = 5098;
        DND_INPUT_ZONING_CHANGE = 5099;
        DND_INPUT_PROGRAM_CHANGE = 5100;
        DND_INPUT_METRICS_CHANGE = 5101;
        DND_INPUT_BUILDING_CHANGE = 5102;
        DND_INPUT_DRAW_TOO_LARGE = 5103;
        DND_INPUT_DRAW_TOO_SMALL = 5104;
        DND_INPUT_TAX_LOTS_TOO_LARGE = 5105;
        DND_INPUT_TAX_LOTS_TOO_SMALL = 5106;
        DND_SHOW_TAX_LOTS_PAYGATE = 5107 [deprecated = true];
        DND_SHOW_DESIGN_QUOTA_PAYGATE = 5108 [deprecated = true];
        DND_SHOW_MAX_SITE_AREA_PAYGATE = 5109 [deprecated = true];
        DND_DESIGN_GENERATION_DISABLED_SOLAR = 5110;
        DND_DESIGN_GENERATION_DISABLED_NEW_BUILD = 5111;
        FEATURE_INFO_COPIED = 5500;
        FEATURE_INFO_ADVANCED_MEASUREMENTS_EXPANDED = 5501;
        FEATURE_INFO_ADVANCED_MEASUREMENTS_COLLAPSED = 5502;
        FEATURE_SELECTED = 5503;
        FEATURE_INFO_ELEVATION_PROFILE_EXPANDED = 5504;
        FEATURE_INFO_ELEVATION_PROFILE_COLLAPSED = 5505;
        ELEVATION_PROFILE_INTERACTION_STARTED = 5601;
        FRAME_RATE_0_10 = 6000;
        FRAME_RATE_10_20 = 6001;
        FRAME_RATE_20_30 = 6002;
        FRAME_RATE_30_40 = 6003;
        FRAME_RATE_40_50 = 6004;
        FRAME_RATE_50_60 = 6005;
        FRAME_RATE_OVER_60 = 6006;
        STARTUP_TIME_0_1_SEC = 6050;
        STARTUP_TIME_1_2_SEC = 6051;
        STARTUP_TIME_2_4_SEC = 6052;
        STARTUP_TIME_4_8_SEC = 6053;
        STARTUP_TIME_8_16_SEC = 6054;
        STARTUP_TIME_16_32_SEC = 6055;
        STARTUP_TIME_32_64_SEC = 6056;
        STARTUP_TIME_OVER_64_SEC = 6057;
        WEBGL1_SUPPORTED = 6500;
        WEBGL2_SUPPORTED = 6501;
        WEBGL_UNSUPPORTED = 6502;
        PROJECTS_LIST_SORT_DRIVE_BY_TITLE = 7000;
        PROJECTS_LIST_SORT_DRIVE_BY_LAST_MODIFIED = 7001;
        PROJECTS_LIST_SORT_DRIVE_BY_LAST_MODIFIED_BY_USER = 7002;
        PROJECTS_LIST_SORT_DRIVE_BY_LAST_ACCESSED_OR_STARRED_BY_USER = 7003;
        PROJECTS_LIST_SORT_DRIVE_BY_LAST_ACCESSED_BY_USER = 7004;
        PROJECTS_LIST_SORT_DRIVE_BY_LAST_SHARED = 7005;
        PROJECTS_LIST_SORT_KML_BY_TITLE = 7006;
        PROJECTS_LIST_SORT_KML_BY_LAST_MODIFIED = 7007;
        PROJECTS_LIST_SWITCH_TO_KML_LIST = 7008;
        PROJECTS_LIST_SWITCH_TO_DRIVE_LIST = 7009;
        EARTH_MATE_OPEN = 8000;
        EARTH_MATE_SUBMIT = 8001;
        EARTH_MATE_CANCEL = 8002;
        EARTH_MATE_SUCCESS = 8014;
        EARTH_MATE_ONBOARDING_DIALOG_OPEN = 8006;
        EARTH_MATE_ONBOARDING_DIALOG_LEARN_MORE = 8007;
        EARTH_MATE_PASSTHROUGH_TRIGGERED = 8013;
        EARTH_MATE_THUMB_UP = 8015;
        EARTH_MATE_THUMB_DOWN = 8016;
        EARTH_MATE_RATING_UNKNOWN = 8018;
        EARTH_MATE_UPLOAD_KML_INTENT = 8017;
        EARTH_MATE_SLIDESHOW_GENERATED = 8019;
        EARTH_MATE_ERROR = 8003;
        EARTH_MATE_TIMEOUT = 8004;
        EARTH_MATE_CREATE_FEATURE_LIMIT_HIT = 8005;
        EARTH_MATE_TOOL_RPC_TIMEOUT = 8008;
        EARTH_MATE_SENSITIVE_POI_TYPE = 8009;
        EARTH_MATE_UNSUPPORTED_POI_TYPE = 8010;
        EARTH_MATE_LOCATION_NOT_FOUND = 8011;
        EARTH_MATE_ANYTHING_MAPPER_UNAVAILABLE = 8012;
        EARTH_MATE_QUERY_LIMIT_EXCEEDED = 8020;
        EARTH_MATE_PROMO_CARD_DISMISSED = 8021;
        EARTH_MATE_CREATE_MAP_PROJECT = 8022;
        EARTH_MATE_GOOGLE_ONE_MANAGE_PLAN = 8025;
        EARTH_MATE_OPEN_IN_EXPLORE_MODE = 8023;
        EARTH_MATE_MARKDOWN_TABLE_RESPONSE = 8024;
        EARTH_MATE_OIS_TOGGLED_ON = 8026;
        EARTH_MATE_OIS_TOGGLED_OFF = 8027;
        EARTH_MATE_OIS_QUERY_SUBMITTED = 8028;
        EARTH_MATE_OIS_QUERY_CANCELLED = 8029;
        EARTH_MATE_OIS_THUMBNAIL_CLICKED = 8030;
        EARTH_MATE_OIS_SEARCH_PROMO_CLICKED = 8031;
        EARTH_MATE_OIS_SEARCH_PROMO_NEW_MAP_CLICKED = 8032;
        EARTH_MATE_OIS_SEARCH_PROMO_SHOWN = 8037;
        EARTH_MATE_OIS_RESPONSE_RECEIVED = 8033;
        EARTH_MATE_SUBMIT_WITH_VIEWPORT = 8034;
        EARTH_MATE_VIEWPORT_ADDED_IMAGERY = 8035;
        EARTH_MATE_VIEWPORT_ADDED_STREET_VIEW = 8036;
        EARTH_MATE_LAYER_GENERATED = 8038;
        EARTH_MATE_SUBMIT_WITH_EDC = 8039;
        EARTH_MATE_OPEN_VIA_COMMAND = 8040;
        EARTH_MATE_GEMINI_VECTOR_LAYER_GENERATED = 8041;
        EARTH_MATE_SUBMIT_WITH_GEMINI_VECTOR_LAYERS = 8042;
        INDUSTRY_SELECTOR_CTA_SHOWN = 9000;
        INDUSTRY_SELECTOR_CTA_DISMISSED = 9001;
        INDUSTRY_SELECTOR_SURVEY_STARTED = 9002;
        INDUSTRY_SELECTOR_PRIMARY_USE_PAGE_SHOWN = 9003;
        INDUSTRY_SELECTOR_INDUSTRY_PAGE_SHOWN = 9004;
        INDUSTRY_SELECTOR_REGION_PAGE_SHOWN = 9005;
        INDUSTRY_SELECTOR_SCALE_PAGE_SHOWN = 9006;
        INDUSTRY_SELECTOR_OPT_INS_PAGE_SHOWN = 9007;
        INDUSTRY_SELECTOR_SURVEY_COMPLETED = 9008;
        INDUSTRY_SELECTOR_SURVEY_USER_RESPONDED = 9009;
        MAP_USE_CASES_PAGE_SHOWN = 9010;
        BILLING_SELECT_GCP_PROJECT = 10000;
        BILLING_LEAVE_GCP_PROJECT = 10001;
        BILLING_SHOW_UPGRADE_DIALOG = 10002;
        BILLING_RATE_CARD_UPGRADE_PROF = 10003;
        BILLING_RATE_CARD_UPGRADE_PROF_ADV = 10004;
        BILLING_RATE_CARD_LEARN_MORE = 10005;
        BILLING_RATE_CARD_REFRESH = 10006;
        BILLING_BANNER_SETTINGS = 10007;
        BILLING_PLAN_CHANGE = 10008;
        BILLING_SHOW_SETTINGS_SELECT_PROJECT = 10009;
        BILLING_CLICK_UPGRADE_BUTTON = 10010;
        BILLING_RATE_CARD_DOWNGRADE_STANDARD = 10011;
        BILLING_RATE_CARD_DOWNGRADE_PROF = 10012;
        BILLING_CLOSE_UPGRADE_DIALOG = 10015;
        EXPLORE_PROMOTION_DIALOG_CLOSED = 10013;
        EXPLORE_PROMOTION_DIALOG_SHOWN = 10014;
        PROMO_COACH_CARD_DISMISSED = 10016;
        PROMO_COACH_CARD_SHOWN = 10017;
        HOMESCREEN_PROMO_HEADER_SHOWN = 10018;
        HOMESCREEN_PROMO_HEADER_DISMISSED = 10019;
        BILLING_PLAN_CHIP_EARTH_MANAGE_PLAN = 10020;
        BILLING_PLAN_CHIP_GOOGLE_ONE_MANAGE_PLAN = 10021;
        GOOGLE_ONE_EARTH_MATE_BANNER_TRY_EARTH_MATE = 10022;
        GOOGLE_ONE_EARTH_MATE_BANNER_DISMISSED = 10023;
        GOOGLE_ONE_EARTH_MATE_BANNER_LEARN_MORE_LINK = 10024;
        BILLING_SEE_FEATURES_CLICKED = 10025;
        BILLING_RATE_CARD_ROW_EXPANDED = 10026;
        BILLING_RATE_CARD_ROW_COLLAPSED = 10027;
        BILLING_SHOW_WELCOME_DIALOG = 10028;
        PAYGATE_CARD_SHOWN = 10029;
        LAYERS_SHOW_CATALOG = 11000;
        LAYERS_SELECT = 11001;
        LAYERS_DESELECT = 11002;
        LAYERS_ADD_TO_PROJECT = 11003;
        LAYERS_OPEN_DETAILS = 11004;
        LAYERS_CLOSE_DETAILS = 11005;
        LAYERS_FILTER_RANGE = 11006;
        LAYERS_FILTER_CATEGORY = 11007;
        LAYERS_SET_OPACITY = 11008;
        LAYERS_DATA_TAB_SHOWN = 11009;
        LAYERS_FILTER_TAB_SHOWN = 11010;
        LAYERS_STYLE_TAB_SHOWN = 11011;
        LAYERS_SOURCE_TAB_SHOWN = 11012;
        LAYERS_SELECTED_FEATURE = 11013;
        LAYERS_RESET_FILTERS = 11014;
        LAYERS_RESET_ATTRIBUTE_FILTERS = 11015;
        LAYERS_DELETE_FILTER = 11016;
        LAYERS_RECENTER_MAP = 11017;
        LAYERS_ADD_FILTER = 11018;
        LAYERS_CLOSE_CATALOG = 11019;
        LAYERS_DESELECTED_FEATURE = 11020;
        LAYERS_VIEW_DATA_TABLE = 11021;
        LAYERS_BRING_TO_FRONT = 11022;
        LAYERS_SEND_TO_BACK = 11023;
        LAYERS_DATA_TABLE_CLOSED = 11024;
        LAYERS_DATA_TABLE_UPDATED = 11025;
        LAYERS_LAYER_LOADED_IN_PROJECT = 11029;
        BILLING_NOTICE_BANNER_GENERAL_AVAILABILITY_LINK = 11026 [deprecated = true];
        BILLING_STANDARD_USER_PROMO_BANNER_LEARN_MORE_LINK = 11027;
        BILLING_NOTICE_BANNER_LEARN_MORE_LINK = 11028 [deprecated = true];
        LAYERS_DATA_TABLE_SELECTED_ROW = 11030;
        LAYERS_STYLE_TO_UNIFORM = 11031;
        LAYERS_STYLE_DATA_ATTR_UPDATE = 11032;
        LAYERS_STYLE_LABEL_ATTR_UPDATE = 11033;
        LAYERS_STYLE_PROPERTY_UPDATE = 11034;
        LAYERS_STYLE_RESET = 11035;
        SPECIAL_LAYER_SHOWN = 11036;
        LAYERS_DETAILS_BILLING_SETTINGS_REDIRECT = 11037;
        LAYERS_CATALOG_BILLING_SETTINGS_REDIRECT = 11038;
        LAYERS_DETAILS_BILLING_UPGRADE_REDIRECT = 11039;
        LAYERS_DELETE_LAYER = 11040;
        LAYERS_SEARCH = 11041;
        LAYERS_SHARE_LAYER_URL = 11042;
        PERFORM_UNDO_UNSPECIFIED = 12000;
        PERFORM_GLOBAL_UNDO = 12001;
        PERFORM_REDO_UNSPECIFIED = 12500;
        PERFORM_GLOBAL_REDO = 12501;
        REQUEST_ACCESS_SENT = 13000;
        REQUEST_ACCESS_USER_ACCOUNT_CHANGED = 13001;
        REQUEST_ACCESS_ANONYMOUS_SIGNED_IN = 13002;
        REQUEST_ACCESS_FROM_VIEW_TO_EDIT = 13003;
        AREA_FILTER_PANEL_OPENED = 14000;
        AREA_FILTER_PANEL_CLOSED = 14001;
        AREA_FILTER_APPLIED = 14002;
        AREA_FILTER_DELETED = 14003;
        AREA_FILTER_BILLING_SETTINGS_REDIRECT = 14004;
        IMAGE_GENERATOR_OPENED = 15000;
        IMAGE_GENERATOR_CLOSED = 15001;
        IMAGE_GENERATOR_GENERATE_STARTED = 15002;
        IMAGE_GENERATOR_GENERATE_SUCCESS = 15003;
        IMAGE_GENERATOR_GENERATE_ERROR = 15004;
        IMAGE_GENERATOR_SCREENSHOT_ERROR = 15005;
        IMAGE_GENERATOR_BACK = 15006;
        IMAGE_GENERATOR_FORWARD = 15007;
        IMAGE_GENERATOR_DOWNLOAD = 15008;
        IMAGE_GENERATOR_SAVE_AS_SLIDE = 15009;
        IMAGE_GENERATOR_OPENED_VIA_COMMAND = 15010;
        IMAGE_GENERATOR_SAVE_AS_PLACEMARK_OK = 15011;
        IMAGE_GENERATOR_SAVE_AS_PLACEMARK_FAIL = 15012;
        IMAGE_GENERATOR_BILLING_SETTINGS = 15013;
        IMAGE_GENERATOR_WATERMARK_FAIL = 15014;
        USER_IMPORT_STARTED = 16000;
        USER_IMPORT_OUTPUT_TYPE_SELECTED = 16001;
        USER_IMPORT_FILE_SELECTED = 16002;
        USER_IMPORT_FILE_MENU_ITEM_LOCAL = 16003;
        USER_IMPORT_FILE_MENU_ITEM_DRIVE = 16004;
        USER_IMPORT_HOMESCREEN_PLUS_BUTTON_LOCAL = 16005;
        USER_IMPORT_HOMESCREEN_PLUS_BUTTON_DRIVE = 16006;
        USER_IMPORT_PROJECT_LHP_PLUS_LOCAL = 16007;
        USER_IMPORT_PROJECT_LHP_PLUS_DRIVE = 16008;
        USER_IMPORT_TERMINATED = 16009;
        USER_IMPORT_THREED_MODEL_LOADED = 16010;
        ON_DEMAND_CONTOURS_OPENED_TOOLBAR = 17000;
        ON_DEMAND_CONTOURS_CLOSED_TOOLBAR = 17001;
        ON_DEMAND_CONTOURS_INPUT_POLYGON = 17002;
        ON_DEMAND_CONTOURS_CLOSED = 17003;
        ON_DEMAND_CONTOURS_CREATE_LAYER_CLICKED = 17004;
        ON_DEMAND_CONTOURS_CREATE_LAYER_CLICKED_AFTER_FAILURE = 17005;
        ON_DEMAND_CONTOURS_BILLING_UPGRADE_REDIRECT = 17006;
        ON_DEMAND_CONTOURS_BILLING_SETTINGS_REDIRECT = 17007;
        ON_DEMAND_CONTOURS_OPENED = 17008;
        ON_DEMAND_SLOPE_BILLING_SETTINGS = 17009;
        ON_DEMAND_ASPECT_BILLING_SETTINGS = 17010;
        ON_DEMAND_QUOTA_EXCEEDED = 17011;
        ON_DEMAND_FAILURE_DETAILS_DIALOG_OPENED = 17012;
        ON_DEMAND_SLOPE_TOOLBAR_OPENED = 17013;
        ON_DEMAND_SLOPE_TOOLBAR_CLOSED = 17014;
        ON_DEMAND_SLOPE_INPUT_POLYGON = 17015;
        ON_DEMAND_SLOPE_CLOSED = 17016;
        ON_DEMAND_SLOPE_CREATE_LAYER_CLICKED = 17017;
        ON_DEMAND_SLOPE_CREATE_AFTER_FAILURE = 17018;
        ON_DEMAND_SLOPE_OPENED = 17019;
        ON_DEMAND_SLOPE_SUCCESS = 17020;
        ON_DEMAND_SLOPE_FAILURE = 17021;
        ON_DEMAND_SLOPE_RESOLUTION_CHANGED = 17022;
        ON_DEMAND_ASPECT_TOOLBAR_OPENED = 17023;
        ON_DEMAND_ASPECT_TOOLBAR_CLOSED = 17024;
        ON_DEMAND_ASPECT_INPUT_POLYGON = 17025;
        ON_DEMAND_ASPECT_CLOSED = 17026;
        ON_DEMAND_ASPECT_CREATE_LAYER_CLICKED = 17027;
        ON_DEMAND_ASPECT_CREATE_AFTER_FAILURE = 17028;
        ON_DEMAND_ASPECT_OPENED = 17029;
        ON_DEMAND_ASPECT_SUCCESS = 17030;
        ON_DEMAND_ASPECT_FAILURE = 17031;
        ON_DEMAND_ASPECT_RESOLUTION_CHANGED = 17032;
        ON_DEMAND_ANALYSIS_SWITCHED_TOOLS = 17033;
        ON_DEMAND_CUT_FILL_TOOLBAR_OPENED = 17034;
        ON_DEMAND_CUT_FILL_TOOLBAR_CLOSED = 17035;
        ON_DEMAND_CUT_FILL_INPUT_POLYGON = 17036;
        ON_DEMAND_CUT_FILL_CREATE_LAYER_CLICKED = 17037;
        ON_DEMAND_CUT_FILL_CREATE_AFTER_FAILURE = 17038;
        ON_DEMAND_CUT_FILL_SUCCESS = 17039;
        ON_DEMAND_CUT_FILL_FAILURE = 17040;
        ON_DEMAND_CUT_FILL_LRO_SUCCESS = 17054;
        ON_DEMAND_CUT_FILL_LRO_FAILURE = 17055;
        ON_DEMAND_SLOPE_QUOTA_EXCEEDED = 17056;
        ON_DEMAND_ASPECT_QUOTA_EXCEEDED = 17057;
        ON_DEMAND_CUT_FILL_QUOTA_EXCEEDED = 17058;
        ON_DEMAND_CONTOURS_QUOTA_EXCEEDED = 17059;
        ON_DEMAND_CUT_FILL_CLOSED = 17041;
        ON_DEMAND_CUT_FILL_OPENED = 17047;
        ON_DEMAND_CUT_AND_FILL_BILLING_SETTINGS = 17042;
        ON_DEMAND_SLOPE_COMMAND = 17043;
        ON_DEMAND_ASPECT_COMMAND = 17044;
        ON_DEMAND_CUT_FILL_COMMAND = 17045;
        ON_DEMAND_CONTOURS_COMMAND = 17046;
        ON_DEMAND_CONTOURS_LRO_SUCCESS = 17050;
        ON_DEMAND_CONTOURS_LRO_FAILURE = 17051;
        ON_DEMAND_CONTOURS_SUCCESS = 17052;
        ON_DEMAND_CONTOURS_FAILURE = 17053;
        ELEVATION_CONTOUR_LRO_CREATED = 17048;
        CUT_AND_FILL_LRO_CREATED = 17049;
        SLOPE_SITE_SIZE_PAYGATE_SEEN = 17060;
        ASPECT_SITE_SIZE_PAYGATE_SEEN = 17061;
        CONTOURS_SITE_SIZE_PAYGATE_SEEN = 17062;
        CUT_FILL_SITE_SIZE_PAYGATE_SEEN = 17063;
        KML_EDITOR_DIALOG_CREATE_NEW_KML_FILE_START = 18000;
        KML_EDITOR_DIALOG_OPEN_KML_FILE_START = 18001;
        KML_EDITOR_DIALOG_OPENED = 18002;
        LEGACY_FILE_WARNING_SEE_ALL_FILES_CLICK = 18100;
        LEGACY_FILE_WARNING_DISMISS_CLICK = 18101;
        CLASSIFY_OPEN_BILLING_SETTINGS = 18200;
        CLASSIFY_CREATE_LAYER = 18201;
        CLASSIFY_EDIT_LAYER = 18202;
        CLASSIFY_CREATE_OPEN_FROM_TOOLBAR = 18203;
        CLASSIFY_CREATE_OPEN = 18204;
        CLASSIFY_CAN_VISUALIZE_LAYER = 18205;
        FLIGHT_SIMULATOR_STARTED = 19000;
        FLIGHT_SIMULATOR_STOPPED = 19001;
        FLIGHT_SIMULATOR_CRASHED = 19002;
        COPY_PROJECT_DIALOG_OPEN = 19100;
        COPY_PROJECT_WITH_ACL = 19101;
        COPY_PROJECT_WITHOUT_ACL = 19102;
        COPY_PROJECT_SUCCESS = 19103;
        COPY_PROJECT_FAILURE = 19104;
        COPY_MYMAPS_TO_PROJECT_DIALOG_OPEN = 19105;
        COPY_MYMAPS_TO_PROJECT_WITH_ACL = 19106;
        COPY_MYMAPS_TO_PROJECT_WITHOUT_ACL = 19107;
        COPY_MYMAPS_TO_PROJECT_SUCCESS = 19108;
        COPY_MYMAPS_TO_PROJECT_FAILURE = 19109;
        CHANGE_DETECTION_CREATE_LAYER_CLICKED = 19200;
        CHANGE_DETECTION_CREATE_AFTER_FAILURE = 19201;
        CHANGE_DETECTION_SUCCESS = 19202;
        CHANGE_DETECTION_FAILURE = 19203;
        CHANGE_DETECTION_OPENED = 19204;
        IMAGERY_UPDATE_REQUEST_OPENED = 19300;
        IMAGERY_UPDATE_REQUEST_START_CLICKED = 19301;
        IMAGERY_UPDATE_REQUEST_CLOSED = 19302;
        IMAGERY_UPDATE_REQUEST_INPUT_POLYGON = 19303;
    }
    
    optional ExperimentFlags flags = 15 [deprecated = true];
    
    optional EarthMirthStatus mirth_status_event = 2;
    message EarthMirthStatus {
        optional double frame_rate = 1;
    }
    
    optional string app_software_id = 3;
    optional EarthFeedEvent earth_feed_event = 4;
    
    optional BaseLayerStyleEvent base_layer_style_event = 5;
    message BaseLayerStyleEvent {
        optional uint32 code = 1;
        optional bool selected = 2;
        optional uint32 style_index = 3;
    }
    
    optional string app_version = 6;
    
    optional BaseLayerEvent base_layer_event = 7;
    message BaseLayerEvent {
        optional string name = 1;
        optional bool selected = 2;
    }
    
    optional TimeControlsEvent time_controls_event = 8;
    message TimeControlsEvent {
        optional string mode = 1;
    }
    
    optional PhotosLayerEvent photos_layer_event = 9;
    message PhotosLayerEvent {
        repeated string photo_id = 1;
    }
    
    optional EarthCrashData earth_crash_data = 10;
    message EarthCrashData {
        optional string state_url = 1;
        optional string graphics_vendor = 2;
        optional string graphics_renderer = 3;
        optional string last_bridge_request = 4;
        optional double time_since_last_bridge_request = 5;
        
        optional ErrorInfo error_info = 6;
        message ErrorInfo {
            optional string name = 1;
            optional string msg = 2;
            optional string stack_trace = 3;
        }
    }
    
    optional EarthLoadData earth_load_data = 11;
    message EarthLoadData {
        optional double load_time = 1;
        optional double startup_time = 2;
    }
    
    optional ShareLinkData share_link_data = 12;
    message ShareLinkData {
        optional string link = 1;
    }
    
    optional MeasureToolEvent measure_tool_event = 13;
    message MeasureToolEvent {
        optional double distance = 1;
        optional double area = 2;
        optional uint32 vertex_count = 3;
        optional bool contains_stylus_points = 4;
    }
    
    optional MeasureToolDistanceUnitChangeEvent measure_tool_distance_unit_change_event = 25;
    message MeasureToolDistanceUnitChangeEvent {
        optional DistanceUnitName distance_unit_name = 1;
        enum DistanceUnitName {
            UNKNOWN_DISTANCE_UNIT = 0;
            CENTIMETERS = 1;
            METERS = 2;
            KILOMETERS = 3;
            INCHES = 4;
            FEET = 5;
            YARDS = 6;
            MILES = 7;
            NAUTICAL_MILES = 8;
            SMOOTS = 9;
            AUTO = 10;
            POOL_LENGTH = 11;
        }
    }
    
    optional MeasureToolAreaUnitChangeEvent measure_tool_area_unit_change_event = 26;
    message MeasureToolAreaUnitChangeEvent {
        optional AreaUnitName area_unit_name = 1;
        enum AreaUnitName {
            UNKNOWN_AREA_UNIT = 0;
            SQUARE_METERS = 1;
            SQUARE_KILOMETERS = 2;
            SQUARE_FEET = 3;
            SQUARE_YARDS = 4;
            SQUARE_MILES = 5;
            SQUARE_NAUTICAL_MILES = 6;
            HECTARES = 7;
            ACRES = 8;
            AUTO = 9;
            POOL_AREA = 10;
        }
    }
    
    optional MeasureToolAddPointEvent measure_tool_add_point_event = 36;
    message MeasureToolAddPointEvent {
        optional InputMethod input_method = 1;
        enum InputMethod {
            UNKNOWN = 0;
            CROSSHAIR = 1;
            MOUSE = 2;
            STYLUS = 3;
        }
    }
    
    optional SuggestionEvent suggestion_event = 14;
    message SuggestionEvent {
        optional string query = 1;
        optional string guid = 2;
        optional bool voyager_shown = 3;
        optional string balloon_feature_id = 4;
        optional string suggested_query = 5;
    }
    
    optional StartupFinishedEvent startup_finished_event = 16;
    
    optional NotificationEvent notification_event = 17;
    message NotificationEvent {
        optional Topic topic = 1;
        enum Topic {
            UNKNOWN = 0;
            VOYAGER = 1;
            POI = 2;
        }
    }
    
    optional NotificationEnrollmentEvent notification_enrollment_event = 18;
    message NotificationEnrollmentEvent {
        optional EntryPoint entry_point = 1;
        enum EntryPoint {
            UNKNOWN = 0;
            FEELING_LUCKY = 1;
            VOYAGER_STORY = 2;
        }
    }
    
    optional DeeplinkEvent deeplink_event = 19;
    
    optional FlyEndAnimationSettingEvent fly_end_animation_setting_event = 20 [deprecated = true];
    message FlyEndAnimationSettingEvent {
        optional AnimationType type = 1;
        enum AnimationType {
            NONE = 0;
            ORBIT = 1;
            CINEMATIC = 2;
        }
    }
    
    optional SettingsEvent settings_event = 21;
    optional NativeLibraryLoad native_library_load = 22;
    
    optional AccessibilityEvent accessibility_event = 23;
    message AccessibilityEvent {
        optional bool talk_back = 1;
        optional double system_font_size = 2;
        optional bool color_correction = 3;
    }
    
    optional IosSizeEvent ios_size_event = 24;
    message IosSizeEvent {
        optional SizeClass width = 1;
        enum SizeClass {
            UNSPECIFIED = 0;
            COMPACT = 1;
            REGULAR = 2;
        }
        
        optional SizeClass height = 2;
    }
    
    optional UserMediaMetadata user_media_metadata = 27;
    message UserMediaMetadata {
        optional UserMediaType type = 1;
        enum UserMediaType {
            USER_MEDIA_TYPE_UNKNOWN = 0;
            USER_MEDIA_TYPE_PHOTO = 1;
            USER_MEDIA_TYPE_VIDEO = 2;
        }
        
        optional int32 index = 2;
    }
    
    optional bool is_wasm = 28;
    optional bool is_wasm_threaded = 29;
    
    optional SearchSuggestResultGroupEvent search_suggest_result_group_event = 30;
    message SearchSuggestResultGroupEvent {
        optional string result_group_id = 1;
        optional string query = 2;
        optional string suggested_query = 3;
        optional string voyager_story_guid = 4;
        optional string voyager_balloon_feature_id = 5;
    }
    
    optional SearchSuggestGroupActionEvent search_suggest_group_action_event = 31;
    message SearchSuggestGroupActionEvent {
        optional string result_group_id = 1;
        optional string query = 2;
    }
    
    optional ImportToCloudEvent import_to_cloud_event = 32;
    message ImportToCloudEvent {
        optional Result result = 1;
        enum Result {
            RESULT_UNSPECIFIED = 0;
            RESULT_FAILURE = 1;
            RESULT_SUCCESS_WITH_WARNINGS = 2;
            RESULT_SUCCESS = 3;
        }
        
        repeated MessageType messages = 2 [deprecated = true];
        enum MessageType {
            MESSAGE_TYPE_UNSPECIFIED = 0;
            MESSAGE_TYPE_BROKEN_URL = 1;
            MESSAGE_TYPE_UNSUPPORTED_NONLOCAL_STYLE = 2;
            MESSAGE_TYPE_UNSUPPORTED_NONLOCAL_SCHEMADATA = 3;
            MESSAGE_TYPE_UNDEFINED_STYLE_URL = 4;
            MESSAGE_TYPE_UNDEFINED_SIMPLEDATA_NAME = 5;
            MESSAGE_TYPE_DUPLICATE_SCHEMA_FIELD = 6;
            MESSAGE_TYPE_UNKNOWN_SCHEMA_FIELD_TYPE = 7;
            MESSAGE_TYPE_KML_PARSE_ERROR = 8;
            MESSAGE_TYPE_FEATURE_ANCHOR_LINK = 9;
            MESSAGE_TYPE_NAMELESS_EXTENDEDDATA_FIELD = 10;
            MESSAGE_TYPE_UNSUPPORTED_FEATURE_TYPE_NETWORKLINK = 100;
            MESSAGE_TYPE_UNSUPPORTED_FEATURE_TYPE_TOUR = 101;
            MESSAGE_TYPE_UNSUPPORTED_FEATURE_TYPE_GROUNDOVERLAY = 102;
            MESSAGE_TYPE_UNSUPPORTED_FEATURE_TYPE_SCREENOVERLAY = 103;
            MESSAGE_TYPE_UNSUPPORTED_FEATURE_TYPE_PHOTOOVERLAY = 104;
            MESSAGE_TYPE_UNSUPPORTED_GEOMETRY_TYPE_TRACK = 200;
            MESSAGE_TYPE_UNSUPPORTED_GEOMETRY_TYPE_MULTITRACK = 201;
            MESSAGE_TYPE_UNSUPPORTED_GEOMETRY_TYPE_MODEL = 202;
        }
        
        optional string origin_earth_client_version = 3;
        optional int32 imported_features_count = 4;
    }
    
    optional DroppedPinEvent dropped_pin_event = 33;
    message DroppedPinEvent {
        optional Duration dropped_pin_card_duration = 1;
    }
    
    optional MirthStatsEvent mirth_stats_event = 34;
    
    optional ConfigRequestEvent config_request_event = 35;
    message ConfigRequestEvent {
        optional StatusCode status_code = 1;
        enum StatusCode {
            INVALID = 0;
            OK = 1;
            CANCELLED = 2;
            UNKNOWN = 3;
            INVALID_ARGUMENT = 4;
            DEADLINE_EXCEEDED = 5;
            NOT_FOUND = 6;
            ALREADY_EXISTS = 7;
            PERMISSION_DENIED = 8;
            RESOURCE_EXHAUSTED = 9;
            FAILED_PRECONDITION = 10;
            ABORTED = 11;
            OUT_OF_RANGE = 12;
            UNIMPLEMENTED = 13;
            INTERNAL = 14;
            UNAVAILABLE = 15;
            DATA_LOSS = 16;
            UNAUTHENTICATED = 17;
        }
        
        optional int32 auto_retries = 2;
        optional bool is_manual_retry = 3;
        optional bool cached = 4;
    }
    
    optional NetworkRequestEvent network_request_event = 37;
    message NetworkRequestEvent {
        optional RequestType request_type = 1;
        enum RequestType {
            REQUEST_TYPE_UNKNOWN = 0;
            REQUEST_TYPE_CONFIG = 1;
            REQUEST_TYPE_EXPERIMENTS = 2;
            REQUEST_TYPE_ACCOUNT = 3;
            REQUEST_TYPE_SEARCH_ZERO_STATE = 4;
            REQUEST_TYPE_SEARCH_SUGGESTION = 5;
            REQUEST_TYPE_SEARCH = 6;
            REQUEST_TYPE_SEARCH_PAGINATION = 7;
            REQUEST_TYPE_PHOTOS = 8;
            REQUEST_TYPE_PHOTOS_LAYER = 9;
            REQUEST_TYPE_VOYAGER_GRID = 10;
            REQUEST_TYPE_VOYAGER_STORY = 11;
            REQUEST_TYPE_ANIMATED_CLOUDS = 12;
            REQUEST_TYPE_FIREBASE_DYNAMIC_LINK = 13;
            REQUEST_TYPE_KNOWLEDGE_CARD = 14;
            REQUEST_TYPE_TERRAIN = 15;
        }
        
        optional int32 http_response_code = 2;
    }
    
    optional EarthMateRequestEvent earth_mate_request_event = 38;
    message EarthMateRequestEvent {
        optional double submit_to_response_time_seconds = 1;
        optional bool is_googler = 2;
    }
    
    optional EarthMateEvent earth_mate_event = 39;
    message EarthMateEvent {
        optional bool is_googler = 1;
        optional bool edc_access = 2;
        optional int32 edc_generated_layer_count = 3;
        optional bool gemini_vector_layers_enabled = 4;
        optional int32 gemini_vector_generated_layer_count = 5;
    }
    
    optional IndustrySelectorResponseEvent industry_selector_response_event = 40;
    
    optional LightboxEvent lightbox_event = 42;
    message LightboxEvent {
        optional int32 media_index = 1;
        optional int32 media_count = 2;
    }
    
    optional MeasureToolSlopeUnitChangeEvent measure_tool_slope_unit_change_event = 43;
    message MeasureToolSlopeUnitChangeEvent {
        optional SlopeUnitName slope_unit_name = 1;
        enum SlopeUnitName {
            UNKNOWN_SLOPE_UNIT = 0;
            DEGREES_SLOPE = 1;
            PERCENT_SLOPE = 2;
            AUTO = 3;
        }
    }
    
    optional LayerDetailsClosed layer_details_closed = 44;
    message LayerDetailsClosed {
        optional double layer_details_open_seconds = 1;
    }
    
    optional SelectedLayerDetails selected_layer_details = 45;
    message SelectedLayerDetails {
        optional string layer_logging_id = 1;
        
        optional LayerResolveError layer_resolve_error = 2;
        enum LayerResolveError {
            LAYER_RESOLVE_ERROR_UNKNOWN = 0;
            LAYER_RESOLVE_ERROR_UNSUPPORTED = 1;
            LAYER_RESOLVE_ERROR_INSUFFICIENT_ENTITLEMENTS = 2;
        }
        
        optional SourceView source_view = 3;
        enum SourceView {
            SOURCE_VIEW_UNKNOWN = 0;
            SOURCE_VIEW_DIALOG_GRID_VIEW = 1;
            SOURCE_VIEW_DIALOG_DETAILS_VIEW = 2;
            SOURCE_VIEW_INSPECTOR_PANEL = 3;
        }
        
        optional bool is_layer_visible = 4;
        
        optional FeatureOrigin feature_origin = 5;
        enum FeatureOrigin {
            FEATUREORIGIN_UNKNOWN = 0;
            FEATUREORIGIN_USER = 1;
            FEATUREORIGIN_GEMINI = 2;
        }
        
        optional float search_semantic_distance = 6;
        optional bool opened_via_deeplink = 7;
    }
    
    optional LayerStyleUpdate layer_style_update = 55;
    message LayerStyleUpdate {
        repeated FeatureType feature_types = 1;
        enum FeatureType {
            FEATURE_TYPE_UNKNOWN = 0;
            FEATURE_TYPE_POLYGON = 1;
            FEATURE_TYPE_POINT = 2;
            FEATURE_TYPE_LINE = 3;
            FEATURE_TYPE_LABEL = 4;
        }
        
        repeated Property properties = 2;
        enum Property {
            PROPERTY_UNKNOWN = 0;
            PROPERTY_STROKE_COLOR = 1;
            PROPERTY_STROKE_WIDTH = 2;
            PROPERTY_FILL_COLOR = 3;
            PROPERTY_CATEGORICAL_RAMP = 4;
            PROPERTY_INTERPOLATED_RAMP = 5;
            PROPERTY_SCALE = 6;
            PROPERTY_VISIBILITY = 7;
            PROPERTY_OPACITY = 8;
        }
    }
    
    optional LayerShownDetails layer_shown_details = 57;
    message LayerShownDetails {
        optional string layer_logging_id = 1;
    }
    
    optional FeatureInfoCopiedEvent feature_info_copied_event = 46;
    message FeatureInfoCopiedEvent {
        optional KnownItemName known_name = 1;
        enum KnownItemName {
            ITEM_UNKNOWN = 0;
            ITEM_LATITUDE = 1;
            ITEM_LONGITUDE = 2;
            ITEM_LOCATION = 3;
            ITEM_ALTITUDE = 4;
            ITEM_LENGTH = 5;
            ITEM_PERIMETER = 6;
            ITEM_AREA = 7;
            ITEM_PLUS_CODE = 8;
            ITEM_ELEVATION = 9;
            ITEM_ELEVATION_GAIN = 10;
            ITEM_ELEVATION_LOSS = 11;
            ITEM_TILE_OVERLAY_URL_PATTERN = 12;
            ITEM_TILE_OVERLAY_TILE_SIZE = 13;
            ITEM_TILE_OVERLAY_TILE_COVERAGE = 14;
            ITEM_DURATION = 15;
            ITEM_ADDRESS = 16;
            ITEM_DESCENDANTS_COUNT = 17;
            ITEM_CENTROID = 18;
            ITEM_AREA_DESCRIPTION = 19;
            ITEM_HEADING = 20;
            ITEM_DISTANCE = 21;
            ITEM_ELEVATION_STATS = 22;
            ITEM_SLOPE_STATS = 23;
            ITEM_FEATURE_TYPE_HEADING = 24;
            ITEM_FEATURE_COUNT = 25;
            ITEM_STREET_VIEW_DATE = 26;
            ITEM_SUMMED_LENGTH = 27;
            ITEM_SUMMED_AREA = 28;
        }
    }
    
    optional FeatureSelectedEvent feature_selected_event = 47;
    message FeatureSelectedEvent {
        optional FeatureType feature_type = 1;
        enum FeatureType {
            FEATURE_TYPE_UNKNOWN = 0;
            FEATURE_TYPE_SUB_DOCUMENT = 1;
            FEATURE_TYPE_FOLDER = 2;
            FEATURE_TYPE_VIEW = 3;
            FEATURE_TYPE_PANEL = 4;
            FEATURE_TYPE_POINT = 5;
            FEATURE_TYPE_PATH = 6;
            FEATURE_TYPE_POLYGON = 7;
            FEATURE_TYPE_MULTI_GEOMETRY = 8;
            FEATURE_TYPE_GROUND_OVERLAY = 9;
            FEATURE_TYPE_TILE_OVERLAY = 10;
            FEATURE_TYPE_3D_MODEL = 11;
            FEATURE_TYPE_NETWORK_LINK = 12;
            FEATURE_TYPE_SCREEN_OVERLAY = 13;
            FEATURE_TYPE_PHOTO_OVERLAY = 14;
            FEATURE_TYPE_TOUR = 15;
            FEATURE_TYPE_TRACK = 16;
            FEATURE_TYPE_MULTI_TRACK = 17;
        }
        
        optional FeatureOrigin feature_origin = 2;
    }
    
    optional BillingPlanChangedEvent billing_plan_changed_event = 48;
    message BillingPlanChangedEvent {
        optional int32 prev_plan_type = 1;
        optional int32 new_plan_type = 2;
    }
    
    optional BillingUpgradeDialogDetails billing_upgrade_dialog_details = 49;
    message BillingUpgradeDialogDetails {
        optional BillingUpgradeDialogSourceView source_view = 1;
        optional string feature_row_id = 2;
    }
    
    optional RateCardVariantDetails rate_card_variant_details = 50;
    message RateCardVariantDetails {
        optional VariantName variant = 1;
        enum VariantName {
            UNKNOWN = 0;
            VARIANT_1 = 1;
            VARIANT_2 = 2;
        }
    }
    
    optional PropertyEditorEvent property_editor_event = 51;
    message PropertyEditorEvent {
        optional DocumentType document_type = 1;
        optional int32 num_other = 2;
        optional int32 num_placemarks = 3;
        optional int32 num_paths = 4;
        optional int32 num_polygons = 5;
        
        optional FeatureOrigin feature_origin = 6;
        enum FeatureOrigin {
            FEATUREORIGIN_UNKNOWN = 0;
            FEATUREORIGIN_USER = 1;
            FEATUREORIGIN_GEMINI = 2;
        }
    }
    
    optional ShowDataCatalogDetails show_data_catalog_details = 52;
    message ShowDataCatalogDetails {
        optional DataCatalogDialogSourceView source_view = 1;
    }
    
    optional ExplorePromotionDialogDetails explore_promotion_dialog_details = 53;
    message ExplorePromotionDialogDetails {
        optional ExplorePromotionDialogVariant variant = 1;
    }
    
    optional AreaFilterDetails area_filter_details = 54;
    message AreaFilterDetails {
        optional string layer_logging_id = 1;
        
        optional SourceView source_view = 2;
        enum SourceView {
            SOURCE_VIEW_UNKNOWN = 0;
            SOURCE_VIEW_INSPECTOR_PANEL = 1;
            SOURCE_VIEW_AREA_FILTER_VIEW = 2;
        }
        
        optional AreaSource area_source = 3;
        enum AreaSource {
            AREA_SOURCE_UNKNOWN = 0;
            AREA_SOURCE_DRAW = 1;
            AREA_SOURCE_SELECT = 2;
        }
        
        optional SelectionType selection_type = 4;
        enum SelectionType {
            SELECTION_TYPE_UNKNOWN = 0;
            SELECTION_TYPE_INTERSECTS = 1;
            SELECTION_TYPE_CONTAINS = 2;
        }
    }
    
    optional UserImportDetails user_import_details = 56;
    message UserImportDetails {
        optional int64 file_size_bytes = 1;
        
        optional UserImportOutputType output_type = 2;
        enum UserImportOutputType {
            UNKNOWN_OUTPUT_TYPE = 0;
            DATA_LAYER_OUTPUT_TYPE = 1;
            MAP_FEATURES_OUTPUT_TYPE = 2;
            THREED_MODEL_OUTPUT_TYPE = 3;
        }
        
        optional UserImportSource import_source = 3;
        enum UserImportSource {
            IMPORT_SOURCE_DRIVE = 0;
            IMPORT_SOURCE_LOCAL_FILE = 1;
            IMPORT_SOURCE_FILE_PASTE = 2;
            IMPORT_SOURCE_UNKNOWN = 3;
        }
        
        optional string mime_type = 4;
        
        optional DataLayerOutputState data_layer_output_state = 5;
        enum DataLayerOutputState {
            LAYER_OUTPUT_STATE_UNSPECIFIED = 0;
            LAYER_OUTPUT_DISABLED_VALIDATION_FAILED_UNKNOWN = 1;
            LAYER_OUTPUT_DISABLED_VALIDATION_FAILED_NOT_OWNER = 2;
            LAYER_OUTPUT_DISABLED_VALIDATION_FAILED_SHARED_DRIVE = 3;
            LAYER_OUTPUT_DISABLED_QUOTA_EXCEEDED = 4;
            LAYER_OUTPUT_DISABLED_IN_PROGRESS_LRO_IMPORT = 5;
            LAYER_OUTPUT_DISABLED_DRIVE_FILE_IMPORT = 7;
            LAYER_OUTPUT_ENABLED = 6;
        }
        
        optional TrackedLroState lro_state = 6;
        enum TrackedLroState {
            LRO_STATE_UNKNOWN = 0;
            LRO_STATE_RUNNING = 1;
            LRO_STATE_SUCCESS = 2;
            LRO_STATE_FAILED = 3;
            LRO_STATE_POLLING_FAILED = 4;
        }
        
        optional float quota_used_percent = 8;
        optional string origin_earth_client_version = 7;
        
        optional UserImportCompletionStatus completion_status = 9;
        enum UserImportCompletionStatus {
            COMPLETION_STATUS_UNKNOWN = 0;
            COMPLETION_STATUS_SUCCESS = 1;
            COMPLETION_STATUS_INTERNAL = 2;
            COMPLETION_STATUS_BACKEND_COMMUNICATION = 3;
            COMPLETION_STATUS_REQUEST_TIMED_OUT = 4;
            COMPLETION_STATUS_IMPORT = 5;
            COMPLETION_STATUS_NO_FEATURES = 6;
            COMPLETION_STATUS_CANCELLED = 7;
        }
    }
    
    optional SearchDataCatalogDetails search_data_catalog_details = 58;
    message SearchDataCatalogDetails {
        optional int32 search_query_count = 1;
        
        repeated ResultLayerDetails result_layer_details = 2;
        message ResultLayerDetails {
            optional string layer_logging_id = 1;
            optional float semantic_distance = 2;
        }
    }
    
    optional BillingWelcomeDialogDetails billing_welcome_dialog_details = 59;
    message BillingWelcomeDialogDetails {
        optional int32 plan_type = 1;
    }
    
    optional PaygateCardDetails paygate_card_details = 60;
    message PaygateCardDetails {
        optional PaygateFeatureType feature_paygate = 1;
    }
    
    optional ElevationContourLroEvent elevation_contour_lro_event = 61;
    message ElevationContourLroEvent {
        optional int32 concurrent_runs = 1;
    }
    
    optional CutAndFillLroEvent cut_and_fill_lro_event = 62;
    message CutAndFillLroEvent {
        optional int32 concurrent_runs = 1;
    }
    
    reserved 41;
    
    message Duration {
        optional double duration_seconds = 1;
    }
    
    enum FeatureOrigin {
        FEATUREORIGIN_UNKNOWN = 0;
        FEATUREORIGIN_USER = 1;
        FEATUREORIGIN_GEMINI = 2;
    }
    
    enum DocumentType {
        DOCUMENT_TYPE_UNKNOWN = 0;
        DOCUMENT_TYPE_LOCAL = 1;
        DOCUMENT_TYPE_CLOUD = 2;
    }
}

enum BillingUpgradeDialogSourceView {
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_UNSPECIFIED = 0;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_LAYERS_INSPECTOR_PANEL = 1;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_LAYERS_DIALOG_DETAILS_VIEW = 2;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_LAYERS_DIALOG_GRID_VIEW = 3;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_DESIGN_INPUT_MODE_CHOOSER = 4;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_SITE_SELECTION = 5;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_BILLING_SETTINGS = 6;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_DEBUG_SETTINGS = 7;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_NEW_BUILD_DESIGN_INPUT_SITE_TAB_ZONING = 8;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_SOLAR_DESIGN_INPUT_SITE_TAB = 9;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_STANDARD_USER_PROMO_BANNER = 10;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_PLAN_CHIP = 11;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_ON_DEMAND_CONTOUR_ANALYSIS = 12;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_HOMESCREEN_PROMO = 13;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_EXPLORE_PROMO_DIALOG = 14;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_AREA_FILTER = 15;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_USER_IMPORTED_LAYER = 16;
    BILLING_UPGRADE_DIALOG_SOURCE_VIEW_HOMESCREEN_STORAGE_SUMMARY = 17;
    BILLING_UPGRADE_DIALOG_CUT_AND_FILL = 18;
    BILLING_UPGRADE_DIALOG_SLOPE_ANALYSIS = 19;
    BILLING_UPGRADE_DIALOG_ASPECT_ANALYSIS = 20;
    BILLING_UPGRADE_DIALOG_CATALOG_SEARCH = 21;
    BILLING_UPGRADE_DIALOG_VIEW_DEEPLINK = 22;
    BILLING_UPGRADE_DIALOG_CLASSIFY_WITH_AI = 23;
    BILLING_UPGRADE_DIALOG_CREATE_IMAGES = 24;
}

enum PaygateFeatureType {
    PAYGATE_FEATURE_TYPE_UNKNOWN = 0;
    PAYGATE_FEATURE_TYPE_DATA_CATALOG = 1;
    PAYGATE_FEATURE_TYPE_LOCKED_LAYER = 2;
    PAYGATE_FEATURE_TYPE_LAYER_DETAILS = 3;
    PAYGATE_FEATURE_TYPE_AREA_FILTER = 4;
    PAYGATE_FEATURE_TYPE_CONTOUR_ANALYSIS = 5;
    PAYGATE_FEATURE_TYPE_SLOPE_ANALYSIS = 6;
    PAYGATE_FEATURE_TYPE_ASPECT_ANALYSIS = 7;
    PAYGATE_FEATURE_TYPE_CUT_AND_FILL = 8;
    PAYGATE_FEATURE_TYPE_SITE_SELECTION = 9;
    PAYGATE_FEATURE_TYPE_SOLAR_DESIGN = 10;
    PAYGATE_FEATURE_TYPE_NEW_BUILD_DESIGN = 11;
    PAYGATE_FEATURE_TYPE_DESIGN_INPUT_MODE = 12;
    PAYGATE_FEATURE_TYPE_CLASSIFY_WITH_AI = 13;
    PAYGATE_FEATURE_TYPE_CREATE_IMAGE = 14;
}

enum DataCatalogDialogSourceView {
    DATA_CATALOG_DIALOG_SOURCE_VIEW_UNKNOWN = 0;
    DATA_CATALOG_DIALOG_SOURCE_VIEW_HOMESCREEN_PROMO = 1;
    DATA_CATALOG_DIALOG_SOURCE_VIEW_TOOLBAR_BUTTON = 2;
    DATA_CATALOG_DIALOG_SOURCE_VIEW_BOTTOM_SHEET = 3;
    DATA_CATALOG_DIALOG_SOURCE_VIEW_EXPLORE_PROMO_DIALOG = 4;
    DATA_CATALOG_DIALOG_SOURCE_VIEW_DEEPLINK_COMMAND = 5;
    DATA_CATALOG_DIALOG_SOURCE_VIEW_CLIP = 6;
    DATA_CATALOG_SOURCE_LAYER_DEEPLINK = 7;
}

enum ExplorePromotionDialogVariant {
    EXPLORE_PROMOTION_DIALOG_VARIANT_UNKNOWN = 0;
    EXPLORE_PROMOTION_DIALOG_VARIANT_NO_GIF = 1;
    EXPLORE_PROMOTION_DIALOG_VARIANT_SMALL_GIF = 2;
    EXPLORE_PROMOTION_DIALOG_VARIANT_REGULAR_GIF = 3;
}
