syntax = "editions";

package geo.earth.app;

import "privacy/pattributes/annotations/proto_field.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option objc_class_prefix = "RTH";
option java_outer_classname = "EarthLogExperimentFlags";
option java_package = "com.google.geo.earth.app";

message ExperimentFlags {
    repeated ExperimentFlag flag = 1;
    message ExperimentFlag {
        optional FlagName name = 1;
        enum FlagName {
            option features = enum_type: CLOSED
            ;
            UNKNOWN_FLAG = 0;
            PHOTOS_LAYER_ENABLED = 1 [deprecated = true];
            TIMELAPSE_LAYERS_ENABLED = 2 [deprecated = true];
            IMPORT_SHEET_ENABLED = 3;
            CINEMATIC_FLY_BUTTON_ENABLED = 4 [deprecated = true];
            MEASURE_TOOL_ENABLED = 5 [deprecated = true];
            USER_PHOTOS_ENABLED = 6;
            MAP_MODE_ENABLED = 7 [deprecated = true];
            CELESTIAL_BODIES_ENABLED = 8;
            SPOTLIGHT_AREAS_ENABLED = 9 [deprecated = true];
            PEGMAN_DRAG_PAN_VIEW_ENABLED = 10 [deprecated = true];
            VOYAGER_SEARCH_SUGGESTIONS_ENABLED = 11 [deprecated = true];
            REPLACE_BASEMAP_LABEL_PINS = 12 [deprecated = true];
            TIMEMACHINE_ENABLED = 13 [deprecated = true];
            PROPERTY_EDITOR_ENABLED = 14 [deprecated = true];
            UMS_DOCUMENTS_ENABLED = 15 [deprecated = true];
            VOYAGER_SUGGESTIONS_FROM_SERVER_ENABLED = 16 [deprecated = true];
            LOCATION_KNOWLEDGE_ENABLED = 17 [deprecated = true];
            THREE_D_IMAGERY_TOGGLE_ENABLED = 18 [deprecated = true];
            MY_PLACES_ATOMIC_VIEW_ENABLED = 19 [deprecated = true];
            CONTENT_CREATION_ENABLED = 20 [deprecated = true];
            DISCOVERY_LAYER_ENABLED = 21;
            STREET_VIEW_SLINGSHOT_ENABLED = 22;
            UMS_NIGHTLY_ENABLED = 23 [deprecated = true];
            NOTIFICATIONS_ENABLED = 24 [deprecated = true];
            NOTIFICATIONS_ENROLLMENT_AFTER_FEELING_LUCKY_ENABLED = 25 [deprecated = true];
            NOTIFICATIONS_ENROLLMENT_AFTER_VOYAGER_STORY_ENABLED = 26 [deprecated = true];
            CLOUD_ANIMATION_TOGGLE_ENABLED = 27 [deprecated = true];
            FLY_END_VIEW_ANIMATION_SETTING_ENABLED = 28;
            MEASURE_TOOL_UNIT_SELECTION_ENABLED = 29;
            MEASURE_TOOL_TOOLBAR_ENABLED = 30;
            HATS_SURVEYS_ENABLED = 31;
            TYPE_TWO_SUGGESTIONS_ENABLED = 32 [deprecated = true];
            RETURN_TO_VOYAGER_GRID_ENABLED = 33 [deprecated = true];
            PROMOTION_CARMEN1_ENABLED = 34 [deprecated = true];
            GRIDLINES_TOGGLE_ENABLED = 35 [deprecated = true];
            PROMOTION_CARMEN2_ENABLED = 36 [deprecated = true];
            PROMOTION_CARMEN3_ENABLED = 37 [deprecated = true];
            BULK_EDITING_ENABLED = 38 [deprecated = true];
            DYNAMIC_BALLOON_TEMPLATES_ENABLED = 39;
            SEARCH_LOCAL_HISTORY_ENABLED = 40 [deprecated = true];
            SEARCH_V2_ENABLED = 41 [deprecated = true];
            LOCATION_TRACKING_ENABLED = 42 [deprecated = true];
            SHOW_EXPERIMENTAL_WARNING_ENABLED = 43;
            AUTO_RELOAD_CLOUD_DOCUMENTS_ENABLED = 44;
            DEEP_LINK_COMMAND_PARAMETER_ENABLED = 45;
            MEASURE_TOOL_POOLS_ENABLED = 46;
            DMS_LAYERS_ENABLED = 47;
            LOADING_INDICATOR_ENABLED = 48 [deprecated = true];
            DARK_MODE_SUPPORT_ENABLED = 49 [deprecated = true];
            IMAGERY_DATE_ENABLED = 50;
            MIRTH_RENDERABLE_AGGREGATION_ENABLED = 51;
            RELOAD_BUTTON_ENABLED = 52 [deprecated = true];
            COPY_PROJECT_ENABLED = 53 [deprecated = true];
            QUICK_SHARING_ENABLED = 54;
            RETURN_TO_STREETVIEW_COVERAGE_ENABLED = 55 [deprecated = true];
            CONFIG_V2_ENABLED = 56 [deprecated = true];
            LOCATION_HALO_ENABLED = 57 [deprecated = true];
            ACCOUNT_PARTICLE_DISC_ENABLED = 58 [deprecated = true];
            TILED_LAYERS_ENABLED = 59;
            MEASURE_TOOL_TABLET_UNDOCKED_ENABLED = 60;
            IMPORT_TO_CLOUD_ENABLED = 61 [deprecated = true];
            SCALE_BAR_ENABLED = 62 [deprecated = true];
            FOLDER_SUPPORT_ENABLED = 64 [deprecated = true];
            SPRAY_PAINT_ENABLED = 65;
            CONTENT_CREATION_MOBILE_ENABLED = 63;
            CONTENT_CREATION_MOBILE_COLLAPSED_DOCUMENT_VIEW_ENABLED = 66;
            CONTENT_CREATION_MOBILE_PROPERTY_EDITOR_ENABLED = 67;
            CONTENT_CREATION_MOBILE_ADD_PHOTOS_ENABLED = 69;
            CSV_IMPORT_ENABLED = 68;
            GROUND_OVERLAYS_ENABLED = 70;
            ONE_PLATFORM_PHOTOS_API_ENABLED = 71 [deprecated = true];
            VIEW_ONLY_MY_MAPS_ENABLED = 72;
            MODEL_3D_ENABLED = 73;
            ENABLE_SEARCH_PIPE_METADATA = 74 [deprecated = true];
            BASEMAP_STYLE_ENABLED = 75 [deprecated = true];
            IS_FISHFOOD_USER = 76;
            IS_DOGFOOD_USER = 77;
            IS_TRUSTED_TESTER = 78;
            DELVE_V1_ENABLED = 79 [deprecated = true];
            DESKTOP_UI_ON_PHONE_ENABLED = 80 [deprecated = true];
            DELVE_PAST_STUDIES_ENABLED = 81 [deprecated = true];
            KILL_SWITCH_ENABLED = 82;
            DELVE_V1_ALLOWLIST_ENABLED = 83 [deprecated = true];
            EARTH_MATE_ENABLED = 84;
            DATA_IMPORT_ENABLED = 85 [deprecated = true];
            EDITABLE_ATTRIBUTES_ENABLED = 86;
            TOUCH_BASED_MULTISELECT_ENABLED = 88 [deprecated = true];
            EARTH_RPC_CC_MIGRATION_ENABLED = 89 [deprecated = true];
            UX_STUDY_EXPERIMENT1_ENABLED = 90 [deprecated = true];
            BUILTENV_V0_DEV_ENABLED = 91 [deprecated = true];
            KML_IMPORT_ENABLED = 92 [deprecated = true];
            LIGHTBOX_GALLERY_ENABLED = 93 [deprecated = true];
            GCP_PROJECT_BILLING_ENABLED = 94 [deprecated = true];
            EV_PLANNER_ENABLED = 95 [deprecated = true];
            FEATURE_COPY_PASTE_ENABLED = 96 [deprecated = true];
            DATA_TABLES_ENABLED = 97 [deprecated = true];
            BULK_STYLING_ENABLED = 98 [deprecated = true];
            DRIVE_PROJECTS_AUTO_POPULATE_ENABLED = 99 [deprecated = true];
            EARTH_PROJECTS_IN_SEARCH_ENABLED = 100 [deprecated = true];
            HOMESCREEN_ENABLED = 101 [deprecated = true];
            BUILT_ENV_EDIT_DESIGNS_ENABLED = 102 [deprecated = true];
            HOMESCREEN_BANNER_ENABLED = 103 [deprecated = true];
            DESIGN_DETAILS_PANEL_ENABLED = 104 [deprecated = true];
            BUILTENV_DESIGN_POLLING_ENABLED = 105 [deprecated = true];
            BUILTENV_DESIGN_ENTITY_INSPECTOR_ENABLED = 106;
            HOMESCREEN_BANNER_SURVEY_LINK_ENABLED = 107 [deprecated = true];
            CREATE_DOCUMENTS_AS_MODEL_VERSION_V2_ENABLED = 108 [deprecated = true];
            BUILTENV_DESIGN_EXPORT_ENABLED = 109;
            BUILTENV_ALLOWLIST_ENABLED = 110 [deprecated = true];
            CREATE_DOCUMENTS_AS_MODEL_VERSION_V3_ENABLED = 111 [deprecated = true];
            RECOMMENDED_BUILDING_INPUTS_ENABLED = 112 [deprecated = true];
            INDUSTRY_SELECTOR_ENABLED = 113 [deprecated = true];
            INDUSTRY_SELECTOR_ALWAYS_SHOW_CTA_ENABLED = 114 [deprecated = true];
            BUILT_ENV_CREATE_MORE_DESIGNS_LIKE_THIS_ENABLED = 115 [deprecated = true];
            BUILTENV_DESIGN_VIEW_PRESETS_ENABLED = 116 [deprecated = true];
            BUILT_ENV_DELETE_DRAFT_ENABLED = 117 [deprecated = true];
            BUILTENV_ZONING_ENABLED = 118 [deprecated = true];
            DMS_IN_EARTH_PROJECTS_ENABLED = 119 [deprecated = true];
            STREET_VIEW_TIMELINE_ENABLED = 120 [deprecated = true];
            EARTH_DATA_CATALOG_ENABLED = 121 [deprecated = true];
            EARTH_MATE_LOGS_IS_GOOGLER = 122;
            BUILT_ENV_BASEMENT_PARKING_ENABLED = 123 [deprecated = true];
            BUILTENV_VIEW_PRESET_SUNLIGHT_HOURS_ENABLED = 124 [deprecated = true];
            BUILTENV_VIEW_PRESET_ON_DEMAND_FETCHING_ENABLED = 125 [deprecated = true];
            BUILTENV_VIEW_PRESET_VIEWS_ENABLED = 126 [deprecated = true];
            BUILT_ENV_QUOTA_SERVER_ENABLED = 127 [deprecated = true];
            ADVANCED_MEASUREMENTS_ELEVATION_PROFILE_ENABLED = 128 [deprecated = true];
            LOGS_IS_GOOGLER = 129;
            PROTO_EDITING_MODEL_ENABLED = 130;
            BUILTENV_ADVANCED_ENTITLEMENTS_ENABLED = 131 [deprecated = true];
            EARTH_MATE_PASSTHROUGH_ENABLED = 132 [deprecated = true];
            BRANDING_UPDATE_ENABLED = 133 [deprecated = true];
            EARTH_MATE_MULTITURN_ENABLED = 134 [deprecated = true];
            UNDO_REDO_PHASE1_PROJECT_MUTATIONS_ENABLED = 135 [deprecated = true];
            DATA_LAYER_FILTERING_ENABLED = 136 [deprecated = true];
            EARTH_MATE_RATINGS_ENABLED = 137 [deprecated = true];
            EARTH_MATE_CONTEXT_CHIP_ENABLED = 138 [deprecated = true];
            EARTH_WITH_GEMINI_PROMOTIONAL_MODAL_ENABLED = 139 [deprecated = true];
            GROUND_ELEVATION_METRICS_ENABLED = 140 [deprecated = true];
            REQUEST_ACCESS_ENABLED = 141;
            BULK_MAP_SELECTION_ENABLED = 142 [deprecated = true];
            BULK_FOLDER_CONTENTS_SELECTION_ENABLED = 143 [deprecated = true];
            DATA_LAYER_FEATURE_RESTYLING_IN_MIRTH_ENABLED = 144 [deprecated = true];
            BULK_EDITS_ENABLED = 145 [deprecated = true];
            BULK_MAP_COORDINATION_ENABLED = 146 [deprecated = true];
            BASEMAP_SETTINGS_ENABLED = 147 [deprecated = true];
            UNIFIED_MAP_DESIGN_DOCUMENT_ENABLED = 148 [deprecated = true];
            HOMESCREEN_PROJECT_LIST_FILTERING_SERVER_SIDE_ENABLED = 149;
            DATA_LAYER_DATA_TABLES_ENABLED = 150 [deprecated = true];
            PERSISTENT_TOOL_CARD_ENABLED = 151 [deprecated = true];
            EARTH_MATE_SLIDESHOW_ENABLED = 152;
            EARTH_MATE_TEST_USA_ENABLED = 153 [deprecated = true];
            EARTH_MATE_TEST_EN_US_ENABLED = 154 [deprecated = true];
            DATA_LAYER_DATA_TABLES_V0_ENABLED = 155 [deprecated = true];
            GIL_LOGGING_ENABLED = 156 [deprecated = true];
            GCP_BILLING_NOTICE_BANNER_ENABLED = 157 [deprecated = true];
            RATE_CARD_EXPERIMENT_ENABLED = 158 [deprecated = true];
            GCP_STANDARD_USER_PROMOTION_BANNER_ENABLED = 159 [deprecated = true];
            AUTO_STYLE_ENABLED = 160 [deprecated = true];
            COPY_PASTE_RESET_STYLE_ENABLED = 161 [deprecated = true];
            KML_IMPORT_DRAG_AND_DROP_ENABLED = 162;
            CREATE_DOCUMENTS_AS_MODEL_VERSION_V4_ENABLED = 163;
            ON_DEMAND_EVALUATION_CONTOURS_ENABLED = 164;
            USER_IMPORTED_DATA_LAYERS_ENABLED = 165 [deprecated = true];
            DESIGN_MAP_MANAGER_ENABLED = 166 [deprecated = true];
            DATA_LAYER_RESTYLING_ENABLED = 167 [deprecated = true];
            AI_VIEWPORT_ENABLED = 168;
            GA_RATE_CARD_ENABLED = 169 [deprecated = true];
            HOMESCREEN_DATA_LAYERS_PROMO_ENABLED = 170 [deprecated = true];
            DATA_LAYER_AREA_FILTERS_ENABLED = 171;
            BOTTOM_SHEET_COLLAPSED_DETAILS_ENABLED = 172 [deprecated = true];
            EDC_EXPLORE_PROMOTION_DIALOG_ENABLED = 173 [deprecated = true];
            EARTH_MATE_OVERHEAD_IMAGERY_SEARCH_ENABLED = 174;
            DATA_LAYERS_COACHCARD_PROMO_ENABLED = 175 [deprecated = true];
            MODEL3D_FILE_IMPORT_ENABLED = 176;
            MODEL3D_LINK_IMPORT_ENABLED = 177 [deprecated = true];
            EARTH_ANNUAL_SURVEY_BANNER_ENABLED = 178 [deprecated = true];
            EARTH_MATE_AGENCY_ENABLED = 179 [deprecated = true];
            BUILT_ENV_DISABLE_DESIGN_GENERATION_ENABLED = 180;
            IMAGE_GENERATOR_ENABLED = 181;
            COLLAPSIBLE_TOOL_CARDS_ENABLED = 182;
            PRIORITIZE_MAP_LABEL_PICKS_ENABLED = 183 [deprecated = true];
            REQUEST_DATA_TABLE_LAYER_BY_ID_ENABLED = 184 [deprecated = true];
            EARTH_MATE_EDC_CORPUS_TRIGGER = 185 [deprecated = true];
            KML_EXPERIENCE_ENABLED = 186;
            GOOGLE_AI_PLAN_INDICATORS_ENABLED = 187 [deprecated = true];
            EARTH_MATE_GOOGLE_ONE_STANDARD_BANNER_ENABLED = 188 [deprecated = true];
            COMMAND_PALETTE_ENABLED = 189;
            EARTH_MATE_SEARCH_PROMO_ENABLED = 190;
            RATE_CARD_REVAMP = 191 [deprecated = true];
            KML_EXPERIENCE_M1_ENABLED = 192;
            DATA_LAYER_DATA_TABLES_FILTERING_ENABLED = 193;
            POLYGON_SELECTION_ENABLED = 194;
            CLASSIFY_WITH_AI_ENABLED = 195;
            ON_DEMAND_EVALUATION_SLOPE_AND_ASPECT_ENABLED = 196;
            CATALOG_SEARCH_ENABLED = 197;
            RATE_CARD_PRICE_STRIKE_THROUGH_ENABLED = 198 [deprecated = true];
            OVERHEAD_IMAGERY_SEARCH_PAYGATE_ENABLED = 199;
            WHATS_NEW_LINK_ENABLED = 200 [deprecated = true];
            STARTER_PROJECT_ENABLED = 201;
            ON_DEMAND_EVALUATION_CUT_AND_FILL_ENABLED = 202;
            POLYGON_STATS_ENABLED = 203;
            ELEVATION_CONTOUR_LRO_ENABLED = 204;
            DATA_LAYER_CHANGELOG_ENABLED = 205 [deprecated = true];
            NANOBANANA_DOWNLOAD_BUTTON_ENABLED = 206;
            DATA_LAYER_NEW_BADGE_ENABLED = 207;
            USER_IMPORT_SHAPEFILE_LAYERS_ENABLED = 208;
            ELEVATION_PROFILE_ENABLED = 209;
            EARTH_MATE_STREAMING_ENABLED = 210;
            GIL_BILLING_POC_ENABLED = 211;
            USER_REQUESTED_IMAGERY_UPDATES_ENABLED = 212;
            SELECTED_FEATURE_STYLING_ENABLED = 213;
            IMAGE_GENERATOR_FOR_STREET_VIEW_ENABLED = 214;
            MODEL3D_VIEWING_ENABLED = 215;
            DATA_LAYER_GLOBAL_COVERAGE_PROMO_ENABLED = 216;
            ON_DEMAND_ANALYSIS_STANDARD_TIER_ENABLED = 217;
            MY_MAPS_IMPORT_TO_EARTH_ENABLED = 218;
            DOCUMENT_ASSET_LAYERS_PASTE_ENABLED = 219;
            EARTH_EXPERT_AGENT_ENABLED = 220;
            ENABLE_FLIGHT_SIMULATOR = 221;
            ADD_EDIT_NETWORK_LINK_ENABLED = 222;
            MANDATORY_PH_SERVER_TOKEN_ENABLED = 223;
            AGE_GENERATED_LAYERS_ENABLED = 224;
            INDUSTRY_SELECTOR_MAP_INTENT_ENABLED = 225;
            FEATURE_SEARCH_ENABLED = 226;
            CLASSIFY_WITH_AI_CLASSIFICATION_SYSTEMS_ENABLED = 227;
            CHANGE_DETECTION_M0_ENABLED = 228;
            SHARE_LAYER_VIA_DEEPLINK_ENABLED = 229;
            BUILTENV_TWO_MENU_OPTIONS_ENABLED = 230;
            CATALOG_FILTER_CHIPS_ENABLED = 231;
            EARTH_MATE_NEW_ENTRYPOINT_ENABLED = 232;
            EARTH_MATE_NEW_ZERO_STATE_ENABLED = 233;
            EARTH_MATE_PERSISTENT_VISION_CONTEXT_ENABLED = 234;
        }
        
        optional bool value = 2 [default = false];
    }
}
