syntax = "proto2";

package maps_versatile.annotations;

import "logs/proto/logs_annotations/logs_annotations.proto";

option objc_class_prefix = "GMV";
option java_outer_classname = "Annotations";
option java_package = "com.google.maps.versatile";

enum UseCase {
    USE_CASE_UNKNOWN = 0;
    USE_CASE_GAS_PRICE = 1;
    USE_CASE_DISCOVERY_HIGHLIGHTS = 2 [deprecated = true];
    USE_CASE_STAR_RATING_SUBTITLE = 3 [deprecated = true];
    USE_CASE_LIVE_BUSYNESS = 4;
    USE_CASE_PROGRESSIVE_DISCLOSURE = 5;
    USE_CASE_CATEGORY_TRANSLATION = 6;
    USE_CASE_OPEN_CLOSE = 7 [deprecated = true];
    USE_CASE_TRANSIT_LINE_ICONS = 8;
    USE_CASE_EVCS_ON_MAP = 9;
    USE_CASE_PERSONAL_SCORE_BOOSTING = 10;
    USE_CASE_RECENTLY_VIEWED_RESULT = 11;
    USE_CASE_CALENDAR_EVENT = 12;
    USE_CASE_SELECTED = 14;
    USE_CASE_SHOPPING_CATEGORY = 15;
    USE_CASE_HOTEL_PRICE = 16;
    USE_CASE_MAPS_API = 17;
    USE_CASE_ATTRACTION_SUMMARY = 18;
    USE_CASE_RECENTLY_VIEWED_PLACE = 19;
    USE_CASE_TEMPORARILY_CLOSED = 20;
    USE_CASE_PERMANENTLY_CLOSED = 86;
    USE_CASE_DINING_MODES = 21;
    USE_CASE_AGGREGATED_PLACE = 22 [deprecated = true];
    USE_CASE_USER_PREFERENCE_BOOSTING = 23;
    USE_CASE_MERCHANT_POSTS = 24 [deprecated = true];
    USE_CASE_LOCAL_RECOMMENDATIONS = 25;
    USE_CASE_HOTEL_PROGRESSIVE_DISCLOSURE = 26;
    USE_CASE_HOTEL_SEARCH_PROGRESSIVE_DISCLOSURE = 45;
    USE_CASE_SEARCH_RESULT_SUMMARY = 28;
    USE_CASE_CATEGORY_BOOST = 30;
    USE_CASE_CATEGORY_BOOST_RELATED_PLACES = 32;
    USE_CASE_DOUBLE_CATEGORY_BOOST = 48;
    USE_CASE_HOTELS_BOOST_ON_TRAVEL_INTENT = 46;
    USE_CASE_REGULATED_AREA = 31;
    USE_CASE_TIME_OF_WEEK_BOOSTING = 33;
    USE_CASE_DISABLE_DURING_SEARCH = 34;
    USE_CASE_SEARCH_NEARBY = 35;
    USE_CASE_WEATHER_FOR_POIS = 37;
    USE_CASE_NON_RESULT_POIS = 38;
    USE_CASE_TOP_RATED_SEARCH_RESULT = 39;
    USE_CASE_CHEAPEST_SEARCH_RESULT = 41;
    USE_CASE_CRISIS_LABEL_SUBTITLE = 87;
    USE_CASE_SECONDARY_POSITION = 40;
    USE_CASE_OMNIMAPS_POI_BOOSTING = 42 [deprecated = true];
    USE_CASE_OMNIMAPS_BACKGROUD_MAP_POIS = 55;
    USE_CASE_OMNIMAPS_MAP_ITEMS = 54;
    USE_CASE_P13N_ML_BOOSTING = 43;
    USE_CASE_TOP_RATED_HOTELS = 44;
    USE_CASE_PHOTOPINS = 47;
    USE_CASE_SEARCH_PHOTOPINS = 57;
    USE_CASE_AREA_BUSYNESS = 49;
    USE_CASE_LOCAL_VS_TOURIST_BOOSTING = 50;
    USE_CASE_USER_INTENT_BOOSTING = 51;
    USE_CASE_EMPHASIZED_POI = 52 [deprecated = true];
    USE_CASE_EMPHASIZED_POI_BOLD = 56 [deprecated = true];
    USE_CASE_LABEL_STRUCTURE = 71;
    USE_CASE_TRAVEL_MAP = 53;
    USE_CASE_TRAVEL_MAP_CATEGORICAL = 76;
    USE_CASE_TRAVEL_AREA_OF_INTEREST_EMPHASIS = 65;
    USE_CASE_TRAVEL_AREA_OF_INTEREST_SUBTITLE = 66;
    USE_CASE_TRAVEL_SUGGESTED_STOP_SUBTITLE = 78;
    USE_CASE_POI_OFFER = 58;
    USE_CASE_POI_OFFER_DETAILED = 60;
    USE_CASE_LIVE_BUSYNESS_BOOSTING = 59;
    USE_CASE_BROWSE_TO_DECIDE_TOP_SAVED = 61;
    USE_CASE_BROWSE_TO_DECIDE_COMMUNITY_FEED = 62;
    USE_CASE_RICH_PLACE_UNDERSTANDING_COMPOUND_POI = 63;
    USE_CASE_BROWSE_TO_DECIDE_PREVIEW_VIDEO = 64;
    USE_CASE_INDOOR_MAP_AVAILABLE = 67;
    USE_CASE_EXPLORE_THIS_AREA = 68;
    USE_CASE_PLACE_EVENTS = 70;
    USE_CASE_3D_SELECTION_DENSITY_REDUCTION = 72;
    USE_CASE_25D_NAV_DESTINATION_HIGHLIGHT = 73;
    USE_CASE_3D_BUILDING_HIGHLIGHT = 74;
    USE_CASE_REMOVE_PISA_BUILDING_FOOTPRINT = 98;
    USE_CASE_TACTILE_DENSITY = 75;
    USE_CASE_TRANSIT_ENTRANCE_SELECT = 77;
    USE_CASE_TRANSIT_DIRECTIONS_MAP = 80;
    USE_CASE_MARS_DEBUG_INFO = 81;
    USE_CASE_TRAVEL_SUGGESTED_STOPS = 82;
    USE_CASE_PERSONAL_EVENT = 83;
    USE_CASE_AIR_QUALITY_LAYER_SELECTED_POI = 84;
    USE_CASE_SEARCH_RESULT_IN_ROUTE_OVERVIEW = 85;
    USE_CASE_SELECTED_POI_ROAD_LABEL = 88;
    USE_CASE_ROUTE_AWARE_ROAD = 90;
    USE_CASE_NON_ROUTE_AWARE_ROAD = 91;
    USE_CASE_USER_LOCATION_ROAD_LABEL = 92;
    USE_CASE_PLACE_SEASONALITY = 89;
    USE_CASE_ROUTE_OVERVIEW_ROAD_LABEL = 93;
    USE_CASE_EXPERIENCE_COLLECTION_LABEL = 94;
    USE_CASE_ROAD_SHIELD_DEBOOST = 95;
    USE_CASE_RECENTLY_NAVIGATED_PLACE = 96;
    USE_CASE_ELEVATED_ROAD_VISIBILITY = 97;
    USE_CASE_SALIENT_SEARCH_MAP_REMOVE_BACKGROUND_CONTENT = 99;
    USE_CASE_MANEUVER_LANDMARK = 100;
    USE_CASE_MAP_ACTION_BOOSTING = 101;
    USE_CASE_GENAI_MAPS_LABEL = 102;
}

enum SubtitleStyleTag {
    STYLE_TAG_UNKNOWN = 0;
    STYLE_TAG_LIVE_DATA = 1;
    STYLE_TAG_STAR_RATING_1 = 2;
    STYLE_TAG_STAR_RATING_1_5 = 3;
    STYLE_TAG_STAR_RATING_2 = 4;
    STYLE_TAG_STAR_RATING_2_5 = 5;
    STYLE_TAG_STAR_RATING_3 = 6;
    STYLE_TAG_STAR_RATING_3_5 = 7;
    STYLE_TAG_STAR_RATING_4 = 8;
    STYLE_TAG_STAR_RATING_4_5 = 9;
    STYLE_TAG_STAR_RATING_5 = 10;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_1 = 11;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_2 = 12;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_3 = 13;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_4 = 14;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_5 = 15;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_5X = 16;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_6 = 17;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_6X = 18;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_7 = 19;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_7X = 20;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_A = 21;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_B = 22;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_C = 23;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_D = 24;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_E = 25;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_F = 26;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_FX = 80;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_G = 27;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_H = 28;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_I = 29;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_J = 30;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_L = 31;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_M = 32;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_N = 33;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_Q = 34;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_R = 35;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_S = 36;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_V = 37;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_W = 38;
    STYLE_TAG_TRANSIT_LINE_US_NY_MTA_Z = 39;
    STYLE_TAG_WEATHER_CLEAR = 67;
    STYLE_TAG_WEATHER_CLOUDY = 68;
    STYLE_TAG_WEATHER_FOGGY = 69;
    STYLE_TAG_WEATHER_HEAVY_RAIN = 70;
    STYLE_TAG_WEATHER_HEAVY_SNOW = 71;
    STYLE_TAG_WEATHER_HEAVY_WIND = 72;
    STYLE_TAG_WEATHER_RAIN = 73;
    STYLE_TAG_WEATHER_SNOW = 74;
    STYLE_TAG_WEATHER_STORMY = 75;
    STYLE_TAG_WEATHER_SUNNY = 76;
    STYLE_TAG_BOLD_JUSTIFICATIONS = 77;
    STYLE_TAG_HIGHLIGHT_DEAL = 78;
    STYLE_TAG_AREA_OF_INTEREST_DESCRIPTION = 79;
    STYLE_TAG_LOST_CLUSTER_SUBTITLE_ICON = 81;
}

enum AnnotationAttributeNamespaceId {
    ATTRIBUTE_NAMESPACE_UNKNOWN = 0;
    ATTRIBUTE_NAMESPACE_MAPS_API_POI_BOOSTING = 1;
    ATTRIBUTE_NAMESPACE_TEST_EXAMPLE = 2;
    ATTRIBUTE_NAMESPACE_TEST_EXAMPLE2 = 3;
    ATTRIBUTE_NAMESPACE_USER_PREFERENCE_PROPERTY_HASH = 4;
    ATTRIBUTE_NAMESPACE_CATEGORY_BOOST = 5;
    ATTRIBUTE_NAMESPACE_TIME_OF_WEEK_SUBVERTICAL = 6;
    ATTRIBUTE_NAMESPACE_TINIES = 7;
    ATTRIBUTE_NAMESPACE_NON_RESULT_POIS = 8;
    ATTRIBUTE_NAMESPACE_MID = 9;
    ATTRIBUTE_NAMESPACE_OMNIMAPS_MAP_ITEMS = 10;
    ATTRIBUTE_NAMESPACE_OMNIMAPS_BACKGROUND_MAP_POIS = 16;
    ATTRIBUTE_NAMESPACE_LOCAL_VS_TOURIST_BOOSTING = 11;
    ATTRIBUTE_NAMESPACE_CRISIS_POIS = 12;
    ATTRIBUTE_NAMESPACE_CRISIS_BASEMAP = 18;
    ATTRIBUTE_NAMESPACE_USER_INTENT_BOOSTING_PRIMARY_GCID = 13;
    ATTRIBUTE_NAMESPACE_USER_INTENT_BOOSTING_CHAIN_MID = 14;
    ATTRIBUTE_NAMESPACE_TRAVEL_BASE_MAP = 15;
    ATTRIBUTE_NAMESPACE_CATEGORICAL_TBM = 21;
    ATTRIBUTE_NAMESPACE_VACATION_RENTALS = 17;
    ATTRIBUTE_NAMESPACE_LANDMARK_SELECTION = 19;
    ATTRIBUTE_NAMESPACE_TACTILE_POIS = 20;
    ATTRIBUTE_NAMESPACE_ROUTE_AWARE_ROADS = 22;
    ATTRIBUTE_NAMESPACE_EXPERIENCE_COLLECTIONS = 23;
    ATTRIBUTE_NAMESPACE_HIGH_PRIORITY_ROADS = 24;
    ATTRIBUTE_NAMESPACE_ELEVATED_DECK = 25;
    ATTRIBUTE_NAMESPACE_SALIENT_SEARCH_MAP = 26;
}

enum DiscoveryType {
    UNKNOWN = 0;
    FOODIE_FAVORITE = 1;
    TRENDING = 2;
    TOP_RATED = 3;
    NEWLY_OPENED = 4;
}

enum TiniesAttribute {
    TINIES_ATTRIBUTE_UNKNOWN = 0;
    TINIES_ATTRIBUTE_BASEMAP_TINY = 1;
}

enum RouteAwareRoadAttribute {
    ROUTE_AWARE_ROAD_PRIORITY_UNKNOWN = 0;
    ROUTE_AWARE_ROAD_PRIORITY_NON_TRAFFIC = 1;
    ROUTE_AWARE_ROAD_PRIORITY_TERMINAL = 2;
    ROUTE_AWARE_ROAD_PRIORITY_LOCAL = 3;
    ROUTE_AWARE_ROAD_PRIORITY_MINOR_ARTERIAL = 4;
    ROUTE_AWARE_ROAD_PRIORITY_MAJOR_ARTERIAL = 5;
}

enum MutingAttributes {
    MUTING_ATTRIBUTE_UNKNOWN = 0;
    MUTING_ATTRIBUTE_BASEMAP_POI = 1;
}

enum OmniMapsPoiBoostingAttribute {
    OMNIMAPS_POI_BOOSTING_UNKNOWN = 0;
    OMNIMAPS_POI_BOOSTING_AIR_QUALITY = 1;
}

enum LocalVsTouristBoostingAttribute {
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_UNKNOWN = 0;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_TOURIST_BOOST_SMALL = 1;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_TOURIST_BOOST_SMALL_EXPERIMENTAL = 11;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_TOURIST_BOOST_MEDIUM = 2;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_TOURIST_BOOST_MEDIUM_EXPERIMENTAL = 12;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_TOURIST_DEBOOST_SMALL = 3;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_TOURIST_DEBOOST_MEDIUM = 4;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_LOCAL_BOOST_SMALL = 5;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_LOCAL_BOOST_MEDIUM = 6;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_LOCAL_DEBOOST_SMALL = 7;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_LOCAL_DEBOOST_MEDIUM = 8;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_TOURIST_CANDIDATE_INDEX_DENYLIST_DEBOOST = 9;
    LOCAL_VS_TOURIST_BOOSTING_ATTRIBUTE_LOCAL_HAIR_SALON_BOOST = 10;
}

enum TravelMapAttributes {
    TRAVEL_MAP_ATTRIBUTES_UNKNOWN = 0;
    TRAVEL_MAP_ATTRIBUTES_POI = 5 [deprecated = true];
    TRAVEL_MAP_ATTRIBUTES_POI_NON_TOURISTY = 6;
    TRAVEL_MAP_ATTRIBUTES_POI_NON_TOURISTY_V2 = 9;
    TRAVEL_MAP_ATTRIBUTES_POI_SLIGHTLY_TOURISTY = 7;
    TRAVEL_MAP_ATTRIBUTES_POI_SLIGHTLY_TOURISTY_V2 = 12;
    TRAVEL_MAP_ATTRIBUTES_POLITICAL = 4;
    TRAVEL_MAP_ATTRIBUTES_POLITICAL_V2 = 10;
    TRAVEL_MAP_ATTRIBUTES_POI_LODGING = 8;
    TRAVEL_MAP_ATTRIBUTES_POI_LODGING_V2 = 11;
}

enum LandmarkSelectionAttribute {
    LANDMARK_SELECTION_ATTRIBUTE_UNKNOWN = 0;
    LANDMARK_SELECTION_ATTRIBUTE_POI = 1;
    LANDMARK_SELECTION_ATTRIBUTE_ICONIC_POI = 2;
}

enum TactilePoisAttribute {
    TACTILE_POIS_ATTRIBUTE_UNKNOWN = 0;
    TACTILE_POIS_SELECTION_ATTRIBUTE_POI = 1;
}

enum HighPriorityRoadsAttribute {
    HIGH_PRIORITY_ROADS_ATTRIBUTE_UNKNOWN = 0;
    HIGH_PRIORITY_ROADS = 1;
}

enum ElevatedDeckAttribute {
    ELEVATED_DECK_ATTRIBUTE_UNKNOWN = 0;
    ELEVATED_DECK_ATTRIBUTE_TRANSPARENCY_ALLOWED = 1;
}

enum SalientSearchMapAttribute {
    SALIENT_SEARCH_MAP_ATTRIBUTE_UNKNOWN = 0;
    SALIENT_SEARCH_MAP_ATTRIBUTE_SAVED_PLACE = 1;
    SALIENT_SEARCH_MAP_ATTRIBUTE_BASE_MAP_NON_RESULT_POI = 2;
    SALIENT_SEARCH_MAP_ATTRIBUTE_TRANSIT_ICON = 3;
}
