syntax = "editions";

package maps_versatile;

option features = enum_type: CLOSED
;
option java_multiple_files = true;

enum ExperimentalRenderOpTriggerId {
    UNSPECIFIED_TRIGGER_ID = 0;
    ATOMIC_PIPELINE2025_PROD_SIMPLIFIED_RENDERING_TRIGGER = 94271539;
    ATOMIC_PIPELINE2025_PREPROD_REAL_RENDERING_TRIGGER = 94271540;
    ATOMIC_PIPELINE_TEST_TRIGGER_ID1 = 94260117;
    ATOMIC_PIPELINE_TEST_TRIGGER_ID2 = 94260276;
    ATOMIC_RELEASE_BATCH_TEST_TRIGGER_ID = 94224176;
    ATOMIC_RELEASE_BATCH_TEST_TRIGGER_ID_2 = 94228591;
}

enum ExperimentalRenderOpCounterfactileId {
    UNSPECIFIED_COUNTERFACTILE_ID = 0;
    LANES_2024_US_METROS_COUNTERFACTILE_ID = 94234409;
    ATOMIC_PIPELINE2025_REAL_RENDERING_COUNTERFACTILE = 94271541;
    ATOMIC_TEST_COUNTERFACTILE_ID = 94223790;
    ATOMIC_TEST_COUNTERFACTILE_ID_2 = 94228592;
}
