syntax = "editions";

package maps_versatile;

import "java/com/google/apps/jspb/jspb.proto";
import "net/proto2/bridge/proto/message_set.proto";

option features = enum_type: CLOSED
utf8_validation: NONE
;
option java_package = "com.google.maps.versatile";

message IntentProto {
    optional IntentKey key = 1;
    enum IntentKey {
        INTENT_ACCESS_POINT = 225;
        INTENT_AD_STYLE = 56;
        INTENT_USE_SUBCATEGORY_ICON = 187;
        INTENT_DEPRIORITIZE_DINING_MODE_ANNOTATION = 188 [deprecated = true];
        INTENT_DYNAMIC_EXTENDED_PIN_TYPE = 298;
        INTENT_AD_BACKGROUND_COLOR = 76;
        INTENT_AIR_QUALITY_COLOR = 173;
        INTENT_AIR_QUALITY_HEATMAP = 240;
        INTENT_AIR_QUALITY_HEATMAP_EXTREME_EVENT_WARNING = 297;
        INTENT_AIR_QUALITY_HEATMAP_LABEL_TITLE_POSITION = 242;
        INTENT_AIR_QUALITY_HEATMAP_LABEL_TITLE_COLOR = 243;
        INTENT_AIR_QUALITY_STATION_ICON = 174;
        INTENT_AIR_QUALITY_STATION_INTENT = 180;
        INTENT_ANNOTATION_USE_CASE = 101;
        INTENT_ANNOTATION_SUBTITLE_PIECE_STYLE_TAG = 104;
        INTENT_ANNOTATION_FEATURE_TYPE = 114;
        INTENT_ANNOTATION_GCID = 116;
        INTENT_ANNOTATION_COUNTRY_CODE = 117;
        INTENT_AREA_LABEL_TRANSITION_ZOOM_DELTA = 60;
        INTENT_AREA_Z17_PIXELS_BUCKET = 166 [deprecated = true];
        INTENT_ARROW_RENDER_OP = 14;
        INTENT_ATOMIC_MAPS = 259;
        INTENT_ATOMIC_MAPS_HIDE_LANE = 271;
        INTENT_ATOMIC_MAPS_LANE = 195;
        INTENT_ATOMIC_MAPS_LANE_MARKER_CROSSABLE = 197;
        INTENT_ATOMIC_MAPS_LANE_MARKER_PLACEMENT = 204;
        INTENT_ATOMIC_MAPS_LANE_MARKER_TYPE = 213;
        INTENT_ATOMIC_MAPS_LANE_TURN_TYPE = 205;
        INTENT_ATOMIC_MAPS_LANE_USAGE_TYPE = 211;
        INTENT_ATOMIC_MAPS_OLD_ROAD_DEPRECATION = 164;
        INTENT_ATOMIC_MAPS_OVERLAPPING_MEDIAN = 246;
        INTENT_ATOMIC_MAPS_RELEASE_STAGE = 141;
        INTENT_ATOMIC_MAPS_ROAD = 151;
        INTENT_ATOMIC_MAPS_SIDEWALK = 152;
        INTENT_ATOMIC_MAPS_SIDEWALK_ROAD_FACING_EDGE = 153;
        INTENT_ATOMIC_MAPS_HIDE_SIDEWALK = 264;
        INTENT_ATOMIC_MAPS_LANE_COUNT = 215;
        INTENT_ATOMIC_MAPS_TURN_MARKER = 219;
        INTENT_ATOMIC_MAPS_MEDIAN_VOID = 281;
        INTENT_ATOMIC_MAPS_MEDIAN_GORE_EXPERIMENT = 306;
        INTENT_ATOMIC_MAPS_MEDIAN_VOID_ASSOCIATED_SEGMENT_PRIORITY = 300;
        INTENT_ATOMIC_MAPS_MEDIAN_VOID_ROAD_FACING_EDGE = 286;
        INTENT_ATOMIC_MAPS_MEDIAN_VOID_OPEN_FACING_EDGE = 287;
        INTENT_ATOMIC_MAPS_MEDIAN_VOID_EDGE_EXPERIMENT = 302;
        INTENT_ATOMIC_MAPS_SHOULDER_LANE_ZERO = 288;
        INTENT_ATOMIC_MAPS_ROAD_DECK_EXPERIMENT = 291;
        INTENT_ATOMIC_MAPS_DRIVEABLE_LANE_EXP = 292;
        INTENT_POLYLINE_ARROW = 68;
        INTENT_POLYLINE_COLOR_ARGB = 304;
        INTENT_BICYCLE_FACILITY = 1;
        INTENT_BICYCLE_RESTRICTION = 15;
        INTENT_BICYCLE_SAFETY = 2;
        INTENT_BORDER_STATUS = 3;
        INTENT_BORDER_TYPE = 140;
        INTENT_BUILDING_HAS_3D_MODEL = 32;
        INTENT_BUILDING_HAS_LEVELS = 26;
        INTENT_BUILDING_IS_UNDERGROUND = 27;
        INTENT_BUILDINGS_IN_NAVIGATION = 236;
        INTENT_BUSYNESS_LEVEL = 183;
        INTENT_TOURIST_CORRIDOR_CATEGORY = 224;
        INTENT_CAPITAL_OF_FEATURE_TYPE = 64;
        INTENT_CATEGORY_TRANSLATION = 83;
        INTENT_CATEGORY_TRANSLATION_GCID = 102;
        INTENT_SEARCH_RESULT_COLOR_OVERRIDE = 158 [deprecated = true];
        INTENT_COMPUTED_FEATURE_TYPE = 44;
        INTENT_CONTAINED_BY_RENDERING_CATEGORY = 170;
        INTENT_CONTAINED_BY_ROAD_MASK = 58;
        INTENT_CONTEXTUAL_BUILT_UP_AREA = 284;
        INTENT_CONTEXTUAL_GROUNDCOVER_TYPE = 289;
        INTENT_COUNTRY_SIZE = 43 [deprecated = true];
        INTENT_CRISIS_BASEMAP = 207;
        INTENT_CRISIS_CURATION_SCORE = 184;
        INTENT_CRISIS_GENERIC_CATEGORY = 191;
        INTENT_CRISIS_LABEL_TYPE = 130 [deprecated = true];
        INTENT_CRISIS_V2_STYLING = 112;
        INTENT_CRISIS_VISUALIZATION_TYPE = 192;
        INTENT_CRISIS_FLOOD_BLUE_POLYGONS = 249;
        INTENT_DEAD_END = 49;
        INTENT_DEPARTMENT_OF_RENDERING_CATEGORY = 171;
        INTENT_DIMENSIONAL_DISPLAY_MODE = 244;
        INTENT_DISCOVERY_HIGHLIGHTS_PLACE = 111 [deprecated = true];
        INTENT_DO_NOT_SHOW_ON_API = 21;
        INTENT_DOMINANT_COMPOUND_USE = 78;
        INTENT_DOODLE_TYPE = 4 [deprecated = true];
        INTENT_DYNAMIC_MAP_ICON_COLOR_OVERRIDE = 294 [deprecated = true];
        INTENT_ELECTRIC_VEHICLE_CHARGING_STATION = 245;
        INTENT_ELECTRIC_VEHICLE_CHARGING_STATION_AVAILABILITY_TYPE = 268;
        INTENT_ELECTRIC_VEHICLE_CHARGING_STATION_CHARGING_SPEED = 283;
        INTENT_AUTO_SURFACE = 285;
        INTENT_ELEVATED_ROAD = 282;
        INTENT_ELEVATION_METERS = 72;
        INTENT_HAS_DETAILED_3D_MODEL = 274;
        INTENT_ENTRANCE_TYPE = 228;
        INTENT_EVACUATION_ZONE_STATUS = 206;
        INTENT_EXPLORE_THIS_AREA_RELATED_RESULT = 238;
        INTENT_EXPERIENCE_LIST_TYPE = 275;
        INTENT_EXPERIENCE_LIST_LABEL_CLASS_TYPE = 276;
        INTENT_SEASONAL_EVENT_TYPE = 252;
        INTENT_EXTENDED_PIN_LAYOUT_TYPE = 156;
        INTENT_FLOOD_FORECAST_RISK_LEVEL = 122;
        INTENT_FLOOD_POLYGON_TYPE = 198;
        INTENT_FREEFORM_LOCALITY_TYPE = 46;
        INTENT_FREEFORM_ROUTE_TYPE = 45;
        INTENT_FREEFORM_TRANSIT_NAME = 47;
        INTENT_GAS_BRAND_ICON = 145;
        INTENT_GCONCEPT = 38;
        INTENT_GENAI_MAPS_AREA_HIGHLIGHT_COLOR = 310;
        INTENT_GENAI_MAPS_DYNAMIC_EXTENDED_PIN_COMPONENT = 311;
        INTENT_GENAI_MAPS_DYNAMIC_EXTENDED_PIN_TYPE = 312;
        INTENT_GENAI_MAPS_HIGHLIGHT = 305;
        INTENT_GENERIC_CRISIS_CATEGORY = 129;
        INTENT_GEO_EXPERIENCE_CATEGORY = 172;
        INTENT_GEOCODE_HIGHLIGHT = 28;
        INTENT_GEOCODE_HIGHLIGHT_INVERTED = 110;
        INTENT_ENTITY_HIGHLIGHT = 231;
        INTENT_TRANSIT_STATION_HIGHLIGHT = 247;
        INTENT_BUILDING_HIGHLIGHT_INVERTED = 216 [deprecated = true];
        INTENT_GEOCODE_HIGHLIGHT_ZOOM = 29;
        INTENT_GEOCODE_LABEL_LINE_LENGTH = 35;
        INTENT_GEOMETRY_HIGHLIGHT = 178;
        INTENT_GLTF_MODEL_CLASS = 220;
        INTENT_GROUNDS_SIZE = 142 [deprecated = true];
        INTENT_GT_JAPAN_FEATURE = 105;
        INTENT_HAND_PLACED_LABEL = 84;
        INTENT_HAS_HAND_PLACED_LABEL = 189;
        INTENT_HOTEL_DISPLAY_TYPE = 123;
        INTENT_HOTPOT_RATING = 25 [deprecated = true];
        INTENT_ICONIC_PLACE = 120;
        INTENT_ICONIC_ROUTE = 144;
        INTENT_IMAGERY_RESULT_TYPE = 208;
        INTENT_VIEWS_EXPERIENCE = 235;
        INTENT_IMPRECISE_LOCATION = 90;
        INTENT_INDOOR_COVERAGE = 34;
        INTENT_INDOOR_LAYER = 51;
        INTENT_UNRENDERABLE_INDOOR_LAYER = 251;
        INTENT_INDOOR_TYPE = 258;
        INTENT_INDOOR_LEVEL_BACKGROUND = 54;
        INTENT_INDOOR_MAPPED_BUILDING = 229;
        INTENT_INTERSECTION_HINTS = 63;
        INTENT_IS_CORRIDOR = 75;
        INTENT_IS_PEDESTRIAN_BRIDGE = 121;
        INTENT_IS_VEGETATED_PARK = 160;
        INTENT_TRANSIT_LOGICAL_PARENT_STATION_TYPE = 137;
        INTENT_TRANSIT_LOGICAL_STATION_TYPE = 138;
        INTENT_TRANSIT_LOGICAL_STATION_SHOW_PARENT_STATION = 266;
        INTENT_IS_TRANSIT_STATION = 99;
        INTENT_IS_UNCLIPPED_BUILDING = 109;
        INTENT_VALID_RRW_FEATURE = 119 [deprecated = true];
        INTENT_JP_ROAD_GEOMETRY_GRADE_LEVEL = 70 [deprecated = true];
        INTENT_LABEL_CLASS = 39;
        INTENT_LANGUAGE_DIRECTION = 146;
        INTENT_LANE_MARKER_FADE_IN = 250 [deprecated = true];
        INTENT_LOCAL_CATEGORICAL_PRESET_QUERY = 157;
        INTENT_LOCAL_CATEGORICAL_VIEW_TYPE = 165;
        INTENT_LU_AIR_QUALITY_PIN_TYPE = 190;
        INTENT_MACRO_LANDMARK = 92 [deprecated = true];
        INTENT_MAP_MODE = 88;
        INTENT_MAPFACTS_TRANSIT_ENTRANCE = 91;
        INTENT_MICRO_LANDMARK = 239;
        INTENT_NAMED_STYLE = 93;
        INTENT_NIGHTTIME_LIGHTING_LEVEL = 128;
        INTENT_OFF_ROUTE_INCIDENT = 277;
        INTENT_ON_DEFAULT_INDOOR_LEVEL = 42;
        INTENT_INDOOR_SHOW_IN_DEFAULT_MODE = 217;
        INTENT_ONE_WAY_SEGMENT = 16;
        INTENT_ORIENTATION_CUE = 253;
        INTENT_OVERRIDE_Z_PLANE_FOR_OVERLAY = 147;
        INTENT_PERSONAL_CLASS = 48;
        INTENT_GEOMETRY_INSIDE_MASK = 135;
        INTENT_GEOMETRY_OUTSIDE_MASK = 136;
        INTENT_RANK_SOURCE = 59;
        INTENT_DESTINATION_PARKING_LOT = 237;
        INTENT_RAP_HIGHLIGHT = 86;
        INTENT_AVERAGE_STAR_RATING = 148;
        INTENT_POI_PINLET_STYLE = 131;
        INTENT_REACHABILITY_POLYGON = 209;
        INTENT_RENDERING_CATEGORY = 167;
        INTENT_RENDER_SEGMENT_WIDTHS = 41;
        INTENT_RENDER_TEST_LABEL_ARGB = 133;
        INTENT_RESERVATION_SIZE = 143 [deprecated = true];
        INTENT_RESTRICTED_ZONE_TYPE = 169;
        INTENT_ROAD_SHIELD = 124;
        INTENT_ROAD_SHIELD_REFINEMENT_PHASE = 295;
        INTENT_ROAD_WITH_POLYGON_SUBSTITUTE_AVAILABLE = 108 [deprecated = true];
        INTENT_ROTATED_ENTRANCE = 223;
        INTENT_ROUTE_CALLOUT_CARET_POSITION = 308;
        INTENT_ROUTE_CALLOUT_TRAVEL_MODE = 309;
        INTENT_ROUTE_DECORATION_TYPE = 303;
        INTENT_ROUTE_SNIPPET = 103;
        INTENT_SAVED_PLACE_EMOJI_REACTION = 241;
        INTENT_SAVED_PLACE_LIST = 87;
        INTENT_SAVED_PLACE_LIST_ITEM_TREATMENT = 230;
        INTENT_SEARCH_RESULT_TITLE_SIZE = 149 [deprecated = true];
        INTENT_SEARCH_RESULT_CATEGORY_COLOR = 150;
        INTENT_SEGMENT_ADDRESS_TAG = 17;
        INTENT_SEGMENT_CONSTRUCTION_CATEGORY = 57;
        INTENT_SEGMENT_ELEVATION = 5;
        INTENT_SEGMENT_PRIORITY = 6;
        INTENT_SEGMENT_PRIVATE = 30;
        INTENT_SEGMENT_RESTRICTION_THROUGH_TRAFFIC = 55;
        INTENT_SEGMENT_SURFACE = 7;
        INTENT_SEGMENT_UNDER_CONSTRUCTION = 20 [deprecated = true];
        INTENT_SEGMENT_USAGE = 8;
        INTENT_SHAKING_INTENSITY = 73;
        INTENT_SHAKING_INTENSITY_JMA = 176;
        INTENT_STOP_SIGN = 210;
        INTENT_STREAMING_SEARCH_RESULT_CLASS = 139 [deprecated = true];
        INTENT_SUMMARY_COUNT_FOOD_AND_DRINK = 96 [deprecated = true];
        INTENT_SUMMARY_COUNT_SHOPPING = 97 [deprecated = true];
        INTENT_SUMMARY_COUNT_THINGS_TO_DO = 98 [deprecated = true];
        INTENT_SKI_LIFT_TYPE = 9;
        INTENT_SKI_TRAIL_DIFFICULTY = 10;
        INTENT_SKI_TRAIL_TYPE = 11;
        INTENT_SMOKE_PLUME_POLYGON = 212;
        INTENT_SPOTLIGHT_CLASS = 36;
        INTENT_SPOTLIGHT_PRIORITY = 37;
        INTENT_SPOTLIT_AD_POI_PIN_COLOR = 79 [deprecated = true];
        INTENT_STREETVIEW_COVERAGE = 18;
        INTENT_STYLE_TRANSFORM = 113;
        INTENT_SUB_STYLE_TAG = 132;
        INTENT_TERRAIN_TYPE = 69;
        INTENT_TOLL_ROAD = 12;
        INTENT_TRAFFIC_DISRUPTION = 77;
        INTENT_TRAFFIC_INCIDENT_PROVIDER = 100;
        INTENT_TRAFFIC_INCIDENT_VARIANT = 106;
        INTENT_JARTIC_TRAFFIC_INCIDENT_CODE = 248;
        INTENT_TRANSIT_DATASET_NAME = 118;
        INTENT_TRANSIT_ICON_ID = 85;
        INTENT_TRANSIT_ICON_RESOURCE = 126;
        INTENT_ICON_RENDER_HINT = 127;
        INTENT_TRANSIT_LINE_COLOR = 50;
        INTENT_TRANSIT_LINE_EXISTS_IN_VSTORE = 94;
        INTENT_TRANSIT_LINE_INFO_ON_STATION = 80 [deprecated = true];
        INTENT_TRANSIT_LINE_FROM_TRANSIT_LAYER_SERVER = 95;
        INTENT_TRANSIT_LINE_NAME = 81 [deprecated = true];
        INTENT_TRANSIT_LINE_OFFSET = 74 [deprecated = true];
        INTENT_TRANSIT_MAP_LABEL_TYPE = 301;
        INTENT_TRANSIT_TEXT_COLOR = 52;
        INTENT_TRANSIT_LINE_TREATMENT = 125;
        INTENT_TRANSIT_LAYER_VERSION = 278;
        INTENT_TRAVEL_MAP_PROMINENCE = 307;
        INTENT_TRAVEL_MAP_AREA_OF_INTEREST = 193;
        INTENT_TRAVEL_MAP_CORRIDOR_OF_INTEREST = 233;
        INTENT_TRAVEL_MAP_ITINERARY_PATH = 221;
        INTENT_TREE_TYPE = 218;
        INTENT_TREE_DENSITY_BUCKET = 270;
        INTENT_TREE_SEASON = 273;
        INTENT_TREE_ALMOST_MASKED = 293;
        INTENT_TROPICAL_STORM_ELEMENT = 66;
        INTENT_TROPICAL_STORM_INTENSITY = 65;
        INTENT_TROPICAL_STORM_PUBLISHER = 67;
        INTENT_UNADDRESSED_BUILDING_POLYGON = 214;
        INTENT_USE_BUILDING_FOOTPRINT = 40;
        INTENT_USER_LABEL_WITH_LINE = 53;
        INTENT_VEHICLE_TYPE = 13;
        INTENT_VIDEO_STREAMING_QUALITY_RATING = 82 [deprecated = true];
        INTENT_WILDFIRE_BOUNDARY = 185;
        INTENT_WILDFIRE_PERCENT_CONTAINED = 234;
        INTENT_WILDFIRE_POLYGON_TYPE = 257;
        INTENT_WILDFIRE_IMMERSIVE = 186 [deprecated = true];
        INTENT_WILDFIRE_LIKELIHOOD = 161 [deprecated = true];
        INTENT_OBSERVED_WINDOW_CLASS = 254;
        INTENT_OBSERVED_SHININESS_CLASS = 255;
        INTENT_OBSERVED_COLOR_CLASS = 256;
        INTENT_CLICKABLE = 260;
        INTENT_SMARTMAPS = 261;
        INTENT_SEARCH_MAP_TRANSPARENT_PIN = 263;
        INTENT_SEARCH_MAP_SECONDARY_LABEL_CAN_BE_DROPPED = 267;
        INTENT_TUNNEL_IN_3D = 265;
        INTENT_VIEW_MODE = 269;
        INTENT_TRANSIT_STATION_TIER = 272;
        INTENT_PROMINENT_NAV_POI = 280;
        INTENT_PISA_LANDMARK = 299;
        INTENT_ASKMAPS_HIGHLIGHT = 296;
    }
    
    optional string fallback_key = 2;
    optional int32 int_value = 3;
    optional bytes string_value = 4;
    repeated fixed32 experiment_id = 5;
}

message IntentListProto {
    repeated IntentProto intent = 1;
    
    extend .proto2.bridge.MessageSet {
        optional IntentListProto message_set_extension = 17338285;
    }
}

enum LabelClassIntent {
    LABEL_CLASS_TITLE = 1;
    LABEL_CLASS_SUBTITLE = 2;
    LABEL_CLASS_ICON = 3;
    LABEL_CLASS_PRIMARY_GROUP = 4;
    LABEL_CLASS_SECONDARY_GROUP = 5;
    LABEL_CLASS_OVERALL = 6;
    LABEL_CLASS_STRUCTURE = 7;
}

enum GltfModelClassIntent {
    GLTF_MODEL_CLASS_UNKNOWN = 0;
    GLTF_MODEL_CLASS_OVERALL = 1;
    GLTF_MODEL_CLASS_BUILDING_FACADE = 2;
    GLTF_MODEL_CLASS_BUILDING_ROOF = 3;
    GLTF_MODEL_CLASS_BUILDING_WINDOW = 4;
    GLTF_MODEL_CLASS_BUILDING_DOOR = 5;
}

enum LanguageDirection {
    LANGUAGE_DIRECTION_UNKNOWN = 0;
    LANGUAGE_DIRECTION_LTR = 1;
    LANGUAGE_DIRECTION_RTL = 2;
}

enum RapHighlightIntent {
    RAP_HIGHLIGHT_NONE = 0;
    RAP_HIGHLIGHT_ROAD_SEGMENT = 1;
}

enum TerrainType {
    TERRAIN_UNKNOWN = 0;
    TERRAIN_ELEVATION = 1;
    TERRAIN_ELEVATION_SHADING = 17;
    TERRAIN_CONTOUR_LINE = 18;
    TERRAIN_CONTOUR_LINE_MAJOR = 289;
    TERRAIN_CONTOUR_LINE_MINOR = 290;
    TERRAIN_BASEMAP_SHADING = 2;
}

enum TransitLogicalStationType {
    LOGICAL_STATION_UNKNOWN = 0;
    LOGICAL_STATION_PROXIMATE_BUS_STOPS = 1;
    LOGICAL_STATION_UNIMODAL_TERMINAL = 2;
    LOGICAL_STATION_LARGE_INTERCHANGE = 3;
    LOGICAL_STATION_MODE_TRANSFER = 4;
}

enum AirQualityStationIcon {
    AIR_QUALITY_STATION_ICON_UNKNOWN = 0;
    AIR_QUALITY_STATION_ICON_DEFAULT = 1;
}

enum AirQualityStationIntent {
    AIR_QUALITY_STATION_INTENT_UNKNOWN = 0;
    AIR_QUALITY_STATION_INTENT_SECONDARY_LABEL_TEXT = 1;
    AIR_QUALITY_STATION_INTENT_TINY = 2;
    AIR_QUALITY_STATION_INTENT_EXTENDED = 3;
    AIR_QUALITY_STATION_INTENT_STANDARD = 4;
    AIR_QUALITY_STATION_INTENT_STANDARD_LABEL_TEXT = 5;
}

enum AirQualityExtendedLabelTextPositionType {
    AIR_QUALITY_EXTENDED_LABEL_TEXT_POSITION_TYPE_UNKNOWN = 0;
    AIR_QUALITY_EXTENDED_LABEL_TEXT_POSITION_TYPE_INNER = 1;
    AIR_QUALITY_EXTENDED_LABEL_TEXT_POSITION_TYPE_OUTER = 2;
}

enum AirQualityExtendedLabelTextColorType {
    AIR_QUALITY_EXTENDED_LABEL_TEXT_COLOR_TYPE_UNKNOWN = 0;
    AIR_QUALITY_EXTENDED_LABEL_TEXT_COLOR_TYPE_ON_LIGHT_LABEL_BACKGROUND = 1;
    AIR_QUALITY_EXTENDED_LABEL_TEXT_COLOR_TYPE_ON_DARK_LABEL_BACKGROUND = 2;
}

enum SmokePlumePolygon {
    SMOKE_PLUME_POLYGON_UNKNOWN = 0;
    SMOKE_PLUME_POLYGON_LIGHT_DENSITY = 1;
    SMOKE_PLUME_POLYGON_MEDIUM_DENSITY = 2;
    SMOKE_PLUME_POLYGON_HEAVY_DENSITY = 3;
}

enum BusynessLevel {
    BUSYNESS_LEVEL_UNKNOWN = 0;
    BUSYNESS_LEVEL_NOT_BUSY = 1;
    BUSYNESS_LEVEL_BUSY = 2;
    BUSYNESS_LEVEL_BUSY_DARK_LAUNCH = 3;
}

enum TouristCorridorCategory {
    TOURIST_CORRIDOR_CATEGORY_UNKNOWN = 0;
    TOURIST_CORRIDOR_CATEGORY_SHOPPING = 1;
    TOURIST_CORRIDOR_CATEGORY_SIGHTSEEING = 2;
    TOURIST_CORRIDOR_CATEGORY_DINING = 3;
}

enum GasBrandIcon {
    GAS_BRAND_ICON_UNKNOWN = 0;
    GAS_BRAND_ICON_76 = 1;
    GAS_BRAND_ICON_7_ELEVEN = 2;
    GAS_BRAND_ICON_ARCO = 3;
    GAS_BRAND_ICON_BP = 4;
    GAS_BRAND_ICON_BJS = 5;
    GAS_BRAND_ICON_BUCEES = 6;
    GAS_BRAND_ICON_CASEYS = 7;
    GAS_BRAND_ICON_CENEX = 8;
    GAS_BRAND_ICON_CHEVRON = 9;
    GAS_BRAND_ICON_CIRCLE_K = 10;
    GAS_BRAND_ICON_CITGO = 11;
    GAS_BRAND_ICON_CONOCO = 12;
    GAS_BRAND_ICON_COSTCO = 13;
    GAS_BRAND_ICON_EXXON = 14;
    GAS_BRAND_ICON_FAST_STOP = 15;
    GAS_BRAND_ICON_GET_GO = 16;
    GAS_BRAND_ICON_GULF = 17;
    GAS_BRAND_ICON_HEB = 18;
    GAS_BRAND_ICON_HESS = 19;
    GAS_BRAND_ICON_HOLIDAY = 20;
    GAS_BRAND_ICON_HOLIDAY_OIL = 21;
    GAS_BRAND_ICON_HYVEE_GAS = 22;
    GAS_BRAND_ICON_IRVING = 23;
    GAS_BRAND_ICON_KROGER = 24;
    GAS_BRAND_ICON_KUM_AND_GO = 25;
    GAS_BRAND_ICON_KWIK_FILL = 26;
    GAS_BRAND_ICON_KWIK_TRIP = 27;
    GAS_BRAND_ICON_LIBERTY = 28;
    GAS_BRAND_ICON_LOVES = 29;
    GAS_BRAND_ICON_LUKOIL = 30;
    GAS_BRAND_ICON_MAPCO_EXPRESS = 31;
    GAS_BRAND_ICON_MARATHON = 32;
    GAS_BRAND_ICON_MAVERIK = 33;
    GAS_BRAND_ICON_MEIJER = 34;
    GAS_BRAND_ICON_MOBIL = 35;
    GAS_BRAND_ICON_MURPHY_USA = 36;
    GAS_BRAND_ICON_PHILLIPS_66 = 37;
    GAS_BRAND_ICON_PILOT = 38;
    GAS_BRAND_ICON_QUICKTRIP = 39;
    GAS_BRAND_ICON_RACEWAY = 40;
    GAS_BRAND_ICON_SAMS_CLUB = 41;
    GAS_BRAND_ICON_SAFEWAY = 42;
    GAS_BRAND_ICON_SHEETZ = 43;
    GAS_BRAND_ICON_SHELL = 44;
    GAS_BRAND_ICON_SINCLAIR = 45;
    GAS_BRAND_ICON_SPEEDWAY = 46;
    GAS_BRAND_ICON_STEWARTS = 47;
    GAS_BRAND_ICON_SUNOCO = 48;
    GAS_BRAND_ICON_TESORO = 49;
    GAS_BRAND_ICON_TEXACO = 50;
    GAS_BRAND_ICON_TURKEY_HILL = 51;
    GAS_BRAND_ICON_TWICE_DAILY = 52;
    GAS_BRAND_ICON_VALERO = 53;
    GAS_BRAND_ICON_WALMART = 54;
    GAS_BRAND_ICON_WAWA = 55;
    GAS_BRAND_ICON_WEIGELS = 56;
}

enum HotelDisplayType {
    HOTEL_DISPLAY_TYPE_UNKNOWN = 0;
    HOTEL_DISPLAY_TYPE_DEAL = 1 [deprecated = true];
    HOTEL_DISPLAY_TYPE_MOD = 2;
    HOTEL_DISPLAY_TYPE_DEAL_MOD = 4 [deprecated = true];
    HOTEL_DISPLAY_TYPE_DEAL_EXTENDED_PIN = 5 [deprecated = true];
    HOTEL_DISPLAY_TYPE_LEGACY_MOD = 3;
    HOTEL_DISPLAY_TYPE_EXTENDED_PIN = 6;
}

enum CrisisLabelType {
    option deprecated = true;
    CRISIS_LABEL_TYPE_DEFAULT = 0;
    CRISIS_LABEL_TYPE_GEOMETRY = 1;
}

enum IntersectionHintsIntent {
    INTERSECTS_NONE = 1;
    INTERSECTS_SINGLES_ONLY = 2;
    INTERSECTS_SAME_PRI_ONLY = 4;
    INTERSECTS_HINTS_ALL = 7;
}

enum ExtendedPinLayoutType {
    EXTENDED_PIN_LAYOUT_UNKNOWN = 0;
    EXTENDED_PIN_LAYOUT_ICON_TEXT = 1;
    EXTENDED_PIN_LAYOUT_TEXT_ICON = 2 [deprecated = true];
    EXTENDED_PIN_LAYOUT_TEXT_ONLY = 3 [deprecated = true];
}

enum SearchResultColorOverride {
    SEARCH_RESULT_COLOR_OVERRIDE_UNKNOWN = 0;
    SEARCH_RESULT_COLOR_OVERRIDE_DEFAULT_COLOR = 1;
    SEARCH_RESULT_COLOR_OVERRIDE_BLANK_CANVAS = 2;
    SEARCH_RESULT_COLOR_OVERRIDE_CATEGORICAL_COLOR = 3;
}

enum AtomicMapsLaneMarkerPlacement {
    ATOMIC_MAPS_LANE_MARKER_PLACEMENT_UNKNOWN = 0;
    ATOMIC_MAPS_LANE_MARKER_PLACEMENT_INSIDE = 1;
    ATOMIC_MAPS_LANE_MARKER_PLACEMENT_OUTSIDE = 2;
}

enum AtomicMapsLaneMarkerType {
    ATOMIC_MAPS_LANE_MARKER_TYPE_UNKNOWN = 0;
    ATOMIC_MAPS_LANE_MARKER_TYPE_CROSSABLE = 1;
    ATOMIC_MAPS_LANE_MARKER_TYPE_SOLID = 2;
    ATOMIC_MAPS_LANE_MARKER_TYPE_CENTERLINE = 3;
    ATOMIC_MAPS_LANE_MARKER_USAGE_SEPARATION = 4;
    ATOMIC_MAPS_LANE_MARKER_TYPE_SHARED = 5;
}

enum AtomicMapsLaneTurnType {
    ATOMIC_MAPS_LANE_TURN_TYPE_NONE = 0;
    ATOMIC_MAPS_LANE_TURN_TYPE_LEFT = 1;
    ATOMIC_MAPS_LANE_TURN_TYPE_RIGHT = 2;
    ATOMIC_MAPS_LANE_TURN_TYPE_BIDIRECTIONAL_LEFT = 5;
    ATOMIC_MAPS_LANE_TURN_TYPE_BIDIRECTIONAL_RIGHT = 6;
}

enum AtomicMapsLaneUsageType {
    ATOMIC_MAP_LANE_USAGE_TYPE_UNKNOWN = 0;
    ATOMIC_MAP_LANE_USAGE_TYPE_BIKE = 1;
    ATOMIC_MAP_LANE_USAGE_TYPE_TAXI = 2;
    ATOMIC_MAP_LANE_USAGE_TYPE_PARKING = 3;
    ATOMIC_MAP_LANE_USAGE_TYPE_HOV = 4;
    ATOMIC_MAP_LANE_USAGE_TYPE_BUS = 5;
    ATOMIC_MAP_LANE_USAGE_TYPE_RESTRICTED = 6;
    ATOMIC_MAP_LANE_USAGE_TYPE_MEDIAN = 7;
    ATOMIC_MAP_LANE_USAGE_TYPE_DRIVABLE = 8;
}

enum AtomicMapsMedianType {
    option deprecated = true;
    ATOMIC_MAPS_MEDIAN_TYPE_UNKNOWN = 0;
    ATOMIC_MAPS_MEDIAN_TYPE_PAINTED = 1;
}

enum ImageryResultType {
    IMAGERY_RESULT_TYPE_UNKNOWN = 0;
    IMAGERY_RESULT_TYPE_RESTRICTED_PARKING = 1;
    IMAGERY_RESULT_TYPE_NO_PARKING = 2;
}

enum ReachabilityPolygonType {
    REACHABILITY_POLYGON_TYPE_UNKNOWN = 0;
    REACHABILITY_POLYGON_TYPE_DEFAULT = 1;
    REACHABILITY_POLYGON_TYPE_UNAVAILABLE = 2;
}

enum TravelMapItineraryPathType {
    TRAVEL_MAP_ITINERARY_PATH_TYPE_UNKNOWN = 0;
    TRAVEL_MAP_ITINERARY_PATH_TYPE_DEFAULT = 1;
    TRAVEL_MAP_ITINERARY_PATH_TYPE_WALK = 2;
    TRAVEL_MAP_ITINERARY_PATH_TYPE_DRIVE = 3;
}

enum UnaddressedBuildingPolygonType {
    UNADDRESSED_BUILDING_POLYGON_UNKNOWN = 0;
    UNADDRESSED_BUILDING_POLYGON_DEFAULT = 1;
}

enum TreeType {
    TREE_TYPE_UNKNOWN = 0;
    TREE_TYPE_DEFAULT = 1;
    TREE_TYPE_WIDE = 2;
    TREE_TYPE_SKINNY = 3;
    TREE_TYPE_CONIFEROUS = 4;
    TREE_TYPE_PALM = 5;
    TREE_TYPE_CACTUS = 6;
}

enum TreeBucket {
    TREE_BUCKET_UNKNOWN = 0;
    TREE_BUCKET_1 = 1;
    TREE_BUCKET_2 = 2;
    TREE_BUCKET_3 = 3;
    TREE_BUCKET_4 = 4;
    TREE_BUCKET_5 = 5;
    TREE_BUCKET_6 = 6;
    TREE_BUCKET_7 = 7;
    TREE_BUCKET_8 = 8;
    TREE_BUCKET_9 = 9;
    TREE_BUCKET_10 = 10;
}

enum TreeSeason {
    TREE_SEASON_UNKNOWN = 0;
    TREE_SEASON_SPRING = 1;
    TREE_SEASON_SUMMER = 2;
    TREE_SEASON_FALL = 3;
    TREE_SEASON_WINTER = 4;
}

enum EntranceType {
    ENTRANCE_TYPE_UNKNOWN = 0;
    ENTRANCE_TYPE_LEGACY_INDOOR = 1;
    ENTRANCE_TYPE_TRANSIT = 2;
    ENTRANCE_TYPE_FOR_SELECTED_POI = 3;
    ENTRANCE_TYPE_ON_BUILDING_FOR_SELECTED_POI = 4;
    ENTRANCE_TYPE_RECOMMENDED_FOR_DIRECTIONS = 5;
    ENTRANCE_TYPE_FOR_SELECTED_TRANSIT_STATION = 6;
    ENTRANCE_TYPE_FOR_SELECTED_INDOOR_POI = 7;
    ENTRANCE_TYPE_ON_BUILDING_FOR_SELECTED_INDOOR_POI = 8;
    ENTRANCE_TYPE_FOR_SELECTED_TRANSIT_STATION_TAPPABLE = 9;
    ENTRANCE_TYPE_ROUTED = 10;
    ENTRANCE_TYPE_STATIC_BASEMAP_INVISIBLE = 11;
    ENTRANCE_TYPE_ALTERNATIVE_ROUTED_TRANSIT_STATION = 12;
    ENTRANCE_TYPE_ROUTED_TRANSIT_STATION = 13;
}

enum BuiltUpAreaType {
    BUILT_UP_AREA_TYPE_UNKNOWN = 0;
    BUILT_UP_AREA_TYPE_CONTEXTUAL = 1;
    BUILT_UP_AREA_TYPE_LEGACY = 2;
    BUILT_UP_AREA_TYPE_LEGACY_SHALLOW_ZOOM = 3;
}

enum ContextualGroundcoverType {
    CONTEXTUAL_GROUNDCOVER_TYPE_UNKNOWN = 0;
    CONTEXTUAL_GROUNDCOVER_TYPE_SYNTHETIC_GREEN = 1;
    CONTEXTUAL_GROUNDCOVER_TYPE_BARE_GROUND = 2;
}

enum EntityHighlighting {
    HIGHLIGHT_UNKNOWN = 0;
    HIGHLIGHT_OUTLINE = 1;
    HIGHLIGHT_FILL = 2;
    HIGHLIGHT_INVERTED = 3;
}

enum ViewsExperienceType {
    VIEWS_EXPERIENCE_UNKNOWN = 0;
    VIEWS_EXPERIENCE_LIVEVIEW = 1;
    VIEWS_EXPERIENCE_STREETVIEW = 2;
}

enum DimensionalDisplayMode {
    DIMENSIONAL_DISPLAY_MODE_UNKNOWN = 0;
    DIMENSIONAL_DISPLAY_MODE_2D = 1;
    DIMENSIONAL_DISPLAY_MODE_3D = 2;
}

enum SeasonalEventType {
    SEASONAL_EVENT_TYPE_UNKNOWN = 0;
    SEASONAL_EVENT_TYPE_CHERRY_BLOSSOM = 1;
}

enum TaggedMaterialWindowClass {
    MATERIAL_WINDOW_UNKNOWN = 0;
    MATERIAL_WINDOW_GENERIC = 1;
}

enum TaggedMaterialShininessClass {
    MATERIAL_SHININESS_UNKNOWN = 0;
    MATERIAL_NOT_SHINY = 1;
    MATERIAL_SEMI_SHINY = 2;
    MATERIAL_SHINY = 3;
}

enum ExperienceListType {
    EXPERIENCE_LIST_TYPE_UNKNOWN = 0;
    EXPERIENCE_LIST_TYPE_TRAVEL = 1;
}

enum ExperienceListLabelClassType {
    EXPERIENCE_LIST_LABEL_CLASS_TYPE_UNKNOWN = 0;
    EXPERIENCE_LIST_LABEL_CLASS_TYPE_EXTENDED_PIN = 1;
    EXPERIENCE_LIST_LABEL_CLASS_TYPE_SECONDARY_TEXT = 2;
}

enum TaggedMaterialColorClass {
    MATERIAL_COLOR_UNKNOWN = 0;
    MATERIAL_COLOR_RED10 = 1;
    MATERIAL_COLOR_RED20 = 2;
    MATERIAL_COLOR_RED30 = 3;
    MATERIAL_COLOR_RED40 = 4;
    MATERIAL_COLOR_RED50 = 5;
    MATERIAL_COLOR_RED60 = 6;
    MATERIAL_COLOR_RED70 = 7;
    MATERIAL_COLOR_RED80 = 94;
    MATERIAL_COLOR_PURPLE10 = 8;
    MATERIAL_COLOR_PURPLE20 = 9;
    MATERIAL_COLOR_PURPLE30 = 10;
    MATERIAL_COLOR_PURPLE40 = 11;
    MATERIAL_COLOR_PURPLE50 = 12;
    MATERIAL_COLOR_PURPLE60 = 13;
    MATERIAL_COLOR_PURPLE70 = 14;
    MATERIAL_COLOR_PURPLE80 = 95;
    MATERIAL_COLOR_BLUE10 = 96;
    MATERIAL_COLOR_BLUE20 = 97;
    MATERIAL_COLOR_BLUE30 = 98;
    MATERIAL_COLOR_BLUE40 = 99;
    MATERIAL_COLOR_BLUE50 = 100;
    MATERIAL_COLOR_BLUE60 = 101;
    MATERIAL_COLOR_BLUE70 = 102;
    MATERIAL_COLOR_BLUE80 = 103;
    MATERIAL_COLOR_GREEN10 = 29;
    MATERIAL_COLOR_GREEN20 = 30;
    MATERIAL_COLOR_GREEN30 = 31;
    MATERIAL_COLOR_GREEN40 = 32;
    MATERIAL_COLOR_GREEN50 = 33;
    MATERIAL_COLOR_GREEN60 = 34;
    MATERIAL_COLOR_GREEN70 = 35;
    MATERIAL_COLOR_GREEN80 = 163;
    MATERIAL_COLOR_YELLOW10 = 36;
    MATERIAL_COLOR_YELLOW20 = 37;
    MATERIAL_COLOR_YELLOW30 = 38;
    MATERIAL_COLOR_YELLOW40 = 39;
    MATERIAL_COLOR_YELLOW50 = 40;
    MATERIAL_COLOR_YELLOW60 = 41;
    MATERIAL_COLOR_YELLOW70 = 42;
    MATERIAL_COLOR_YELLOW80 = 164;
    MATERIAL_COLOR_ORANGE10 = 43;
    MATERIAL_COLOR_ORANGE20 = 44;
    MATERIAL_COLOR_ORANGE30 = 45;
    MATERIAL_COLOR_ORANGE40 = 46;
    MATERIAL_COLOR_ORANGE50 = 47;
    MATERIAL_COLOR_ORANGE60 = 48;
    MATERIAL_COLOR_ORANGE70 = 49;
    MATERIAL_COLOR_ORANGE80 = 165;
    MATERIAL_COLOR_BLUEGREY10 = 104;
    MATERIAL_COLOR_BLUEGREY20 = 105;
    MATERIAL_COLOR_BLUEGREY30 = 106;
    MATERIAL_COLOR_BLUEGREY40 = 107;
    MATERIAL_COLOR_BLUEGREY50 = 108;
    MATERIAL_COLOR_BLUEGREY60 = 109;
    MATERIAL_COLOR_BLUEGREY70 = 110;
    MATERIAL_COLOR_BLUEGREY80 = 111;
    MATERIAL_COLOR_GREENGREY10 = 112;
    MATERIAL_COLOR_GREENGREY20 = 113;
    MATERIAL_COLOR_GREENGREY30 = 114;
    MATERIAL_COLOR_GREENGREY40 = 115;
    MATERIAL_COLOR_GREENGREY50 = 116;
    MATERIAL_COLOR_GREENGREY60 = 117;
    MATERIAL_COLOR_GREENGREY70 = 118;
    MATERIAL_COLOR_GREENGREY80 = 119;
    MATERIAL_COLOR_BROWN10 = 120;
    MATERIAL_COLOR_BROWN20 = 121;
    MATERIAL_COLOR_BROWN30 = 122;
    MATERIAL_COLOR_BROWN40 = 123;
    MATERIAL_COLOR_BROWN50 = 124;
    MATERIAL_COLOR_BROWN60 = 125;
    MATERIAL_COLOR_BROWN70 = 126;
    MATERIAL_COLOR_BROWN80 = 127;
    MATERIAL_COLOR_TERRACOTTA10 = 128;
    MATERIAL_COLOR_TERRACOTTA20 = 129;
    MATERIAL_COLOR_TERRACOTTA30 = 130;
    MATERIAL_COLOR_TERRACOTTA40 = 131;
    MATERIAL_COLOR_TERRACOTTA50 = 132;
    MATERIAL_COLOR_TERRACOTTA60 = 133;
    MATERIAL_COLOR_TERRACOTTA70 = 134;
    MATERIAL_COLOR_TERRACOTTA80 = 135;
    MATERIAL_COLOR_BRICK10 = 136;
    MATERIAL_COLOR_BRICK20 = 137;
    MATERIAL_COLOR_BRICK30 = 138;
    MATERIAL_COLOR_BRICK40 = 139;
    MATERIAL_COLOR_BRICK50 = 140;
    MATERIAL_COLOR_BRICK60 = 141;
    MATERIAL_COLOR_BRICK70 = 142;
    MATERIAL_COLOR_BRICK80 = 143;
    MATERIAL_COLOR_GLASS30 = 144;
    MATERIAL_COLOR_GLASS40 = 145;
    MATERIAL_COLOR_GLASS50 = 146;
    MATERIAL_COLOR_WARMWHITE10 = 147;
    MATERIAL_COLOR_WARMWHITE20 = 148;
    MATERIAL_COLOR_WARMWHITE30 = 149;
    MATERIAL_COLOR_WARMWHITE40 = 150;
    MATERIAL_COLOR_WARMWHITE50 = 151;
    MATERIAL_COLOR_WARMWHITE60 = 152;
    MATERIAL_COLOR_WARMWHITE70 = 153;
    MATERIAL_COLOR_WARMWHITE80 = 154;
    MATERIAL_COLOR_COOLWHITE10 = 155;
    MATERIAL_COLOR_COOLWHITE20 = 156;
    MATERIAL_COLOR_COOLWHITE30 = 157;
    MATERIAL_COLOR_COOLWHITE40 = 158;
    MATERIAL_COLOR_COOLWHITE50 = 159;
    MATERIAL_COLOR_COOLWHITE60 = 160;
    MATERIAL_COLOR_COOLWHITE70 = 161;
    MATERIAL_COLOR_COOLWHITE80 = 162;
    MATERIAL_COLOR_GRASSY_AREA = 91;
    MATERIAL_COLOR_WATER = 92;
    MATERIAL_COLOR_DEFAULT_MATERIAL = 93;
    MATERIAL_COLOR_DARK_BLUE10 = 15 [deprecated = true];
    MATERIAL_COLOR_DARK_BLUE20 = 16 [deprecated = true];
    MATERIAL_COLOR_DARK_BLUE30 = 17 [deprecated = true];
    MATERIAL_COLOR_DARK_BLUE40 = 18 [deprecated = true];
    MATERIAL_COLOR_DARK_BLUE50 = 19 [deprecated = true];
    MATERIAL_COLOR_DARK_BLUE60 = 20 [deprecated = true];
    MATERIAL_COLOR_DARK_BLUE70 = 21 [deprecated = true];
    MATERIAL_COLOR_LIGHT_BLUE10 = 22 [deprecated = true];
    MATERIAL_COLOR_LIGHT_BLUE20 = 23 [deprecated = true];
    MATERIAL_COLOR_LIGHT_BLUE30 = 24 [deprecated = true];
    MATERIAL_COLOR_LIGHT_BLUE40 = 25 [deprecated = true];
    MATERIAL_COLOR_LIGHT_BLUE50 = 26 [deprecated = true];
    MATERIAL_COLOR_LIGHT_BLUE60 = 27 [deprecated = true];
    MATERIAL_COLOR_LIGHT_BLUE70 = 28 [deprecated = true];
    MATERIAL_COLOR_DARK_GREY10 = 50 [deprecated = true];
    MATERIAL_COLOR_DARK_GREY20 = 51 [deprecated = true];
    MATERIAL_COLOR_DARK_GREY30 = 52 [deprecated = true];
    MATERIAL_COLOR_DARK_GREY40 = 53 [deprecated = true];
    MATERIAL_COLOR_DARK_GREY50 = 54 [deprecated = true];
    MATERIAL_COLOR_DARK_GREY60 = 55 [deprecated = true];
    MATERIAL_COLOR_DARK_GREY70 = 56 [deprecated = true];
    MATERIAL_COLOR_BROWN_GREY10 = 57 [deprecated = true];
    MATERIAL_COLOR_BROWN_GREY20 = 58 [deprecated = true];
    MATERIAL_COLOR_BROWN_GREY30 = 59 [deprecated = true];
    MATERIAL_COLOR_BROWN_GREY40 = 60 [deprecated = true];
    MATERIAL_COLOR_BROWN_GREY50 = 61 [deprecated = true];
    MATERIAL_COLOR_BROWN_GREY60 = 62 [deprecated = true];
    MATERIAL_COLOR_BROWN_GREY70 = 63 [deprecated = true];
    MATERIAL_COLOR_BROWN_YELLOW10 = 64 [deprecated = true];
    MATERIAL_COLOR_BROWN_YELLOW20 = 65 [deprecated = true];
    MATERIAL_COLOR_BROWN_YELLOW30 = 66 [deprecated = true];
    MATERIAL_COLOR_BROWN_YELLOW40 = 67 [deprecated = true];
    MATERIAL_COLOR_BROWN_YELLOW50 = 68 [deprecated = true];
    MATERIAL_COLOR_BROWN_YELLOW60 = 69 [deprecated = true];
    MATERIAL_COLOR_BROWN_YELLOW70 = 70 [deprecated = true];
    MATERIAL_COLOR_BROWN_RED10 = 71 [deprecated = true];
    MATERIAL_COLOR_BROWN_RED20 = 72 [deprecated = true];
    MATERIAL_COLOR_BROWN_RED30 = 73 [deprecated = true];
    MATERIAL_COLOR_BROWN_RED40 = 74 [deprecated = true];
    MATERIAL_COLOR_BROWN_RED50 = 75 [deprecated = true];
    MATERIAL_COLOR_BROWN_RED60 = 76 [deprecated = true];
    MATERIAL_COLOR_BROWN_RED70 = 77 [deprecated = true];
    MATERIAL_COLOR_BROWN_OLD10 = 78 [deprecated = true];
    MATERIAL_COLOR_BROWN_OLD20 = 79 [deprecated = true];
    MATERIAL_COLOR_BROWN_OLD30 = 80 [deprecated = true];
    MATERIAL_COLOR_BROWN_OLD40 = 81 [deprecated = true];
    MATERIAL_COLOR_BROWN_OLD50 = 82 [deprecated = true];
    MATERIAL_COLOR_BROWN_OLD60 = 83 [deprecated = true];
    MATERIAL_COLOR_BROWN_OLD70 = 84 [deprecated = true];
    MATERIAL_COLOR_GLASS_BLUE30 = 85 [deprecated = true];
    MATERIAL_COLOR_GLASS_BLUE40 = 86 [deprecated = true];
    MATERIAL_COLOR_GLASS_BLUE50 = 87 [deprecated = true];
    MATERIAL_COLOR_GLASS_TEAL30 = 88 [deprecated = true];
    MATERIAL_COLOR_GLASS_TEAL40 = 89 [deprecated = true];
    MATERIAL_COLOR_GLASS_TEAL50 = 90 [deprecated = true];
}

enum IndoorType {
    INDOOR_TYPE_UNKNOWN = 0;
    INDOOR_TYPE_AIRPORT = 1;
}

enum ElectricVehicleChargingStationAvailabilityType {
    ELECTRIC_VEHICLE_CHARGING_STATION_AVAILABILITY_TYPE_UNKNOWN = 0;
    ELECTRIC_VEHICLE_CHARGING_STATION_AVAILABILITY_TYPE_UNKNOWN_AVAILABILITY = 1;
    ELECTRIC_VEHICLE_CHARGING_STATION_AVAILABILITY_TYPE_OUT_OF_SERVICE = 2;
    ELECTRIC_VEHICLE_CHARGING_STATION_AVAILABILITY_TYPE_UNAVAILABLE = 3;
    ELECTRIC_VEHICLE_CHARGING_STATION_AVAILABILITY_TYPE_AVAILABLE = 4;
}

enum ElectricVehicleChargingStationChargingSpeed {
    ELECTRIC_VEHICLE_CHARGING_STATION_CHARGING_SPEED_UNKNOWN = 0;
    ELECTRIC_VEHICLE_CHARGING_STATION_CHARGING_SPEED_SLOW = 1;
    ELECTRIC_VEHICLE_CHARGING_STATION_CHARGING_SPEED_MEDIUM = 2;
    ELECTRIC_VEHICLE_CHARGING_STATION_CHARGING_SPEED_FAST = 3;
    ELECTRIC_VEHICLE_CHARGING_STATION_CHARGING_SPEED_VERY_FAST = 4;
    ELECTRIC_VEHICLE_CHARGING_STATION_CHARGING_SPEED_SUPER_FAST = 5;
}

enum ViewMode {
    VIEW_MODE_UNKNOWN = 0;
    VIEW_MODE_FIRST_PERSON = 1;
}

enum RoadShieldRefinementPhase {
    ROAD_SHIELD_REFINEMENT_UNKNOWN = 0;
    ROAD_SHIELD_REFINEMENT_PHASE1 = 1;
    ROAD_SHIELD_REFINEMENT_PHASE2 = 2;
}

enum AskMapsHighlightType {
    ASK_MAPS_HIGHLIGHT_TYPE_UNKNOWN = 0;
    ASK_MAPS_HIGHLIGHT_TYPE_AREA = 1;
}

enum GenaiMapsHighlightType {
    GENAI_MAPS_HIGHLIGHT_TYPE_UNKNOWN = 0;
    GENAI_MAPS_HIGHLIGHT_TYPE_AREA = 1;
}

enum GenaiMapsAreaHighlightColor {
    GENAI_MAPS_AREA_HIGHLIGHT_COLOR_UNKNOWN = 0;
    GENAI_MAPS_AREA_HIGHLIGHT_COLOR1 = 1;
    GENAI_MAPS_AREA_HIGHLIGHT_COLOR2 = 2;
    GENAI_MAPS_AREA_HIGHLIGHT_COLOR3 = 3;
    GENAI_MAPS_AREA_HIGHLIGHT_COLOR4 = 4;
}

enum GenaiMapsDynamicExtendedPinType {
    GENAI_MAPS_DYNAMIC_EXTENDED_PIN_TYPE_UNKNOWN = 0;
    GENAI_MAPS_DYNAMIC_EXTENDED_PIN_TYPE_POI = 1;
}

enum RouteCalloutCaretPosition {
    ROUTE_CALLOUT_CARET_POSITION_UNKNOWN = 0;
    ROUTE_CALLOUT_CARET_POSITION_TOP_LEFT = 1;
    ROUTE_CALLOUT_CARET_POSITION_TOP_RIGHT = 2;
    ROUTE_CALLOUT_CARET_POSITION_BOTTOM_LEFT = 3;
    ROUTE_CALLOUT_CARET_POSITION_BOTTOM_RIGHT = 4;
}

enum RouteCalloutTravelMode {
    ROUTE_CALLOUT_TRAVEL_MODE_UNKNOWN = 0;
    ROUTE_CALLOUT_TRAVEL_MODE_DRIVE = 1;
    ROUTE_CALLOUT_TRAVEL_MODE_WALK = 2;
    ROUTE_CALLOUT_TRAVEL_MODE_BICYCLE = 3;
    ROUTE_CALLOUT_TRAVEL_MODE_TRANSIT = 4;
    ROUTE_CALLOUT_TRAVEL_MODE_TWO_WHEELER = 5;
    ROUTE_CALLOUT_TRAVEL_MODE_TAXI = 6;
    ROUTE_CALLOUT_TRAVEL_MODE_FLIGHT = 7;
}
