syntax = "proto2";

package maps_versatile;

option objc_class_prefix = "GMV";
option java_package = "com.google.maps.versatile";

enum RenderingCategory {
    TYPE_ANY = 0;
    TYPE_UNDEFINED = 1;
    TYPE_BUSINESS = 2;
    TYPE_TRAVEL_SERVICE = 33;
    TYPE_LODGING = 8449;
    TYPE_RESORT = 135185;
    TYPE_VACATION_RENTAL = 135186;
    TYPE_ELECTRIC_VEHICLE_CHARGING_STATION = 8450;
    TYPE_SHOPPING = 34;
    TYPE_APPAREL = 8705;
    TYPE_SHOPPING_CENTER = 8706;
    TYPE_GROCERY = 8707;
    TYPE_SUPERMARKET = 139313;
    TYPE_MARKET = 139314;
    TYPE_ANTIQUES = 8708;
    TYPE_GIFTS = 8709;
    TYPE_SPORTING_GOODS = 8710;
    TYPE_VEHICLE = 8711;
    TYPE_SOUVENIR_SHOP = 8712;
    TYPE_CONVENIENCE_STORE = 8713;
    TYPE_AUTO_STORE = 8720;
    TYPE_BABY_STORE = 8721;
    TYPE_HARDWARE_STORE = 8722;
    TYPE_JEWELRY = 8723;
    TYPE_LIQUOR_STORE = 8724;
    TYPE_PET_STORE = 8725;
    TYPE_PLANT_STORE = 8726;
    TYPE_BOOK_STORE = 8727;
    TYPE_PERSONAL_CARE_STORE = 8728;
    TYPE_INDUSTRIAL = 35;
    TYPE_TRANSPORTATION = 8961;
    TYPE_PUBLIC_TRANSIT = 143377;
    TYPE_AIRPORT = 143378;
    TYPE_TRANSIT_STATION = 143379;
    TYPE_BUS_STATION = 2294065;
    TYPE_FERRY_TERMINAL = 2294066;
    TYPE_FUNICULAR_STATION = 2294067;
    TYPE_GONDOLA_LIFT_STATION = 2294068;
    TYPE_MONORAIL_STATION = 2294069;
    TYPE_TRAIN_STATION = 2294070;
    TYPE_SUBWAY_STATION = 2294071;
    TYPE_TRAMWAY_STATION = 2294072;
    TYPE_CABLE_CAR_STATION = 2294073;
    TYPE_SEAPORT = 143382;
    TYPE_AIRPORT_TERMINAL = 143390;
    TYPE_AGRICULTURE = 8962;
    TYPE_ENTERTAINMENT = 36;
    TYPE_AMUSEMENT_PARK = 9217;
    TYPE_ARTS = 9218;
    TYPE_PERFORMING_ARTS = 147489;
    TYPE_CLUBS = 9219;
    TYPE_GAMES = 9220;
    TYPE_CASINO = 147521;
    TYPE_FAIRGROUNDS = 9221;
    TYPE_HISTORICAL = 9222;
    TYPE_NATIONAL_HISTORIC_AREA = 147553;
    TYPE_MOVIES = 9223;
    TYPE_MOVIE_THEATER = 147569;
    TYPE_MUSEUM = 9224;
    TYPE_SERVICES = 37;
    TYPE_BANKING = 9473;
    TYPE_GAS_STATION = 9474;
    TYPE_REST_AREA = 9475;
    TYPE_REST_ROOM = 9476;
    TYPE_CASH_MACHINE = 9477;
    TYPE_CAR_RENTAL = 9478;
    TYPE_POST_OFFICE = 9479;
    TYPE_AUTO_REPAIR = 9480;
    TYPE_CAR_WASH = 9481;
    TYPE_CONSTRUCTION = 9482;
    TYPE_LAUNDRY = 9483;
    TYPE_DRY_CLEANER = 9484;
    TYPE_PET_SERVICES = 9485;
    TYPE_PROFESSIONAL_SERVICES = 9486;
    TYPE_REAL_ESTATE = 9487;
    TYPE_REPAIR_SERVICE = 9488;
    TYPE_PERSONAL_CARE = 38;
    TYPE_SPA = 9729;
    TYPE_BEAUTY_SALON = 9730;
    TYPE_BEAUTY_HAIR = 9731;
    TYPE_FITNESS_DEPRECATED = 9732;
    TYPE_FITNESS_YOGA_DEPRECATED = 2491393;
    TYPE_FOOD_AND_DRINK = 39;
    TYPE_BAR = 9985;
    TYPE_BEER = 159761;
    TYPE_BREWERY = 9986;
    TYPE_CAFE = 9987;
    TYPE_COFFEE = 9988;
    TYPE_FAST_FOOD = 9989;
    TYPE_FOOD_DELIVERY = 9990;
    TYPE_RESTAURANT = 9991;
    TYPE_ASIAN_RESTAURANT = 2557697;
    TYPE_CHINESE_RESTAURANT = 40923153;
    TYPE_INDIAN_RESTAURANT = 40923154;
    TYPE_JAPANESE_RESTAURANT = 40923155;
    TYPE_RAMEN_RESTAURANT = 654770481;
    TYPE_SUSHI_RESTAURANT = 654770482;
    TYPE_THAI_RESTAURANT = 40923156;
    TYPE_BBQ_RESTAURANT = 2557698;
    TYPE_BREAKFAST_RESTAURANT = 2557699;
    TYPE_BURGER_RESTAURANT = 2557700;
    TYPE_CHICKEN_RESTAURANT = 2557701;
    TYPE_FRENCH_RESTAURANT = 2557702;
    TYPE_ITALIAN_RESTAURANT = 2557703;
    TYPE_MEDITERANEAN_RESTAURANT = 2557704;
    TYPE_MEXICAN_RESTAURANT = 2557705;
    TYPE_PIZZA_RESTAURANT = 2557706;
    TYPE_SANDWICH_RESTAURANT = 2557707;
    TYPE_SEAFOOD_RESTAURANT = 2557708;
    TYPE_STEAK_RESTAURANT = 2557709;
    TYPE_VEGETERIAN_RESTAURANT = 2557710;
    TYPE_AMERICAN_RESTAURANT = 2557711;
    TYPE_TEA = 9992;
    TYPE_WINERY = 9993;
    TYPE_BAKERY = 9994;
    TYPE_DESSERT = 9995;
    TYPE_BUBBLE_TEA = 2558721;
    TYPE_DONUT = 2558722;
    TYPE_ICE_CREAM = 2558723;
    TYPE_EVENT_VENUE = 40;
    TYPE_AUDITORIUM = 10241;
    TYPE_CONCERT_HALL = 10242;
    TYPE_ACTIVITIES = 3;
    TYPE_BASEBALL = 769;
    TYPE_BOATING = 770;
    TYPE_CRICKET = 771;
    TYPE_FISHING = 772;
    TYPE_FOOTBALL = 773;
    TYPE_GOLF = 774;
    TYPE_GOLF_COURSE = 12385;
    TYPE_HIKING = 775;
    TYPE_RUGBY = 776;
    TYPE_SOCCER = 777;
    TYPE_SWIMMING = 778;
    TYPE_TENNIS = 779;
    TYPE_WINTER_SPORTS = 780;
    TYPE_BASKETBALL = 781;
    TYPE_SKYDIVING = 782;
    TYPE_WATER_SPORTS = 783;
    TYPE_SURF = 12529;
    TYPE_GO_KARTING = 12545;
    TYPE_ADVENTURE_SPORTS = 12546;
    TYPE_FITNESS = 12547;
    TYPE_FITNESS_YOGA = 200753;
    TYPE_GOVERNMENT = 4;
    TYPE_CITY_HALL = 1025;
    TYPE_EMBASSY = 1026;
    TYPE_LIBRARY = 1027;
    TYPE_MILITARY = 1028;
    TYPE_DAM = 1029;
    TYPE_EMERGENCY = 5;
    TYPE_HOSPITAL = 1281;
    TYPE_PHARMACY = 1282;
    TYPE_POLICE = 1283;
    TYPE_FIRE = 1284;
    TYPE_DOCTOR = 1285;
    TYPE_DENTIST = 1286;
    TYPE_PET_HEALTH = 1287;
    TYPE_TOURIST_DESTINATION = 6;
    TYPE_AQUARIUM = 1537;
    TYPE_LIGHTHOUSE = 1538;
    TYPE_MONUMENT = 1539;
    TYPE_PALACE = 1540;
    TYPE_SCENIC_POINT = 1541;
    TYPE_VISITOR_CENTER = 1542;
    TYPE_ZOO = 1543;
    TYPE_TEMPLE = 7;
    TYPE_BUDDHIST_TEMPLE = 1793;
    TYPE_CHURCH = 1794;
    TYPE_GURUDWARA = 1795;
    TYPE_JAIN_TEMPLE = 1796;
    TYPE_HINDU_TEMPLE = 1797;
    TYPE_MORMON_TEMPLE = 1798;
    TYPE_MOSQUE = 1799;
    TYPE_SYNAGOGUE = 1800;
    TYPE_SHINTO_TEMPLE = 1801;
    TYPE_UNITARIAN_UNIVERSALIST_CHURCH = 1802;
    TYPE_SPORTS_COMPLEX = 8;
    TYPE_STADIUM = 2049;
    TYPE_SCHOOL = 9;
    TYPE_DAYCARE = 2305;
    TYPE_SKILL_INSTRUCTION = 2306;
    TYPE_UNIVERSITY = 2307;
    TYPE_EARLY_EDUCATION = 2308;
    TYPE_TUTORING = 2309;
    TYPE_PARK = 10;
    TYPE_NATURE_RESERVE = 2561;
    TYPE_NATIONAL_PARK = 2562;
    TYPE_CAMPGROUNDS = 2563;
    TYPE_BOTANICAL_GARDEN = 2564;
    TYPE_MARINE_PROTECTED_AREA = 2565;
    TYPE_GARDEN = 2566;
    TYPE_BEACH = 2567;
    TYPE_DOG_PARK = 2568;
    TYPE_ENCLOSED_TRAFFIC_AREA = 11;
    TYPE_PARKING = 2817;
    TYPE_NATURAL_FEATURE = 12;
    TYPE_ELEVATED = 193;
    TYPE_PEAK = 3089;
    TYPE_HOUSING = 13;
    TYPE_APARTMENT = 3329;
    TYPE_CEMETERY = 61441;
    TYPE_HOUSING_DEVELOPMENT = 61442;
    TYPE_BRIDGE = 61443;
    TYPE_ORPHANAGE = 61444;
    TYPE_ADULT = 61445;
    TYPE_RESTRICTED_ZONE = 61446;
    TYPE_LOW_EMISSION_ZONE = 983137;
    TYPE_LIMITED_TRAFFIC_ZONE = 983138;
    TYPE_ROAD_STRUCTURE = 61447;
    TYPE_MEDIAN = 61448;
    TYPE_PAINTED_MEDIAN = 983169;
    TYPE_PHYSICAL_MEDIAN = 983170;
    TYPE_WALKABLE_MEDIAN = 983171;
}
