syntax = "editions";

package logs.proto.maps.pathfinder.client;

import "logs/proto/maps/pathfinder/client/request-source.proto";
import "logs/proto/maps/pathfinder/replay/proto/replay_metadata.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

option features = utf8_validation: NONE
;
option java_multiple_files = true;
option java_outer_classname = "LoggingContextProto";
option java_package = "com.google.logs.proto.maps.pathfinder.client";

message LoggedLoggingContext {
    optional string extended_session_id = 1;
    optional fixed64 session_id = 3;
    optional string software_version = 4;
    optional string client_version = 5;
    optional string platform_id = 6;
    optional string application_name = 7;
    optional string referrer_name = 8;
    repeated int32 experiment_ids = 9;
    optional int32 trip_version = 12;
    optional int32 traffic_version = 13;
    optional int64 project_number = 14;
    optional bool third_party = 15;
    optional bool logging_enabled = 16;
    optional LoggedRequestSource request_source = 17;
    optional replay.LoggedReplayMetadata replay_metadata = 18;
    optional string customization_id = 19;
}

message LoggedResponseLoggingContext {
    optional string extended_session_id = 1;
    optional string request_id = 2;
}
