syntax = "proto3";

package google.internal.earth.v1.billing;

option java_multiple_files = true;
option java_package = "com.google.internal.earth.v1.billing";

enum Capability {
    CAPABILITY_UNSPECIFIED = 0;
    CAPABILITY_STANDARD_DATA_LAYERS = 6;
    CAPABILITY_PROFESSIONAL_DATA_LAYERS = 1;
    CAPABILITY_PROFESSIONAL_ADVANCED_DATA_LAYERS = 2;
    CAPABILITY_AREA_FILTERS = 15;
    CAPABILITY_USER_LAYERS = 16;
    CAPABILITY_STANDARD_DATA_TABLES = 12;
    CAPABILITY_TAX_PARCELS = 10;
    CAPABILITY_STANDARD_MAX_SITE_AREA = 3;
    CAPABILITY_PROFESSIONAL_MAX_SITE_AREA = 4;
    CAPABILITY_PROFESSIONAL_ADVANCED_MAX_SITE_AREA = 5;
    CAPABILITY_STANDARD_THIRTY_DAY_DESIGNS = 7;
    CAPABILITY_PROFESSIONAL_THIRTY_DAY_DESIGNS = 8;
    CAPABILITY_PROFESSIONAL_ADVANCED_THIRTY_DAY_DESIGNS = 9;
    CAPABILITY_BUILTENV_ZONING_AUTOFILL = 11;
    CAPABILITY_ON_DEMAND_EVALUATION = 14;
    CAPABILITY_STANDARD_ON_DEMAND_EVALUATION = 23;
    CAPABILITY_DEFAULT_ON_DEMAND_EVALUATION_REQUEST_COUNT = 25;
    CAPABILITY_TIER_ONE_ON_DEMAND_EVALUATION_REQUEST_COUNT = 26;
    CAPABILITY_TIER_TWO_ON_DEMAND_EVALUATION_REQUEST_COUNT = 27;
    CAPABILITY_GOOGLE_ONE_AI_PRO_MAX_EARTH_MATE_QUERIES = 17;
    CAPABILITY_GOOGLE_ONE_AI_ULTRA_MAX_EARTH_MATE_QUERIES = 18;
    CAPABILITY_STANDARD_MAX_EARTH_MATE_QUERIES = 19;
    CAPABILITY_PROFESSIONAL_MAX_EARTH_MATE_QUERIES = 20;
    CAPABILITY_PROFESSIONAL_ADVANCED_MAX_EARTH_MATE_QUERIES = 21;
    CAPABILITY_OVERHEAD_IMAGERY_SEARCH = 22;
    CAPABILITY_DEFAULT_CHANGE_DETECTION = 28;
    CAPABILITY_TIER_ONE_CHANGE_DETECTION = 29;
}
