syntax = "proto2";

package earth.core.viewgroup;

import "devtools/staticanalysis/pipeline/analyzers/proto_best_practices/proto/optouts.proto";

option objc_class_prefix = "RTHCORE";
option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_package = "com.google.geo.earth.app.common.core.viewgroup";

message ViewGroup {
    repeated View view = 1;
    optional ViewId focused = 2;
}

message View {
    optional ViewId id = 1;
    optional bool available = 2;
}

enum ViewId {
    VIEW_ID_UNSPECIFIED = 0;
    VIEW_ID_AREA_FILTER = 94;
    VIEW_ID_ASPECT_ANALYSIS = 101;
    VIEW_ID_BALLOON = 1;
    VIEW_ID_BOTTOM_PANEL = 2;
    VIEW_ID_BOTTOM_SHEET = 3;
    VIEW_ID_CARD_DOCK = 5;
    VIEW_ID_CHANGE_DETECTION = 107;
    VIEW_ID_CLASSIFICATION_LAYER_CREATOR = 103;
    VIEW_ID_CLEAR_SEARCH_CHIP = 6;
    VIEW_ID_COLLAPSED_WIDGETS = 7;
    VIEW_ID_COMPASS_BUTTON = 8;
    VIEW_ID_CONTOUR_ANALYSIS = 93;
    VIEW_ID_CUT_AND_FILL_ANALYSIS = 102;
    VIEW_ID_DEPRECATED_LEGEND = 11;
    VIEW_ID_DESIGN_BUILT_ENTITY = 12;
    VIEW_ID_DESIGN_DETAILS = 13;
    VIEW_ID_DESIGN_INPUT_MODE_CHOOSER = 15;
    VIEW_ID_DESIGN_VIEWER = 16;
    VIEW_ID_DRAWING_CROSSHAIRS = 17;
    VIEW_ID_DRAWING_TOOLS = 18;
    VIEW_ID_DROPPED_PIN = 19;
    VIEW_ID_EARTH_MATE = 20;
    VIEW_ID_EXPLORE_TOOLS = 21;
    VIEW_ID_FLIGHT_SIMULATOR = 105;
    VIEW_ID_FULLSCREEN_SLIDE = 22;
    VIEW_ID_GCP_PROJECT_AVAILABLE_BANNER = 23;
    VIEW_ID_GLOBE = 24;
    VIEW_ID_HOMESCREEN = 25;
    VIEW_ID_IMAGERY_UPDATE_REQUEST = 104;
    VIEW_ID_IMAGE_GENERATOR_DIALOG = 97;
    VIEW_ID_INDUSTRY_SELECTOR_BANNER = 26;
    VIEW_ID_INDUSTRY_SELECTOR_COMPLETED_SURVEY_DIALOG_PAGE = 27;
    VIEW_ID_INDUSTRY_SELECTOR_GEOGRAPHIC_REGION_SURVEY_DIALOG_PAGE = 28;
    VIEW_ID_INDUSTRY_SELECTOR_GEOGRAPHIC_SCALE_SURVEY_DIALOG_PAGE = 29;
    VIEW_ID_INDUSTRY_SELECTOR_INDUSTRY_SURVEY_DIALOG_PAGE = 30;
    VIEW_ID_INDUSTRY_SELECTOR_MAP_USE_CASES_SURVEY_DIALOG_PAGE = 106;
    VIEW_ID_INDUSTRY_SELECTOR_OPT_INS_SURVEY_DIALOG_PAGE = 31;
    VIEW_ID_INDUSTRY_SELECTOR_PRIMARY_USE_SURVEY_DIALOG_PAGE = 32;
    VIEW_ID_INSPECTOR = 33;
    VIEW_ID_KNOWLEDGE_CARD = 34;
    VIEW_ID_LAYERS_DATA = 35;
    VIEW_ID_LAYERS_FILTER = 36;
    VIEW_ID_LAYERS_SELECTED_FEATURE = 37;
    VIEW_ID_LAYERS_SOURCE = 38;
    VIEW_ID_LAYERS_STYLE = 39;
    VIEW_ID_LAYER_DATA_TABLE = 40;
    VIEW_ID_LAYER_DETAILS = 41;
    VIEW_ID_LEFT_PANEL = 42;
    VIEW_ID_LEFT_PANEL_COLLAPSE_HANDLE = 43;
    VIEW_ID_LIGHTBOX = 44;
    VIEW_ID_MAIN_TOOLBAR = 45;
    VIEW_ID_MAP_STYLES = 46;
    VIEW_ID_MAP_STYLES_BUTTON = 47;
    VIEW_ID_MEASURE_TOOL = 48;
    VIEW_ID_MEASURE_TOOL_CROSSHAIRS = 49;
    VIEW_ID_MEASURE_TOOL_DISTANCE_LABEL = 50;
    VIEW_ID_MENU_BAR = 51;
    VIEW_ID_MODEL_EDITING_GIZMO = 52;
    VIEW_ID_MY_LOCATION_BUTTON = 53;
    VIEW_ID_NAVIGATION_CONTROLS = 54;
    VIEW_ID_NAVIGATION_CONTROLS_BUTTON = 55;
    VIEW_ID_NAVIGATION_WIDGETS = 56;
    VIEW_ID_NEW_BUILD_DESIGN_INPUT = 57;
    VIEW_ID_ONBOARDING_BANNER = 58;
    VIEW_ID_PANEL_BALLOON = 59;
    VIEW_ID_PEGMAN_BUTTON = 60;
    VIEW_ID_PERSISTENT_TOOL = 61;
    VIEW_ID_PLAY_MODE_CONTROLS = 62;
    VIEW_ID_PLAY_MODE_TOOLBAR = 63;
    VIEW_ID_POLYGON_CREATOR_CROSSHAIRS = 96;
    VIEW_ID_POLYGON_CREATOR_DRAWING_LABEL = 95;
    VIEW_ID_PREVIEW_DATA_LAYER_TOOLBAR = 98;
    VIEW_ID_PROJECT_DETAILS = 64;
    VIEW_ID_PROPERTY_EDITOR = 65;
    VIEW_ID_SCALE_BAR = 66;
    VIEW_ID_SEARCH_RESULTS = 67;
    VIEW_ID_SEARCH_SUGGESTIONS = 68;
    VIEW_ID_SETTINGS = 69;
    VIEW_ID_SITESELECTION = 70;
    VIEW_ID_SITE_SELECTION_CROSSHAIRS = 71;
    VIEW_ID_SLOPE_ANALYSIS = 99;
    VIEW_ID_SOLAR_DESIGN_INPUT = 72;
    VIEW_ID_SPLASH_SCREEN = 73;
    VIEW_ID_STATUS_BAR = 74;
    VIEW_ID_STREAMLINED_FLOATING_WIDGETS = 75;
    VIEW_ID_STREETVIEW = 76;
    VIEW_ID_STREETVIEW_TIMELINE_COLLAPSED = 77;
    VIEW_ID_STREET_VIEW_ARROW_CONTROLS = 78;
    VIEW_ID_STREET_VIEW_CONTROLS = 79;
    VIEW_ID_STREET_VIEW_COVERAGE_VIEW = 80;
    VIEW_ID_STREET_VIEW_CROSSHAIRS = 81;
    VIEW_ID_STREET_VIEW_FLOATING_PANO_TIMELINE = 82;
    VIEW_ID_STREET_VIEW_LEGACY_TOOLBAR = 83;
    VIEW_ID_STREET_VIEW_TOOLBAR = 84;
    VIEW_ID_TIMELAPSE = 85;
    VIEW_ID_TIMELAPSE_COLLAPSED = 86;
    VIEW_ID_TIME_MACHINE = 87;
    VIEW_ID_TIME_MACHINE_COLLAPSED = 88;
    VIEW_ID_TOUR_PLAYER = 89;
    VIEW_ID_TWOD_THREED_BUTTON = 90;
    VIEW_ID_UNIFIED_SEARCH_PANEL = 91;
    VIEW_ID_ZOOM_BUTTONS = 92;
    VIEW_ID_TEST_VIEW_ID_1 = 256;
    VIEW_ID_TEST_VIEW_ID_2 = 257;
    VIEW_ID_TEST_VIEW_ID_3 = 258;
    VIEW_ID_TEST_VIEW_ID_4 = 259;
    VIEW_ID_TEST_VIEW_ID_5 = 260;
}
