syntax = "proto2";

package earth.document;

option objc_class_prefix = "RTH";
option java_multiple_files = true;
option optimize_for = CODE_SIZE;
option java_outer_classname = "CapabilityProto";
option java_package = "com.google.android.apps.earth.document";

message ProtoRequiresAtLeastOneMessageInFileCapability {
    
}

enum Capability {
    CAPABILITY_UNKNOWN = 0;
    CAPABILITY_NONE = 1;
    CAPABILITY_DUPLICATE = 2;
    CAPABILITY_MUTATE_PROPERTIES = 3;
    CAPABILITY_MUTATE_STYLE = 30;
    CAPABILITY_REMOVE_DESTROY = 4;
    CAPABILITY_REMOVE_TRASH = 5;
    CAPABILITY_REMOVE_FORGET = 6;
    CAPABILITY_REFRESH = 7;
    CAPABILITY_EXPORT_AS_KML = 8;
    CAPABILITY_COPY_TO_CLIPBOARD = 9;
    CAPABILITY_CUT_TO_CLIPBOARD = 10;
    CAPABILITY_SORT_CONTENTS = 11;
    CAPABILITY_EXPAND = 12;
    CAPABILITY_SELECT = 13;
    CAPABILITY_MUTATE_CONTENTS = 15;
    CAPABILITY_PIN_AND_UNPIN = 16;
    CAPABILITY_SHARE_ON_DRIVE = 17;
    CAPABILITY_ACCEPT_SHARING_POLICY = 23;
    CAPABILITY_REQUEST_ACCESS = 18;
    CAPABILITY_PRESENT = 19;
    CAPABILITY_GET_LINK = 20;
    CAPABILITY_REPORT_ABUSE = 22;
    CAPABILITY_ADJUST_OPACITY = 24;
    CAPABILITY_DROP_INTO = 25;
    CAPABILITY_SHOW_PROJECT_DETAILS = 26;
    CAPABILITY_SHOW_DATA_TABLE = 27;
    CAPABILITY_SHOW_DESIGN_VIEW = 28;
    CAPABILITY_GENERATE_DESIGNS = 29;
    CAPABILITY_ARRANGE_DRAW_ORDER = 31;
    CAPABILITY_DOWNLOAD_EXTERNAL = 32;
    CAPABILITY_DIRECT_FILE_ACCESS = 33;
    CAPABILITY_SAVE_EXTERNAL_CHANGES = 34;
    CAPABILITY_COPY_WITH_CONVERSION_TO_EARTH_PROJECT = 35;
}
